### ISSUE TITLE
Passive mode users shouldn't appear in "pls rich"

### ISSUE THREAD

**Issue by catclaws118** [DankMemer/dank-memer-suggestions-and-bugs#10]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I see someone with lots of money on pls rich, but when I try to rob them, it says they are in passive mode.

**Describe the solution you'd like**

I would like it so passive mode users disappear from pls rich, this makes it easier to find people to rob, instead of searching again and again through pls rich for someone without passive mode on.

**Describe alternatives you've considered**

I have considered the alternate idea of there being some sort of marker or badge next to their name on the leader board, or on their profile, however it would be much easier and simpler for passive users to disappear from pls rich, because most of the pages could be filled by people who have lots of money out, but passive mode on.

**Additional context**
In large servers which many people are in, this would be a bad problem.

**Comment by melmsie** [comment]
> I have considered the alternate idea of there being some sort of marker

This is way more likely to happen than them being removed. It's a rich leaderboard, not a "who can I steal from today" leaderboard. Same reason fake IDs are still there, just with a different name.
