### ISSUE TITLE
Reversal Wars are biased for the richer user

### ISSUE THREAD

**Issue by W1NGD1NG5-G4ST3R** [DankMemer/dank-memer-suggestions-and-bugs#100]
Reversal wars are often ended when the poorer user runs out of money. While this may seem fair, what if the poorer user was the one who got robbed? So i suggest that:
1. Reversed money is put on escrow and paid when it has been 20 minutes since the last reversal
2. If the richer user uses a reversal and 20 minutes passes without anyone using another reversal, he only gets a certain % of the robbed cash back

Alternatives:
-Chance for the robber to fail when reversing a reversal
-Remove the ability to reverse reversals entirely
-Require a certain phrase to be typed in a period of time(similar to events) to reverse a steal(or reverse a reversal). If the user fails to type it within the allowed time, he loses the reversal war

**Comment by melmsie** [comment]
Reversals are staying how they are. Making new issues isn't going to change them.
