### ISSUE TITLE
Adjust ttt and fight cool down for premium users/servers

### ISSUE THREAD

**Issue by omgitzmo** [DankMemer/dank-memer-suggestions-and-bugs#1001]
**Is your feature request related to a problem? Please describe.**
The ttt and fight command for premium users/servers is 0 seconds, this can be heavily abused when trying to call police to stop a heist. 

**Describe the solution you'd like**
Longer ttt and fight cool down for premium users
**Additional context**
When being heisted, people spamming makes it difficult to use cell, using the ttt or fight command with 0s cool down practically makes it impossible to stop a heist, was recently heisted due to this, cell wouldn’t work since I was being spammed with the commands.

**Comment by samdabloxyccola** [comment]
Yeah, I agree it should be extended, but why didn't you leave the server?

**Comment by omgitzmo** [comment]
> Yeah, I agree it should be extended, but why didn't you leave the server?

Some people on Reddit tell me leaving the server works, some people on dank memer support tell me leaving server doesn’t really work and stop the heist so I dunno which is true.

**Comment by samdabloxyccola** [comment]
Leaving the server will end the heist

**Comment by omgitzmo** [comment]
> Leaving the server will end the heist

Dank memer mods says otherwise: https://imgur.com/a/zzErmEt

**Comment by PhantomFrenzy151** [comment]
I mean, you might as well try if you can get back in

**Comment by omgitzmo** [comment]
> I mean, you might as well try if you can get back in

Yeah I tried but when more than 5 people are spamming the command with 0s cool down, it’s impossible. I looked back at the heist, I ended the game, tried calling the police but saw another person request the pls fight command, it’s impossible.

**Comment by oliverysfx** [comment]
> > Leaving the server will end the heist
> 
> Dank memer mods says otherwise: https://imgur.com/a/zzErmEt

I think they mean the heister leaving doesn't stop it

**Comment by samdabloxyccola** [comment]
> > I mean, you might as well try if you can get back in
> 
> Yeah I tried but when more than 5 people are spamming the command with 0s cool down, it’s impossible. I looked back at the heist, I ended the game, tried calling the police but saw another person request the pls fight command, it’s impossible.

Well, its possible to leave the server, it totally stops the heist
Yes, even getting TTTed and fought, u still can leave
