### ISSUE TITLE
Pls hack

### ISSUE THREAD

**Issue by picklesrgood** [DankMemer/dank-memer-suggestions-and-bugs#1004]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andrewisaboomer** [comment]
this is already a command right

**Comment by defnotdankmemer** [comment]
nope

> 
> 
> this is already a command right

**Comment by andrewisaboomer** [comment]
![image](https://user-images.githubusercontent.com/6878083/86928898-3109a600-c103-11ea-98b9-06af8cec13a1.png)
it exists, the command is probably just disabled for you

**Comment by PhantomFrenzy151** [comment]
this is already a command
