### ISSUE TITLE
[Feature Request] Mining?

### ISSUE THREAD

**Issue by ree123456789** [DankMemer/dank-memer-suggestions-and-bugs#1005]
I think it would be cool if mining was added to the game and there were different rarity of things you can get, coal being like common fish, iron or gold being like exotic fish and then diamonds like legendary fish. A pick axe would cost something like 20k or more up to you but I just think it would add more to do for the bot and you can die if you fail the events by “the cave collapsed” or something like that.

**Comment by andrewisaboomer** [comment]
fairly sure the devs are intending to add this in the rewrite, theres already an item called stone do pls shop stone
still impossible to get but its going to be added

**Comment by ree123456789** [comment]
That would be amazing! I didn’t know it was already being thought about since I didn’t see any requests in the open discussions

**Comment by PhantomFrenzy151** [comment]
this has actually been requested at least 3 other times in the past month

**Comment by ree123456789** [comment]
I didn’t say it hasn’t been requested I said there are none public ally visible that are open that request it.
