### ISSUE TITLE
Houses

### ISSUE THREAD

**Issue by Aelloner** [DankMemer/dank-memer-suggestions-and-bugs#1011]
Make a housing feature, from boxes to luxury mansions, each giving you a chance to get more money with you work or fish/hunt,also making pets moods decline slower depending on the housing type (same with fishing and hunting and work) Maybe lowering chances of being stolen from depending on house kind,with the ability to break in to said houses,with difficulty increasing with house kind. Allowing the burglar to get a low rarity item (cookie, etc) with high quality item chances increasing with the quality of the box (Mansions have a very low chance,boxes have a high chance.)

**Comment by MysticTANMAN** [comment]
That’s cool

**Comment by TRIFIilyes** [comment]
not cool
