### ISSUE TITLE
pls sellall <item> / pls useall <item>

### ISSUE THREAD

**Issue by almostStatic** [DankMemer/dank-memer-suggestions-and-bugs#1013]
Okay so, I think it would be EXTREMELY USEFUl to have a `pls useall <item>` to instantly use all of `<item>` on your inventory at once. 

There should also be `pls sellall <item>` to sell EVERYTHING of a specific item, or just a specific amount. It would be extremely useful rather than sitting there for 20mins copy pasting "pls sell fish"

**Comment by andrewisaboomer** [comment]
do pls sell fish [number here/all]
that works
as for pls useall you can also do pls use [item] [number], doesnt work with some items like bank notes or candies but does with loot boxes

**Comment by andrewisaboomer** [comment]
im so surprised by the amount of people who request pls sellall and stuff 
PUT THE NUMBER AFTER THE ITEM AND IT DOES WHAT YOU WANT

**Comment by almostStatic** [comment]
WELL HOW WAS I MEANT TO KNOW

>

-- 


*Company and disclaimer information related to this email can be found 
here. 
<https://sites.google.com/aetinet.org/academies-enterprise-trust/email-disclaimer>

*

**Comment by andrewisaboomer** [comment]
because thats how you buy things
you have to test things out if you do pls buy 5 life itll tell you that it isnt an item, so switch them around

**Comment by almostStatic** [comment]
Yeah but it never says that anywhere, i never thought that. i had 40 sunks
and manually did pls sell skunk or ages man

>

-- 


*Company and disclaimer information related to this email can be found 
here. 
<https://sites.google.com/aetinet.org/academies-enterprise-trust/email-disclaimer>

*

**Comment by PhantomFrenzy151** [comment]
for god sake at least close the thread after realizing this is a bad suggestion

**Comment by almostStatic** [comment]
.
