### ISSUE TITLE
Blackjack Algorithm

### ISSUE THREAD

**Issue by Snowballx7370** [DankMemer/dank-memer-suggestions-and-bugs#1014]
Hello,

I am not sure if this is a bug but there's a problem with the algorithm on blackjack. PFB 
![image](https://user-images.githubusercontent.com/68061123/87033327-9e5b2b00-c218-11ea-9f47-7e51297078af.png)
So if you could see, the bot could have won if he STAND on his first 2 cards (Q, J = 20) instead of hit. 

And I will attach more examples of it..
![image](https://user-images.githubusercontent.com/68061123/87033632-25100800-c219-11ea-81ba-7df8f1a0e8a9.png)
![image](https://user-images.githubusercontent.com/68061123/87033661-36591480-c219-11ea-90cd-72230cb2f3ef.png)

**Comment by andrewisaboomer** [comment]
i feel like this all depends on the order the dealer got the cards. i think that in each of those cases there is a way where the dealer has less than you when you reveal, and then they draw another card because they have less and go bust

**Comment by bruhder** [comment]
As far as i remember the order of the cards drawn is from right to left meaning, the first 2 cards from the right are the first 2 cards drawn. So basically, in the second picture you attached the dealers hand at first was 14 (4 and K) to which is why he needs to hit
