### ISSUE TITLE
Rare Fish Adjustment

### ISSUE THREAD

**Issue by Letoplaz** [DankMemer/dank-memer-suggestions-and-bugs#102]
Rare Fish feel like they are too rare to use for their sell price. When I get them, I am more inclined to just hoard them in my inventory than sell them. This is also the case for exotic fish, but the rarity at least makes sense, especially since they sell for 6k.
I think that the drop rate of Rare Should be slightly increased, so that when you get them you actually feel like it's a good idea to sell them, not a waste.
An alternative solution would be to up the sale price of rare fish so that when you get them you don't hesitate to sell them because it's a quick buck. Just something to make getting them cool beyond. Oh! That's rare. Maybe 1000 coins would be fair because that's 10x the price of a regular fish, and the rare fish is far beyond 10x rarer. 
I know that pls fish is already OP and in doesn't really deserve a buff, but this would make rare fish feel more like a rare reward than a novelty.

**Comment by melmsie** [comment]
> I know that pls fish is already OP and in doesn't really deserve a buff

ding ding ding, closing this because I don't agree with your solutions. However I'll keep it in mind in the future
