### ISSUE TITLE
Add Pls rich bank

### ISSUE THREAD

**Issue by ShadowGamer3** [DankMemer/dank-memer-suggestions-and-bugs#1020]
Instead of pls rich, which only shows the leaderboard based on coins in your wallet, add an optional “bank” argument to show the leaderboard in the server based on money in the bank (example: pls rich bank), or a “total” argument (pls rich total) to show the leaderboard based on total riches (bank + wallet).

**Comment by MysticTANMAN** [comment]
Yes please

**Comment by PhantomFrenzy151** [comment]
or add this to the wishlist
