### ISSUE TITLE
Alt accounts

### ISSUE THREAD

**Issue by NihitKiller** [DankMemer/dank-memer-suggestions-and-bugs#1021]
It's about the alt account that users uses now also. I see that you put the commands till 250 so that they cannot share or gift anyone but then also the users types until the commands are over 250 and then farm coins or keeps the coins in their alt account. So, I am suggesting that you should put the commands till 5000 or 10000 so that the users wouldn't use the alt account to farm the coins or keep the coins in their alt accounts.

**Comment by samdabloxyccola** [comment]
How is the bot even going to detect alt accounts?

**Comment by NihitKiller** [comment]
Devs know how to do that.

> How is the bot even going to detect alt accounts?

**Comment by thisaccisnowxiarous** [comment]
That was too much. Imagine a user losing their account password and creating a new one just to type 5000 commands. 250 is enough for a noob.
