### ISSUE TITLE
The Money Calculation Was Having A Problem

### ISSUE THREAD

**Issue by iiGamingAlexYTii** [DankMemer/dank-memer-suggestions-and-bugs#1023]
Bug: Money Calculation Error
I Was Playing Some Random Game Of Black Jack I Was Having 1mill 547k I Belive Ive Only Betted 25k On That Black Jack Game

After That Ive Checked My Balance It Was 1mill 475k Please Try Fixing This Bug

There Is Nothing I Can Reproduce So I Am Going To Leave This Part

**Expected behavior**
I Tought It Would Give Me A Bit More Than 1m 475k It Didnt Happen 

**Screenshots**
![image](https://user-images.githubusercontent.com/68093203/87113574-a4382700-c27f-11ea-88aa-d3093a10c117.png)
![image](https://user-images.githubusercontent.com/68093203/87113596-ae5a2580-c27f-11ea-8803-2d5d7708c4d1.png)
![image](https://user-images.githubusercontent.com/68093203/87113615-b7e38d80-c27f-11ea-97d4-be1bb074ab98.png)
![image](https://user-images.githubusercontent.com/68093203/87113642-c631a980-c27f-11ea-8e8f-3e465df8f257.png)

**Your User ID**
590411225423282176

**Additional context**
Nothing Much Ive Aldready Explaained Hoping For A Reply

**Comment by MysticTANMAN** [comment]
I don’t get it

**Comment by MysticTANMAN** [comment]
I see u lost 25k at 7:04 then u cut what happend and 7 minutes later, u show ur balance and u lost 75k.

**Comment by andrewisaboomer** [comment]
ur leaving something out because your bank balance has changed and your max bank has also changed
there's certainly something you arent showing us

**Comment by PhantomFrenzy151** [comment]
What he said ^

**Comment by Rearcoplays** [comment]
yea, this guy is just trying to get coins. Man, if you want to trick us, you'd have to be way smarter than that, lmao

**Comment by anonymouswrita** [comment]
close this
