### ISSUE TITLE
Lose coins on bot ban and unban

### ISSUE THREAD

**Issue by MysticTANMAN** [DankMemer/dank-memer-suggestions-and-bugs#1025]
Idk if this counts as a bug but I was bot banned then a staff member unbanned me (tysm for the unban) and I lost one million coins.

I expected to get my coins as well as inventory back but I guess I only get the inventory. 

My user ID is: 729365109381529661

**Comment by andrewisaboomer** [comment]
pretty sure this was intended

**Comment by kablekompany** [comment]
This is normal behavior

**Comment by Yoshi1627324** [comment]
Huh you did have an alt and scammed my friend so I think you deserve to lose coins @MysticTANMAN also I don't think you deserved an unban as well
