### ISSUE TITLE
Stop people from spamming pls rob "one user"

### ISSUE THREAD

**Issue by Bulmenisaurus** [DankMemer/dank-memer-suggestions-and-bugs#1026]
**Is your feature request related to a problem? Please describe.**
I noticed in big servers whenever there was somebody with even a tiny bit of money and passive mode disabled, ~50% of the comments relating to the bot would be trying to rob that user, like ants stealing food.

**Describe the solution you'd like**
Whenever somebody tries to rob a user and the 'wait 2 min' text pops up, there will be a slight chance 'the police got suspicious and fined you x coins'. The chance of police coming increase with every consecutive 'wait 2 min'

This would (hopefully) stop people from unnecessarily spamming the chats with pls rob.

**Comment by thisaccisnowxiarous** [comment]
I got robbed in a server many times TWT

**Comment by sircheezball** [comment]
YES I got robbed like 80k from one person and im not his only victim
