### ISSUE TITLE
pls say not fully censoring links

### ISSUE THREAD

**Issue by NateTheCarrot** [DankMemer/dank-memer-suggestions-and-bugs#103]
**Describe the bug**
With `pls say`, it can be abused by just typing `discord.gg/code` without the `https://` (will force Dank Memer to say the link)

**To Reproduce**
1. Type `pls say discord.gg/servercode` (must not be a custom link, i.e. `discord.gg/meme`)

**Expected behavior**
It should say `invite`

**Screenshots**
![image](https://user-images.githubusercontent.com/34255388/78847127-e8dfc800-79db-11ea-8764-eb13e4345a2e.png)

(for the "must not be custom link")
![image](https://user-images.githubusercontent.com/34255388/78847155-fd23c500-79db-11ea-937c-48b765e0a5a3.png)

**Additional context**
Though stated before, this will not happen with custom server links. I have tried it with multiple custom server links and each output `invite`.

**Comment by melmsie** [comment]
While technically a bug, low priority as the "- user" prevents discord from holding us liable for this
