### ISSUE TITLE
Coins disappeared 

### ISSUE THREAD

**Issue by Chippio** [DankMemer/dank-memer-suggestions-and-bugs#1033]
**Describe the bug**
So basically I bought a coin bomb, i had 96k. And when i used it and checked my balance i had 0 coins, i dont know if it's supposed to happen or if it's a glitch.

**To Reproduce**
4. See error           i dont know what this means

**Expected behavior**
It will show me my normal 96k coins.

**Screenshots**
If applicable, add screenshots to help explain your problem. I cant send it, I'm on mobile.

**Your User Id**
Chippio#1458

**Additional context**
.

**Comment by andrewisaboomer** [comment]
death?

**Comment by Yoshi1627324** [comment]
maybe his pet killed him from lack of care?
or maybe he got robbed, can you check notifs?
