### ISSUE TITLE
Event award bug

### ISSUE THREAD

**Issue by thisaccisnowxiarous** [DankMemer/dank-memer-suggestions-and-bugs#1037]
**Describe the bug**
Sometimes the people who type less and slower get more items and coins (everyone has good network). Is there a last hit or some weird system?

**To Reproduce**

**Expected behavior**
I wish the rewards corresponds to how much the users have typed.

**Screenshots**

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed

**Additional context**

**Comment by andrewisaboomer** [comment]
just random
people who are first are supposed to get more (i think) but rng can give them more sometimes
