### ISSUE TITLE
Pirate talk confusion

### ISSUE THREAD

**Issue by Yourself1011** [DankMemer/dank-memer-suggestions-and-bugs#1039]
**Describe the bug**
When Pirate Talk is enabled, it says "Example: ye => ye"

**To Reproduce**
1. Turn on pirate talk
2. Use pls settings

**Expected behavior**
It says "Example you => ye"

**Screenshots**
![This](https://user-images.githubusercontent.com/57602332/87229903-1c831300-c37a-11ea-9da1-b72329b8f2cb.png)

**Comment by melmsie** [comment]
its not a bug, you have pirate speak on you quack

**Comment by Yourself1011** [comment]
Well... That's kinda my point. It's confusing for new users.
