### ISSUE TITLE
New Command Request and Bugs! 

### ISSUE THREAD

**Issue by Rearcoplays** [DankMemer/dank-memer-suggestions-and-bugs#1044]
### **Hey, Dank Memer Support Staff! (I am a random guy here), and I have something to tell you guys.**

~Firstly, for the bug. If you have a job, (for example a youtuber.) I could actually glitch the system (you can only work once per hour) and work twice, even three times. What I do is copy "pls work" and spam it quickly (Crtl+V it) and then it actually lets you work twice. This might be a glitch in the system, (but it's good for me+everyone else because we can get extra coins, lol), but I just wanted to tell you this.

~Secondly, for the request. I wanna see pls postvid (or pls pv) like pls postmeme (or pls pm) except that you use a camera, which could be a new item added on to the shop. THIS would be SO cool, please do something like this. Make the camera the same price as the laptop, and also have such a thing as "Your video got 2419 likes and 2 dislikes. You got 496 coins from the ads, and one of your fans also gave you candy!"   OR....    "Your video got 0 likes and 2400 dislikes. You got 0 coins and now your camera is broken LOL, go buy a new one, sucks to be you." Basically the same as the laptop, but slightly different, as the pls fish is similar to the pls hunt. 

THANKS A LOT DANK MEMER! You have done a great job satisfying bored people, and I really like your guys's bot. Please email me at rearcoplays@outlook.com if you think my idea is good, I would just LOVE this to be on Dank Memer's bot. Bye :)

**Comment by Rearcoplays** [comment]
Another add-on to the video thing, it would be even BETTER if there could be such a thing like subscribers to your channel, and if you don't upload often then you get less subscribers, and the more subscribers you have, for example every 10000 subscribers, you get a certain multiplier.

This would just be AMAZING, thanks Dank Memer team!

**Comment by IeuanGol** [comment]
Just so you're aware this is public and anyone viewing this can see your email

**Comment by Rearcoplays** [comment]
@IeuanGol yea ik, this isn't my main email so I don't really care :)

**Comment by PhantomFrenzy151** [comment]
The double working thing Memsie has talked about before in some other closed bug report iirc, and he said it wasn't important enough to be top priority or something, since it isn't making the gameplay worse
