### ISSUE TITLE
Fast XP, Gamble Multipliers, and New Powerups

### ISSUE THREAD

**Issue by 1e1000** [DankMemer/dank-memer-suggestions-and-bugs#1048]
--- XP is extremely hard to gain, and it takes hours of grinding to gain on a few levels. I think and so do many other that I've talked to that an item that gives you XP would be very popular. (I know that cheese gives you an XP multiplier, but it still takes lots of time to level up even with a maximum cheese multiplier.)

--- Buying multipliers in the shop? Multipliers are a big deal when people consider gambling a lot. It would be nice if there was an item in the shop that didn't cost as much as a Pepe Trophy but still gave you a small multiplier. 

--- Fortune multiplier. It would be great if a new multiplier was added, where it determines how many coins you get from begging, searching, lootboxes, daily rewards, etc. So if I got 100 coins from begging, but had a 30% fortune multiplier, I'd get 130 coins. An alternate solution would be to make a powerup in the shop that gave you +x% coins for a certain duration.

--- Lucky potion. This potion doesn't do anything except give you a small chance of getting rare items while doing currency commands. If I were to buy one from the shop, then use it, maybe if I run "pls beg" I'd have a 0.01% chance of getting a Pepe Coin, or some other rare item.

(I edited some screenshots to demonstrate what I have in mind) 

**XP Boost Item**

![XP](https://user-images.githubusercontent.com/68196252/87252904-a8617180-c444-11ea-98f1-ab534a708508.png)

**Multiplier Boost Item**

![Multi](https://user-images.githubusercontent.com/68196252/87252916-c5964000-c444-11ea-80e6-69c74ef79967.png)

**Fortune Multi**

![Fortune](https://user-images.githubusercontent.com/68196252/87252923-cf1fa800-c444-11ea-92ba-e77193850c9f.png)

**Lucky Powerup Item**

![Lucky](https://user-images.githubusercontent.com/68196252/87252927-d8107980-c444-11ea-85dc-128bafd51e86.png)

I hope you consider my ideas! :)

**Comment by andrewisaboomer** [comment]
seems interesting, but four leaf clover seems kinda bad
begging 10k times would give you around only a 1/3 chance of getting at least 1 pepe coin
thats WAYYYYYY too low
good effort for the screenshots tho

**Comment by 1e69** [comment]
> seems interesting, but four leaf clover seems kinda bad
> begging 10k times would give you around only a 1/3 chance of getting at least 1 pepe coin
> thats WAYYYYYY too low
> good effort for the screenshots tho

Thanks! The percentage chance isn't fixed though, I just put random ones. If Melmsie considers adding my idea, he can choose percentages that he approves of.
