### ISSUE TITLE
Bug - Quests not redoing correctly

### ISSUE THREAD

**Issue by conqr2** [DankMemer/dank-memer-suggestions-and-bugs#105]
**Describe the bug**
When I try to redo the redouble quest won't back down, every time it will tell me that I need to wait 0 seconds until I can do it again.

**To Reproduce**
1. Get an account where you finished the quest before you were allowed to redo quests
2. Try to redo it
3. It should say you can redo this quest in 0 seconds.

**Expected behavior**
I expected it to let me redo the quest.

**Screenshots**

<img width="776" alt="Screen Shot 2020-04-08 at 7 21 58 PM" src="https://user-images.githubusercontent.com/34463817/78913729-4a388300-7a3e-11ea-8706-382cabe92499.png">

**Additional context**
This happens all the time, so its not a timing bug

**Comment by KennywasTaken** [comment]
I'm having this same bug too

**Comment by melmsie** [comment]
will be fixed later this summer
