### ISSUE TITLE
Cooldown cmd

### ISSUE THREAD

**Issue by progboy** [DankMemer/dank-memer-suggestions-and-bugs#1056]
I want to see all my cooldowns for hunt, fish, work, daily etc commands with one command

I should type a command (pls cd or pls cooldown) and should be able to see all cooldowns for all currency commands

Alternatively, there can be a cmd called pls ready where I can see what all commands I can use. For example, if I can use pls fish command, then by typing pls ready it should show that I can use pls fish command.

**Comment by andrewisaboomer** [comment]
do pls profile --cooldowns
if it doesn't work remove the s

**Comment by progboy** [comment]
can you change pls profile --cooldowns to just pls cd since I use it a lot?

**Comment by ARU300** [comment]
`pls profile --cd` also works
