### ISSUE TITLE
An Improvement Of Pls Notifications 

### ISSUE THREAD

**Issue by Chepstikk** [DankMemer/dank-memer-suggestions-and-bugs#1058]
It Would Be Nice If Pls Notifications Would Show When Someone Gives You Money / Gifts Any Items Because This Is Possible To Do Without Tagging So You Receive Money Without Knowing And It’s Frustrating. 
It Shows When People Steal Money So Why Not When They Give?

**Comment by andrewisaboomer** [comment]
it does
![image](https://user-images.githubusercontent.com/6878083/87734601-19848a00-c7a1-11ea-81b1-fe1156c2e308.png)

also dont you title print it hurts my eyes

**Comment by Chepstikk** [comment]
Oh Oof.  I Wasn’t Aware. I Gambled Some Money And Accidentally Gambled Way Too Much Bcos It Didn’t Show In Notifications 🙈
