### ISSUE TITLE
Just a mistype from the command

### ISSUE THREAD

**Issue by haharv** [DankMemer/dank-memer-suggestions-and-bugs#106]
**Describe the bug**
When using the command pls trivia it gave me the question:
This Canadian television sportscaster is known for his "Hockey Night in Canada" role, a commentary show during hockey games.
One of the answers wasn't italic and appeared like this :
C) *Don Taylor *
There is just an uneeded space there.

**To Reproduce**
This Canadian television sportscaster is known for his "Hockey Night in Canada" role, a commentary show during hockey games.
You have 20 seconds to answer with the correct letter.

A) Don Cherry
B) Don McKellar
C) *Don Taylor *
D) Donald Sutherland
Worth
10 coins
Difficulty
Easy
Category
Sports

**Expected behavior**
that there would be no space after Taylor to make it italic
**Screenshots**
![plsglitch](https://user-images.githubusercontent.com/63419863/78925641-ac6fa300-7a93-11ea-8ec1-2c1dc2f9ac69.png)

**Additional context**

**Comment by NateTheCarrot** [comment]
I don't believe they can change that; it's from an API. The only thing I can suggest is to .replace " *" with "*".

**Comment by melmsie** [comment]
Nate is correct.
