### ISSUE TITLE
Make banknote available in shop

### ISSUE THREAD

**Issue by marvelfan101** [DankMemer/dank-memer-suggestions-and-bugs#1061]
Please can u guys make banknotes in the shop? I am finding a hard time trying to get them. I have a few suggestions for u.
Suggestion 1: Price for banknote - $9000
Suggestion 2: Banknotes can be given from events, fans(post memes), begging, search, fish and hunt 
Suggestion 3: When a banknote is used, it expands the bank from 5000-10000

Overall, I think ur bots are great and really fun. NiCe WoRk DiSoRd.

**Comment by PhantomFrenzy151** [comment]
suggestions 2 and 3 are already in the game. The rarity of banknotes is what makes it fun, as you can trade with other people for expensive prices.

**Comment by ARU300** [comment]
It's meant to be a collectible item so no it shouldn't be in the shop. Also its not made by discord.
