### ISSUE TITLE
pls embedcolor

### ISSUE THREAD

**Issue by almostStatic** [DankMemer/dank-memer-suggestions-and-bugs#1063]
Set a custom embed colour for yourself, makes all embed colours that colour.
OR you could have `pls embedcolor random` to get a random one each time

**Comment by PhantomFrenzy151** [comment]
But that would make Santa's hat useless :(

**Comment by almostStatic** [comment]
No it wouldn't. 
Santa's hat is a RANDOM chance of getting a red/green embed.
pls embedcolor would give it a constant embed colour, or a set embed colour.

**Comment by PhantomFrenzy151** [comment]
Yeah, but if you could make the embed colors green or red without money, wouldn't you do it?

**Comment by almostStatic** [comment]
I guess santa's hat's value would be reduced
