### ISSUE TITLE
Heists stop you using your bank :(

### ISSUE THREAD

**Issue by z-er** [DankMemer/dank-memer-suggestions-and-bugs#1066]
**Describe the bug**
After someone performs a bank heist on me, i can no longer withdraw any money from my bank. this happens after one bank heist and persists over multiple, i just get completely barred from using my bank.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get people to bank heist you
2. Let them finish heist

**Expected behaviour**
To be able to use my bank after heist has completed.

**Your User ID**
138221941558345728

**Comment by samdabloxyccola** [comment]
Yes its 100% annoying and it should be fixed

**Comment by Wise2006** [comment]
This happened to me too.

**Comment by ARU300** [comment]
Just do `pls use phone` then `p`.
