### ISSUE TITLE
WHERE IS ALL MY MONEY????

### ISSUE THREAD

**Issue by diegoat69** [DankMemer/dank-memer-suggestions-and-bugs#1071]
I had about 200k this morning and would've had about 250k next time I checked but when I did, all of m money was gone and that has happened to me about 3 times already, I checked and nobody robbed me and I didn't get killed,  so please give the money back

**Comment by andrewisaboomer** [comment]
u sure u didnt die

**Comment by diegoat69** [comment]
> u sure u didnt die

yeah man I checked like 50 times and I didn't die, I've lost more than 300k with that stupid ass bug

**Comment by ARU300** [comment]
Are you using a bot by any chance?
