### ISSUE TITLE
Feature request: Cooldown timer setting between command usage to prevent spam

### ISSUE THREAD

**Issue by snowblind666** [DankMemer/dank-memer-suggestions-and-bugs#1072]
**Is your feature request related to a problem? Please describe.**
Yes - I have enabled the use of the bot in a general chat room and there's no way to prevent people spamming bot commands in there. I dont want to set the room to slow mode since it's also used for chat.

**Describe the solution you'd like**
I would like to see a cooldown setting where I could limit how frequently people can use commands. So like set 60 second limit between using **pls emojify** command as an example. 

**Additional context**
Thanks for all the hard work on the bot!

**Comment by Rearcoplays** [comment]
Hey @snowblind666 , I have a solution for you. Go to the channel settings, and disable Dank Memer to read/send messages in the general chat room. Then make a bot commands channel, and allow Dank Memer to read/send messages there. This is how to prevent people from using Dank Memer in general chat. If you need help, comment here, and I will send you my Discord username, or you can send me yours.

**Comment by ARU300** [comment]
The cooldown is set in dank memers code. The only way you can change how often people use commands is with slowmode.

**Comment by ARU300** [comment]
> Hey @snowblind666 , I have a solution for you. Go to the channel settings, and disable Dank Memer to read/send messages in the general chat room. Then make a bot commands channel, and allow Dank Memer to read/send messages there. This is how to prevent people from using Dank Memer in general chat. If you need help, comment here, and I will send you my Discord username, or you can send me yours.

You could just do `pls disable all` then `pls disable all` and then `pls enable all <#channel>`. I might be wrong with syntax.
