### ISSUE TITLE
Currency 

### ISSUE THREAD

**Issue by mosyeeto** [DankMemer/dank-memer-suggestions-and-bugs#1074]
----I died---- my  bad wasn't checking

So I was just trying to get some coins by typing pls beg/pls search and suddenly all the money I have in my wallet dissappeared but not the money in my bank, I have about 15k-18k. 

It doesn't happen all the time but it does happened twice for me. 

I believe that after typing pls beg/pls search and then do pls bet/blackjack/slots your money in your wallet will dissappear.

**Screenshots**

mosyeeto#5362

![Desktop Screenshot 2020 07 16 - 17 23 22 67](https://user-images.githubusercontent.com/68377588/87660378-25fce880-c789-11ea-80cc-a8ffed02a449.png)
![Desktop Screenshot 2020 07 16 - 17 23 27 53](https://user-images.githubusercontent.com/68377588/87660387-29906f80-c789-11ea-82a0-f69c77e7c745.png)

**Additional context**

**Comment by mosyeeto** [comment]
Sorry the picture I added wasn't showing the issue properly, here's the one.

![Desktop Screenshot 2020 07 16 - 17 25 33 18](https://user-images.githubusercontent.com/68377588/87660521-65c3d000-c789-11ea-9791-385a26afa551.png)
![Desktop Screenshot 2020 07 16 - 17 25 38 07](https://user-images.githubusercontent.com/68377588/87660526-665c6680-c789-11ea-82be-a372e19f3009.png)

**Comment by samdabloxyccola** [comment]
@mosyeeto U got robbed lmao

**Comment by andrewisaboomer** [comment]
you died my guy
![image](https://user-images.githubusercontent.com/6878083/87709294-0ad2ae80-c772-11ea-882c-f0597f49959e.png)

**Comment by mosyeeto** [comment]
@andrewisaboomer oh crap i didnt know that I died, thought the drowned was just a funny part to describe.

**Comment by anonymouswrita** [comment]
close
