### ISSUE TITLE
A way to remove tax fees: Hiding from the government. 

### ISSUE THREAD

**Issue by DunkMeymerrr** [DankMemer/dank-memer-suggestions-and-bugs#108]
So, it’s like not being able to go out doors. Search and beg commands are disabled for you because, you’re hiding from the government. Heisting while under this will give you a bigger fine, as well as robbing. 

I thought of an idea where you pay the government, and you’re tax free for a period of time. (50k, 5 days, 2 million, tax free or some shit). The richer you are, the more the government will charge you for this. 

(This has been on my bucket list for the past week, GitHub never loaded on my computer)

**Comment by aidenislit** [comment]
that's pretty smart

**Comment by Assassin1733** [comment]
That’s actually good because then it would be harder for richer people, meaning the poorer can catch up easier

**Comment by melmsie** [comment]
No. Taxes are to discourage alts, not to be a fun mechanic.
