### ISSUE TITLE
Dictator job typo

### ISSUE THREAD

**Issue by RandomTurtleBoi** [DankMemer/dank-memer-suggestions-and-bugs#1081]
My current job is as a Dictator, and I happened to get the Reverse minigame. Dank Memer asked me to spell the word _politician_ in reverse, so that's what I did. Little did I know that there's a typo in the word _politician_ so when I copied the word backwards, Dank Memer didn't accept it. The way Dank Memer spelt it was "poitilican" where the correct spelling was "politician".

![image](https://user-images.githubusercontent.com/64146447/87801278-7de52f00-c81d-11ea-833e-7aac39f9d12d.png)

**Comment by andrewisaboomer** [comment]
my guy
that
is
not
the
reverse minigame
that is the unscramble minigame the word just happens to be really similar to politician, so im assuming you thought it was the backwards one

**Comment by PhantomFrenzy151** [comment]
Lol. That's the unscramble minigame. Please close the bug report.

**Comment by TijTuna** [comment]
Are you actually dumb

**Comment by RandomTurtleBoi** [comment]
ok yea im blind im sorry
