### ISSUE TITLE
New Tax Suggestion

### ISSUE THREAD

**Issue by Eee12345799** [DankMemer/dank-memer-suggestions-and-bugs#1082]
Hi,
 
First and foremost, I hope you and your family are doing well and staying safe. My proposed tax reform is taking the tx out of the giver's wallet instead of taking it out of the receiver's portion. For example, if I gave 100k to person B, the tax rate is 3%. Currently, person B would receive 97k, but with my proposal, person B would instead receive 100k and I would get the 3k taken out my my wallet. Adding this feature would make trading much easier because it allows you to still passively take currency out of the economy and makes covering tax not an issue for everybody.

Thank you so much and I hope you and your family keep on doing well and staying safe!

**Comment by Wise2006** [comment]
Um, What if You only had 100k in your wallet?
Would the money be taken from your bank?
If so, What if you had no money in your bank?

**Comment by Eee12345799** [comment]
Well, if your wallet had nothing left, it would be taken from your bank. Your point about having no money in the bank is fair and my answer to that is just go negative.

**Comment by Wise2006** [comment]
It's a good idea then.
