### ISSUE TITLE
cancel quests

### ISSUE THREAD

**Issue by donkeyman3000** [DankMemer/dank-memer-suggestions-and-bugs#1086]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donkeyman3000** [comment]
i want a cancel quest command so i coudl cancela quests and pick another instead of finishing the quests i have on me

**Comment by Wise2006** [comment]
This already exists. The command is `pls quest stop`.
Thank you!

**Comment by Wise2006** [comment]
Can Close #1086

**Comment by PhantomFrenzy151** [comment]
please close the request. Pls quest stop already exists.
