### ISSUE TITLE
Add a giveaway mode for people wanting to do giveaways for dank memer money and items 

### ISSUE THREAD

**Issue by ghost** [DankMemer/dank-memer-suggestions-and-bugs#1093]
There should be a command called pls giveaway, which starts the giveaway. There should also be a Giveaway ID.

Here is how it should go:
User: pls giveaway start
Dank Memer: How much coins/what item(s) do you want to giveaway
User: 10k coins
Dank Memer: Where do you want to start your giveaway?
User: #giveaways 
Dank Memer: How long is your giveaway?
User: 2d

However to prevent alt abuse there should be requirements:
1. A tax rate system same as when you share coins
2. Your discord account must be a few weeks old to enter/start a giveaway
3. Your server must have at least 10 members (bots don't count)

If you are in giveaway mode no one can rob or bankrob you.

You should also need to confirm the winner of the giveaway by saying pls confirm giveaway giveawayID. If you want to change winners, then do pls giveaway giveawayID reroll.

**Comment by JustSomeoneOnGithub** [comment]
You can just use any other giveaway bot, and turn on passive mode temporarily.

**Comment by electricstriker** [comment]
> You can just use any other giveaway bot, and turn on passive mode temporarily.

i know but i would like to see this in dank memer
