### ISSUE TITLE
MAX ROCK

### ISSUE THREAD

**Issue by IBP-0** [DankMemer/dank-memer-suggestions-and-bugs#11]
Because a pet rock is the silliest and first pet you can get. If someone grinds their way to leveling out a rock to max defense/attack/hunting/sustainability, they should get a secret multiplier, or this could be a secret quest, or some sort of thing. I just think it'd be a really cool easter egg. 

Cheers~

**Comment by MakingPoutine** [comment]
This'd be nice but the rock can't actually attack or defend so this makes it a rather bad pet to have, a multiplier like this could work with just a multiplier boost to any pet at max level. (Not that big though, maxing the pet isn't too difficult)

**Comment by IBP-0** [comment]
Yeah but that the point dude. You're doing a pointless thing for the hell of it, like I currently am. It's funny. MAX ROCK only.

**Comment by melmsie** [comment]
We have plans for more multipliers in the future, I'll take this into consideration
