### ISSUE TITLE
Do a thorough investigation before really blacklisting someone or banning someone

### ISSUE THREAD

**Issue by samdabloxyccola** [DankMemer/dank-memer-suggestions-and-bugs#1106]
Some users did nothing but were either blacklisted or banned due to false reports, but somehow, the false reports still get through. There was this person in a giveaway person in a giveaway server who got banned as someone reported him of having an alt, but he doesn't have one at all. Some people may joke having alts too and get reported as people think he really has alts but in reality he just wants to mess around with them. Somehow, the report mostly works. But what if, the user was impersonated by someone and was falsely reported due to impersonation and got bot banned?
The reporting system could improved in my opinion but its up to the bot devs on how to improve their reporting system

**Comment by andrewisaboomer** [comment]
would be nice but i dont think there are enough staff for this

**Comment by PhantomFrenzy151** [comment]
If I had to guess, dozens of people are banned every day, and the staff isn't going to go through them. In basically any platform, if someone is impersonated to do something, it's still your fault.
