### ISSUE TITLE
Cheese XP Loss/Bank Balance

### ISSUE THREAD

**Issue by LytningStryke** [DankMemer/dank-memer-suggestions-and-bugs#1107]
If you have a full bank (or almost full), and you happen to use cheese but get the lactose intolerance effect, your bank balance will decrease along with your XP. With a full bank, this may leave you with more bank balance than the bank should be able to hold.
![DM_Bug](https://user-images.githubusercontent.com/54752853/88061383-0b31c780-cb2d-11ea-9879-75a10e4c6099.jpg)

**Comment by andrewisaboomer** [comment]
thats intended
bank scales with xp, so xp loss causes bank space to decrease

**Comment by LytningStryke** [comment]
> thats intended
> bank scales with xp, so xp loss causes bank space to decrease

I know, but this makes it possible to have more in your bank than your storage can handle. Yeah, it's super easy to get that balance back, but it's still annoying. Perhaps the excess money can go into your wallet.

**Comment by Astriccs** [comment]
> > thats intended
> > bank scales with xp, so xp loss causes bank space to decrease
> 
> I know, but this makes it possible to have more in your bank than your storage can handle. Yeah, it's super easy to get that balance back, but it's still annoying. Perhaps the excess money can go into your wallet.

As the previous comment said, bank space is managed by xp amounts.
