### ISSUE TITLE
Alcohol Edit in dank memer

### ISSUE THREAD

**Issue by Chugh2** [DankMemer/dank-memer-suggestions-and-bugs#1108]
**Describe the solution you'd like**
I'd like it if you sold alcohol there is a small chance the police will fine you since it is kind of illegal in real life.

**Describe alternatives you've considered**
not really any alternatives

**Additional context**
pretty sure the above is clear enough

**Comment by Astriccs** [comment]
No, this is not real life though. Dank is not about mimicking real life, you can physically rob people with 10mill coins +, I mean that's not real life. Dogs give you like 400 coins + not real life.
