### ISSUE TITLE
Request: pls stonks feature

### ISSUE THREAD

**Issue by tctalk** [DankMemer/dank-memer-suggestions-and-bugs#1109]
**Something to do besides gamble and work**
I always felt it was strange that the most powerful way to create more value in the currency system, or make money, is to bet or use slots. Working is cool, but only gives a little depending on which job you have and especially in th wend game it’s just better to use bet/slots.
**Heres where Stonks come in**
Stonks is already a popular meme. Though it’s an old one, it’s still relevant. Doing pls stonks could list the current stonks available (could be companies popular in meme culture or made-up ones) and they could refresh every hour or day depending on what’s better. You could do pls stonks choose [stonk] to choose one. Maybe you could even sell them to other players as the prices change over time. They don’t have to reflect real life stock values of course. Overall, I feel like this could be a major improvement in the currency system, and it could be a less-risky alternative to slots/betting while still having risk, and it’s a better way to make money irl vs going to casinos. Thanks for your time, and have a good day! Hope you like this idea.

**Comment by PhantomFrenzy151** [comment]
This has been recommended at least 7 times over the past few months.
