### ISSUE TITLE
LEGENDARY FISH

### ISSUE THREAD

**Issue by aidenislit** [DankMemer/dank-memer-suggestions-and-bugs#111]
THE 1 IN 1000 FISH THAT YOU CAN GET FROM pls fish. I WAS THINKING THAT IT SELLS FOR 20K OR MORE. ALSO, YOU SHOULD ADD MORE ITEMS IN THE SHOP LIKE CARS TO GET AWAY FROM POLICE. ADDITIONALLY, THERE SHOULD BE LIKE pls family AND YOU CAN START YOUR OWN FAMILY AND YOU HAVE TO BUY THEM STUFF DAILY OR WEEKLY LIKE FOOD AND CLOTHES BUT THEY HELP FIND YOU ITEMS LIKE MONEY OR RARE ITEMS. ALSO, I WAS THINKING pls donate bread OR ANY OTHER TYPES OF FOOD TO LIKE A HOMELESS SHELTER AND FOR EVERY LIKE 1,000,000,000 ITEMS DONATED YOU GUYS DONATE LIKE 10 DOLLARS TO A HOMELESS SHELTER OR CHARITY. YOU GUYS SHOULD ALSO BOOST THE NUMBER OF COINS YOU EARN FROM pls beg AND pls search. THERE SHOULD ALSO BE LIKE FAKE PASSPORT IN THE SHOP SO YOU CAN USE THEM TO GET AWAY FROM THE POLICE AND GOVERNMENT. MORE SUGGESTIONS COMING SOON!!!

**Comment by melmsie** [comment]
maybe lets type in *not* all caps next time

**Comment by HexCoder101** [comment]
ye lol

**Comment by RandomTurtleBoi** [comment]
uh
