### ISSUE TITLE
Passive Mode

### ISSUE THREAD

**Issue by localbisexual** [DankMemer/dank-memer-suggestions-and-bugs#1110]
**Is your feature request related to a problem? Please describe.**
Partly. I get a bit frustrated about not being able gift or receive on passive mode.

**Describe the solution you'd like**
I would like gifting and receiving to be enabled on passive mode.

**Describe alternatives you've considered**
An alternative could be having some expensive item that can prevent you from getting robbed more than once.

**Additional context**

**Comment by Astriccs** [comment]
That will be a good idea, so you won't have to go out of passive just to trade, and be afraid of getting your money robbed for the next 24 hours.

**Comment by ARU300** [comment]
The dev's stopped trading on passive so that people wouldn't abuse it and so more people would come out of it because it means you can get robbed and heisted as that's a major part of the currency system. It's the same reason why you lose 25/30% of your winnings whilst in passive.

**Comment by Astriccs** [comment]
> The dev's stopped trading on passive so that people wouldn't abuse it and so more people would come out of it because it means you can get robbed and heisted as that's a major part of the currency system. It's the same reason why you lose 25/30% of your winnings whilst in passive.

Would do you mean by "abuse it"

**Comment by PhantomFrenzy151** [comment]
Passive is for people who don't want to play the game.

**Comment by andrewisaboomer** [comment]
i think people would just get an alt on passive, use a normal account and gambling a bunch of money, yeet it on the passive person and theres nothing anyone can do about it
