### ISSUE TITLE
Add The Ability To Sell Multiple Items In On Command

### ISSUE THREAD

**Issue by Xpilia** [DankMemer/dank-memer-suggestions-and-bugs#1111]
I Have 70 Common Fish For Sale But Its Gonna Take Forever To Sell Them One By One Add A New Part For Pls Sell Command For Amount Of Items Selling
EX:pls sell common fish 70

**Comment by dirtyman2005** [comment]
you can already do this, just type "pls sell fish all" or the number of fish you want to sell

**Comment by PhantomFrenzy151** [comment]
Please close. This already exists.
