### ISSUE TITLE
Being “pls rob” spammed

### ISSUE THREAD

**Issue by Assassin1733** [DankMemer/dank-memer-suggestions-and-bugs#112]
I got spam robbed. It had taken me a while to get to 130k coins, and then 2 people overnight spam robbed me until I had 14k, and I could do nothing about it

I would like it if something could be changed to prevent people from spam robbing. 

I am thinking that increasing the cool down from 5 minutes to something like 30 minutes as I was asleep so they had plenty of time to do this. Another alternative, although probably not the best one, is too increase the number of uses from the padlock. This probably wouldn’t work as well as above, but it’s an idea. Another one is to limit the amount of times you can rob someone each day, if this is even possible.

**Comment by kablekompany** [comment]
Passive mode *exists*
