### ISSUE TITLE
Enhancement request for currency system: Income tax and Charity Box

### ISSUE THREAD

**Issue by RaSH1303** [DankMemer/dank-memer-suggestions-and-bugs#1120]
Had a suggestion for the currency system called Income Tax and Charity Box.

Income Tax:
After the user uses "pls work", and receives their salary, they have to file a part of it as income tax within 24 hours of working using "pls file IT" (the amount can be decided by the developers). If the user fails to do so, they will be fined and 10%(or maybe more) of their total balance will be confiscated.

Charity Box:
The money from Income Tax, fines, etc. will be deposited in the Charity Box. People using "pls beg" will receive money from this box. If the box is empty, the tax rates are increased. If the user may want, they can donate to the box using "pls charity [amount]". Also, a user may choose to raid the Charity box, which will have a low success rate, however, the amount of money in the box will not be known to the public which means that the user may end up having a successful raid but they will get only 1 coin.

**Comment by andrewisaboomer** [comment]
thats sorta dumb
no point in having income tax, thats just like asking for a nerf on pls work
no point in charity box, people would spam pls raid charity or whatever
