### ISSUE TITLE
Buff Snowballs

### ISSUE THREAD

**Issue by Brucewastaken** [DankMemer/dank-memer-suggestions-and-bugs#1122]
Ok, I know snowballs has been added a few months ago, but I just want to point this out. 

In the shop, snowballs cost 700 and sand costs 500, but sand can stop people from robbing you for 30 minutes but snowballs can only stop them for 5 minutes. I know that there is a chance for sand to blow back into your face, but you can add that to snowballs too, and stopping them from doing any negative actions on you basically is just stop them from robbing you. So maybe extend the stun duration for snowballs or make them cheaper, either one is good.

**Comment by andrewisaboomer** [comment]
sand can only be done once a day to a person
