### ISSUE TITLE
buff pepe trophy

### ISSUE THREAD

**Issue by Lycanblade** [DankMemer/dank-memer-suggestions-and-bugs#1124]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
So the pepe trophy cost 25m instead of 10% multi I think it should be 25% multi

**Describe alternatives you've considered**
The pepe trophy give 2% event luck and I think thats ok but 2.5% event luck would be better cuz it cost 25m

**Additional context**

**Comment by anuraggg26** [comment]
Yes i agree but i am too far away to buy one.
