### ISSUE TITLE
life saver bug

### ISSUE THREAD

**Issue by xyIophone** [DankMemer/dank-memer-suggestions-and-bugs#1128]
**Describe the bug**
I recently died and lost my coins + active items. I had the life saver in my inventory at that time, but it didn't activate.

**To Reproduce**
1. somehow die
2. have life saver in ur inv
3. See error

**Expected behavior**
I would like to see the life saver working when I die.

**Screenshots**
![png](https://user-images.githubusercontent.com/65609290/88426043-4ccca780-cda5-11ea-9638-60f5a0b6fffd.PNG)
![Capture](https://user-images.githubusercontent.com/65609290/88426059-535b1f00-cda5-11ea-8500-c2db2c997383.PNG)

**Your User ID**
337776314062864384 (xylophone#6877)

**Additional context**
thank you for your time!

**Comment by andrewisaboomer** [comment]
did you buy the life saver after you died
