### ISSUE TITLE
Commands are Delayed

### ISSUE THREAD

**Issue by chadxman** [DankMemer/dank-memer-suggestions-and-bugs#1131]
**Describe the bug**

Bot is not responding to commands or taking a lot longer than usual. 

**To Reproduce**

In screenshot:
User uses 'pls beg'
Bot does not respond
User tries again
No response
User uses 'stankrate'
Bot responds but is slower than usual

**Expected behavior**

Expected bot to respond to commands either instantly or within a few seconds. 

**Screenshots**

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed: 660221790815256590

**Additional context**
![Screenshot (70)](https://user-images.githubusercontent.com/68758473/88439223-984c7900-cdd8-11ea-8dfa-2b5daf9d36e1.png)

**Comment by andrewisaboomer** [comment]
its just lag

**Comment by PhantomFrenzy151** [comment]
lag is a problem that can't really be fixed by the developers, it all depends on other factors.
