### ISSUE TITLE
Robbers Wishlist being Unfair

### ISSUE THREAD

**Issue by Jatin-exe** [DankMemer/dank-memer-suggestions-and-bugs#1132]
**Is your feature request related to a problem? Please describe.**
Robbers wishlist shows the robbable users to everyone in the server so it feels kinda Unfair to the person using it 

**Describe the solution you'd like**
It would be great if the bot sent the robbable users through Dm to the person who is using the command in this way only the person using it will have an advantage

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by samdabloxyccola** [comment]
The thing the bot needs to be fixed is that in pls rich 9 or 10, it may show users with more than 100k. The wishlist may not show those with about 10k and are not in passive mode. Sending DMs is basically spamming the user and what if a lot of users use the wishlist in diff servers?
