### ISSUE TITLE
Blackjack bug

### ISSUE THREAD

**Issue by LeopardCheetah** [DankMemer/dank-memer-suggestions-and-bugs#1133]
**Describe the bug**
5 aces in a blackjack game

**To Reproduce**
1. Do pls bj 100
2. Keep on entering h
3. If you lose the game or do not get 4 aces on your side, and 1 ace on the other side, repeat. Else: go to step 4
4. See that there are 5 aces on the board.

**Expected behavior**
A normal blackjack game without having 5 aces in it.

**Screenshots**
![Screenshot (57)](https://user-images.githubusercontent.com/68766450/88449042-9eeae880-cdf8-11ea-990c-92fb5c933c6c.png)

**Your User ID**
736446676163887156

**Additional context**
Happens very, very rarely.

**Comment by samdabloxyccola** [comment]
Um thats 4 aces and 1 "5"?

**Comment by andrewisaboomer** [comment]
theres an ace on the other side so theres 5 aces

**Comment by PhantomFrenzy151** [comment]
Many real life blackjack games use multiple decks of cards to limit the amount of strategy, so that might be it.
