### ISSUE TITLE
Don't lose certain items when died

### ISSUE THREAD

**Issue by samdabloxyccola** [DankMemer/dank-memer-suggestions-and-bugs#1134]
When we die, we should at least not lose very expensive stuff like robbers wishlist or rare Pepe, Pepe coin, Medal and trophy.

**Comment by PhantomFrenzy151** [comment]
why do you have those things but not a life saver?

**Comment by samdabloxyccola** [comment]
Um haha I was too broke to buy a lifesaver at that time
