### ISSUE TITLE
Pls pickpocket

### ISSUE THREAD

**Issue by harpseal503** [DankMemer/dank-memer-suggestions-and-bugs#1135]
My request isn't really a problem

The command pickpocket
You can attempt to steal an item from a player and maybe some coins while you are at it?

The command should look like this:

Me pls pickpocket @someone

DM you managed to steal one fake id and 50 coins

BUT they is a 50 percent chance you will fail and pay something between 500 and 1000
Or pets would do hospital fee's

Great bot by the way I've used it for a while

**Comment by andrewisaboomer** [comment]
would allow people to steal extremely high value items like pepe trophies or pepe medals
people who store their value in items would be screwed

**Comment by harpseal503** [comment]
True but maybe the higher the rarity the harder to steal?
Eg Pepe coin 5% chance
