### ISSUE TITLE
Honor/karma level

### ISSUE THREAD

**Issue by JuicyFolder** [DankMemer/dank-memer-suggestions-and-bugs#1137]
**Is your feature request related to a problem? Please describe.**
No, not really.
**Describe the solution you'd like**
The main idea is that you could add something like "random strangers" with quests and a "honor/karma level". So there is a chance that someone asks you for money or an item, if you give it to the stranger you will get good karma and if you ignore the stranger it will give you bad karma. Good karma makes you win more when gambling and bad karma makes people steal from you easier/you die easier. You can check your karma level using `pls profile`
**Describe alternatives you've considered**
If you can't add the karma level, then maybe a "helpful hand" multiplier which you get when completing 10 stranger quest.
**Additional context**
Something like the Red Dead Redemption 2 honor bar.

**Comment by andrewisaboomer** [comment]
i feel like maybe something like this should be added because when somebody robs you they don't really get a good reprimand since working is kinda bad anyways

im gonna say it now some random person is gonna reply to me and say "IF YOU DONT WANNA BE ROBBED GO ON PASSIVE YOU NOOB"
