### ISSUE TITLE
crypto miner

### ISSUE THREAD

**Issue by kool-big-boi69** [DankMemer/dank-memer-suggestions-and-bugs#114]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
ig add in a crypto mining addition.
like in the shop u can buy these crypto miners where they are like a bit pricey costing fior a bronze tier miner to be like 25k, a silver tier 50k, gold tier 75k
what happens is that it basically works as a idle mining, you can at any time access the crypto miner and with draw the items/coins it got, like for the bronze one, it can get you up to 20k worth of items/coins before u have to upgrade it to hold more or either to buy a better miner to make it quicker. the bronze tier can get like 20 coins per minute. every upgrade for the bronze tier would go up 5k and every time you upgrade it.also for every crypto miner, for every tier every upgrade would add  10% for the next upgrade. max level for each miner would be 69 lvls, for the bronze tier every upgrade would add a additional 200 that can hold. 
10k a upgrade of on the silver miner, and gold to be 20k. Silver adds an additional 400 and gold to add an additional 800. gold starting limit that it can hold would be 69k and silver to be 40k
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've could consider?

**Additional context**

**Comment by OreoCoder101** [comment]
Pretty cool actually
