### ISSUE TITLE
Drones and more

### ISSUE THREAD

**Issue by pridedjungle361** [DankMemer/dank-memer-suggestions-and-bugs#1140]
Drones are a item used to scout out players for Intel, when sent out by running /drone send @test1234 it will create a channel where you get to see your active drones, when a drone is sent out you will get a live feed of stats like: balance, inventory, recent activities. I will edit that part when I get more ideas for uses. To get a drone you need a drone station. The drone station is the catalyst to making the channel only you can access.the drone can get shot down by running pls drone hunt. You will need a rifle and luck, if they have upgrades their drones rotors a lot. When you first get the drone it will take a few minutes to deploy and start sending live feed (This will be intentional). And the chance of it being shot down when you first get it is 100%. Upgrading it's camera allows you to monitor certain actions like robbing or bankrobbing this upgrade is only acquired once but to make up for that it will be expensive. You can also attach things to drones like a net or a rifle. If you attach a rifle it will automatically hunt down drones until it runs out of ammo, the drone is shot down, it crashes, or it's captured by a drone with a net. When given a net, which costs 200 coins to get the drone will capture other drones but takes a while to initiate and doesn't always do it successfully. The net will have a chance of being broken by the other drones blades.
You can upgrade it's hard drive which will allow you to monitor frequently done actions.

That concludes the drone part.

Houses

When you get a house (for 10,000 coins) you will unlock a new public channel where people can chat and do whatever, a vault for increased and more secure bank storage. You will be unable to be bankrobbed but people can drill your vault and take money from it and put it into their escape vehicle, when you use a drill it will always alert the person who owns the vault, unless you have the silent drill upgrade for your drill, without that type of drill the person you mentioned will get alerted when you use it. If you have the ad (silent drill) it will only alert them if they are online. You can buy a more expensive lock pick set which will allow you to silently pick the lock on the vault. This will never alert the owner but it takes longer to do and can leave you vulnerable. The upgrades to your house are: (when you first buy it) buy printer (the printer generates a small amount of coins that have to be manually collected at first, until you reach printer lvl 50 then it will be automatically collected when you go online), upgrade security (which from levels 1-10 will be just getting security cameras, levels 11-20 are just setting up motion detectors, levels 21-30 are just for activation laser defense systems, level 31 is the cap and the alarm is placed. The alarm (when triggered) will make the person who tried to rob your house be unable to rob for a longer time and will fail to rob your house, you will be alerted as will be everyone else that has access to that channel), buy better lock (This upgrade adds 1 extra pin to the lock for every level increase), buy control centre (This upgrade allows you to see when a robbery happened from beginning to end unlike when you don't have this upgrade robberies will only be recorded for 5 minutes per camera, defenses will have to be maxed out in order to get this), stronger vault (This makes the vault take longer to drill), increased storage (you can secure more money in the vault), bulkhead vault door (your vault door is much stronger and opens faster, this is only gotten when maxing out stronger vault), crate maker (you can make crates to put items in the with pls crate fill (item) and to put a item in it and then running Pls crate mail @test1234 to send it to them. You can also use it to store items by running Pls item store), deposit chute (players can put money in your vault by running pls vdep @test1234) messenger bot (you get to set a message that other people see when they enter your house, the bot can also do tasks like security, first aid (which decreases your chances of dying exponentially), and housekeeping). This concludes my house suggestion, I tried to be as specific as I can.

That wraps up my suggestion, I will edit this when I have any more ideas.

**Comment by pridedjungle361** [comment]
If you have any problems dm me I'm hackerman#2303 or message my alt deleted user#1116

**Comment by andrewisaboomer** [comment]
would be cool but the thing is
a. for a new public channel dank memer would have to assign a person a role like "house owner" so they could see public channels and 
b. how would this be implemented on the dank memer official server with the extra channel
