### ISSUE TITLE
Improve / Buff box of sand?

### ISSUE THREAD

**Issue by RedCon329** [DankMemer/dank-memer-suggestions-and-bugs#1141]
Box of sand is getting kinda worthless in my opinion.. imagine u can only use a box of sand to a player once per day and that effect only lasts for 30 min? i mean i as a player can last in a session for at least more than 30 min and that box of sand wont really prevent a player (like me) from robbing them (30 min isn't that much, i can sit it off).

extending the duration of the box of sand would be awesome.. OR removing the limit of box of sand that u can use on a player within the day and at the same time increase the price / rarity of box of sand to balance it out.

or rather than preventing a player to rob when affected by box of sand.. maybe its more feasible to just to greatly reduce the chance of them succeeding when robbing? along with the things i've stated / proposed int he 1st and 2nd paragraph

so far loving the system still :))

**Comment by andrewisaboomer** [comment]
yeah this is true most people just get someone to sand themselves at the beginning of the day and noone can sand them, making sand useless most of the time
i mean it is super cheap but still

i bet melmsie is gonna come here and close this saying "will be changed in the rewrite"
