### ISSUE TITLE
New Item: Bolt Cutters

### ISSUE THREAD

**Issue by Reanimated3400** [DankMemer/dank-memer-suggestions-and-bugs#1143]
Are you tired of those pesky people that buy padlocks? Introducing Bolt Cutters! With this new item even though someone has a padlock on them you can still rob them. It might be an one time use or one time purchase it doesnt matter. Its up to the devs. 
Desc for the item:
Use this to breake padlocks. Just like in the description when you cant rob someone when someone has a padlock. 
Price: Up to the devs
Have a great day!

**Comment by JustSomeGitHubAccount** [comment]
i just made a post about that same thing!

i also said to make padlocks cheaper in an attempt to balance the bolt cutters
