### ISSUE TITLE
hospital fees

### ISSUE THREAD

**Issue by RainbowLoom100** [DankMemer/dank-memer-suggestions-and-bugs#1144]
**Describe the bug**
I started with a wallet of around 5,022,967 (and I say around because I didn't check for a few minutes) and used tides to get a higher multi to try to gamble. The first two times was a fail and I had to pay hospital fees while I got the 5% multi on the third try. The first hospital fee I had to pay was 940,209 and the next was 705,157 which is a total of 1,645,366 lost to tides. I checked my balance right after I was successful on the third try and it showed that I had like only 2.8m. That's 2.2m lost from the beginning when the tide shows that I only lost 1,645,366. I did not buy anything nor get stolen from. I checked my notifs and it was clean but somehow 600k just got lost to nowhere?
 
**To Reproduce**
1. Check your balance and have a "maxed"/big wallet
2. Lose money to tide pods 
3. Check ur balance/wallet

**Expected behavior**
I expected my wallet after I lost to the tide pods to be around 3.4m

**Screenshots**
![Screen Shot 2020-07-27 at 12 23 55 PM](https://user-images.githubusercontent.com/68869280/88577190-9cfd7100-d014-11ea-9438-b02de781d95c.png)
![Screen Shot 2020-07-27 at 12 24 29 PM](https://user-images.githubusercontent.com/68869280/88577204-a2f35200-d014-11ea-8afb-c16698893106.png)
![Screen Shot 2020-07-27 at 12 24 56 PM](https://user-images.githubusercontent.com/68869280/88577215-a8509c80-d014-11ea-91a6-2be6cdaa39fd.png)

**Your User ID**
609925391628500992

**Additional context**
none

**Comment by andrewisaboomer** [comment]
known bug the value is wrong theres a dupe somewhere
