### ISSUE TITLE
Gift Command Update

### ISSUE THREAD

**Issue by illuminerdy8091** [DankMemer/dank-memer-suggestions-and-bugs#1145]
With the pls gift command, it would be beneficial if it automatically sent one of the items. So lets say u want to send a phone to a friend because they are getting heisted and can't access their bank because of the heist. When you run the pls gift command, you can just do pls gift phone @funnyhahaguy and it would automatically give them one of the item you listed. I mean there isn't a problem with the command as of now but I think it could be improved if it auto'd to one of the items.

**Comment by andrewisaboomer** [comment]
isnt this what it already does??????
