### ISSUE TITLE
Pls disable command

### ISSUE THREAD

**Issue by KaleUsR** [DankMemer/dank-memer-suggestions-and-bugs#1148]
**Is your feature request related to a problem? Please describe.**
It is frustrating when you would like to look at the pls rich leaderboard but used a fake id a few days ago
**Solution**
I would like a **pls disable command**
The command would disable items such as a fake id, landmine, or padlock

**Comment by Nightmare-1** [comment]
pls disable is already a command

**Comment by Rhino149** [comment]
They could just go to a private server and do the exact same with a fake id or pad they would never add the possibility to disable items for a person by someone else if your trying to disable commands that arent items do pls disable (command)
