### ISSUE TITLE
pls raid 

### ISSUE THREAD

**Issue by DonetGames** [DankMemer/dank-memer-suggestions-and-bugs#1149]
pls raid can be like pls bankrob but it takes things from inventory

**Comment by andrewisaboomer** [comment]
would screw over people who save money by using items

thats a lotta people bad idea

**Comment by NotemTotem** [comment]
no plz no

**Comment by MysticTANMAN** [comment]
Yes plsssssss

**Comment by MysticTANMAN** [comment]
Pls invrob

**Comment by JustSomeGitHubAccount** [comment]
make it so you have to buy something from the shop in order to be able to run the command

bc then everyone would use pls raid to steal that item from their inventories

also there should be a padlock but for the inventory

**Comment by Nightmare-1** [comment]
a timer or limit to how many items you can steal in x amout of time, and you cant steal anything thats worth more than 100,000
