### ISSUE TITLE
Gambling limits should be revoked

### ISSUE THREAD

**Issue by newaccount23** [DankMemer/dank-memer-suggestions-and-bugs#1152]
**Is your feature request related to a problem? Please describe.**
My request related to the issue of not being able to gamble enough
**Describe the solution you'd like**
The solution is to make no gambling limits 
**Describe alternatives you've considered**
As mentioned above
**Additional context**
I won 83,000 on the gambling but it could of been more if there was no limit

**Comment by andrewisaboomer** [comment]
gambling limit?
like the 5mil too rich to gamble limit?
