### ISSUE TITLE
I lost 30k in a few minutes yesterday

### ISSUE THREAD

**Issue by WoahNice** [DankMemer/dank-memer-suggestions-and-bugs#1153]
I lost 30k in a few minutes yesterday and I don't know why, i was just vibing and saw that im the 1st richest in the leaderboard but a few minutes came i checked my pet (got me 1k) then my friend checked my balance and all i have is 1k (sorry for the bad english it isn't my first language)
![Screenshot_2020-07-29-22-39-15-39](https://user-images.githubusercontent.com/68995925/88916216-46a06480-d298-11ea-8659-ce0804d3da08.png)
![Screenshot_2020-07-29-22-39-30-31](https://user-images.githubusercontent.com/68995925/88916218-486a2800-d298-11ea-8f8b-9306c5ed061b.png)

**Comment by andrewisaboomer** [comment]
did you die
theres 5 minutes ur not showing us check your notifs
