### ISSUE TITLE
I died when i was afk and lost pepe

### ISSUE THREAD

**Issue by Novarde** [DankMemer/dank-memer-suggestions-and-bugs#1154]
**Describe the bug**
I was afk having my lunch on returning back i saw that i had died and lost pepe[i had 0 coins in my wallet and was afk]

**To Reproduce**

**Expected behavior**
So as i mentioned earlier i was afk on returning back to the game i saw that i had died cause of somw strange reasons and lost my pepe i had 0 coins in my wallet and could not use any items as i was afk

**Screenshots**
![Screenshot_20200730-143701_Discord](https://user-images.githubusercontent.com/68997695/88920648-ded92200-d275-11ea-84aa-0ae3a03f8a0a.jpg)

![Screenshot_20200730-144032_Discord](https://user-images.githubusercontent.com/68997695/88920660-e4366c80-d275-11ea-93e6-6e5513707ec6.jpg)

**Your User ID**
624587706118438924

**Additional context**
This is not the first time this has happened to me please check and confirm as i keep on losing stuff in my inventory for no apprent reasons

**Comment by andrewisaboomer** [comment]
i mean you died
it would be nice if dank memer told you how you died tho
