### ISSUE TITLE
There should be a higher count of Pink Phallic Objects allowed

### ISSUE THREAD

**Issue by zombiepigdragon** [DankMemer/dank-memer-suggestions-and-bugs#1156]
I have about 2,549 pink phallic objects in my inventory. I achieved this because nothing prohibits giving them with `pls use pink` after the 2,500 item cap. However, I would like to ask for additional objects to be permitted.

Right now, my best bet is making another account to give them to myself with, or asking for them to be used on me. The goal was to reach 6,969 of them and give them to a friend, but this may not happen now that I've reached a cap. Therefore, it would be for the best if there was a higher cap on these wonderful inventory items.

**Comment by anonymouswrita** [comment]
wonderful inventory items, haha
but yea there should be a hiher cap cuz the money cap was also massive increased
i suggest 9999
