### ISSUE TITLE
NVM it gimme my money like 5 minutes after this

### ISSUE THREAD

**Issue by Rader439** [DankMemer/dank-memer-suggestions-and-bugs#1164]
I was stealing someone and it told me "you get a fucking ton 11996" so i go check my bal and i just lost 900  but i didnt get the money wtf, then i check the user that i was robbing from and he was 11996 YO WTF IT JUST TAKE MY MONEY AWAY AND GIME SOME EXTRA FOR HIM

Bruh just use "pls rob"

i dunno

![image](https://user-images.githubusercontent.com/69050057/89054803-0932ea00-d31f-11ea-852d-6be5257f0d53.png)
![image](https://user-images.githubusercontent.com/69050057/89054879-25368b80-d31f-11ea-871f-f1fef4928b2b.png)
![image](https://user-images.githubusercontent.com/69050057/89054937-34b5d480-d31f-11ea-9344-b03e9007afc9.png)

522876291217620992

If someone can explain to me what the actual fuck happen pls do it cya

**Comment by andrewisaboomer** [comment]
then close it if its been solved
