### ISSUE TITLE
make bolt cutters a real thing and make padlocks cheaper

### ISSUE THREAD

**Issue by JustSomeGitHubAccount** [DankMemer/dank-memer-suggestions-and-bugs#1168]
you know when you rob someone with a padlock on their wallet it says "you didnt bring your bolt cutters with you", well i was thinking it would be cool if that was a real item in the shop, and also, to balance it you should make padlocks cheaper.

thanks

**Comment by andrewisaboomer** [comment]
but...


THAT WOULD MAKE PADLOCKS USELESS
