### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by OckTheOctopus** [DankMemer/dank-memer-suggestions-and-bugs#1171]
I know that Melmsie is getting stressed about the whole Dank Memer hoax nonsense so I suggest a hidden command that would hopefully solve this.

Basically, whenever someone types in "Dank Memer can hack you" or some other nonsense it would lead to the blog post describing the issue [https://dankmemer.lol/blogs/the-hoax](url).

I've tried to explain to many people including my own brother about this nonsense but unfortunately too many people have believed it that it is getting ridiculous. I make bots as well and I try my best to explain but they don't want to listen. 

I'm really sorry about what is happening Mel, if you are reading this I just want you to know that you have the entire community behind you. Don't let a couple of idiots spoil things for you. I hope things get better for you.

**Comment by andrewisaboomer** [comment]
considering that this is a hoax about how dm is bad, dm probably wont be in the server
so it would be helpful but probably not too helpful
