### ISSUE TITLE
Add "xp bottles"

### ISSUE THREAD

**Issue by ApErSoN170** [DankMemer/dank-memer-suggestions-and-bugs#1172]
I was thinking that a good item to add to the bot would be a "level up bottle", kind of similar to the xp bottles in Minecraft Java. It should be an event drop, like banknote, so people rich in dank memer currency cant abuse the wealth and easily gain levels. I feel that it should be worth around 10k and give you from 100 - 1000 experience ( I'm not sure how much it should give). I think it would be good as it helps people level up a bit more quicker, basically like how cheese give xp multiplier

**Comment by andrewisaboomer** [comment]
should give a lot less, with that much people could completely ignore the level requirement of prestige, should only be an event drop imo
