### ISSUE TITLE
Remove rob and bankrob commands

### ISSUE THREAD

**Issue by Nightmare-1** [DankMemer/dank-memer-suggestions-and-bugs#1173]
**I would like the rob and bankrob commands to be removed**

They should be removed cos people could just go into a server with rich people and just straight up rob them, and leave, i was robbed about **600,000** the other day and was left with **50,000**, i feel like you should remove it so people can stop robbing and bank robbing other people when they can earn money properly 

**If not, bring back reversals instead**
If you won't remove either of those commands, then please at least bring back reversals and put a **1 hour** time limit instead of the **5 minute** limit

**Comment by andrewisaboomer** [comment]
im just gonna say it before other people get here, enable passive mode
if u dont wanna do it only other options are leaving the server, getting an admin to disable rob and bankrob, or be on constant vigilance with padlocks

**Comment by Nightmare-1** [comment]
passive mode ahs downsides as well, e.g. you cant share or gift, and people can share or gift to you, the servers im in that are rob enabled dont give one, and what if the padlock breaks when someone tries to rob and im offline, then they try to rob again, and i lose more money

**Comment by andrewisaboomer** [comment]
yeah because thats the dank memer system
would love if you could enable passive mode for only some specific servers so you can talk there but not get robbed there but eh
