### ISSUE TITLE
Robbers Wishlist Suggestion

### ISSUE THREAD

**Issue by Shinnichii** [DankMemer/dank-memer-suggestions-and-bugs#1177]
**Is your feature request related to a problem? Please describe.**
This is not really related to a problem, just more of an annoyance I have had numerous times.

**Describe the solution you'd like**
Have the robbers wishlist dm you the list instead of publicly showing everyone in the channel.

**Describe alternatives you've considered**
Have the bot dm you when using the item, pretty much it probably.

**Additional context**
So i’m suggesting this, because in the server i’m in is so big, the robbers wishlist is busted and only works when someone has large large amounts of cash out. And when I happen to find someone using the wishlist, everyone sees it and instantly takes the rob from me. It makes the whole point of me buying and using the item pointless, since anyone can come across me using it and take the rob. This is why I believe it would be better if the bot could dm you the list instead of just putting it in the chat. I believe this wouldn’t be too much to do so hopefully it can be considered.

**Comment by satyamedh** [comment]
no. it makes no sense. robbing is robbing xD. also if dat happens come bak when less ppl are online or smth

**Comment by MyNameIsNotDerek** [comment]
Addition: You could configure it in settings

**Comment by Shinnichii** [comment]
> no. it makes no sense. robbing is robbing xD. also if dat happens come bak when less ppl are online or smth

This server i’m referring to has 133k people. There is no coming back later when there’s less people, people are always online and someone will always be there.
