### ISSUE TITLE
hey! make that if a channel is private, dank memer cannot be used. cuz idiotic server owner tricked me into joining and robbed 200k from me in a private channel

### ISSUE THREAD

**Issue by satyamedh** [DankMemer/dank-memer-suggestions-and-bugs#1179]
**Is your feature request related to a problem? Please describe.**
hey! make that if a channel is private, dank memer cannot be used. cuz idiotic server owner tricked me into joining and robbed 200k from me in a private channel

**Describe the solution you'd like**
Dont allow dank memer in private channels

**Describe alternatives you've considered**
number5, a premium dank memer server owner is just a scammer. took over 7 banks and banned me instead of paying. just blacklist him. and if possible my 200k plssssss

**Additional context**
![image](https://user-images.githubusercontent.com/47636284/89157909-eefd4400-d58a-11ea-9dfb-2485a49055be.png)

**Comment by satyamedh** [comment]
my id: ||satyamedh||#9549
idiot's id: Number5#6969
server id:729301854940299264
server name: Dank Events

**Comment by anonymouswrita** [comment]
I dont think there isnt a good solution for you just use ur passive mode next time you enter a server
**pls settings passive true**

**Comment by satyamedh** [comment]
@anonymouswrita he wanted to trade my banks. what would be the use?
