### ISSUE TITLE
Feature Request: Remove the "pls rob" and "pls steal" commands.

### ISSUE THREAD

**Issue by thecowmilk** [DankMemer/dank-memer-suggestions-and-bugs#1190]
I love Dank Memer bot for its commands and I love its features but there is a thing that always bugged me for a long time. What bugged me was the "pls rob" and "pls steal" commands.

I'm not the only one who is frustrated from this but I have seen many people who complains about this. We get blind robbed and the thing is that the people who rob us don't even mention us, the just write the name and you got robbed.  The amount of coins people steal are large like, 5k, 7k and even 8.5k while to get those coins we spend A LOT of time...

This is very demotivating and makes you to leave the bot. We already have one way to lose coins and it is by dying, but stealing and robbing its too much. Your answer might be: "Be in passive mode" but this mode won't let others gift you items or giving coins and vice versa. You are forced to leave passive mode and in a time window of 24h(which is a long time) you are getting robbed 10 times....

It's not just fair and I request that these two commands to be removed. Thank You.

**Comment by PhantomFrenzy151** [comment]
It's perfectly fair, it happens to everyone. It's an essential part of the currency aspect of the bot. I've been robbed for more than 150k at once before. I take it you haven't figured out about the bankrob and heist commands too?
