### ISSUE TITLE
Notifs show error or money disappeared

### ISSUE THREAD

**Issue by MyNameIsNotDerek** [DankMemer/dank-memer-suggestions-and-bugs#1196]
**Describe the bug**
Some guy was going to give me 69k, however for some reason it disappeared when he tried to give it to me. His notifs showed that he died within the same minute he was giving me 69k (at 7:16 pm), however he lost 0 coins. It is unclear to me whether he lost the 69k when he died and his notifs showed 0 coins or he died after the 69k disappeared. 

**Expected behavior**
Notifs should show that they lost 69k, however apparently it showed he lost 0 coins

**Screenshots**
![Annotation 2020-08-05 191840](https://user-images.githubusercontent.com/53015641/89483947-29650d80-d752-11ea-9b91-f7c6f5c2121f.png)
![Annotation 2020-08-05 192420](https://user-images.githubusercontent.com/53015641/89483957-2f5aee80-d752-11ea-9814-c90acbfa20fe.png)
![Annotation 2020-08-05 192358](https://user-images.githubusercontent.com/53015641/89483961-341fa280-d752-11ea-80b8-290f52e9be09.png)

**Your User ID**
id of the person who it happened to: 482990117716492298
my id: 493974374056198154

**Additional context**
This did not happen to me, however it seems weird that this happened, could have been faked but it would have been very hard.

**Comment by DankMemerBotJK** [comment]
It is all in your bank.
