### ISSUE TITLE
Lottery Chances

### ISSUE THREAD

**Issue by KyxonZ** [DankMemer/dank-memer-suggestions-and-bugs#1199]
I was thinking that you would be able to make it so that we can buy more tickets to lotteries, and then we can have a higher chance at winning the lottery in the Dank Memer Discord Server.

**Comment by Bulmenisaurus** [comment]
That would give a much bigger advantage to people with millions of coins, and would do the exact opposite. People who have more tickets have a higher chance of winning, and then in turn use their winnings to buy more tickets.
