### ISSUE TITLE
Passive Mode in pls rich

### ISSUE THREAD

**Issue by MakingPoutine** [DankMemer/dank-memer-suggestions-and-bugs#12]
It'd be nice to add a feature to `pls rich` that lets you see on the leaderboard whether the person is on Passive Mode or not. This would be similar to the Prestige Level emoji already implemented and it could be represented perhaps by the green square emoji or something else that represents peace or passiveness. 

EDIT: deleted mention of implementing this into `pls profile`, found the rainbow bar today which I never paid attention to before.

**Comment by melmsie** [comment]
will take this into consideration
