### ISSUE TITLE
Withdrawing after Heist Issue

### ISSUE THREAD

**Issue by phenom4n4n** [DankMemer/dank-memer-suggestions-and-bugs#120]
**Describe the bug**
After a calling the cops on a heist, I could not withdraw money for 3 minutes. I was repeatedly shown the "Probably not a great idea to access your bank..." even though I wasn't being heisted. This may also occur when a heist succeeds.

**To Reproduce**
1. Have someone heist you
2. Use phone to call the police
3. After the heist failure message, try withdrawing money
4. See "Probably not a great idea to access your bank right now, people are planning a heist on you!"
5. Try again 1 minute later.
6. See "Probably not a great idea to access your bank right now, people are planning a heist on you!"

**Expected behavior**
It should withdraw as normal, since I am not actually being heisted.

**Comment by Druva-D** [comment]
i have the same bug

**Comment by melmsie** [comment]
Should be fixed next update
