### ISSUE TITLE
Balance Heist aka Less People get more money

### ISSUE THREAD

**Issue by MyNameIsNotDerek** [DankMemer/dank-memer-suggestions-and-bugs#1205]
**Is your feature request related to a problem? Please describe.**
Alright so these days, there are many heist where because everyone gets the same amount, anyone who wins money ends up with less than 10k. There is also the risk of losing a life saver or getting fined. Some of these heist are massive, such as 1 mil, however too many people join and everyone ends up with barely anything.

**Describe the solution you'd like**
Make the percentage of people winning lower, so less people end up with more money, or make a maximum amount of people who win money based off how much it is. For example, maximum people who can win money in a 1 mil heist could be around 25-50 people.

**Describe alternatives you've considered**
No ideas

**Additional context**
None

**Comment by andrewisaboomer** [comment]
yeah but then the people who dont win would "also have the risk of losing a life saver or getting fined"

no matter what each person still has the same expected value of coins that they're gonna get, changing the amount of people who can win doesnt help
