### ISSUE TITLE
pls disable is not working 

### ISSUE THREAD

**Issue by valerievalval18** [DankMemer/dank-memer-suggestions-and-bugs#1206]
**Describe the bug**
I disabled rob in a server and it was not disabled even when it said it was.

**To Reproduce**
1. say pls disable rob
2. try robbing
3. see error

**Expected behavior**
Rob should be disabled and i should not be getting robbed.

**Screenshots**
![Screen Shot 2020-08-08 at 1 38 54 AM](https://user-images.githubusercontent.com/69379387/89703455-f325ba80-d918-11ea-96a4-db932d3f4da1.png)
![Screen Shot 2020-08-08 at 1 38 11 AM](https://user-images.githubusercontent.com/69379387/89703459-f7ea6e80-d918-11ea-8341-864fa0cff918.png)

**Your User ID**
637774547239829525
**Additional context**
rob only seems to be disabled if i disable all. i tried clearing enable and rob list and disabling rob again but it did not work.

**Comment by PhantomFrenzy151** [comment]
The only thing I can think of from a non bug perspective is that enable is overriding disable
