### ISSUE TITLE
Can't sell some cards from a bot

### ISSUE THREAD

**Issue by mina1499** [DankMemer/dank-memer-suggestions-and-bugs#1207]
**Describe the bug**
I want to be cleared from the ban of not being able to sell some cards.

**To Reproduce**
1. Go to '#bot-commands'
2. Type ~cards
3. Type ~sell dumb songhee
4. Error occurs that I'm not allowed to do

**Expected behavior**
I want to be able to clear my discord username from being banned.

**Screenshots**
![Screenshot_20200808-065848_Discord](https://user-images.githubusercontent.com/69391814/89711990-1a957b00-d94b-11ea-835f-63491ab2e321.jpg)

**Your User ID**
Mina14

**Additional context**
Pls I'm not a bot, so can you remove all my ban.

**Comment by PhantomFrenzy151** [comment]
This isn't Dank Memer, is it? This bug report forum is for Dank Memer only.

**Comment by mina1499** [comment]
It isn't but AltDentifier is from Dank Memer right? AltDintifier may have
blocked something I think.
Also how can I send gift to friends?

**Comment by PhantomFrenzy151** [comment]
Oh I forgot about AltDentifier. I have absolutely no idea how it works, but to gift items in dank memer it's pls gift <number> <item> <username>. I'm not sure if that's what you're asking about.

**Comment by mina1499** [comment]
Oh okay, I think AltDentifier is the one that "protected" my account from
realizing other commands and for the gift, I do everything Dank Memer tells
me but he shows up with a my account is new to send gifts.

**Comment by melmsie** [comment]
this has literally nothing to do with dank memer at all
