### ISSUE TITLE
blacklisted users should get to use mod commands too

### ISSUE THREAD

**Issue by evangelinecofi** [DankMemer/dank-memer-suggestions-and-bugs#1208]
so i've been blacklisted for a few days already (and im still not sure why) and i've been meaning to use the mod cmds and also the enable and disable command feature... but well im blacklisted so i cant use it just yet
for example today we had a friendly heist in our server but the admin forgot to disable heist for the heist starter and i was very well aware of it (and unfortunately the only one aware) but ofc i couldnt disable it and i couldnt find anyone to disable it... also if i used an alt i would/might break rule 3 and that wont be any good :/

i think  it would be nice if dank memer allowed mod cmds and also disable/enable cmd features for bl or bot banned people coz i use them a lot and life is hard...  might be asking for a lot tho

that's it thanks for reading

**Comment by PhantomFrenzy151** [comment]
Alts won't break rule three, as long as you don't use the currency.
