### ISSUE TITLE
Pls hax command

### ISSUE THREAD

**Issue by OreoCoder101** [DankMemer/dank-memer-suggestions-and-bugs#121]
Hello developers!

I'd like "pls hax" command on dank Memer, and ill explain how it works.

First, to use it you need a "Hacker's Laptop. When typing pls hax, there is a chance to hack a normal good Amount of money Or items and there is also a chance to get caught by cops with fines Or dying. Also there is a chnace to get a BIG AMOUNT but you need to complete a mini-game thats like some text like in "pls fish" boss and 5 sec time. Then if you fail there is 20% chance your Hacker's Laptop Will break. Now if you still complete the mini-game,  you will get a good Amount of money Or an item.

This is a command i really want, and the money hacked doesnt be hacked from real People. Also, if you are passive you can't use this command so it would be More better!

Thank you!

-OreoCoder

**Comment by OreoCoder101** [comment]
What do you thing guys?

**Comment by kablekompany** [comment]
> money hacked doesn’t be hacked from real People

Can’t speak for development fam on this but seems pretty useless to refactor the bot to only reward — the injection of coin without coin taken is not stimulus to the economy, it’s inhibiting of it. 

Aside, pls hack exists and totally real already.

**Comment by OreoCoder101** [comment]
Well, it actually could be hacked from real users..

**Comment by OreoCoder101** [comment]
And you need hacker's LAPTOP witch costs like 20k
