### ISSUE TITLE
Feature request-Stock system in dank memer

### ISSUE THREAD

**Issue by Rashbel** [DankMemer/dank-memer-suggestions-and-bugs#122]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem

**Describe the solution you'd like**
Maybe you could add a stock system to the currency section of dank memer, you will be able to to buy, sell and trade stocks, every certain amount of time stock prices will be published. 

**Describe alternatives you've considered**
It's not a problem, it's a feature request

**Additional context**
.

**Comment by kablekompany** [comment]
Duplicate
