### ISSUE TITLE
Visual error while using and viewing landmine

### ISSUE THREAD

**Issue by oyuncurobloxer3445** [DankMemer/dank-memer-suggestions-and-bugs#123]
**Describe the bug**
When you use the landmine, it says it will work for 4 hours. When you look at it's info, it says 12 hours. It also lasts for 12 hours.

**To Reproduce**
1. Buy a landmine if you don't have it
2. Use the landmine
3. See "You placed a landmine down! Anyone who tries to steal from you for the next **4 hours** has a 50% chance of instantly dying."
4. View info by typing "pls shop landmine"
5. See "If someone tries to steal from you there's a 50% chance they will die from blowing up. Lasts 12 hours."

**Expected behavior**
The bot saying 12 hours instead of 4 hours while using a landmine

**Screenshots**
![image](https://user-images.githubusercontent.com/63605945/79142821-ce836100-7dc4-11ea-8e44-2a3b677e10ef.png)

**Comment by melmsie** [comment]
fixed in next update
