### ISSUE TITLE
Gambling number change

### ISSUE THREAD

**Issue by Ely242** [DankMemer/dank-memer-suggestions-and-bugs#128]
So I'm sure we have lost a considerable amount of coins during gambling.
And I'm sure a lot of people have definitely gotten annoying lose streaks like up to 15+ loses in a row.
And alcohol does little to nothing in helping you or "boosting your luck"
**My suggestion is that the numbers you roll in gambling (1-12) is changed to (1-6) idk anything about coding or programming so idk how it works.**
**With the numbers like this, if you use alcohol you might actually be able to win at times with the help of the alcohol.**
Usually alcohol doesn't help any bit because you roll numbers like 2 and 12 or 4 and 10 and the alcohol only boosts your roll by +1 (one).

**Comment by melmsie** [comment]
No
