### ISSUE TITLE
Censor links through cell

### ISSUE THREAD

**Issue by Rhino149** [DankMemer/dank-memer-suggestions-and-bugs#129]
Idrk if its a bug or not but i found out its possible to dm advertise through dank memer by using cell and texting them the link it the bot should somehow censor the link to prevent dm advertising by it. 
![image](https://user-images.githubusercontent.com/56201800/79402751-6febed80-7f52-11ea-9d35-d22b9829a2d6.png)
                    (Me testing it)

**Comment by melmsie** [comment]
fixed in next update
