### ISSUE TITLE
Scaling issue on Appeals page

### ISSUE THREAD

**Issue by davidjcralph** [DankMemer/dank-memer-suggestions-and-bugs#13]
**Describe the bug**
On a 1440p monitor, the appeals page goes wonky

**To Reproduce**
Steps to reproduce the behaviour:
1. Obtain 1440p monitor
2. Visit https://dankmemer.lol/appeals
3. Enjoy the meme

**Expected behaviour**
I expected it to look like normal

**Screenshots**
<img src='https://u.derpyenterprises.org/pDJs'>

**Additional context**
I'm using the latest stable Edge Chromium. Please note I am not banned from Dank Memer.

**Comment by melmsie** [comment]
It's a caching issue I'm fairly certain. If you hard reload it should look as intended. Definitely a bug, but a harder one to fix than some CSS

**Comment by JLT3102** [comment]
it looks like an arrow
