### ISSUE TITLE
Pet Repeatedly Kills Whilst Maxed Stats

### ISSUE THREAD

**Issue by Cynquivy** [DankMemer/dank-memer-suggestions-and-bugs#131]
**Describe the bug**
This started just recently along with the recent status update. I've cared my pet dog for atleast 2-3 times a day and whenever I go online with non-empty stats, it randomly kills me for no actual reason. Moderators say that my luck is just bad, however this just happened 3 times in a row.

**To Reproduce**
1. Go online on any discord server with the bot with a pet
2. Run any command
3. See Error

**Expected behavior**
My pet shouldnt had killed me repetitively whilst my pet had maxed/good stats. Even with 80% Love, I shouldnt have been killed for no reason.

**Screenshots**
![20200417_095340](https://user-images.githubusercontent.com/63828727/79524570-7766e000-8093-11ea-96c6-847cdceeced2.jpg)

**Additional context**
I have nothing else to say.

**Comment by HexCoder101** [comment]
That seems actually not a bug, and my pet seems to be fine hwen running any command. Those happened on a 1 hour cooldwon, to 1 day cooldown.

**Comment by Pro496951** [comment]
Yeah must be a bug complaint to moderator again
