### ISSUE TITLE
Fake ID Finder

### ISSUE THREAD

**Issue by HexCoder101** [DankMemer/dank-memer-suggestions-and-bugs#132]
**Is your feature request related to a problem? Please describe.**
Always when i am about to go search some targets to rob, i always fine fake ID users and whatever i try, its so difficuilt to find their true name.

**Describe the solution you'd like**
I am introducing: Fake ID Finder which works like this:
When you use it, and you tell the name of the Fake ID target it will start the process, and when started the user will get notified about that. When that happens the user can stop it by typing a command named: "Pls findstop" or "pls fs" in any server. If the user is offline, you need to wait 10mins until it will reveal the name. And the chance of revealing it is 5-10%. And the req's to use this item would be atleast 50lvl+ or 3rd+ prestige. The item would not be bought from the shop, but from rare events you can get it if you type the event succesfully, but the chance to obtain it is way smaller than to obtaining bank note. Also, if the user enters a name that is not a fake id name currently in the server, then the dank memer will say something like: "Wtf, that isn't a fake id name dum dum."

**Describe alternatives you've considered**
I've been trying to use the discord search bar and some other tools to find the fake id person, but its difficuilt.

**Additional context**
N/A

**Comment by HexCoder101** [comment]
What do you guys think?

**Comment by HexCoder101** [comment]
mm

**Comment by HexCoder101** [comment]
?

**Comment by kablekompany** [comment]
bumping the issue won't get you acknowledgement of it. Patience is a virtue of which you are lacking.
