### ISSUE TITLE
Self-feeding pet

### ISSUE THREAD

**Issue by Suval1ne** [DankMemer/dank-memer-suggestions-and-bugs#133]
**origin of the plan**
When I forget or I don't have time to care for my pet for over a day, it usually kills me.

**Extra feature I'd like**
I have been thinking, that it would be funny Easter egg or a meme, that if your pet kills you or someone else it would count as a pls feed command and the pet would get food from that.
For example: You trie to rob UserX
UserX's dog named Doggo ate you alive when you tried to steel from UserX.
*+10-40% Hunger for UserX's pet*

**Additional context**
This feature is not very useful but it would be funny and sarcasticaly realistlic.

**Comment by lululemonspamiess** [comment]
Ya pets are not very good!
