### ISSUE TITLE
api request page text overflow

### ISSUE THREAD

**Issue by asportnoy** [DankMemer/dank-memer-suggestions-and-bugs#135]
**Describe the bug**
api request page text overflow

**To Reproduce**
1. Go to [](https://dankmemer.services/dashboard) and log in if required
2. Log in if prompted
3. Click "Request New"

**Expected behavior**
Text should fit in page

**Screenshots**
![image](https://user-images.githubusercontent.com/14863373/79628964-0d8a1d00-810b-11ea-8c1f-d2ed840e599a.png)

**Additional context**
also, when will the APIs be reopened?

**Comment by melmsie** [comment]
This is more of an issue for that repo, this repo is for the bot. Additionally, the api will likely not be open again for months, if at all.
