### ISSUE TITLE
'I'm Bored" event

### ISSUE THREAD

**Issue by lululemonspamiess** [DankMemer/dank-memer-suggestions-and-bugs#138]
**Is your feature request related to a problem? Please describe.**
Whenever I encounter a super rare event I think of big prizes. With the "I'm Bored" super rare event you get a slight 200 coins with a box of sand If you are lucky. 

**Describe the solution you'd like**
Maybe, there can be a good chance of a medium-tiered item like coin bomb, fake id or laptop. 
**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by melmsie** [comment]
this will be in the next update, just added it
