### ISSUE TITLE
Add a new pet? A dragon?

### ISSUE THREAD

**Issue by MrMudkip** [DankMemer/dank-memer-suggestions-and-bugs#139]
**Is your feature request related to a problem? Please describe.**
No, it isn't.

**Describe the solution you'd like**
I'd love to have a dragon pet added to "pls pet list"

**Describe alternatives you've considered**
N/A

**Additional context**
The pet would be in pls pet list 3 since pet list 1 and 2 are full

**Comment by HexCoder101** [comment]
Good idea!

**Comment by HexCoder101** [comment]
⠀

**Comment by lululemonspamiess** [comment]
Nice!

**Comment by melmsie** [comment]
more pets in the future are planned
