### ISSUE TITLE
Passive Mode is Annoying

### ISSUE THREAD

**Issue by Wepepepene** [DankMemer/dank-memer-suggestions-and-bugs#14]
**Is your feature request related to a problem? Please describe.**
Well I’m here to say that passive mode is annoying - rich people that have somehow got a lot of money are on passive because they don’t need anymore and we just can’t rob them.

**Describe the solution you'd like**
Either remove passive mode or make only advanced people (like prestige 3 or level 100) have it.

**Describe alternatives you've considered**
Robbing non passive people?

**Additional context**
I’m not the only one who doesn’t like this, like 75% of others also don’t; I always hear complaints in the dank memer channel of the server they’re in.

**Comment by catclaws118** [comment]
A marker for them is way more likely to happen than them being removed. It's a rich leaderboard, not a "who can I steal from today" leaderboard. Same reason fake IDs are still there, just with a different name.

**Comment by melmsie** [comment]
Frankly I don't care about this complaint. Passive mode has been long requested, and LOTS of people don't want to partake in the robbing system. It's not going anywhere, and we're not locking it down to only players who have played a ton.
