### ISSUE TITLE
Energy Drink

### ISSUE THREAD

**Issue by HexCoder101** [DankMemer/dank-memer-suggestions-and-bugs#140]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would want an item named: "Energy Drink". It would work like this:
When you use it you either Die from the drink toxins, get a small amount of energy boost, get a good amount of energy boost, get a HUGE amount of energy boost. Now, the energy boost would give you a bit of extra money on following commands:
Pls bet
Pls slots
Pls beg
Pls search
Pls pm
Pls fish
Events
Now on pls bet you would get an extra bit of money like this. Your going to get extra (amount of won divided by 20) on small boost, (amount of won divided by 15) on good boost, (amount of won divided by 10) on HUGE boost.
On slots, small is divided by 17, good 12, huge by 8.

On pls beg, you have a 0.50% bigger chance to get an item on small boost, 0.90% on good,
1.50% on huge. Also, you will always get a small amount of coins depending how big your boost is.

On pls search, you will always get a small amount of coins depending how big your boost is and by searching from sewer, you have a bigger chance to get a normie box: 0.50% on small, 0.90% on good, 1.50% on HUGE.

On pls pm, you will always get a small amount of coins depending how big your boost is and chance to get an item is boosted by 0.30% on small, 0.70% on good, 1.10% on HUGE.

On pls fish, you can get an extra amount of fish. On small, you can get 4 common fishes at max. On good, you can get 5 common fishes at max. On huge, you can get 5 common fishes at max and an item when getting a fish! There is also a chance to get boss in is 0.20% on small, 0.45% on good, 0.75% on HUGE. Also if you are fishing you might get items by a better rate depending on your boost level.

On dank memer events, On the small boost you have a 0.30% bigger chance of event appearing per command, on good you have a 0.70%, on HUGE you have 1.10% biggger chance to get an event to appear.

----------------------------------------------------------------------------------------------------------------------------------------

Chances to get things by using it:
50% to die.
30% to small.
15% on good.
5% on HUGE.

Item cost: 10k-30k.

Item description: "Get your day better by a fresh and good, Energy Drink! Use this item to get a BOOST of money in diffrent commands. But warning! It contains a lot of toxins and sugars to make the drink perfect, which may lead to poisoning and death. It's a 50/50, drink or not?

Text when you use it:
:energydrink_emoji: **ENERGY DRINK - EFFECTS**
There's a chance you'll die from the drink's toxins (meaning you'll lose all of your coins).

Do you still want to use this item? Please respond with `y` or `n` within 30 seconds.

Text when you die of it:

:energydrink_emoji: You start to feel extremely nauseous, and you throw up a few times. Your kidneys can't handle the amount of toxins took, so you die of **too big poisoning**.

Text when small boost:

:energydrink_emoji: You drink the whole bottle and start to feel yourself energized, with a small boost of energy!

Text when good boost: :energydrink_emoji: You drink the whole bottle and start to feel yourself energized, with a good boost of energy!

Text when HUGE boost:

:energydrink_emoji: You drink the whole bottle and start to feel yourself energized, with a HUGE boost of energy!

**Describe alternatives you've considered**
None.
**Additional context**
I worked really hard to type this and plan it, i hope that at least some part will be in use. Thank you!
![WhatsApp Image 2020-04-19 at 20 26 31](https://user-images.githubusercontent.com/62809598/79694911-40075780-827c-11ea-8fdd-caeb06d93e50.jpeg)
I also made that image so how it  would look like! Thank you i worked reallly hard for this.

I edited how it works a bit!

**Comment by HexCoder101** [comment]
Oh, and the energy drink would cost 15k.

**Comment by lululemonspamiess** [comment]
This is really good! Props bro!

**Comment by HexCoder101** [comment]
I edited it a bit so it can be read again. Sorry!

**Comment by HexCoder101** [comment]
oh god mel's gonna close this one too

**Comment by HexCoder101** [comment]
f
