### ISSUE TITLE
Drop command

### ISSUE THREAD

**Issue by cakebirthdaylol** [DankMemer/dank-memer-suggestions-and-bugs#143]
Somewhat like the ‘pls give’ command but not really- 
If someone were to say ‘pls drop <item>’ into a channel, then somebody else could type ‘pls grab’ and pick up whatever somebody drops
It could be used if you want people to race/fight over an item (because who doesn’t enjoy watching that)
- - Also, if there’s more than one item dropped at a time, then whoever types ‘pls grab’ first gets all the dropped items (or you could only allow one item to be dropped at a time, but then that’d be more confusing so idrk..)

**Comment by HexCoder101** [comment]
Depends..

**Comment by melmsie** [comment]
a giveaway system is planned later which is essentially the same
