### ISSUE TITLE
The Gambling Command

### ISSUE THREAD

**Issue by ShadowOof** [DankMemer/dank-memer-suggestions-and-bugs#147]
The gambling command has way too many possible outcomes. I have been stuck in the 0.7mil-1.3mil range for about 4 hours now and have rarely only dropped out of the range even below the 200 thousands. I'm suggesting to make the rates of winning higher than losing to make the game more enjoyable for people. (I'm not saying you should make it so you can never lose. Maybe like 40% win, 45% lose and 15% tie.) and make it like 9 numbers in the gambling instead of 12. Since I noticed that when I've been gambling the past 4 hours that I win like about 2 wins and a lose when I profit a little bit, but when I lose more than twice then that usually goes for about 5 bets until I win again. Therefore making the win to lose ratio very small. I know you're probably making it more realistic. But the game would be more enjoyable for people if you could win more often than lose since I've seen many people lose and even rage quit when they lose larger amounts of money. I know this text might be a little messy and jumbled up but I wanted to get the word out there asap. Please take this into consideration.

Sincerely, Fancy

**Comment by melmsie** [comment]
The real time odds are better than what you're suggesting.
https://i.imgur.com/QvtyOgF.png

**Comment by ShadowOof** [comment]
Well clearly not based on what I have earned vs what I have lost

**Comment by melmsie** [comment]
I just showed you the global rate over the last day. If you win less, that's a you problem.

**Comment by ShadowOof** [comment]
I know you did but I'm just saying the game would be more enjoyable if there is about 60% win, 35% lose and 5% tie global rates. Aka you make the chances of winning higher and losing lower

**Comment by ShadowOof** [comment]
and if it's a tie I feel like money should be refunded

**Comment by ShadowOof** [comment]
It's just impossible for me to enjoy something like this where I constantly lose

**Comment by melmsie** [comment]
Interesting that you just said in the issue 40% win, now you're changing it to 60% win bc I told you it was already higher.

Either way, entire thing is not happening, move on

**Comment by ShadowOof** [comment]
The rates that I mentioned we're suggestions. And the rates you showed we're globally not whats actually coded into the bot
