### ISSUE TITLE
"Pls mock" Bug

### ISSUE THREAD

**Issue by HexCoder101** [DankMemer/dank-memer-suggestions-and-bugs#149]
**Describe the bug**
When you type: "pls mock (text)" and there comes a tip, it doesnt show the text.

**To Reproduce**
1. Type: "pls mock (some text)" and do it until you get a tip.
2. See error.

**Expected behavior**
The tips would be added to the bottom, or no tips at all.

**Screenshots**
Okay, look at this. 
![Screenshot 2020-04-21 at 10 25 08](https://user-images.githubusercontent.com/62809598/79837950-ef4a4880-83ba-11ea-98e1-82585271c630.png)

**Additional context**
N/A

**Comment by melmsie** [comment]
yeahhhh will be fixed in the rewrite later, minor really
