### ISSUE TITLE
Passive mode disabled before 6 hours passed 

### ISSUE THREAD

**Issue by Saxtreme** [DankMemer/dank-memer-suggestions-and-bugs#15]
**Describe the bug**
After trying to disable passive mode before 6 hours had passed, the bot sent the message telling me that I had to wait 6 hours, then disabled it.

**To Reproduce**
1. Run "pls settings passive true"
2. After, run "pls settings passive false"

**Expected behavior**
What should have happened was that the 6 hour wait message should have sent with no follow up message, and the setting remains disabled.

**Screenshots**
![C8E1E558-CC12-488B-B407-605EC91C924C](https://user-images.githubusercontent.com/50342920/76470861-905ee000-63c7-11ea-9091-6af02469f902.jpeg)
![579682F3-274E-45E0-AD38-8ACB01A5F860](https://user-images.githubusercontent.com/50342920/76470869-96ed5780-63c7-11ea-892c-6bfb948d296a.jpeg)

**Additional context**
None.

**Comment by melmsie** [comment]
I'll get this fixed in the next few days, thank you

**Comment by melmsie** [comment]
Looking at this again, this isn't a bug. It's telling you you can't turn it back on for x hours
