### ISSUE TITLE
Check Your Stank Rate

### ISSUE THREAD

**Issue by DylanCP** [DankMemer/dank-memer-suggestions-and-bugs#151]
**Is your feature request related to a problem? Please describe.**
I thought that a howstank command could add a variety of fun rng command like howgay, epicgamerrate, etc, especially when Carl has it too in the server as a tag.

**Describe the solution you'd like**
Create a fun rng command of how stanky you are with the cmd "howstank", with possible aliases such as "howstanky", "stankrate", "stankyrate", etc.

**Describe alternatives you've considered**
Well, unfortunately I can't think of any alternatives that fit for this.

**Additional context**
There's no additional context/screenshots

**Comment by melmsie** [comment]
sure why not, will be added in next update
