### ISSUE TITLE
New pet idea Rhino

### ISSUE THREAD

**Issue by Rhino149** [DankMemer/dank-memer-suggestions-and-bugs#152]
I would love to see a Rhino become a pet lol it would be like the pepe one where it doesnt need much feeding and lots of water  but if someone somehow forgets about it for awhile the part where it kills you says.
"**Your pet Rhino Felt extremely unloved and charged right at you breaking your spine on impact and killing you.**"
But theres a chance it will runaway and when it does it says this.
"**Your pet Rhino felt imprisoned and super unloved it decided to runaway back to its family**"

**Comment by HexCoder101** [comment]
ehhh

**Comment by melmsie** [comment]
lol
