### ISSUE TITLE
Warn Before blacklist/ban

### ISSUE THREAD

**Issue by TexRexTex** [DankMemer/dank-memer-suggestions-and-bugs#154]
**Is your feature request related to a problem? Please describe.**
I was just banned today from the currency commands and I didn't even realise i was doing anything wrong.

**Describe the solution you'd like**
I think there should be a warn before banning someone so when people do things wrong they get warned so they know they're doing something wrong and maybe also a link to the rules.

also if they've been unbanned they wouldn't get a warn.

**Additional information**
this is not for my benefits I'm all ready banned, but i didn't realise what i was doing was wrong and i don't want this to happen to other people.

**Comment by MrMudkip** [comment]
I agree with you.

**Comment by kablekompany** [comment]
The warning is at https://dankmemer.lol/rules as well as in tips, as well as in the server, the reddit, and like everywhere else.

**Comment by TexRexTex** [comment]
Well that warning obviously didn't work otherwise I wouldn't have been banned.

**Comment by kablekompany** [comment]
That's like saying you blame the red light for getting a ticket when you run it lmfao. I digress, pretty low effort issue here in my opinion. However, dev's have now made it where blacklists have a fuse. Allowing users a second opportunity to use the bot in a conducive fashion.

**Comment by TexRexTex** [comment]
People will know they'll get a ticket from doing that thou.
