### ISSUE TITLE
Selling all of one item

### ISSUE THREAD

**Issue by RandomTurtleBoi** [DankMemer/dank-memer-suggestions-and-bugs#156]
This isn't related to a problem, but i think `pls sell <itemName> all` should be a thing, so you don't have to check how many of an item you have in your inventory, then specify the exact number to sell all of your items. For example, say you have 36 fresh breads, and you want to sell them for coins. You can just do `pls sell bread all` and it sells all your 36 breads.

**Comment by HexCoder101** [comment]
Hmmm, good one!

**Comment by lululemonspamiess** [comment]
all is a pink phallic object

**Comment by RandomTurtleBoi** [comment]
yes mel added it i think
