### ISSUE TITLE
pls simprank

### ISSUE THREAD

**Issue by SergeTFM** [DankMemer/dank-memer-suggestions-and-bugs#159]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Make a pls simprank command

**Describe alternatives you've considered**
Well, there aren't any but if you do you can make it pls simp instead of pls simprank

**Additional context**
I would like a pls simp/simprank command that will basically be like pls howgay or pls waifu or pls stankrank.

**Comment by HexCoder101** [comment]
i dont think it will come lol

**Comment by RandomTurtleBoi** [comment]
you won

**Comment by SergeTFM** [comment]
i indeed won
