### ISSUE TITLE
Nerf Passive mode

### ISSUE THREAD

**Issue by Druva-D** [DankMemer/dank-memer-suggestions-and-bugs#16]
Passive Mode is too OP, this decreases my income is a bank-robber (and gambler)

**Describe the solution you'd like**
You can make passive mode as **less chance** to get stolen from or bank-robbed but not completely no chance,

**Describe alternatives you've considered**
you can also decrease the amount of time a user can stay in passive mode for continuously

**Comment by JLT3102** [comment]
No!!
