### ISSUE TITLE
pls inv supports decimal numbers

### ISSUE THREAD

**Issue by SergeTFM** [DankMemer/dank-memer-suggestions-and-bugs#160]
**Describe the bug**
If you do pls inv 4.20420420420420420 for example, it will show in the bottom of the embed
"Owned Items ─ Page 4.2042042042042045 of 5"

**To Reproduce**
1. Go to any bot channel
2. Type "pls inv" with any decimal number that the first number is actually a page that you have
3. Look in the bottom of the embed
4. See decimal number

**Expected behavior**
It should say "Hey idiot, page 4.20420420420420420 doesn't exist. There's only 5 pages"

**Screenshots**
Screenshot:
![image](https://user-images.githubusercontent.com/50763771/80211448-70fdd880-863e-11ea-9afe-32da86c7ab5e.png)

**Additional context**
This isn't bot breaking but I do think it's a bug.

**Comment by melmsie** [comment]
fixed in next update probably
