### ISSUE TITLE
Voting/upvoting not working properly

### ISSUE THREAD

**Issue by Goofierknot5537** [DankMemer/dank-memer-suggestions-and-bugs#161]
**Describe the bug**
I voted on all four votes, which meant I should’ve gotten 4 normie boxes. I ended up with 2.

**To Reproduce**
1. Do “pls vote”
2. Vote on all websites
3. Then it happened

**Expected behavior**
I expected to get 4 normie boxes as usual

**Screenshots**
https://share.icloud.com/photos/0hXrhHikjUybg4D_wKq7Lahnw

**Additional context**
I don’t know if this can happen again or be reproduced, if I get 4 normie boxes again from voting I’ll delete this post. #

**Comment by SergeTFM** [comment]
It's a 3rd party client so probs lag from their side but idk
