### ISSUE TITLE
Insurance or something related to it

### ISSUE THREAD

**Issue by Akash9409** [DankMemer/dank-memer-suggestions-and-bugs#164]
**Is your feature request related to a problem? Please describe.**
Today I lost all my coins since I died in a hospital on dank memer. The coins were a lot like 90k+ and now I thought this might have been happened with so many people.
**Describe the solution you'd like**
An insurance or something so if you die you get all your coins back. 

**Describe alternatives you've considered**
An alternative can be a time travel or something where I save myself from dying and get my coins back or something innovative like time travelling and taking money from my past self or something like that.

**Additional context**

**Comment by klin08** [comment]
You can easily buy 5 lifesavers with 90k. That way u don't die.
