### ISSUE TITLE
Trick Die

### ISSUE THREAD

**Issue by ToPhu31** [DankMemer/dank-memer-suggestions-and-bugs#167]
**What is the Trick Die?** 
The Trick Die is used during the stages of betting. It essentially increases the chance of winning by removing the chance of rolling 1, 2, and 3. This allows you to only roll 4-12. Dank Memer, the dealer, however won't receive this effect.
I know rolling usually involves two dice, but I thought 4 would be too overpowered, still, it's your choice.
**Effects**
  •  Increase chance of winning gambles
  •  One Use
  •  20-30% of getting caught and losing your bet.
      • When you get caught, you not only lose the bet but also have a chance to get beat up by Dank Memer's cronies (50%), either dying or losing even more money (2000-10000$)
  •  Can not be used with alcohol (Because when your drunk, you don't know what the <bad word> you are doing)
  •  Can be bought for 25000 DMC
  •  Can be found during events
  •  Can be found using "pls search" 
  •  Can be found by pets
**Why Trick Die?** 
I feel like this would encourage betting even more, and adding new aspects to betting.

**Comment by HexCoder101** [comment]
Damn, dying from some beat up and so is complicated.. i don't know..
