### ISSUE TITLE
Add a cooldown to pls tictactoe

### ISSUE THREAD

**Issue by xmoreno21** [DankMemer/dank-memer-suggestions-and-bugs#168]
It's always annoying when people want to spam you with pls tictactoe and eventually this prevents you from using commands in that channel. It could be used to prevent people from calling the police in a heist or just when someone wants to be mean.

I would like it so one person cannot create more than one tictactoe request at a time, or increase the cooldown to something more reasonable, like 30 seconds.

![tictactoe bad](https://user-images.githubusercontent.com/40253866/80330621-8881c080-87fa-11ea-955e-b02870513f01.JPG)

As you can see, spamming that command on someone inhibits them from running commands.

**Comment by chegde01** [comment]
Again, this feature shouldn't be added as it removes the tactical nature of this game.

**Comment by andrewisaboomer** [comment]
nah thats not tactical its just a pain in the ass

thats like shutting down someones computer every time they open it because "its just the tactical nature of life"
