### ISSUE TITLE
Disable the wallet limit.

### ISSUE THREAD

**Issue by TrainerEevee615** [DankMemer/dank-memer-suggestions-and-bugs#17]
Sometimes, the bank just isn’t big enough to store, like winning the lottery, or trading with someone. If the wallet has a limit, doesn’t that make us unable to hold money as much as we want? People can’t rob us if we have passive on, so please disable/delete the wallet limit.

**Comment by Druva-D** [comment]
Isn't wallet limit only for giving, you can gamble and sell items all u want

**Comment by kablekompany** [comment]
Dev **temporarily** raised the wallet hold amount in acknowledgement of the pandemic that is Coronavirus. The buff won't last forever. There's some other temp buffs you can check out in their update channel on the official server. Stay healthy, and get rich.
