### ISSUE TITLE
Automatic pls ui when someone joins a server

### ISSUE THREAD

**Issue by William9451** [DankMemer/dank-memer-suggestions-and-bugs#171]
**Is your feature request related to a problem? Please describe.**

For new and existing dank servers, member compliance with the rules could often be a constant worry. Therefore, managing the existence of alts and/or brand new accounts, incapable of sharing, within a server would be particularly helpful. This is because the recent growth of the bot and as a result the popularity of dank servers, could make manually checking the ui of every new member a little much. I therefore propose that a possible auto response from dank regarding a new member and their basic account details could be useful. 

**Describe the solution you'd like**

Perhaps not the existing command but a simplified version of the current “pls ui” could show when an account was made and it’s commands used, giving a good indication of the nature of the account and it’s likely compliance with the rules and the recently imposed 2 week minimum for sharing. Although the pls ui function is already quite simplistic, removing the join date and pfp of every individual could, I assume, greatly reduce the stress on the main bot servers of this suggestion. 

**Describe alternatives you've considered**

The only real alternative is manually checking the accounts which would likely get quite tedious. Other bot join messages triggering the command is (sensibly) not possible and therefore aside from self bots (against discord tos) there is no current way to automate this process, hence the suggestion

**Additional context**

n/a

**Comment by melmsie** [comment]
unlikely to add
