### ISSUE TITLE
Melmsie bug.

### ISSUE THREAD

**Issue by HexCoder101** [DankMemer/dank-memer-suggestions-and-bugs#172]
**Describe the bug**
Melmsie needs to be fixed. He adds wontfix label to every suggestion without reading it. Please fix it and dont put wontfix kabel now. He also blacklisted many people for kinda fun, like.

**To Reproduce**
1. Go ahead and click new issue.
2. Click feature request.
3. Type a good feature request that's kinda long.
4. Post it.
5. See error.
**Expected behavior**
Melmsie would read all of those suggestions and bugs clearly, and won't blacklist people for posting 2 suggestions. That's not even in the rules like, tf.

**Screenshots**
I swear he didnt even read it. Right after he came online, he placed wontfix label on my other suggestion, and then automatically to this.
![Screenshot 2020-04-28 at 06 39 23](https://user-images.githubusercontent.com/62809598/80444761-2ff61480-891b-11ea-9206-4a4c65ec355d.png)
![Screenshot 2020-04-28 at 06 39 10](https://user-images.githubusercontent.com/62809598/80444763-31bfd800-891b-11ea-8317-fbbf44ec34d3.png)

f
**Additional context**
Don't blacklist me for 2 suggestions

**Comment by Rhino149** [comment]
maybe hes using it as a substitute of a wont add tag

**Comment by HexCoder101** [comment]
i know

**Comment by HexCoder101** [comment]
Who agrees to this bug confirmed?

**Comment by HexCoder101** [comment]
me

**Comment by Rhino149** [comment]
and plus theres most likely other reasons they got bot banned or bot blocked.

**Comment by Rhino149** [comment]
theres been ban waves recently so its most likely what i said just before

**Comment by melmsie** [comment]
I didn't blacklist you for making your terrible suggestions you idiot. However now you're banned from posting here.
