### ISSUE TITLE
Pls pet play requires more than needed words on unscramble

### ISSUE THREAD

**Issue by thewilloftheshadow** [DankMemer/dank-memer-suggestions-and-bugs#173]
**Describe the bug**
When playing the unscramble game in `pls pet play`, when i get above the number of points needed, i always have to complete one more word

**To Reproduce**
1. pls pet play
2. once you get an unscramble game, do the 3 point one three times so you have 9 points out of the needed 7
3. it will still list new words and wait for an answer
4. any correct answer will then finish the pls pet play

**Expected behavior**
Once you get the required number of points, you finish the game

**Screenshots**
~~I'll try to get a screen recording next time I get an unscramble game in pls pet play~~
https://youtu.be/LZowXB_DPas

**Comment by melmsie** [comment]
please get me screenshots

**Comment by thewilloftheshadow** [comment]
Done: https://youtu.be/LZowXB_DPas
