### ISSUE TITLE
Add discordbotlist.com in the vote list

### ISSUE THREAD

**Issue by rayhan6726** [DankMemer/dank-memer-suggestions-and-bugs#175]
**Is your feature request related to a problem? Please describe.**
Not a problem, maybe a bug. The discordbotlist.com is still giving normie box.

**Describe the solution you'd like**
Re-add the discordbotlist.com on the vote list.

**Describe alternatives you've considered**
Add Octave and Apex Legends bots in discordbotlist.com too if it's possible.

**Additional context**
None.

**Comment by Wise2006** [comment]
Fixed

**Comment by melmsie** [comment]
They are not currently added as the site is riddled with bugs so I don't want to send users there at this time.
