### ISSUE TITLE
Pet Update/Overhaul? & Pet Quest Flaw

### ISSUE THREAD

**Issue by Suevi** [DankMemer/dank-memer-suggestions-and-bugs#182]
So the "Buy a Pet' quest requires you to buy a pet to complete the quest. The problem I find with this quest is that it requires you to disown your current pet (assuming you already have one). Then you have to buy a new pet with the quest active. I want to complete all the quests because I feel like there's a secret multiplier behind it. I already have a pet Pepe and it's at a high level so if I wanted to complete this quest, I'd have to disown it and then buy a new Pepe, effectively paying 350k for a Pepe pet because I forgot the "Buy a Pet" quest existed.

So my suggestion would be to add (at least for the "Buy a Pet" quest) something to detect that you already own a pet. The reason this quest should have this feature over other quests having the same feature is that if we compare the "Buy a Pet" quest to something like "Streaker" quest, you could have a 40 day streak with that quest and then keep progressing that streak to 50 in order to complete it. With the "Buy a Pet" quest, since there's no way to store pets or have multiple pets. If you never knew about quests or completely forgot to activate the quest before buying your pet then you'd face the same problem where you'd waste time gaining experience for your pet and then paying double the price for it at the same time. I'm sure you can see the differentiation between this quest and others.

Some other ideas are to possibly overhaul the pet part of the bot and maybe make it possible to have multiple pets that could have multiple functions. Without straying away fro the bot's main focus which is coins. There's a lot of ideas you could come up with to resolve this issue, but I think an overhaul to the pets with the bot which allows you to house multiple pets would be a cool feature, I believe there was a recent vote for things we wanted to have updated and pets were one of the choices to vote on.

Sorry for any run-on sentences or anything like that, I'm basically writing down my thoughts, I hope it's fairly readable.

**Comment by melmsie** [comment]
quests and pets are getting an overhaul later this summer
