### ISSUE TITLE
pls Work bug

### ISSUE THREAD

**Issue by XavPigMC** [DankMemer/dank-memer-suggestions-and-bugs#183]
![image](https://user-images.githubusercontent.com/57669890/80864778-1808f280-8c85-11ea-923a-a0e1893fa885.png)

The bot lagged and i was impatient, so i typed "pls work again" and looks like i was a bit slow and the pls work command ran 2 times, the first one was a fail, since my work was "pls work".

**Comment by melmsie** [comment]
known issue
