### ISSUE TITLE
Auto vote

### ISSUE THREAD

**Issue by Sanitizedcoffee** [DankMemer/dank-memer-suggestions-and-bugs#184]
Some people do not have acsess to internet and/or wifi but still want to vote for the bot. 

There should be an Auto Vote command where you can automatically vote for the bot. 

I haven't really found any alternatives to that. 

There is no additoinal context, i hope whoever is reading this has a wonderful day/night💖

**Comment by RandomTurtleBoi** [comment]
I don't think Dank Memer can make you vote for yourself, you need to log in and manually vote for the bot. Top.gg, discord bot list, and everything else needs your login with a password. That's gonna be one hell of a "discord account login frenzy" 24/7.

**Comment by melmsie** [comment]
not possible
