### ISSUE TITLE
Search Location: Reddit

### ISSUE THREAD

**Issue by ToPhu31** [DankMemer/dank-memer-suggestions-and-bugs#188]
**Is your feature request related to a problem? Please describe.**
We have discord as a search option, why not other platforms?

**Describe the solution you'd like**
Since reddit has r/memes, which is where Dank Memer's memes are supplied from, it'd be a nice addition for reddit to be on there

**Describe alternatives you've considered**
Youtube search location

**Additional context**
No.

**Comment by RandomTurtleBoi** [comment]
where would you find coins on reddit? r/memeeconomy?
