### ISSUE TITLE
Regarding to the latest update

### ISSUE THREAD

**Issue by lyl-jerry** [DankMemer/dank-memer-suggestions-and-bugs#189]
**Is your feature request related to a problem? Please describe.**
Yes. In the most recent update, gambling is nerfed and most other commands are buffed. Before this nerf occurs, most people are able to make money from gambling. It also became a way for people to catch up with the other insanely rich people. The gap between the rich and the poor is therefore reduced. However, gambling is no longer profitable now, with no luck boost and low multiplier. Meanwhile, stealing and other commands are also buffed. This would attract a lot more people to go to passive mode as gambling is no longer needed, they have to avoid stealing and they can make a lot more money with other commands. Now, everyone needs to grind a lot harder to catch up with those rich people, while PVP interactions will decrease.

**Describe the solution you'd like**
Reverse the nerfs to gambling.

**Describe alternatives you've considered**
Increase the average % of bet won

**Additional context**
After grinding like half a month, I got from 100k to 2mil in 3hours by gambling, which is why I like this game so much. Once you know how to be rich, you will be rich.

**Comment by RandomTurtleBoi** [comment]
Admit it, gambling _was_ pretty op jto begin with.
