### ISSUE TITLE
Make this a template for the images category

### ISSUE THREAD

**Issue by Meltinglce** [DankMemer/dank-memer-suggestions-and-bugs#19]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I'd like this to be a meme template
![image](https://user-images.githubusercontent.com/35200979/76675867-77575a00-6594-11ea-855c-1ced448385cc.png)
the command could be something like pls whygod

**Describe alternatives you've considered**
none.

**Additional context**
Once you use the command, you put something after it so the text goes in the 3rd box and it's whatever you want

**Comment by melmsie** [comment]
will take this into consideration

**Comment by HexCoder101** [comment]
assigned???

**Comment by GeoffreyWesthoff** [comment]
This has been implemented with https://github.com/DankMemer/imgen/commit/c63802123e2f3aebfde9b02b768b4722f952f2fd
