### ISSUE TITLE
Working hours

### ISSUE THREAD

**Issue by lyl-jerry** [DankMemer/dank-memer-suggestions-and-bugs#190]
**Is your feature request related to a problem? Please describe.**
Yes. The working hours are now becoming unreasonable after the update. It is understandable that at least 1 hour each is needed for all jobs. However, for some jobs, they require 5 to even 10 hours a day, which means people will have to log into discord and play every hour in order not to get fired. This would limit those not-so-active people to work only as housewife and YouTuber. 

**Describe the solution you'd like**
Reduce the difference in working hours between all jobs.

**Describe alternatives you've considered**
Make some allowances to workers where to might not need to fulfil the requirement every day, besides using cell phones

**Additional context**
There is nothing I need to add.

**Comment by RandomTurtleBoi** [comment]
Tbh my job is dictator with 10 hours of work a day and I'm still fine with only 2 hours of work a day.

**Comment by melmsie** [comment]
> which means people will have to log into discord and play every hour in order not to get fired. This would limit those not-so-active people to work only as housewife and YouTuber.

Then those people don't need those high paying jobs.
