### ISSUE TITLE
Previous/Next Level Continuous Reward Duplication

### ISSUE THREAD

**Issue by Lgreenbunny** [DankMemer/dank-memer-suggestions-and-bugs#192]
**Describe the bug**
I believe that I got multiple level rewards by losing and gaining enough experience to go back and forth between levels.

**To Reproduce**
1: Lose enough experience to lose a level on your profile
2: You get the rewards for the current level you're on.
3: Get enough exp to get to the next level
4: Get the rewards for that level as well.
5: Repeat to duplicate rewards.

**Expected behavior**
I expected no reward for losing a level, and I expected one reward for leveling up to level 21.

**Screenshots**
![image](https://user-images.githubusercontent.com/32439466/80919891-67f5c100-8d3a-11ea-9e20-bdbcd5878174.png)

**Additional context**

**Comment by Wise2006** [comment]
This is happening to me too! 
![Error](https://user-images.githubusercontent.com/45759535/80940279-f0d53100-8dfc-11ea-9ca0-dd60cc8ef0d0.PNG)
Hope you fix it soon!

**Comment by alexmehta** [comment]
Its happening to me to but with quests.
