### ISSUE TITLE
pls shop information

### ISSUE THREAD

**Issue by ToPhu31** [DankMemer/dank-memer-suggestions-and-bugs#194]
**Describe the bug**
The new update states that banknotes can give 2500 bank space, but on pls shop banknote the description says that it can give only 1000 even though the result is different.

**To Reproduce**
pls shop bomb
pls shop bank

**Expected behavior**
A correct and updated description of the coin bomb and bank note

**Screenshots**
[Bug](https://imgur.com/a/7SCDSXm)

**Comment by SergeTFM** [comment]
alcohol too btw it says it can give luck in gambling
