### ISSUE TITLE
Hidden multis - being locked out

### ISSUE THREAD

**Issue by griff27** [DankMemer/dank-memer-suggestions-and-bugs#195]
**Is your feature request related to a problem? Please describe.**

One of my goals is to also get all of the hidden multis and it makes me really upset that I’ve apparently locked myself out of one of them .. “good boye”... I really wish you would reconsider locking out multis like that...what is the point in using commands then being locked out of a multi?? I think hidden multis are some of the best things to look for in playing with the bot. How would it feel if you’re trying to get 100% in a game and you’re at 80% and they tell you nope too bad you’ll never have 100%? Food for thought. Something to think about.

**Describe the solution you'd like**
Add cool down to unlock multis if previously locked out
**Describe alternatives you've considered**

**Additional context**

**Comment by melmsie** [comment]
sounds like a you problem, you can only lose that one from saying blacklisted words.
