### ISSUE TITLE
dank memer feature

### ISSUE THREAD

**Issue by human1232131231** [DankMemer/dank-memer-suggestions-and-bugs#196]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
It would be cool if you could do like pls scope @jesuschrist#1234 and it would like tell if he has padlocks or landmines so it wouldn't be such a guessing game.
**Describe alternatives you've considered**

**Additional context**

**Comment by RandomTurtleBoi** [comment]
just do `pls profile <user>` and you can see everything they have on them. This includes their level, coins, inventory value, and active items like padlocks, landmines, and fakeids. It even tells you when those active items expire.
