### ISSUE TITLE
Marrying

### ISSUE THREAD

**Issue by seenaer** [DankMemer/dank-memer-suggestions-and-bugs#198]
I would like to suggest, marrying type of thing, like many other bots, there is a type of marrying thing, wether you buy rings, and propose or just simply marrying. Like if you marry, your banks murge together, and you can say pls spouse and it would say you are married to [@]. I would really appreciate if you did this. Thanks.
- $𝚒𝚕𝚟𝚎𝚛#6966

**Comment by RandomTurtleBoi** [comment]
um

**Comment by Wise2006** [comment]
hmm...
 I don't think this will be accepted.

**Comment by melmsie** [comment]
we already have plans for fuck buddy system
