### ISSUE TITLE
Automatic Selling

### ISSUE THREAD

**Issue by 439oniichan** [DankMemer/dank-memer-suggestions-and-bugs#20]
**Is your feature request related to a problem? Please describe.**
Whenever I get bread, chill pill I always have to sell it myself and it's always a pain for me.

**Describe the solution you'd like**
A feature that would automatically sell specified items. For example if I got bread from the command 'pls beg' it would usually go to my inventory but if you have automatic selling for bread on it would sell it instead.

**Describe alternatives you've considered**
None, I only have that one solution.

**Additional context**

**Comment by JLT3102** [comment]
it should be on settings like pls autosell bread,and bot responds with,alright every bread that will go in your inventory will be sold.Good suggestion

**Comment by melmsie** [comment]
We're not interested in this at this time.
