### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by deezyy** [DankMemer/dank-memer-suggestions-and-bugs#201]
Hey dank memer bot, i got suddenly blacklisted today because of breaking some rule i guess. I don’t know which rule i broke because i was just focusing on getting money and doing pls beg etc. Can i get unblacklisted by any chance and i promise i will never break a rule again because now i readed the rules very carefully and i remember them very good now and i know what not to do. Thanks greetings. Chris

**Comment by RandomTurtleBoi** [comment]
Most likely this won't happen, but if you want to get back on the bot as soon as possible, you can do `pls removemydata` and it will wipe **all** your info from the bot including your blacklist. Or you can just wait for a week or two and you're gonna be back with everything you previously had. Your choice.
