### ISSUE TITLE
Option to sell in bulk 

### ISSUE THREAD

**Issue by insanerawrz** [DankMemer/dank-memer-suggestions-and-bugs#202]
My suggestion  is that we are able to sell more than 1 item from your inventory at a time
 Ex: i.got 24 common fish and i have to spam "pls sell fish" 24 times.  Would save time to give it same option as gifting does.

**Comment by V3NOM2802** [comment]
That is already a thing, try out "pls sell fish <quantity>", Example: "pls sell fish 8" would sell 8 common fishes @insanerawrz

**Comment by insanerawrz** [comment]
Wow. I tried that before and NOTHING. I try it again and wow you are right.  I'm do sorru
