### ISSUE TITLE
Can we add a BitCoin mining feature? (if you have 5 laptops, you can mine BitCoin)

### ISSUE THREAD

**Issue by MadScriptCode** [DankMemer/dank-memer-suggestions-and-bugs#208]
**Is your feature request related to a problem? Please describe.**
I currently have 5 laptops, and I was thinking, what if you could do something more than just post memes with them?

**Describe the solution you'd like**
I would like for a "mine" command to be added, and it the response should be something like this:
"You went mining for Bitcoin and got XXX coins." The earnings should be slightly higher than that of postmemes, though. The requirement should be that you have at least 5 laptops (or some other number).

**Describe alternatives you've considered**
Another thing you can do is add an item to the shop called "mining rig", which you can buy to use the "mine" command.

**Comment by RandomTurtleBoi** [comment]
I think they've discussed the mine command already, like they're considering on adding it but haven't leaked much info yet.

**Comment by lyl-jerry** [comment]
and I think bitcoin mining command should not be dependent on the number of laptops as this would become strange as usually one item only has one feature in the game. Rather I would say that Bitcoin mining can also be done with one laptop, but the laptop will have a higher chance to break and you are also prone to lose money when the Bitcoin price drops
