### ISSUE TITLE
Trivia command

### ISSUE THREAD

**Issue by pizzablablabla96** [DankMemer/dank-memer-suggestions-and-bugs#209]
**Is your feature request related to a problem? Please describe.**
Everytime I go to do Trivia with the Dank Memer bot, it tells me "you have 8 seconds". That is not NEARLY enough time to actually read the question and answers and think of an answer. You really please need to give peoppe more time to read it and think about it. Some people wear glasses as well like myself and slower eyes. Everytime I do it, I have to quickly SKIM through it without even really getting every detail because the bot never gives you nearly enough time. 

**Describe the solution you'd like**
Maybe give us more time to read it and the answers and to think about it before answering? Because 8 seconds is really not nearly enough time at all. Sorry, im not trying to be rude.  But it's just frustrating me.

**Describe alternatives you've considered**
Getting another trivia bot if this isn't fixed.

**Additional context**
Nothing really besides just please add more time to the trivia command with the bot. Maybe like at least 15 seconds?

**Comment by melmsie** [comment]
no
