### ISSUE TITLE
pls search "feature"?

### ISSUE THREAD

**Issue by StevenRafft** [DankMemer/dank-memer-suggestions-and-bugs#21]
**Is your feature request related to a problem? Please describe.**
when you run pls search if you type a wrong letter or extra letter by mistake you can't search again until the counter is over,example:
A-pls search
B-Where do you want to search? Pick from the list below and type it in chat.
   mailbox  hospital  couch
A-mailboc
B-what are you THINKING man that's not a valid option from the list??
A-pls search
B-Slow it down, cmon
You've already scouted the area for coins, try again in 28 seconds
The default cooldown is 30s

**Describe the solution you'd like**
maybe do it like the laptop when you type a wrong letter you can use the laptop again

**Describe alternatives you've considered**
idk what to say here

**Additional context**
neither here

**Comment by melmsie** [comment]
This system is in place to prevent people who spam the command without a cooldown for free xp, won't fix
