### ISSUE TITLE
Message says to bet a whole number greater than 0 instead of 100

### ISSUE THREAD

**Issue by SergeTFM** [DankMemer/dank-memer-suggestions-and-bugs#211]
**Describe the bug**
The bot says "Needs to be a whole number greater than 0 yeah?" when trying to blackjack 53.54545 for example
**To Reproduce**
1. Go to any bot channel
2. Type 'pls blackjack 55.56665656565
4. See that bot doesn't say 100

**Expected behavior**
Bot should say "Needs to be a whole number greater than 100 yeah?"
**Screenshots**
![image](https://user-images.githubusercontent.com/50763771/81377206-a78f2500-910d-11ea-903b-1a87dc701309.png)

**Comment by Wise2006** [comment]
This has expired?

**Comment by SergeTFM** [comment]
this happens on blackjack too
![image](https://user-images.githubusercontent.com/50763771/81377126-83cbdf00-910d-11ea-8750-9e5429ba4c3b.png)
