### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by alexmehta** [DankMemer/dank-memer-suggestions-and-bugs#215]
**Describe the bug**
Dank Memer will give you your reward for quests two times if you do pls quest after completing but the bot hasn't given it yet.
**To Reproduce**
1. Start a quest
2. After completing the quest, before the bot mentions you saying that you got the reward, do pls quest. 
3. You should get 2 mentions at the same time and you will have double the reward. 

**Expected behavior**
To have double the reward then expected.

**Screenshots**
Here is what happens when given the reward 2 times.
![dankmemerbug](https://user-images.githubusercontent.com/53285116/81244537-99cf8780-8fc7-11ea-894c-6df94b31b580.PNG)

**Additional context**
This may have to do with being on a server with lots of people doing bot commands at the same time, since the server I was on has 90k members and lots in dank memer chat.

**Comment by melmsie** [comment]
will be fixed later this summer in our rewrite

**Comment by CodedLightning** [comment]
Someone told me about it recently; I tried it and it worked.
To be specific, I got double rewards one the Shopper quest.
