### ISSUE TITLE
upon winning the lottery, be placed into passive mode

### ISSUE THREAD

**Issue by tristingreenstein** [DankMemer/dank-memer-suggestions-and-bugs#216]
upon winning the lottery, be placed into passive mode regardless of last time you toggled passive. If you win at 3am and you are sleeping but some jackass decides to rob you, it would be very sad.

**Comment by ToPhu31** [comment]
You get put into an one hour grace period where you have time to use your money, and it is on you if you get robbed. If you don't want to be robbed, just stay in passive mode.
