### ISSUE TITLE
A suggestion to make Dank Memer more interesting. 

### ISSUE THREAD

**Issue by someonerw1122** [DankMemer/dank-memer-suggestions-and-bugs#218]
**Is your feature request related to a problem? Please describe.**

It is not related to a problem.

**Describe the solution you'd like**

It would be cool if there was a house shop and you can buy houses from it. There would be different types of houses like Box houses (For the poor) and Mansions (For the Rich).

**Describe alternatives you've considered**

Maybe even add cars and a map, each server has its own map and you can drive around in that map looting different places and also you can rob people's houses for coins or something in there inv.

**Additional context**

It would be cool and some of my friends would like this update too.

**Comment by ToPhu31** [comment]
That'd be way too much for the developpers...

**Comment by lyl-jerry** [comment]
What about a in-game stock market with 10 stocks? It would be another interesting way to make money.
