### ISSUE TITLE
pls pet play glitch

### ISSUE THREAD

**Issue by ScrubiDub** [DankMemer/dank-memer-suggestions-and-bugs#219]
Description:
When "pls pet play" is executed with no coins in the wallet, and if it charges you coins, it actually produces that number of coins in the wallet.

1. have an empty wallet
2. do "pls pet play"
3. two things happen
 a. it doesn't charge you coins, in which case the bug will not occur
 b. it charges you coins, i.e it costs you 82 coins to get ripped at the gym

If you check your balance now, you will see that 82 coins has appeared in your wallet, rather than subtracting 82 coins.

**Comment by melmsie** [comment]
fixed in next update
