### ISSUE TITLE
New Quests

### ISSUE THREAD

**Issue by JLT3102** [DankMemer/dank-memer-suggestions-and-bugs#22]
I suggest a new quest cause they are not many,my suggestion is to add this quest.
Coin Finder:successfully search 5000 coins(or smth like that)by using pls search
Reward:Coin Bomb and Reversal
And
Memer:make 2000 coins by using pls postmeme command.
Reward:Padlock
That's it hope this gets accepted and have a good day
-JLT

**Comment by melmsie** [comment]
will take this into consideration
