### ISSUE TITLE
Passive mode users Shouldn't show up on pls rich

### ISSUE THREAD

**Issue by BarlB0se** [DankMemer/dank-memer-suggestions-and-bugs#221]
So there is a server I'm in with over 100k people and it's very friendly but with dank memer is very hard to find people to rob because from pls rich 1 to pls rich 10 everyone is on passive mode just trying to flex the fact that their bank size is tiny, it would be super useful if either there was a seperate command to see only the richest people with passive disabled or just have passive mode users not show up on the pls rich leaderboards, thanks for the amazing bot and good luck for the future of your development!

**Comment by melmsie** [comment]
its "pls rich" not "pls who can I steal from:
