### ISSUE TITLE
An idea for the newish feature pls pet 

### ISSUE THREAD

**Issue by IAmThe0neWhoKnocks** [DankMemer/dank-memer-suggestions-and-bugs#222]
**Is your feature request related to a problem? Please describe.**

This post is about an idea id personally like.

**Describe the solution you'd like**

So, the feature id like to request is certain pets in dank memer can auto beg for you if you enable it in pls pet settings, obviously not every 25/30 seconds because that's way too op. What makes scene to me is you'd charge 100,000 coins for the pet in the shop or it could be a premium user feature only and the pet would go out and gather x amount, say 1000 every hour or so what ever you think is a reasonable time. But the catch is theirs a small chance your pet can die or get lost and if it comes back its hungry and you'd have to feed it more than you usually would but the pet owner can try and lower the chances by micro chipping the pet.

**Describe alternatives you've considered**

An alternative feature would be pets can find random stuff every now and then. for example a user would type "pls pet search" "your pet is now searching" and then 2 or so hours later it could possibly come back with fresh bread, chill pills or pink phallic objects nothing major but just something to help out. This pet feature would also only be included in 100,000 or up or only as a premium user pet only.

**Additional context**

I'd just like to thank you for reading this and I hope you understand everything I've explained correctly. 

Regards Josh

**Comment by lyl-jerry** [comment]
But pets already have the hunting feature, which serves a similar purpose except it is automatic and random
