### ISSUE TITLE
quest stays on 10 points

### ISSUE THREAD

**Issue by sugarbab3** [DankMemer/dank-memer-suggestions-and-bugs#224]
**Describe the bug**
When I first chose the gambling quest I immediately had 10 points on the quest and no matter how many times I gambled on top of it it never changed. Now recently I stopped that quest and decided to do a new one and buy a pet, but even though I never bought a pet yet it still said I had 10/1 points. 

**To Reproduce**
I’m not sure if it would be the same for others but here I go:
1. Pls quests list 2
2. Pls quests choose chronic gambler 
3. Pls quests (and noticed I had 10 points)
4. Pls gamble <amount> (Won)
5. Pls quests (didn’t change)
6. Repeated steps 4 and 5 several times.
7. Pls blackjack (when it changed to blackjack and I still had the same problem) +repeat that demand.
8. Pls quests stop 
9. Pls quests list 1, 2, 3
10. Pls quests choose pet (and notice I have the same problem.

**Expected behavior**
I expected to start with 0 points and gain more points every time I gambled. I also expected the points would be gone when I stopped the gamble quest.

**Screenshots**
![F920314E-CECD-48D5-A5A3-3DBA18E7DA03](https://user-images.githubusercontent.com/64993187/81353873-81946100-90ca-11ea-9e7a-b64bb3bca86b.png)
![CFD09629-A5AB-4A2C-AEA7-88A027DFC5AB](https://user-images.githubusercontent.com/64993187/81353877-848f5180-90ca-11ea-9d19-0ce067fe20e6.png)
![537DA25E-412B-4093-8F5B-BF7E25F31349](https://user-images.githubusercontent.com/64993187/81353879-85c07e80-90ca-11ea-9079-7d60cef4d6b1.jpeg)
(Idk if u can see those u can always contact me with sugarbabe#1010 on discord if they aren’t attached)

**Additional context**
I did other quests before this and they worked fine but when I started the chronic gambler this problem showed up.

**Comment by melmsie** [comment]
quests will be overhauled this summer in our rewrite
