### ISSUE TITLE
pls bet doesnt work

### ISSUE THREAD

**Issue by hamharam** [DankMemer/dank-memer-suggestions-and-bugs#225]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Wise2006** [comment]
You have to explain!

**Comment by hamharam** [comment]
uh when i type pls bet all, the command doesnt show up

**Comment by Wise2006** [comment]
`Pls bet` was disabled a few days ago! Please refer to [this](https://discord.com/channels/470337009886429194/502215543915413504/707654812774301838)
announcement. Also, stay tuned in the server so you don't miss updates.

**Comment by hamharam** [comment]
ok thanks

**Comment by Wise2006** [comment]
Can close #225
