### ISSUE TITLE
fishing balance

### ISSUE THREAD

**Issue by yerikpoo1** [DankMemer/dank-memer-suggestions-and-bugs#226]
a feature in settings or something in the shop
setting:a setting that lets you not find the fishing boss as some people type very slow and can not beat it and end up losing their rod such as me ive lost many poles due to not being able to type fast but to balance this you find the boss therefore not getting the prizes for beating his

feature:new shop item heavy fishing pole a fishing pole that costs maybe 50k? but when you encounter the boss you still only have 7 seconds to beat it but the chance for the pole to break will only be 5% if you lose

**Comment by lyl-jerry** [comment]
What about we have a setting that can let us choose whether we want to face a fishing boss or not?
