### ISSUE TITLE
Add a place for how much money you have after a game of blackjack

### ISSUE THREAD

**Issue by cryptor10** [DankMemer/dank-memer-suggestions-and-bugs#229]
It would be useful to have a place for how much money you have after you won/lost in a game of blackjack, like how betting used to have. Maybe something similar to:

You lost 1234 coins. You now have 14224 coins.

This way people can know how much they have in their wallet and save time instead of typing pls bal after using blackjack.

**Comment by melmsie** [comment]
done in next update
