### ISSUE TITLE
Suggestions Regarding Passive Mode

### ISSUE THREAD

**Issue by V3NOM2802** [DankMemer/dank-memer-suggestions-and-bugs#23]
**Is your feature request related to a problem? Please describe.**
Umm sort of yes, so Three issues 
1.) It's very annoying when the whole of the "pls rich" leaderboard is filled with people with passive mode enabled and having withdrawn all their money, it's a pain to search through the whole list trying to find someone who can be robbed
2.) Even though people in passive mode aren't able to "Start a heist" but they still are able to "Join" if someone else has started the heist, this, In my opinion, defeats the purpose of passive
3.) Again somewhat similar to point 1 but a little different, this time concerned with heists, so its a pain to test if someone is on passive mode or not, (we have to fail heist them to check)

**Describe the solution you'd like**
For issue 1.) People with passive mode on, Not to show up on the rich leaderboard
For issue 2.) People with passive mode on, along with not being able to rob or start a heist shouldn't be allowed to join a heist
For issue 3.) There should be an option or something like that which tells us if a person has passive on or not if we check their embed level using "pls level --embed" (just like how we can check someone's job using this)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by melmsie** [comment]
1. no
2. already reported
3. already planned
