### ISSUE TITLE
Bug Report For Profile Commands

### ISSUE THREAD

**Issue by no-u1** [DankMemer/dank-memer-suggestions-and-bugs#230]
**Describe the bug**
The bug is with the profile command, it is showing the multiplier wrong, when you do "pls profile" it shows the correct profile of you but when you mention someone to see their profile it will get everything right except the multiplier. It was showing the person who ran the commands multiplier, instead of the 
**To Reproduce**
1. Do "pls profile"
2. Then do "pls profile <tag a user>
3. Get the other user to do "pls profile" or "pls multiplier"

**Expected behavior**
I expected it to show the correct multiplier of that person I guess?
**Screenshots**
https://cdn.discordapp.com/attachments/708157774785282130/708157971028377600/unknown.png
https://cdn.discordapp.com/attachments/708157774785282130/708158038967582750/unknown.png
https://cdn.discordapp.com/attachments/707012950438838322/708161435783397401/unknown.png
It wasn't letting me paste the photos...
**Additional context**
Just note the 1st screenshot is when I ran the "pls profile" command on myself then on my friend, the second one is the correct multiplier for my friend and 3rd is the correct one for me. If anything else you need I can be contacted directly on Discord, my username is Dad™️#5695 The person who suggested I fill in this report was Erebus#0123

**Comment by scp174** [comment]
This also happened to me earlier

**Comment by melmsie** [comment]
fixed in next update
