### ISSUE TITLE
Dank Memer Blackjack Soft and Hard totals

### ISSUE THREAD

**Issue by idiot12345** [DankMemer/dank-memer-suggestions-and-bugs#234]
**Describe the bug**
An ace in blackjack can be either 1 or 11, whichever is better for the player

**To Reproduce**
1. `plz bj 100`
2. Repeat the above command until you get at least one ace in your hand
3. Hit (a few times if needed)
4. You bust.

**Expected behavior**
Instead of busting with a soft total (where the ace represents 11) the ace "changes" to a 1 and you can keep playing.

**Screenshots**
https://drive.google.com/file/d/1-sfD7Hsz50Zb8Cipcm12C95jfktvRJ4z/view?usp=sharing

**Additional context**

**Comment by Wise2006** [comment]
Hello!

**Comment by melmsie** [comment]
We are aware of this and @aetheryx is working on a fix to come soon
