### ISSUE TITLE
Stacking Inventory System

### ISSUE THREAD

**Issue by ToPhu31** [DankMemer/dank-memer-suggestions-and-bugs#238]
**Is your feature request related to a problem? Please describe.**
Many people when they get rich, they just buy large quantities of alcohol, cheese, rare pepes and more. It basically allows them not to be robbed 

**Describe the solution you'd like**
Like Minecraft, for example, add a stacking limit for items (For example: You can have 16 pepes per stack) so that hoarding items will be less common

Also, an inventory space limit must be added for my idea to work, and throughout the time you use Dank Memer, you slowly gain inventory space.

**Comment by lyl-jerry** [comment]
But then when they buy inv, they will lose money in the process. This is a matter of whether they want to be stolen or lose a bit to prevent it. I don't see why this is a problem.

**Comment by melmsie** [comment]
there already is a stack limit lol
