### ISSUE TITLE
Increase bet limits

### ISSUE THREAD

**Issue by Zahber** [DankMemer/dank-memer-suggestions-and-bugs#239]
It's very frustrating that the limit is so low. I want to do bets bigger than 9,999. Preferably without limit, or a very high limit like 1,000,000 

As far as I can see there would not be a problem with increasing the limit, other than potential abuse if there was a glitch, then again there's always room for abuse in anything.

**Comment by ToPhu31** [comment]
The rule is probably set to prevent rich users to lose all of their fortune quickly.
