### ISSUE TITLE
Adding something new to pls search

### ISSUE THREAD

**Issue by grossly** [DankMemer/dank-memer-suggestions-and-bugs#24]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem. It's something that would be added to the "pls search" command.

**Describe the solution you'd like**
Add searching a vending machine coin return slot to "pls search". People frequently forget their coin change at vending machines after buying something. 

**Describe alternatives you've considered**
There are many other things that could be added to the command, but I'm just going to give one example and see what the response is. 

**Additional context**
It would be nice to see more things to "pls search". This is just one example I think would work well.

**Comment by melmsie** [comment]
Will consider this
