### ISSUE TITLE
Account balance after a blackjack game is displayed incorrectly

### ISSUE THREAD

**Issue by sollicitudin** [DankMemer/dank-memer-suggestions-and-bugs#241]
**Describe the bug**
Account balance after a blackjack game is not displayed correctly. Seems like the old amount before the game started.

**To Reproduce**
1. Start a new bj match
2. Finish the match
3. Observe account balance number ("You now have xxx")

**Expected behavior**
Should display new bal number

**Screenshots**

![image](https://user-images.githubusercontent.com/11869878/81491005-f32f0380-92b2-11ea-89e4-4d8f45581085.png)

![image](https://user-images.githubusercontent.com/11869878/81491041-5456d700-92b3-11ea-8631-6d7755403ecc.png)

**Comment by rayhan6726** [comment]
I got that bug too
![2020_05_10_01_32_46](https://user-images.githubusercontent.com/50134736/81492580-1feb1700-92c3-11ea-90a2-c20c02ec0c15.jpg)
