### ISSUE TITLE
"Working Hard or Hardly Working?" glitch

### ISSUE THREAD

**Issue by kathrax** [DankMemer/dank-memer-suggestions-and-bugs#242]
**Describe the bug**
there is a glitch in the quest status for the aforementioned quest

**To Reproduce**
Steps to reproduce the behaviour:
1. pls quests choose working hard or hardly working
2. pls quests

**Expected behaviour**
see: "10/1 promotions" \n "-9 promotions remaining"

**Screenshots**
<img width="202" alt="Screenshot 2020-05-10 at 10 04 30 PM" src="https://user-images.githubusercontent.com/65120643/81501406-d0c8d480-930a-11ea-8d77-465e5b685d81.png">

**Comment by melmsie** [comment]
fun
