### ISSUE TITLE
Blackjack balance shows balance before game

### ISSUE THREAD

**Issue by William5553** [DankMemer/dank-memer-suggestions-and-bugs#244]
**Describe the bug**
When the blackjack game ends, it shows your balance from before the game. #241 

**To Reproduce**
1. start a blackjack game
2. win or lose
3. see balance

**Expected behavior**
The balance with the money you won or lost, not before the game

**Screenshots**

![](https://i.imgur.com/KSmoHjz.jpg)

**Additional context**

**Comment by melmsie** [comment]
fixed already
