### ISSUE TITLE
pls pet train Command Issue

### ISSUE THREAD

**Issue by JazzziHD** [DankMemer/dank-memer-suggestions-and-bugs#248]
**Describe the bug**
When using `pls pet train` and then Attack, Defense etc, it will only allow you to do it if you use attack + defense in lower case.

**To Reproduce**
1. Own a Pet.
2. Do `pls pet train Attack`
3. Watch it say how retarded you are lmao.
4. Then try `pls pet train attack`

**Expected behavior**
Should allow you to add points to said Section.

**Screenshots**
![Discord - 10 22 PM - 10 05 2020](https://user-images.githubusercontent.com/34623111/81510990-facfc600-930d-11ea-93dd-5f67f666244b.png)

**Comment by melmsie** [comment]
should be fixed next update
