### ISSUE TITLE
Add a meme posted every time you use the pls postmeme command

### ISSUE THREAD

**Issue by SergeTFM** [DankMemer/dank-memer-suggestions-and-bugs#25]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but it would just be cool if every time you used the pls postmeme command a meme would show up. like merge the pls meme code with pls pm

**Describe the solution you'd like**
Like I said above, I would like the pls pm command to have a meme posted with it and it'll say "Your Meme:" as title and the meme.

**Describe alternatives you've considered**
I don't think that there are any.

**Additional context**
Merge the pls meme command with pls pm command and the title will be "Your Meme:" and the meme as picture.

**Comment by melmsie** [comment]
This will just be spammy, if you want a meme, go use pls meme
