### ISSUE TITLE
Regrading updates

### ISSUE THREAD

**Issue by lyl-jerry** [DankMemer/dank-memer-suggestions-and-bugs#253]
Some of your updates are on the changes in the value of some items. Two recent updates reduced the price on alcohol, rares and pepecs, which the player love to stack a lot. It is extremely frustrating when the item which a player grinded really hard on suddenly dropped its price. Some of me even wanted to give up this game. I understand the need of balance changes, but I hope that at the same time the team can offer refunds to affected players. Value veteran players more as they are one of the best fans of the game. They help a most in spreading the game too.

**Comment by melmsie** [comment]
As I've said before and will say again, your inventory is NOT a bank. If you treat it that way, it's at your own risk.
