### ISSUE TITLE
Fishing rod not deleting from inventory when you lose it

### ISSUE THREAD

**Issue by Elektron-blip** [DankMemer/dank-memer-suggestions-and-bugs#254]
**Fishing rod not deleting from inventory when you lose it**
As you know, when you fish, there is a small chance of losing the rod. But in this case, even after the bot says that I have lost the rod, it still is present in my inventory and I still can use it.

**To Reproduce**
1. Spam 'pls fish' until you have "lost" your rod.
2. Check your inventory.
3. It still is present in the inventory.
4. That is the error.

**Expected behavior**
The fishing rod is lost and you have to buy a new one from shop.

**Screenshots**
I can't share the screenshot coz It is really hard to get it.

**Additional context**
No additional context.

**Comment by melmsie** [comment]
I can't duplicate this
