### ISSUE TITLE
Pepe Coin purchase

### ISSUE THREAD

**Issue by NotAlly** [DankMemer/dank-memer-suggestions-and-bugs#256]
![B0E3801E-9DB0-4949-9D41-5BD75DEC3496](https://user-images.githubusercontent.com/65251171/81734191-0b597b00-948b-11ea-9f30-e303a2325206.jpeg)

I tried to buy a Pepe Coin after selling all my items when it was discounted and this happened (see image). I've now lost half of my overall money and all of my inventory for pretty much nothing, is this fixable?

Please add me on discord to contact me, or @ me in the server:
Not Ally#9179

**Comment by Wise2006** [comment]
The command was `pls buy pepecoin` or `pls buy pepec`. 
Whenever you buy an item, please check it's id.
For this command, the bot only accepts one argument, and the argument it received was `pepe`.
Unfortunately, I don't think you can revert this.
