### ISSUE TITLE
nerf the cost for pepe trophy

### ISSUE THREAD

**Issue by oliverysfx** [DankMemer/dank-memer-suggestions-and-bugs#261]
**Is your feature request related to a problem? Please describe.**
the current cost for a pepe trophy is very high and is just very very out of reach without grinding for a whole year or so if you are new

**Describe the solution you'd like**
reduce the cost of pepe trophy to about 15mil

**Describe alternatives you've considered**
an alternative would be increase the average amount of money earned

**Additional context**
no context as this is general

**Comment by melmsie** [comment]
NO
