### ISSUE TITLE
Pls disable rob not working

### ISSUE THREAD

**Issue by OnlyxGhOsT** [DankMemer/dank-memer-suggestions-and-bugs#263]
Okay so, I have been trying to do the command pls disable rob but it doesn't work people can still rob even tho it says it's disabled in the disable list, i tried enabling it and then disable it but it doesn't work i also tried to clear the disable list and then disable rob but it won't work it's not only rob but also heist they both bug in the same way
![Screenshot_20200511_182046](https://user-images.githubusercontent.com/65305275/81845549-54363000-956e-11ea-997b-83697e8920e2.png)
![Screenshot_20200511_182222](https://user-images.githubusercontent.com/65305275/81845576-6021f200-956e-11ea-8af9-5fe1e673c7a1.png)

**Comment by ToPhu31** [comment]
GhOsT, do **pls enable list** maybe you have perms that allow you to use commands.

**Comment by Wise2006** [comment]
@OnlyxGhOsT `pls enable list` will show you the list of commands that are overridden.
Example: You have a command disabled server-wide. You want to enable it in a specific channel. You type `pls enable <command> <channel>`. It will be enabled. So, you have to do `pls enable <command> <channel>` to disable it in that channel again.
Alternatively, if you have no other overrides, you can type `pls enable clear` to remove all overrides.

Hope it helps!

**Comment by OnlyxGhOsT** [comment]
I tried them already for some reason it doesn't work

**Comment by OnlyxGhOsT** [comment]
Wait nvm

**Comment by Wise2006** [comment]
Can close #263
