### ISSUE TITLE
Target Files (Item Request) (Category: Robbing)

### ISSUE THREAD

**Issue by ToPhu31** [DankMemer/dank-memer-suggestions-and-bugs#264]
**Is your feature request related to a problem? Please describe.**
Overall, I've seen some upset concerns regarding how passive mode is slowing down the process of finding targets to rob & heist. As you may know, many rich users are already quitting because of the update, and new users who uses thievery to get rich are also aware of how annoying passive mode is to them. So I propose a way to find targets _easier._

But, with a cost.

**Describe the solution you'd like**
My proposal is that a new item should be introduced that will **DM** the user the list of **non-passive** players' _riches._ Both Bank **AND** Wallet when used. This will make scouting targets easier, however this item is **one-use**, so that it can only be used once. 

**Describe alternatives you've considered**
Not Any

**Additional context**
Note: This was made before the new passive mode nerf, so I wouldn't expect my suggestion to make it through

**Comment by melmsie** [comment]
interesting idea, but not what the bot needs right now imo
