### ISSUE TITLE
make landmines multi-use again

### ISSUE THREAD

**Issue by princessburtmacklin** [DankMemer/dank-memer-suggestions-and-bugs#266]
So up until around a week ago, the landmine had infinite uses during its 12hr time. I don’t know what happened but now it disappears after one person blows it up. This makes the landmine much less worth the money now and is really annoying as multiple people can all easily just spam rob you and break your protection at the same time leaving you defenseless and making it very likely for one of them to get a successful steal, which completely disrupts the balance between robbers and victims as the robbers have a huge advantage now and victims are losing a lot of money when being targeted.

I would like this problem to be solved by making the landmine multi-use again, at least to some limit to discourage robbers from stealing non-stop and bothering victims as well as to protect against spam robbing as the robbers would have a 50% chance of dying no matter what, which was much fairer before this hidden change.

Another way to solve this could be adding a new protective item that would be multi-use, but that could take quite a bit of time, so I can also suggest that you add a rob cooldown on a person even if the rob fails due to padlock or landmine or whatever, so the victim has time to replace their protection before someone else spams them.

This issue has really bothered me as today itself I lost about 100k in cash due to several people all trying to rob me at once, leaving me unable to protect myself at all, other than sanding and snowballing, which never ensures 100% protection as you can only snowball one person and sand can only be used once a day on a person. This is really annoying for people who have extra money in their wallet a lot as they deserve some kind of longer-term protection, other than leaving the server completely which ruins the bot experience.

**Comment by ToPhu31** [comment]
That's unrealistic though, like if you had a landmine would it blow up and magically come back to blow up again?

**Comment by oliverysfx** [comment]
if I am not wrong landmine was never multi-use, what you have encountered was probably a bug where a one-time item was able to be activated twice, like what happened to my friend with his padlock not long ago

**Comment by W1NGD1NG5-G4ST3R** [comment]
would like to have this added back too

**Comment by melmsie** [comment]
@oliverysfx is correct, it was a bug. It makes no sense for a landmine to be more than a single use.
