### ISSUE TITLE
NPC Traders (Searching Enhancement)

### ISSUE THREAD

**Issue by ToPhu31** [DankMemer/dank-memer-suggestions-and-bugs#267]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Since I started collecting collectables such as bread and cookies, I've always wanted to buy/sell mass quantities of it for the good of other people, yet I never had the riches to do so. My suggestion is that when you search a certain location (attic, sewer etc.) There will be a small chance (1% or larger with trophy) you encounter one of these traders. These traders will request an amount of items for something, usually higher than the sell price of those items, and will want it immediately so that the user cannot go to the shop and buy the item to complete the request. From what I see, I imagined it like this:

Me: pls search
DM: attic, tree, pantry
Me: attic
DM: You found a wandering trader! This trader is willing to pay 10000 coins for 50 common fish!
Do you want accept the deal? (y/n)
Me: y
DM: You received 10000 coins!

**Describe alternatives you've considered**
Just a quest that alternates in requirements and prizes

**Comment by melmsie** [comment]
sounds fun, but not really possible right now
