### ISSUE TITLE
Prestige upgrading

### ISSUE THREAD

**Issue by swimmer2028** [DankMemer/dank-memer-suggestions-and-bugs#268]
When you prestige, you should be able to get more items because the rare pepe is now cheaper and there is no real point in prestiging now.

**Comment by ToPhu31** [comment]
Not true. Bank Space is much easier to grind, There's a bonus multi, and the whole point of prestiging is restart but with slightly more of an advantage.

**Comment by Wise2006** [comment]
Adding to what @ToPhu31 mentioned, you will also get a badge showing the prestige level which can be seen in your profile and the rich leaderboard. Do `-prestige` in the [official server](discord.gg/meme) for more info.
Thank you!
