### ISSUE TITLE
no spending money for a short time after using reversal or stealing

### ISSUE THREAD

**Issue by oliverysfx** [DankMemer/dank-memer-suggestions-and-bugs#269]
**Is your feature request related to a problem? Please describe.**
It's very frustrating when people just steal from you and then spend that money so that you can't use a reversal to get it back.

**Describe the solution you'd like**
I would like to see that pls buy is disable for 30s after you have succesfully robbed someone else or used a reversal.

**Describe alternatives you've considered**
no alternatives

**Additional context**
![image](https://user-images.githubusercontent.com/54044780/81901129-9dc75f00-95f0-11ea-81a0-d2de7d2cc21d.png)
so I was stolen and used a reversal then they reversed it back and spent it straight away after they reversed. it's really annoying as it completely prevents me from using a reversal.(the pls use rev before pls buy rev 34 is just a lag, their buy message was sent first and processed first)

**Comment by chegde01** [comment]
This shouldn't be considered imo. Let the game remain tactical and fun. It will become too monotonous if you'll be adding features that will leave no space for smart moves. I guess that's what the currency system is all about.

**Comment by oliverysfx** [comment]
but the fact the money gets immediately used and doesn't even give you a chance to use a reversal is seriously annoying

**Comment by epicjonny312** [comment]
Let’s consider this really really really really carefully.
