### ISSUE TITLE
Reveal the answer in pls work if we get it wrong

### ISSUE THREAD

**Issue by AstroFotino** [DankMemer/dank-memer-suggestions-and-bugs#27]
**Is your feature request related to a problem? Please describe.**
It's frustrating when you can't figure out a word and pls work keeps giving you it and you keep getting it wrong.

**Describe the solution you'd like**
If we get it wrong, it should reveal the answer.

**Describe alternatives you've considered**
I don't think there are any except asking on support channels.

**Comment by melmsie** [comment]
Will consider

**Comment by melmsie** [comment]
This will be fixed/considered during the rewrite
