### ISSUE TITLE
Take passive people off the rich board

### ISSUE THREAD

**Issue by pjgreen89** [DankMemer/dank-memer-suggestions-and-bugs#270]
**Is your feature request related to a problem? Please describe.**
With the amount of times people try to steal from someone who is in passive mode it’s annoying to get pinged every 30 seconds
Take people who are in passive mode off of the rich leaderboard. Would save a lot of drama and hassle
**Describe the solution you'd like**
Remove them from the leaderboards... What’s the point in seeing someone have all these coins and they get tagged a billion times 
Take passive people off the rich leaderboards.
**Describe alternatives you've considered**

**Additional context**

**Comment by melmsie** [comment]
no
