### ISSUE TITLE
Lucky Potion and Magical Cheese

### ISSUE THREAD

**Issue by IcyHot2553** [DankMemer/dank-memer-suggestions-and-bugs#272]
I would really love to see two new items in dank memer. These items are a lucky potion and a magical cheese. The lucky potion would be like the alcohol, except it would make you much more lucky for a couple of hours. You would get more money from begging, betting, meme posting, and everything else as well. However, because it would be so awesome, it would have to cost 25k or more. The other item, a magical cheese, would be like a cheese except purple. And, instead of EXP multiplier, it would give a very small percentage steal shield that would remain. This item wouldn't have to be used of course, for those who like getting heisted upon. This item would also have to cost a good chunk of change. This is just an idea I had, and I think that the items could be pretty neat if implemented.

**Comment by W1NGD1NG5-G4ST3R** [comment]
then people could just spam magical cheese and become nearly impossible to rob
