### ISSUE TITLE
Fishing boss bug

### ISSUE THREAD

**Issue by Anon2203** [DankMemer/dank-memer-suggestions-and-bugs#274]
This bug happened twice now where this specific fishing boss doesn't recognize that i did it correctly

**To Reproduce**
1. Encounter the fishing boss where you need to type " fish fish fish fishy "
2. Retype it, then it said i suck

**Expected behavior**
Get loot

**Screenshots**
![Capture](https://user-images.githubusercontent.com/65386998/82017699-4e4b6680-96b6-11ea-930f-11b7915654b6.PNG)

**Additional context**
Nothing

P.S. my first time doing this so sorry if i did it wrong

**Comment by oliverysfx** [comment]
might be time out though, just saying
