### ISSUE TITLE
Pet upgrade

### ISSUE THREAD

**Issue by WiseDevHelper** [DankMemer/dank-memer-suggestions-and-bugs#276]
**Is your feature request related to a problem? Please describe.**
When I upgrade my pet to MAX, there is no use of getting points. 
 
**Describe the solution you'd like**
The idea I have is, as soon as your pet reaches the MAX level, it could upgrade into a more advanced pet. Maybe, an improved version of itself or a different pet altogether.

**Describe alternatives you've considered**
Another way of solving this is to expand the skills to get better protection / sustainability / items found.

These are just my thoughts as we don't have any use of points after our pet reaches MAX.
Thank you!

**Comment by wolf653** [comment]
What your Cat is evolving?
...
Cat has evolved into chonker.

**Comment by epicjonny312** [comment]
Lol.
Omg, rock is evolving?
Rock has grown arms and legs.
Rock is now a crab.
