### ISSUE TITLE
Ablity to mention roles with pls say

### ISSUE THREAD

**Issue by x0** [DankMemer/dank-memer-suggestions-and-bugs#279]
**Describe the bug**
Basically a user was able to ping the main role in my server and piss off 20k users.. This is really annoying pls fix
**To Reproduce**
pls say <@&roleid>

**Expected behavior**
I think my explanation is fine..
**Screenshots**

**Additional context**
I've already done `pls disable all`

**Comment by Matt2517** [comment]
Can vouch for this issue, someone in a commands channel who just joined the server, had the ability to mention @member. Over 1k people got this mention. He had the member id so he typed "pls say <@#roleid>" roleid being member.

**Comment by ToPhu31** [comment]
This is really on moderation, so i would suggest just disabling say.

**Comment by x0** [comment]
> This is really on moderation, so i would suggest just disabling say.

Dude did you even read the bug report?

**Comment by x0** [comment]
Actually got more information on this apparently it isn't just mentioning the role you gotta do ```\<@&ID>``
