### ISSUE TITLE
Stock Market

### ISSUE THREAD

**Issue by DekuHavingASeizure** [DankMemer/dank-memer-suggestions-and-bugs#28]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. No, I think that this would be beneficial to the people who enjoy betting or "slotting"

**Describe the solution you'd like**
I would like a stock market because then you could invest and wait for it to go up etc.

**Describe alternatives you've considered**
I didn't really have alternatives to the stock market but I would enjoy a new pet feature called "fetch" A feature where you could play fetch with your pet every 2-6 hours and it will have a 25% chance to bring back an item and a 75% chance to bring back 200-3,000 coins

**Additional context**

**Comment by melmsie** [comment]
No for the 1000th time
