### ISSUE TITLE
Pls work anagram minigame too hard

### ISSUE THREAD

**Issue by W1NGD1NG5-G4ST3R** [DankMemer/dank-memer-suggestions-and-bugs#280]
**Is your feature request related to a problem? Please describe.**
Sometimes the anagram of pls work is so hard that you don't have any idea what the word is

**Describe the solution you'd like**
I would like it so that if you type the word wrongly, the anagram rescrambles itself

**Comment by ToPhu31** [comment]
then its literally a long-term memory game, but yea its annoying.
