### ISSUE TITLE
Let people in passive mode receive gifts from pls gift

### ISSUE THREAD

**Issue by AstroFotino** [DankMemer/dank-memer-suggestions-and-bugs#284]
**Is your feature request related to a problem? Please describe.**
It's annoying that people in passive mode can't receive gifts, because my (small) server basically revolves around Dank Memer giveaways. Pretty much everyone there has passive enabled which means that giveaways cannot continue.

**Describe the solution you'd like**
Let people on passive mode to receive gifts.

**Comment by melmsie** [comment]
no
