### ISSUE TITLE
using coin bomb in passive

### ISSUE THREAD

**Issue by BreadedApples** [DankMemer/dank-memer-suggestions-and-bugs#285]
**Describe the bug**
coin bomb being consumed even though in passive
**To Reproduce**
1. be in passive
2. do pls use coin bomb
3. get the error saying you cant use this in passive mode
4. see that is consumed it even though it should not

**Expected behavior**
Not consume the coin bomb
**Screenshots**

![IMG_0113](https://user-images.githubusercontent.com/46753530/82113553-753c8380-971c-11ea-9afb-6dece102c984.PNG)
![IMG_0114](https://user-images.githubusercontent.com/46753530/82113560-7d94be80-971c-11ea-92e0-bb80f10db689.PNG)

**Additional context**
img 113 is when I tried to use coin bomb
img 114 is when I tried to sell it and also when I checked my inventory and noticed that is was gone

**Comment by BreadedApples** [comment]
img 113 is the first image and img 114 is the second image for clarification

**Comment by BreadedApples** [comment]
pls refund me my id is @Dank Hola#4712

**Comment by scp174** [comment]
Passive users cant use the coin bomb check the latest bot update

**Comment by BreadedApples** [comment]
@scp174  i know, but when you try to use it and says no, it still takes it from your inventory

**Comment by melmsie** [comment]
you're not getting a refund lol

**Comment by BreadedApples** [comment]
Ooooooooof

**Comment by ZetsuboZetsubo** [comment]
I have the same problem show up, just stating that its not only happening to this person
![Screenshot (46)](https://user-images.githubusercontent.com/65519999/82168601-ee9aba00-9873-11ea-8f04-e26424267278.png)

**Comment by melmsie** [comment]
this is fixed now
