### ISSUE TITLE
Job Bug.

### ISSUE THREAD

**Issue by zZman1** [DankMemer/dank-memer-suggestions-and-bugs#286]
After I type 'pls work,' it'll ask me to do something. Unscramble a word, do a memory test, but mainly copying and pasting. Once I copy and paste the text correctly, it says that I've done a terrible job. I don't get it, and I've lost a job multiple times because of this.
![image](https://user-images.githubusercontent.com/65443656/82115440-c8203600-9730-11ea-81ef-1fe92ac73245.png)

**Comment by Neptunus-Equester** [comment]
copy and pasting will automatically fail your job. there's invisible characters that you cannot see but that the bot can detect. the only way to do it successfully is to type it yourself and not copy paste. itll get you every time
