### ISSUE TITLE
Allow "pls pet name" to accept unicodes and Special characters

### ISSUE THREAD

**Issue by BlackStone5677** [DankMemer/dank-memer-suggestions-and-bugs#288]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
My pets name was an emoji When i bought it then we accidentally removed the emoji and when we added it back it didnt fix itself.
And i couldnt rename my pet to the emoji
**Describe the solution you'd like**
A clear and concise description of what you want to happen
Basically when you first buy your pet its name CAN have unicodes but it CANT when renaming it. Maybe changing the syntax to ask for the name in the next message or even making it allow special characters
**Describe alternatives you've considered**
Could not do anything about it
**Additional context**
Hmm nah

**Comment by melmsie** [comment]
Fixed in next update
