### ISSUE TITLE
I would like If you could add item name:˝lockpick˝ it would be able to lock pick padlocks and to add item:˝Defuser˝ it can defuse landmines,thats all and thank you for reading my suggestion

### ISSUE THREAD

**Issue by WhoCarees** [DankMemer/dank-memer-suggestions-and-bugs#289]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ToPhu31** [comment]
Bruh, Robbing already got buffed a bunch, at this point you might as well steal their account.
