### ISSUE TITLE
Pls Blackjack miscalculating results

### ISSUE THREAD

**Issue by Jatata** [DankMemer/dank-memer-suggestions-and-bugs#290]
![Screenshot_20200516_135431](https://user-images.githubusercontent.com/65452120/82120393-8ff31480-977d-11ea-8b85-6297d9258b68.jpg)

I should have lost here, but the bot redrew a card

**Comment by isxbel** [comment]
Same has happened to me.
![C085BCAA-9F33-4588-BB20-A8F818D60642](https://user-images.githubusercontent.com/65477600/82135181-bb483300-9853-11ea-85a1-6d255385d4fb.png)
![14989EAA-C0D5-479E-B19D-91682DF8F18D](https://user-images.githubusercontent.com/65477600/82135184-bf745080-9853-11ea-8430-9eb459c8d2ab.png)
![390D5189-1D10-4F74-9763-4FE913101702](https://user-images.githubusercontent.com/65477600/82135185-c0a57d80-9853-11ea-890f-d227887d9335.png)
![40DF0C16-4458-4EC2-B5A7-1E151384308B](https://user-images.githubusercontent.com/65477600/82135186-c13e1400-9853-11ea-8c21-b3b6a11e6a0c.png)
![B8E4FD21-E0D4-4664-9F48-18517568B3FA](https://user-images.githubusercontent.com/65477600/82135187-c1d6aa80-9853-11ea-9776-c9885d5106c1.png)
![78072CBB-C1A9-440E-938E-DBB32B1669C5](https://user-images.githubusercontent.com/65477600/82135188-c1d6aa80-9853-11ea-854f-38071c3da28a.png)

**Comment by BreadedApples** [comment]
No you won, it the opponent goes over 21, you will win

**Comment by SirAnyS** [comment]
Yes @BreadedApples but the dealer shouldn't have drawn another card after already being over his 17

**Comment by SirAnyS** [comment]
this only happens cuz the cards Show in a weird order
