### ISSUE TITLE
Working and Boss Fights [Bug]

### ISSUE THREAD

**Issue by Ionomycin** [DankMemer/dank-memer-suggestions-and-bugs#291]
**Describe the bug**
Working sometimes fails even though the user types if correctly (disregarding copy and paste as the user says they didn't). Hunting is similar in that the boss fights (specifically with the dragon), don't always go through and cause the user to die (more dying than successfulness).

**To Reproduce**
1. Use the fish or hunt system (pls fish / pls hunt).
2. Continue to use those commands (waiting the required cool downs).
3. When you get to a boss fight, try to complete it.
4. You'll see the error immediately after you've typed it most likely (it may not happen all the time I have no gather enough input from users about that).

**Expected behavior**
Currently, some of the hunting and fishing events are causing people to fail although they're typing it out correctly. Assuming they aren't copy and pasting the sentence, it seems there might be a minor bug. The expected behavior is that they pass the boss fight and don't die. The known behavior, however, is that they normally **always** die in the screenshots they're sending in support.

**Screenshots**
https://cdn.discordapp.com/attachments/491466924799164426/711213159121420349/unknown.png

Other than the above screenshot (which is of a job that is having similar issues to the above), the proof can easily be obtained through using the currency system.

Contact me on Discord at "Nunca#0001" if you need the actual screenshot.

**Additional context**
Don't know whether the events are case sensitive or not and don't know whether or not the user is telling the truth about the copy and pasting portion of this ticket.

**Comment by melmsie** [comment]
they're almost certainly not telling the truth, we've never had this reported until people started dying over losing
