### ISSUE TITLE
my pls pet won't work

### ISSUE THREAD

**Issue by eviestargirl** [DankMemer/dank-memer-suggestions-and-bugs#294]
**Describe the bug**
When i say pls pet it says that there is a problem with the pet command and won't show my pet's status even after i waited for a day.
**To Reproduce**
1. Type pls pet
2. See error

**Expected behavior**
I expected to see my pet's status like its hunger, hygiene, fun, energy, and experience.
**Screenshots**
![image](https://user-images.githubusercontent.com/65461335/82126016-b7df7980-9777-11ea-8718-69c4e0d6183b.png)

**Additional context**

**Comment by chxrryblxssoms** [comment]
Yes, I have the same problem. I have been waiting for about 7-8 hours for it to be fixed but this problem is not fixed yet.

**Comment by melmsie** [comment]
@chxrryblxssoms I was sleeping, patience goes a long way
