### ISSUE TITLE
Huge Fishing Update

### ISSUE THREAD

**Issue by Shinobishibe** [DankMemer/dank-memer-suggestions-and-bugs#299]
Obviously this is a huge idea but with the addition of the hunt command the fish seem rather basic, let's fix that. here's my idea list below

boot (10c) sardine(50c) trout (150c) bass (300c) tuna (500c) jelly (1000c)
        Boss shark (3000c or rod lost)
          Rare boss kraken (10000c)
players can flee or fight
fight: throw a harpoon 3 times
miss all three: die
miss two: lose the rod
miss one: flee to safety
if they don't miss they catch it

**Comment by melmsie** [comment]
not a bad idea, but a bit too in depth
