### ISSUE TITLE
Colour or Color

### ISSUE THREAD

**Issue by tigertank5911** [DankMemer/dank-memer-suggestions-and-bugs#3]
I used the 'pls work' command and it was a memory one. The 4 things were Outfit, Cosplay, Art and Color. Me, being English, thought it was rather odd having that spelling. If anyone was to read this, could you please fix this. 
Sincerely, tigertank5911

**Comment by melmsie** [comment]
It's not a bug, this isn't an English bot.

**Comment by HexCoder101** [comment]
bruh
