### ISSUE TITLE
Blackjack adding error

### ISSUE THREAD

**Issue by ChrisV428** [DankMemer/dank-memer-suggestions-and-bugs#302]
The Blackjack game 

**Expected behavior**
I expected to hit a few times and do pretty well since I had 2 and an ace in my hand. I hit and got a 4. Then another ace and i ended up busting when I got another cause it said i had 22 when I should've had 12 and won because it takes 5 hits without going over to win. 
**Screenshots**
i dont know how the images work so I have a disoord link and i uploaded it here too.
![dankmemereabbabfyavbydfabd](https://user-images.githubusercontent.com/65483670/82138301-75f11a80-97ed-11ea-98af-4e9776ec5d31.png)
https://cdn.discordapp.com/attachments/698813611866456064/711478004013858886/unknown.png

**Comment by oliverysfx** [comment]
this is the same bug as [this one](https://github.com/DankMemer/dank-memer-suggestions-and-bugs/issues/234) right?

**Comment by melmsie** [comment]
known bug, won't be fixed until after rewrite probably
