### ISSUE TITLE
Robbing without the victims knowing so

### ISSUE THREAD

**Issue by ObnoxiousRed** [DankMemer/dank-memer-suggestions-and-bugs#304]
**Describe the bug**
To rob someone with Dank Memer, people are supposed to say “Pls rob @username#tag” right? But I realized people have started using the ID’s to rob, so that the victims wouldn’t realized they’ve been robbed.

**To Reproduce**
1. Go to any server with Dank Memer...
2. Ping your victim then send that text.
3. Copy the text of you pinging the victim...
4. Paste it when you text, it should say something like <@!10282375927261195>.
5. Copy the ID thing...
6. Text “Pls rob”, then paste the ID, in this case, “10282375927261195“, so “Pls rob 10282375927261195“
7. Send it, then Dank Memer will respond successfully.

**Expected behavior**
I would’ve expected Dank Memer to not respond!!

**Comment by Neptunus-Equester** [comment]
there are 3 ways you can rob someone, you can ping them with pls rob @ username#0000, pls rob Username#0000, or pls rob 12345678901112134. 2 of those ways wont ping them in chat but they will still get notified through the notification system

**Comment by melmsie** [comment]
this isn't a bug, it's a literal feature lmfao
