### ISSUE TITLE
Work Not Going through/not editing the text

### ISSUE THREAD

**Issue by DJJammer30** [DankMemer/dank-memer-suggestions-and-bugs#306]
I said "pls work" for my hourly wages like normal, and got the memorize the colors activity. I memorized them and waited for the edit so I knew which one I was supposed to say and it just failed me, although nothing was edited. This has happened in a fashion like this during BlackJack and now it's happening to me during work, but it's seemingly random.

**To Reproduce**
1. "pls work"
2. Wait for color edit
3. Get failed'
It only does this half of the time, it didn't happen last night but it did this morning. 

I expected to be able to answer it, even if it was incorrectly because I'm bad, however, that's not what happened. 
![image](https://user-images.githubusercontent.com/65500017/82152571-cbe2b400-9827-11ea-83b1-441371006616.png)

**Comment by melmsie** [comment]
often just due to discord issues/latency
