### ISSUE TITLE
The <pls hunt> system needs to be better.

### ISSUE THREAD

**Issue by CBF69420** [DankMemer/dank-memer-suggestions-and-bugs#308]
For the hunting rifle to cost 20,000 coins, I feel like there should be a better payoff. When you go hunting you catch an animal that is sold for only 100-200 coins, thats the problem. The animals sell for so little, they add nothing to your balance, especially because of the 1m 15s cooldown. The animals should sell for a lot more especially when you realize a deer sells for almost the sam as a fish. I suggest that you change the prices of these animals because it makes the 20,000 coins purchase, feel like a waste.

**Comment by austinlame** [comment]
I think the animal prices are good, but I do agree that cooldown is a lot.
