### ISSUE TITLE
Trading Scam / commands: pls exchange/pls trade/pls exch, and pls takeback

### ISSUE THREAD

**Issue by ToPhu31** [DankMemer/dank-memer-suggestions-and-bugs#31]
**Is your feature request related to a problem? Please describe.**
A lot of people have extra items which they don't use or they don't need. Some get items a lot but doesn't want to sell it for the 33% price we are stuck with, so some sell and buy items for higher prices than the sell price, but lower prices than the buy price. But there isn't really much of an efficient way to do this other than using "pls gift" and "pls share/give." Not only is the inefficient, many can get scammed while doing so, me included. I understand that getting scammed is our fault, but as a fellow Dank Memer Items Trader (only for in-bot currency) I feel like this could be pretty nice.

**Describe the solution you'd like**
So like I said in the title, the command could be like "pls exchange (exch for short?) and pls trade." How I thought this should work is a user types out "pls exchange <item/# of dmc you are trading> <what you are getting back> and the other trader can type something like "pls exchange accept" to accept or "pls exchange decline" to decline the trade. An example of you buying an alc for 5000 dmc off another person can be like: 
User1: pls exch 5000 alc
Dank Memer: User2 Do you accept 5000 for your alcohol? do pls trade accept or pls trade decline.
(User2: pls trade accept
Dank Memer: User1 good job, you got your alcohol.)
(User2: pls trade decline
Dank Memer: User1, stop selling at the black market and get a job.)
You can choose the dialogue from the Dank Memer bot and the time, but the overall idea is in that example.
I know I might be asking for too much, and this might be impossible to code, but I feel like this might be able to increase Dank Memer's popularity even more, and avoid traders quitting from being scammed even if it was their fault.

**Describe alternatives you've considered**
Another solution to avoid people being scammed is a takeback command where they can take their money back within 20 minutes of giving/gifting someone. Like, if I gave User2 10000 instead of user1, I can use pls takeback to takeback the 10000 dmc i gave them. This can be used in trading too to avoid being scammed.

**Additional context**
Sorry for any grammar issues.

- ToPhu#4836

**Comment by melmsie** [comment]
We don't encourage trading like that, and it's really on you if you get scammed.
