### ISSUE TITLE
Blackjack

### ISSUE THREAD

**Issue by xzmario101** [DankMemer/dank-memer-suggestions-and-bugs#311]
![Screenshot_20200517-193951](https://user-images.githubusercontent.com/65521786/82170373-15a7ba80-9879-11ea-9969-59102e1bd77d.png)
So I was blackjacking and then got 1 king and two aces but still went over 21, is this a bug because I thought both aces have to turn 1 instead of 1 being 11 and the other be a 1.

**Comment by oliverysfx** [comment]
this is a known bug right, there's already a report [here](https://github.com/DankMemer/dank-memer-suggestions-and-bugs/issues/234)
