### ISSUE TITLE
pls search

### ISSUE THREAD

**Issue by BobbyTie** [DankMemer/dank-memer-suggestions-and-bugs#312]
**Describe the bug**
When using the pls search command, if you mistype where you want to search the cooldown is activated without a search having been done.

**To Reproduce**
Type pls search and respond to the bot with something not on the list of searchable places (or a typo). Try searching again and you will be hit with a cooldown.

**Expected behavior**
Since pls postmeme does not consider a mistype as a use of the command, a mistype in pls search should not count either.

**Screenshots**
![image](https://user-images.githubusercontent.com/65522279/82171169-65878100-987b-11ea-87d5-4a94fef93d60.png)

**Comment by Neptunus-Equester** [comment]
you've already executed the command and then proceeded not to give it a valid answer, you cant avoid that cooldown since its still a use
