### ISSUE TITLE
It keeps on reseting my currency!

### ISSUE THREAD

**Issue by MRSaizawa** [DankMemer/dank-memer-suggestions-and-bugs#315]
So I keep on getting my money resetted with the currency thingy- I had lots of dank memer currency and it rested out of nowhere, only the money in my bank wasn’t reset, this has happened to me a few times aswell but I had some money left, I would really appreciate if you gave me my money back and fixed this glitch! Here’s some proof - 
![83F9ADBA-CF12-4BA9-A904-80D63AA7043E](https://user-images.githubusercontent.com/65538941/82200837-24b45a00-98c5-11ea-8029-0bdf298b5cce.jpeg)
![C91A6100-82B2-4F8C-85F4-FA07B54FCB67](https://user-images.githubusercontent.com/65538941/82200843-25e58700-98c5-11ea-8c93-7ed5a6dcca21.jpeg)

Xoxo, MRS. aizawa 😎#5106 on discord.

**Comment by melmsie** [comment]
thats not proof
