### ISSUE TITLE
my donating fund didnt go through and scammed my money

### ISSUE THREAD

**Issue by semsha** [DankMemer/dank-memer-suggestions-and-bugs#317]
so i payed for the 5$ donor perk nd it took my money but still didnt allow me to link,redeem or say "pls pserver add". which is really strange. i can still use pls weekly which means i have donated. i've waited for 2 days and nothing new has happened. i even contacted kable and he wasnt able to help me.

i would have expected it to work normally,let me use perks and link and say pls pserver add because thats one of the only reasons i bought that perk.

![1111](https://user-images.githubusercontent.com/65541319/82205957-49c5be80-98ff-11ea-824e-3f243caafa13.PNG)
![2222](https://user-images.githubusercontent.com/65541319/82205961-4b8f8200-98ff-11ea-9d91-4b5cf0795cf2.PNG)
![3333](https://user-images.githubusercontent.com/65541319/82205967-4d594580-98ff-11ea-9ded-fe8bf7f1eda4.PNG)

if you cannot help me,please refund my money in pound sterlings so i can rebuy the product. thanks,

**Comment by melmsie** [comment]
this is not a bug, or something that should be on github
