### ISSUE TITLE
"Pls unuse" command 

### ISSUE THREAD

**Issue by rayhan6726** [DankMemer/dank-memer-suggestions-and-bugs#32]
**Is your feature request related to a problem? Please describe.**
When I've used an fake ID, and I robbing someone but got caught, I'm very frustrated. "Pls unuse" command will make me can rob someone without worrying about losing my fake ID.

**Describe the solution you'd like**
"Pls unuse" command will made users can unuse some things, like alcohol, fake ID, padlock, landmine, etc. Of course there will be a cooldown to make the user think twice before using that command to unuse fake ID, so they can't just unuse then rob then use it again in the same time, I'm recommending that the cooldown is 6h. After an tool unused, when used again, the expiry will decreased 25%.

**Describe alternatives you've considered**
I don't understand English well so I don't understand this part.

**Additional context**
The bot developers can decide tools that have longer/shorter cooldown.

**Comment by melmsie** [comment]
pls remove perhaps
