### ISSUE TITLE
pls profile --help not valid

### ISSUE THREAD

**Issue by NewoMadness** [DankMemer/dank-memer-suggestions-and-bugs#323]
**Describe the bug**
in pls profile the footer says pls profile --help for more commands, then by running the command it says it's invalid.

**To Reproduce**
1. Type pls profile --help
2. See error

**Expected behavior**
The command.

**Screenshots**
![Screen Shot 2020-05-18 at 12 41 59 PM](https://user-images.githubusercontent.com/52988707/82238886-f60aa380-9905-11ea-81a8-f3fc03cebe81.png)
![Screen Shot 2020-05-18 at 12 47 49 PM](https://user-images.githubusercontent.com/52988707/82238888-f60aa380-9905-11ea-9f03-05bcf53d4167.png)

**Comment by melmsie** [comment]
What? I don't see a bug here, it's giving you a menu for more stats lmao
