### ISSUE TITLE
BlackJack. getting the same cards as the dealer.

### ISSUE THREAD

**Issue by Zombieking1** [DankMemer/dank-memer-suggestions-and-bugs#324]
**Describe the bug**
When I play Black Jack, I've noticed that I sometimes get the same exact cards as the dealer. For example, we both get the Ace of spades... In a deck of cards, then there should only be 1 ace of spaces, which means the dealer must be cheating or the deck's messed up... otherwise, it's not really black jack

**To Reproduce**
1. Go to 'any server where you can use the dank memer bot'
2. Play the Black Jack game with Dank Memer a few times until you see that you get the same card as them...

**Expected behavior**
When the games ends you will notice that you both have the same card. For example, you and the dealer will have the Ace of spades.

**Screenshots**
<img width="469" alt="same cards?" src="https://user-images.githubusercontent.com/65560689/82242216-b8ece400-98fa-11ea-99d2-704e97fd5b01.png">

**Additional context**
I think that in order to make the Black Jack game a real Black Jack game, you should also be able to count cards. (this is why people even play black jack... This is the aspect of black jack that helps players to actually win) I hope you know what "counting cards" means, cuz this is an aspect that all forms of black jack need... otherwise, it isn't really black jack... (it would just be a new game every time... which isn't fair for the player)

**Comment by Neptunus-Equester** [comment]
just an fyi, a lot of casinos use anywhere from 6-8 decks, you can read cards and predict based off of what you see, but it keeps the deck random. not sure how many have been programmed into the bot though

**Comment by Zombieking1** [comment]
dang... but even so, it's a new game every time...
