### ISSUE TITLE
New Money Duplicating Glitch 

### ISSUE THREAD

**Issue by Jacob4266** [DankMemer/dank-memer-suggestions-and-bugs#327]
Earlier today I was robbed from so I did what anyone would do and I used a reversal card, but before I used it somebody already robbed the person that robbed the money from me so then when I used the reversal I got my money without actually taking the money back.

**Comment by oliverysfx** [comment]
that's probably because that person had at least the amount that they stole from you in their bank, because as long as you have more money than what you stole the robbed person can use reversal
