### ISSUE TITLE
Remove Passive Users from the pls rich list or make a way to clearly mark passive users.

### ISSUE THREAD

**Issue by AlexPecktacular** [DankMemer/dank-memer-suggestions-and-bugs#328]
**I personally am not one for robbing users, but I can see the frustration of constantly trying to rob someone, and just being left with passive users.** 

I would personally love a feature where passive users are clearly marked on the pls rich list. I think it will be beneficial to both the passive user and the robbing user. The main helpful reason why for a passive user is to not get all of those annoying pings from people who have tons of money. Getting pinged every second is a HUGE issue. 

Also for the robber: They don’t have to spend their time pinging everyone just to get a chance of robbery. It will be more simple, with ease. I would love to see this get implemented in the near future.
The 2 ways I see the passive people being marked: Either highlighted with a passive color stated, maybe a tag for them; like [PASSIVE] {user.id} or just simply removing them from the pls rich list. Either or, the passive user will be clearly marked as so.

**Comment by thewilloftheshadow** [comment]
Is it not already marked enough?
![image](https://user-images.githubusercontent.com/35580099/82307512-11b58e80-9986-11ea-9c78-ef9089ff38fe.png)

**Comment by oliverysfx** [comment]
it's really not obvious if you don't know what's the difference between the dashes though so

**Comment by AlexPecktacular** [comment]
Yeah. Maybe a highlight to make it more bold. I didn’t even see that and so did most people probably.

**Comment by RandomTurtleBoi** [comment]
Really

> Yeah. Maybe a highlight to make it more bold. I didn’t even see that and so did most people probably.
I've never missed that, but if you have that problem then you can go ahead.

**Comment by melmsie** [comment]
Its literally in the footer what it means
