### ISSUE TITLE
Rewards for level 40 were incomplete 

### ISSUE THREAD

**Issue by YourMomAqua** [DankMemer/dank-memer-suggestions-and-bugs#330]
**Rewards for LVL 40 were incomplete**, out of the 5000 coins and the bank note only the coins where given but the bank note Was missing.

1. Level up to LVL 40
2. Get a reward ( bank note and 5000 coins)
3. Check the notifications and inventory but only had the coins added.
4. See Part of the reward missing (bank note)
![CD1C2EBF-BB97-48CA-BF7C-22EEFD68DCA9](https://user-images.githubusercontent.com/65581828/82281453-f67f5a80-9956-11ea-9aa0-d106c995605f.jpeg)
 

**Expected behavior**
I expected to get my 5000 coins and my bank note for levelling up to lvl 40.

**Screenshots**
I’m adding a screenshot of my notifications which also shows that the only thing given was the 5000 coins.

Just reporting this as a mod advised me cause it might be a bug.
Thanks for your time

**Comment by melmsie** [comment]
fixed a few weeks ago
