### ISSUE TITLE
My multiplier is broken

### ISSUE THREAD

**Issue by papachrlz** [DankMemer/dank-memer-suggestions-and-bugs#331]
The multiplier I have is broken as can be seen in the screenshot I have a 6% increase from prestige alone yet the total is only 5%
![Screen Shot 2020-05-19 at 11 20 03 am](https://user-images.githubusercontent.com/65582052/82281462-f36e8380-99c3-11ea-894f-410ed139bda0.png)
![Screen Shot 2020-05-18 at 11 54 48 am](https://user-images.githubusercontent.com/65582052/82281474-fe291880-99c3-11ea-86ad-ef89861e9129.png)
it does not appear to be visual as it is active when gambling idk who this is effecting so far I am the only one of my friends having this problem.

**Comment by melmsie** [comment]
its visual lol
