### ISSUE TITLE
Work promotions not adding up

### ISSUE THREAD

**Issue by Goofierknot5537** [DankMemer/dank-memer-suggestions-and-bugs#332]
**Describe the bug**
I work as a youtuber, and I get promoted often, lets say I get 300+39 coins per work hour. I get that amount of coins. I work again multiple times later and I get promoted again, but instead of showing “339 + 39” I would get “300 +39”.

**To Reproduce**
1. Work as a job that can get promoted.
2. Work a lot.
3. Get promoted.
4. Work a lot again.
5. Get promoted again, then it appears.

**Expected behavior**
I would get something like “339 + 39”

**Screenshots**
https://share.icloud.com/photos/04HAVoUXazjgFucqnP1f0zNOg
Edit: Finally Figured out how to add screenshots
**Additional context**
If this is intended, please ignore this post.

**Comment by melmsie** [comment]
not worth spending time on
