### ISSUE TITLE
bankrobbing and cellphones

### ISSUE THREAD

**Issue by plumpyplumby** [DankMemer/dank-memer-suggestions-and-bugs#334]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frus1trated when [...]
my freinds have bankrobbed me of over 80k, I understand that the function kf bankrobbing is to attack the rich person but the reason I was rich is because I was saving up for my first prestige(this is also why I wasnt and cant be in passive) and had the money but not the levels this has been a huge setback but I have an Idea I hope you find balanced
**Describe the solution you'd like**
I think a cellphone option of 'crime report' or something should be in place, it will work like a reversal card for heists, the police can have a chance to find your money but it is rare they getall of it, like the 'small chunk' 'huge chunk' mechanic

**Describe alternatives you've considered**
maybe you have to pay for an investigation so if the poor people dont steal a significant amount its not worth the effort
**Additional context**

**Comment by oliverysfx** [comment]
![image](https://user-images.githubusercontent.com/54044780/82325843-76b4c700-9a0e-11ea-8648-1df3e1953aa9.png)
there's already a call the police feature which can be used when the heist is still preparing.

**Comment by plumpyplumby** [comment]
yes but sometimes they dont ping you and having all notifications on is annoying to prep for if you get bankrobbed
