### ISSUE TITLE
Donation Perks Not Working 

### ISSUE THREAD

**Issue by DPHANTOMS97** [DankMemer/dank-memer-suggestions-and-bugs#337]
I first bought the two dollar one and that worked fine, but I wanted it for my whole server, so I went to buy the 5 dollar. Ive added my server to the premium list, and ive gotten the dm about my ability to add a server as premium. People on my server still cannot use the premium features 5 dollars comes with.

**Comment by Neptunus-Equester** [comment]
![image](https://user-images.githubusercontent.com/56994342/82368136-e745ee80-99e2-11ea-9766-ae89ee951edc.png)
you need the 10 dollar tier of perks in order to get premium server benefits for all server users
