### ISSUE TITLE
Blackjack glitch

### ISSUE THREAD

**Issue by iAmNobodyToYou** [DankMemer/dank-memer-suggestions-and-bugs#338]
**Describe the bug**
I was using blackjack when a msg came up saying my money was changed snd when i did pls bal i inly had the money i was betting

**To Reproduce**

**Expected behavior**
I lost all my money while using blackjack 

**Screenshots**
I have screen shots but I cannot add them here

**Additional context**

**Comment by iAmNobodyToYou** [comment]
My first time reporting i have no idea what im doing

**Comment by Neptunus-Equester** [comment]
send a dm to Erebus#0123 through discord so we can sort this out
