### ISSUE TITLE
pls blackjack bug

### ISSUE THREAD

**Issue by ev3rage** [DankMemer/dank-memer-suggestions-and-bugs#339]
![Screenshot 2020-05-19 at 4 56 25 PM](https://user-images.githubusercontent.com/65595162/82307702-4ca1db80-99f3-11ea-9f9f-8bbcc7f7a4a3.png)

the number went backwards

16 >> 12 >> 20

**Comment by ev3rage** [comment]
![Screenshot 2020-05-19 at 5 17 13 PM](https://user-images.githubusercontent.com/65595162/82308767-d3a38380-99f4-11ea-9f63-e316895966c7.png)
![Screenshot 2020-05-19 at 5 18 24 PM](https://user-images.githubusercontent.com/65595162/82308776-d69e7400-99f4-11ea-9fc5-d241d9627696.png)

**Comment by austinlame** [comment]
It’s not a bug. The Ace of Spades card is at first an 11, when another card causes the total number to be over 21 the Ace of Spades is counted as a 1. Ace of Spades is always valued as either a 1 or an 11. It’s the basic mechanic of that card.
