### ISSUE TITLE
Apples

### ISSUE THREAD

**Issue by Bennnsonnn** [DankMemer/dank-memer-suggestions-and-bugs#34]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

A new item you can obtain is the Apple. When you use the Apple, you will consume it and it’ll say a similar message like the Bread of how you consumed it. Additionally, it’ll give you a small multiplier towards the coins you earn from the Teacher job (due to the stereotype that teachers like apples). If you aren’t employed for the job, you get no multiplier. Apples can be found by using the “pls search” command. A new location you can search for the Apples is the School. A possible way you can die in the School is if you come across a bully.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by HexCoder101** [comment]
good idea

**Comment by lyl-jerry** [comment]
What about for each job there will be an extra place to search for?
And for some jobs, we add a special item to be searched for.

**Comment by andrewisaboomer** [comment]
um, close this or smth? apples have been implemented but with a different use
thread is probably just dead rn
