### ISSUE TITLE
I had won money on bj but lost it the next day w/out anyone robbing

### ISSUE THREAD

**Issue by Dzhang07** [DankMemer/dank-memer-suggestions-and-bugs#340]
**Describe the bug**
The bug is how i bj and won money, but got it removed
**To Reproduce**
I don't think you can reproduce it because it was a glitch.
**Expected behavior**
i expected 5k money, but got 50 mil. I was super pumped but then they removed all my money.
**Screenshots**
![IMG_20200517_161955](https://user-images.githubusercontent.com/65608535/82335979-024f3900-99b8-11ea-8298-f1e2a9b9744c.jpg)
![Screenshot_20200517-161944](https://user-images.githubusercontent.com/65608535/82336001-09764700-99b8-11ea-84f8-2f159974d67d.jpg)
![Screenshot_20200517-161948](https://user-images.githubusercontent.com/65608535/82336023-0ed39180-99b8-11ea-9c9f-40494ce0397c.jpg)

**Additional context**
Is it possible if I get my money back?

**Comment by Neptunus-Equester** [comment]
that money was due to a bug in the code and was patched. send a dm to Erebus#0123 through discord

**Comment by Dzhang07** [comment]
umm i can't message him bc im not in any mutual servers. which server is he in?

**Comment by Dzhang07** [comment]
> that money was due to a bug in the code and was patched. send a dm to Erebus#0123 through discord
umm i can't message him bc im not in any mutual servers. which server is he in?

**Comment by Neptunus-Equester** [comment]
In DMO. Just send a fr if you need to
