### ISSUE TITLE
“Memorize the words” is broken D:

### ISSUE THREAD

**Issue by luzer-x** [DankMemer/dank-memer-suggestions-and-bugs#341]
**Describe the bug**
When it says something like
Memory - Memorize the words shown and type them in chat;;
`p﻿o﻿i﻿n﻿t﻿y﻿
﻿r﻿o﻿c﻿k﻿
﻿m﻿o﻿u﻿n﻿t﻿a﻿i﻿n﻿
﻿r﻿o﻿c﻿k﻿`
(It did edit it so I can’t see the words)
I typed in “pointy rock mountain rock” , pointy,rock,mountain,rock” , “pointy, rock, mountain, rock” , and “pointy
Rock
Mountain
Rock” and it won’t answer to me at all
**To Reproduce**
1. Say “pls pet play”
2. I think it gives u a random prompt so u keep waiting until It gives you a prompt like that
3. Type in the answer

**Expected behavior**
Maybe fix up the bug and have dank memes actually replies

**Screenshots**
![DA3C63AB-C4FB-4CDC-B11F-7FF805CD5B5A](https://user-images.githubusercontent.com/65609290/82337976-33703f00-99a1-11ea-8605-b4da28f8e709.jpeg)

**Additional context**

**Comment by RandomTurtleBoi** [comment]
You just say `pointy rock mountain rock` on the first time without spaces and i think it should work
