### ISSUE TITLE
Blackjack Bug/Bad coding and not Following rules on Blackjack.

### ISSUE THREAD

**Issue by Roahu** [DankMemer/dank-memer-suggestions-and-bugs#342]
**Describe the bug**
I would say this is bad coding more so than a bug but either applies, to keep it simple
--ive noticed the blackjack doesnt really make sense , is this to give the player a higher chance of winning?
small example, the dealer hits with 17+ sometimes, even soft 17 the dealer hits
-- bot can win with a 4, if player busts or stands below a 4 yes, but the dealer even hits on a double face 20 , i guess im just confused because the basic rules dont apply

                            **Expected behavior**
The expected behavior of blackjack is in simple is this. Player can hit until 5 cards, if player goes over 21 player loses. simple
~~ Now the problem is the dealer. Dealer rules. Dealer must stay on 17, (some versions of blackjack allow dealer to hit on 17 its only a soft 17 { Ace 7 opening } . The bot will hit on 17 occasionally, or even higher than 17.

                         **Screenshots**
 here is one example that just happened, dealer open with a 20, and hits, not only does dealer hit on a 20, but dealer then has 23? and hits again to get 25, how did dealer hit on a 23?

![Screenshot (12)](https://user-images.githubusercontent.com/65609736/82338594-19dbf100-99bb-11ea-9cd5-240ce0dd62af.png)

                   **Additional context**
Having the dealer hit at 17+ loses the Basic dealer advantage that casinos abuse, allowing bot to hit on 17 means a player (discord user) can abuse the Blackjack system to put the game in their favor and increase their odd of winning about 50%, I don't have the whole table and number but I would guess allow a hit on 17+ that the player could have a win rate of around 57-61% if hit and stand right.
Not sure if you want to address this, but I do think the right person who notices could take advantage and abuse this "bug". 
Thank you for your time, and I hope whoever takes the time to reads this has a great day ! And well hope everyone has a great day :)

**Comment by Neptunus-Equester** [comment]
the cards can pop up in any order, so the order is shows above might not be the order they appear in. so in your case, it was probably 10+3+2 and then the additional 10, giving it a bust of 25. the display is just weird. that also covers your second issue as well. dealer stay values 17-21 or bust. in this case, the dealer wouldve had 15 and could take another card

**Comment by melmsie** [comment]
What @Neptunus-Equester said is true in most cases of what you're explaining.
