### ISSUE TITLE
“Unscramble the words” is broken D:

### ISSUE THREAD

**Issue by luzer-x** [DankMemer/dank-memer-suggestions-and-bugs#343]
**Describe the bug**
When it say “unscramble the words for points” or something like that, it did work when I answer for 3 times then it stopped working

**To Reproduce**
1. Say “pls pet play”
2. I think this is random so u have to keep tryin until u get a prompt like that
3. Answer the prompt by unscrambling the words

**Expected behavior**
Probably actually getting my points and make my pet happy

**Screenshots**
![175DFC90-3902-458F-9EE0-8D67383B3A35](https://user-images.githubusercontent.com/65609290/82339620-150b4300-99a3-11ea-8026-4e0ad36aad09.jpeg)

**Additional context**

**Comment by melmsie** [comment]
will be fixed later this summer
