### ISSUE TITLE
Pet Training Points

### ISSUE THREAD

**Issue by PhantomFrenzy151** [DankMemer/dank-memer-suggestions-and-bugs#345]
**Describe the bug**
When maxing out all of the stats of a my pet dog (attack, defense, hunting, sustainability), I ended up with one extra point.

**To Reproduce**
1. Level up a dog pet to the max. (Not sure if it has to be a dog)
2. Assign ten points to each category.
3. You will have one point remaining.

**Expected behavior**
I expected to have 0 points when all points are assigned, or am able to level up skills past their max.

**Additional context**
I'm sure you could just lower the max level by 1.
![Screenshot (26)](https://user-images.githubusercontent.com/65619554/82360426-5a496800-99d7-11ea-9f8d-b1e82ec6a890.png)

**Comment by PhantomFrenzy151** [comment]
Someone else here stated that there should be more types of stats, and I also agree with that.

**Comment by melmsie** [comment]
minor af, will be fixed later this summer in our rewrite
