### ISSUE TITLE
Trivia does not give enough time (I'm not trying to complain, I have a genuine reason)

### ISSUE THREAD

**Issue by lynnsquad24** [DankMemer/dank-memer-suggestions-and-bugs#351]
I have found that trivia questions do not give enough time to read the question and all answers, then type in your response. 
This is coming from someone with a reading disability (called alexia), and I know I'm not the only person using your programs who has difficulty with reading and/or processing. 
For example, in the question attached, I was only able to read the question and the first two answers before I was out of time. ![Screen Shot 2020-05-20 at 12 53 41 AM](https://user-images.githubusercontent.com/65643156/82411414-bc3db800-9a3f-11ea-8022-88353ae2b46b.png)
The questions should all be given at least 10 seconds, more if the question/answers are long. This would give anyone enough time to read and process the question, then come up with a response, while still not allowing enough time to google the answer. 
I believe these fun commands should be more accessible to everyone, and this slight tweak could really help. Thank you
- Henn#1958

**Comment by melmsie** [comment]
added
