### ISSUE TITLE
Dank Memer Bot Work Color 

### ISSUE THREAD

**Issue by Ketchupxx** [DankMemer/dank-memer-suggestions-and-bugs#352]
Hi melmsie, 

I just want to start off by saying I love the bot. There is one minor thing you should change. You see, I’m colourblind, and when I do pls work, I get the color thing a lot, but Idk which is which. I’m not sure if you can fix this, but it causes me to fail. Thank you so much for your time. 

Thanks,

Ketchupxx

**Comment by melmsie** [comment]
We will change this when we rewrite the minigames from scratch in our rewrite, thanks for bringing it to my attention
