### ISSUE TITLE
Rule 4 Change

### ISSUE THREAD

**Issue by ninjardx** [DankMemer/dank-memer-suggestions-and-bugs#355]
**Is your feature request related to a problem? Please describe.**

- yes, currently myself and plenty other people have been banned for violating rule 4

**Describe the solution you'd like**

 - My solution to fix this issue is have it so when someone tries to use the bot to create a meme and uses a blacklisted slur the bot doesn't create the meme and sends a reply saying "Sorry memer, you can't use that sort of language!" or anything like "can't say that word!" this should alleviate the need to go through possibly hundreds of appeals on the forum all from this one rule break, and it would allow people like myself to continue to enjoy the bot!

**Describe alternatives you've considered**

 - I have tried appealing but I do know just from reading the support channels on the official support server that appeals either take a while to get to or they don't appeal people who broke rule 4

**Additional context**

- I have talked to 2 different people who also got banned for using the same word as me and we all where on a private server just goofing around, we had no idea it was against the rule to use slurs with the bot in our own servers. The bot has already coded "error messages" like when yo make a statement such as pls doot the bot will reply "What do you want me to say?" so I thought that either A the bot would say the slur and have no issue ORR the bot would not let me say it and say "sorry can't say that word" but instead we got banned, I think everyone or mostly everyone banned from this rule can agree, IF we had known we would get banned from using the bot for using that kind of word with the bot non of us would have said it, sure its on the "rules" page but nobody reads that first because rules are pretty much the same no matter the game, no cheating / macroeing etc and I was under the impression any swearing / bad language rules would be for the support server only

**Comment by wolf653** [comment]
honestly the punishment is excessive and just creates more appeal spam
