### ISSUE TITLE
Dank memer won't work at all 

### ISSUE THREAD

**Issue by lilscooby12** [DankMemer/dank-memer-suggestions-and-bugs#357]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add
 screenshots to help explain your problem.

**Additional context**

**Comment by Neptunus-Equester** [comment]
whats your user id. this doesnt sound like a bug. im a mod (erebus) and i can check some things for you

**Comment by lilscooby12** [comment]
Sorry I found out that it was that I got banned and I'm very sorry that I
broke a rule and I just want a Second chance and I will learn from my
mistakes and never break a rule again.
