### ISSUE TITLE
work hrs not resetting 

### ISSUE THREAD

**Issue by Neptunus-Equester** [DankMemer/dank-memer-suggestions-and-bugs#358]
**Describe the bug**
work hours are not reset, which causes the issue of being unable to be fired in jobs where you should theoretically be able to
**To Reproduce**
Steps to reproduce the behavior: (idk much cause idk when it happened)
1. choose to work politician
2. work normally
3. hours dont reset
(idk much other than this cause i have no idea when it occured.) i can only logically assume it was bugged from the start as the hrs are the same as my total

**Expected behavior**
work hours should reset to zero when a new day hits, instead, they accumulate over time like your total work hours

**Screenshots**
https://cdn.discordapp.com/attachments/639920133841747999/712741290105765955/unknown.png

**Additional context**

**Comment by melmsie** [comment]
not worth fixing right now
