### ISSUE TITLE
Bug with scientific notation and "k" to describe thousands. 

### ISSUE THREAD

**Issue by Slick56278** [DankMemer/dank-memer-suggestions-and-bugs#363]
In some instances, such as "pls share," the bot will understand "k" to describe thousands as well as scientific notation, such as "e3." However, in other instances, such as "pls blackjack," the bot does not seem to understand "k" while still understanding "e3." For a visual example, please look at this image link. 
https://cdn.discordapp.com/attachments/491466924799164426/712811963494826014/Screen_Shot_2020-05-20_at_4.39.52_PM.png.

**Comment by melmsie** [comment]
slots and bj will allow "k" next update
