### ISSUE TITLE
Change the quest "Terrible Fate"

### ISSUE THREAD

**Issue by wolf653** [DankMemer/dank-memer-suggestions-and-bugs#364]
**Is your feature request related to a problem? Please describe.**
I believe its not really well thought out the quest "Terrible Fate" as it involves sacrificing a life which can result in losing expensive items like a reversal card making the quest far less worth it and acting as a per say "i died but atleast i got something to pay for that death"
**Describe the solution you'd like**
i suppose simply removing the quest

**Describe alternatives you've considered**
possibly making it so when you die with the quest active the penalty for the deaths don't occur.
or buffing the reward of the quest like making it give a life saver to make it more worth it

**Comment by melmsie** [comment]
or simple don't do it if you don't wanna die
