### ISSUE TITLE
Quests Bug

### ISSUE THREAD

**Issue by haydenmfu** [DankMemer/dank-memer-suggestions-and-bugs#368]
So let me just give an example. I did the old **Chronic Gambler** quest by winning 25 gambling games. The updated quest is winning 50 blackjack games. That is why I would like the quests bug to be patched.

**To Reproduce**
1. Go to pls quests list
2. See the Chronic Gambler quest
3. Reads Completed

**Expected behavior**
I expected the quest to be incomplete, I have not won 50 blackjacks and I would like to get bank notes.

**Screenshots**
![image](https://user-images.githubusercontent.com/37965038/82581457-7408bd80-9b45-11ea-9b2a-5961fc59071c.png)

**Comment by melmsie** [comment]
its not a bug, you completed the quest before it got updated

**Comment by haydenmfu** [comment]
Ok fine its not really a bug but i guess its more like PLEASE UPDATE YOUR
QUESTS PLEASE I WANT BANK NOTES PLEASE
