### ISSUE TITLE
Hunting Text

### ISSUE THREAD

**Issue by Rotorial** [DankMemer/dank-memer-suggestions-and-bugs#369]
**Is your feature request related to a problem? Please describe.**
I'm not sure if my request is related to a problem. But I would like the Dank Memer creators to make it so when you catch a Dragon with `pls hunt` that you don't have to swear to catch it. I'm not that type of person to swear. The rest of the bot is fine though.

**Describe the solution you'd like**
The type of solution I'd like is if you could remove the text and replace it with something else.

**Describe alternatives you've considered**
An alternative is just to maybe replace the text with something like "oh shoot a dragon" or "oh frick a dragon" not "oh ---- a dragon."

**Additional context**
I hope you can accept this suggestion because I don't really swear and this would be forcing me too.

**Comment by melmsie** [comment]
uhhhh I guess I can do this

**Comment by Rotorial** [comment]
Thanks!
