### ISSUE TITLE
Fixing pings in non-embed  commands like "pls say" or autoresponse commands like I'm x -> Hi x, I'm dad!

### ISSUE THREAD

**Issue by Squidtoon99** [DankMemer/dank-memer-suggestions-and-bugs#370]
**Is your feature request related to a problem? Please describe.**
multiple different dank memer text-based response commands are being turned off in servers because of raids where user's will spam messages like "*pls say @everyone*" in which the bot pings everyone or I'm @everyone in which the bot pings responsds with a "Hi @everyone" , I'm dad

**Describe the solution you'd like**
I suggest the easiest option to change this would be to replace all message output strings in these with a whitespace character like .replace("@", "@\u200b") which would clear the pings in the message without affecting how the message will look.
**Describe alternatives you've considered**
an alternative to this would be to parse the message.mentions and only replace the parts of the message dank memer is saying that doesn't contain pings.
**Additional context**

**Comment by melmsie** [comment]
we removed say entirely, wasn't aware it was happening in autoresponses too. Will fix this ASAP
