### ISSUE TITLE
Silent Mentioning Issue

### ISSUE THREAD

**Issue by TNAVRESSDOG** [DankMemer/dank-memer-suggestions-and-bugs#371]
**Describe the bug**
When I try to see someone's balance, profile, inv... without pinging them it doesn't work for some users. I've tried pls bal [user], pls bal [id], and pls bal [nickname] but they either all work or they don't depending on which user I'm attempting to mention. I've given a user to the mods in Dank Memer Official #support and they confirmed the issue and so directed me here.

**To Reproduce**
1. Go to any server with dank and use any method you can think of to check a user's balance without a ping.
2. If it works as expected repeat the process with another user until the bot returns your bal rather than the desired user's. (Shouldn't take many tries, most of my server's users won't work) 
3. If after some tries they all work try a different server. Unfortunately I cannot b any more detailed than that the issue seems very random.

**Expected behavior**
I would expect the bot to return the desired user's bal rather than mine.

**Screenshots**
<img width="141" alt="Screen Shot 2020-05-21 at 11 24 56 AM" src="https://user-images.githubusercontent.com/48927937/82593462-66f4ca00-9b57-11ea-8942-0e516a366b36.png">
<img width="284" alt="Screen Shot 2020-05-21 at 11 24 42 AM" src="https://user-images.githubusercontent.com/48927937/82593482-6e1bd800-9b57-11ea-8b43-783a37b8501f.png">
<img width="502" alt="Screen Shot 2020-05-21 at 11 43 04 AM" src="https://user-images.githubusercontent.com/48927937/82594322-bdaed380-9b58-11ea-908b-34fee28d988c.png">
<img width="347" alt="Screen Shot 2020-05-21 at 11 43 37 AM" src="https://user-images.githubusercontent.com/48927937/82594350-cd2e1c80-9b58-11ea-9517-302be8f4af65.png">

**Additional context**
Mods have confirmed this is an issue and directed me here.
A user who does not work may later start working while others still don't.
It seems to apply to all cmds when silent mentioning.

**Comment by melmsie** [comment]
It's a known issue that won't be fixed until the rewrite is done later this summer
