### ISSUE TITLE
Duping Glitch With Quests

### ISSUE THREAD

**Issue by NotYourBuisnessWhoIAm** [DankMemer/dank-memer-suggestions-and-bugs#372]
You can dupe items when completing quests.

I know its not something very many people would do, but to do it you
Complete the quest, and share on of the rewards to someone, if you happen to be trying to do this cause you just sold them something you would get from a quest or something, it will tell you "you dont have this item and then the quest will give you the rewards a second time. (You would need to have none of the items you were sharing)

To recreate
Complete a quest
Try to share the item you get to someone else
It will say you dont have that item
Quest will recomplete and give another set of rewards.

Example
You just finished the bj quest and someone has been waiting for you to give them the banknotes they bought, you finish the last game (it gives you your 3 banknotes) and you instantly share the banknotes to them, but it responds with you dont have 3 of that item, you only have 0, and then it gives you 3 banknotes again, so in the end you get 6.

**Comment by epicjonny312** [comment]
This also happens when you do ‘pls quest’ again after completering this quest. I only know this type of bug works for the bj quest.

**Comment by melmsie** [comment]
known bug, will be fixed in the future
