### ISSUE TITLE
Soz for last on but the bug I’m reporting is on work

### ISSUE THREAD

**Issue by inevergonnausethiswebijustwantreportbug** [DankMemer/dank-memer-suggestions-and-bugs#374]
When up you type pls work and it is an unscramble task if you write pls work again it would let you do two work tasks at the same time

**To Reproduce**

**Expected behavior**
I thought it would of just said you have to more try’s to unscramble but it would give a new task added on to the unscramble task

**Screenshots**
![CBDA7749-9D7E-4AA5-86ED-3F1904046744](https://user-images.githubusercontent.com/65690084/82617750-68d09300-9c14-11ea-87d6-33e37d65966e.png)

**Additional context**
I don’t think this was intentional so just a heads up.

**Comment by PhantomFrenzy151** [comment]
this bug report is a repeat
