### ISSUE TITLE
BlackJack Hack

### ISSUE THREAD

**Issue by TrollMrRicky** [DankMemer/dank-memer-suggestions-and-bugs#375]
**Describe the bug**
When you do BlackJack, if your wallet isn't the same as when you start it, you get to keep your bet. So if you have someone helping you, you can easily just keep blackjacking and not loose coins at all.

**To Reproduce**
1. Do pls bj all
2. If it is a bad hand, have a friend give you 1 coin.
3. You get out of a bad blackjack Scott-free.

**Expected behaviour**
I just don't want blackjack to be a free money earner.
**Screenshots**

**Additional context**

**Comment by melmsie** [comment]
This is no longer the case
