### ISSUE TITLE
Pet killed when full. 

### ISSUE THREAD

**Issue by austinlame** [DankMemer/dank-memer-suggestions-and-bugs#376]
My buddy here’s pet bunny killed him even though his hunger stat was 62%. 

We assumed hunger and hygiene stats are the only stats that will result in your pet killing. Does the fun stat matter too? Not sure if this is a bug or if it’s meant to be like that. 

![0E73E298-1880-4256-A550-C48B81F3AAE6](https://user-images.githubusercontent.com/65549616/82626446-b14c6a00-9b9c-11ea-8666-14db75e0576b.jpeg)
![11D50B45-4AE9-46F6-918F-5701EA7BF815](https://user-images.githubusercontent.com/65549616/82626451-b3aec400-9b9c-11ea-923e-176e7bf70c11.jpeg)

**Comment by oliverysfx** [comment]
the fun bar is empty, as long as any of the top 3 bars are empty(if I am not wrong), the pet may kill
