### ISSUE TITLE
Server is premium but noone can use the premium commands

### ISSUE THREAD

**Issue by dvlewis** [DankMemer/dank-memer-suggestions-and-bugs#379]

**Comment by dvlewis** [comment]
![Capture](https://user-images.githubusercontent.com/63025595/82641842-3b5ef780-9bca-11ea-8f89-e9a30bdeddbd.PNG)
![Capturew](https://user-images.githubusercontent.com/63025595/82641853-3f8b1500-9bca-11ea-85b3-e00d3bc56994.PNG)

**Comment by oliverysfx** [comment]
only $10 patreon premium servers allow everyone in the server to use premium commands, a $5 premium server only allows the premium user to use the command
