### ISSUE TITLE
$5 patreon

### ISSUE THREAD

**Issue by xDexterCu** [DankMemer/dank-memer-suggestions-and-bugs#380]
Pserver add does not work properly. I am still the only one with premium commands

I used pls link and pls pserver add

**Comment by oliverysfx** [comment]
only $10 premium servers allows everyone to use premium commands

**Comment by oliverysfx** [comment]
a $5 still only allows the premium user to use premium commands

**Comment by xDexterCu** [comment]
Oh I must of read the donations wrong, sorry
