### ISSUE TITLE
The __K__ in __withdraw__ and __deposit__ commands

### ISSUE THREAD

**Issue by addicted-to-hot-octolings** [DankMemer/dank-memer-suggestions-and-bugs#381]
**Is your feature request related to a problem? Please describe.**
No, I don't really think so. But I think it's better if we would use both the __e(number)__ and __k__ in __withdraw__ and __deposit__ commands.

**Describe the solution you'd like**
Since some of the commands use the __k__ in currency, why not add __deposit__ and __withdraw__ to it? I think it's good, and a quick way to deposit/withdraw your money

**Describe alternatives you've considered**
I know the __e(number)__ also exists, but I think the __k__ is better, so no alternatives here.

**Comment by King-Of-Cold** [comment]
@melmsie wtf, why did u put the under consideration
i said the same thing and u said it already existed

**Comment by Letoplaz** [comment]
would be convenient, I can think of some times I'd have used this
