### ISSUE TITLE
Command to see how many of an item you have in your inventory

### ISSUE THREAD

**Issue by Ra-ze** [DankMemer/dank-memer-suggestions-and-bugs#385]
It would be very useful if, when you do the `pls shop [item]` command to get more info about it, it also lists how many of the item you have in your inventory (if any). It may seem like a trivial suggestion but it's actually kind of time consuming and annoying to scroll through your 5 pages of inventory to see if you have an item/how much you have. 

Adding this would a very nice quality of life feature.

**Comment by oliverysfx** [comment]
it does already, when you do pls shop [item]
![image](https://user-images.githubusercontent.com/54044780/82732142-f2c84b00-9d3d-11ea-8788-3d49c7aba4a2.png)

**Comment by oliverysfx** [comment]
it does already, when you do pls shop [item]
![image](https://user-images.githubusercontent.com/54044780/82732152-070c4800-9d3e-11ea-96f2-5ace7276c5cc.png)
