### ISSUE TITLE
Pet Hunting not working properly

### ISSUE THREAD

**Issue by Maczie-Clay** [DankMemer/dank-memer-suggestions-and-bugs#387]
**Describe the bug**
My pet (dog) have 10 points in hunting ability, but it only give me 1k coins, it never give me coins worth more than 2k or even things that worth more than 1k. I Have fullfill all requirements such as having love, hunger and fun at full bar.

**Expected behavior**
I expect to receive more coins upto 20k and stuff worth 5k

**Screenshots**
![photo6217718696248453613](https://user-images.githubusercontent.com/65799560/82720858-a6e7b880-9ce1-11ea-9459-b0c9a9a05624.jpg)
![photo6217718696248453612](https://user-images.githubusercontent.com/65799560/82720861-ab13d600-9ce1-11ea-98f9-29bc4dd3a5ae.jpg)

**Additional context**
I tried asking in discord but issue still unsolved.
Sorry for my bad english.

**Comment by oliverysfx** [comment]
might be just your luck though
