### ISSUE TITLE
Bug/typo..?

### ISSUE THREAD

**Issue by spoy1** [DankMemer/dank-memer-suggestions-and-bugs#391]
There is common event called “REEEEEE” where you must type the word “reeee” but the event doesn’t take my response, I’ve actually encountered this event twice, the first time I put the phrase but I was off by two “EE’s”, the second time I just copied the the phrase and pasted it after removing the “ ‘ “ symbol from both sides, it also failed so I’m not sure if it’s character sensitive, or if it’s just a bug , here’s a screenshot. 
![337B2E9D-6576-4B10-9A1E-DB6F63AA8B82](https://user-images.githubusercontent.com/65803066/82726326-fa89e000-9ca8-11ea-8e94-5930d159efbc.jpeg)

**Comment by oliverysfx** [comment]
you can't copy the text for any event, if you copy you fail(the bot has ways to detect this)

**Comment by oliverysfx** [comment]
also the amount of "E"s is completely random so you have to count them
