### ISSUE TITLE
BlackJack ;((((((

### ISSUE THREAD

**Issue by dankfuzed** [DankMemer/dank-memer-suggestions-and-bugs#395]
**Is your feature request related to a problem? Please describe.**
**_Yes, obviously blackjack was added to the game and I feel as if there are a few problems if you're going to implicate an existing game into this game all rules and standards should follow as the real game. Everything seems smooth except for the fact that the bot will start with 2-4 cards, that's not how it should be. If you look it up the dealer and player both start with 2 cards. It should be like that in the game_**
**Describe the solution you'd like**
**_A simple and good solution would just be the dealer and player both starting with 2 cards_**
**Describe alternatives you've considered**
**_There are no alternatives this is how the game should be played_**
**Additional context**
![Screenshot 2020-05-24 at 4 49 01 AM](https://user-images.githubusercontent.com/65848803/82750000-39886600-9d7b-11ea-90c7-bec290a53ed5.png)
both dealers and players start with 2, please change this its ruining blackjack

**Comment by melmsie** [comment]
the bot does start with 2, what are you smoking
