### ISSUE TITLE
doing pls rich while not being in the first rich list shows a white dash next to your name even when you're not passive.

### ISSUE THREAD

**Issue by SergeTFM** [DankMemer/dank-memer-suggestions-and-bugs#398]
**Describe the bug**
Doing pls rich and being like place 15 and having passive off still shows a white line next to your name

**To Reproduce**
1.have passive off 
2.Be like place 15 in rich 
3. Do pls rich
4. See that next to your name it still has a white line next to it even tho ur not passive

**Expected behavior**
should have a blue line because you're not passive

**Screenshots**
![image](https://user-images.githubusercontent.com/50763771/82755498-8c463a00-9ddc-11ea-959d-8177aab63670.png)
![image](https://user-images.githubusercontent.com/50763771/82755526-c1528c80-9ddc-11ea-8205-47da65db9673.png)
![image](https://user-images.githubusercontent.com/50763771/82755569-0d053600-9ddd-11ea-8162-dedf6ab0e22f.png)

**Additional context**
doing pls rich with the number ur in will show the blue line
i have fake id on im tallguy
it also shows ur name even tho u have fake id [in page 1]

**Comment by melmsie** [comment]
I don't see how this is an issue, it's your own rich command
