### ISSUE TITLE
Idea to make pls hunt better

### ISSUE THREAD

**Issue by backinboliet** [DankMemer/dank-memer-suggestions-and-bugs#399]
I would like pls hunt to be more explorational and in depth becuase now its very boring and too much like fishing 

You should add a more in depth way of hunting, such as a search in the woods thing. What im thinking is that whenever you hunt you have four options labeled a b c d and each are a direction north south east west which is the direction you search to hunt. In addition you add secret rare animals which can be found via a specific option of directions for example north, north, east, north, west and you arrive at a dragons lair then do the traditional type "Oh shit a dragon". Also as I was talking about haveing several times to choose which direction to go, each time you choose a direction you have a chance to meet an animal which you have a 25% to catch. So to sum it all up you have 5 opprotunites to catch an animal meaning by chance you should always get at least one and if you're lucky you can stumble upon the dragons lair by a specfic path which will be a seceret for people to find and maybe every 24 hours the lath changes so people cant grind dragons and tell the whole world about it. In addition you could also add new types of guns to add a higher chance of getting an animal each direction you take like if you buy the 30k gun there is a 40% chance of getting an animal each turn instead of a 25% chance and so on.

**Comment by backinboliet** [comment]
Melmsie so do i get feedback or something idk how this works exactly

**Comment by melmsie** [comment]
Your feedback was me closing this, don't be annoying about it.
