### ISSUE TITLE
Additional Color choices ?

### ISSUE THREAD

**Issue by LmaoItsAustin** [DankMemer/dank-memer-suggestions-and-bugs#4]
**Is your feature request related to a problem? Please describe.**

no problem, just a suggestion/request 
**Describe the solution you'd like**

I was wondering if there were any other color roles that could be added to the DMO server, thank 
you for your time <3

**Describe alternatives you've considered**

Can't think of any other way to ask tbh

**Additional context**

Add more color role options

**Comment by melmsie** [comment]
We're looking for suggestions on the bot, not the server.

**Comment by HexCoder101** [comment]
tf
