### ISSUE TITLE
the ability to SWAT people with the phone

### ISSUE THREAD

**Issue by InfernoSuperNova** [DankMemer/dank-memer-suggestions-and-bugs#401]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
I dunno, just a quick way to make someone lose like 300ish coins (can only do it to people with more than x coins) with the risk of losing coins yourself

**Describe alternatives you've considered**

**Additional context**

**Comment by melmsie** [comment]
no
