### ISSUE TITLE
y allow people to only use 'k' for pls gamble?

### ISSUE THREAD

**Issue by King-Of-Cold** [DankMemer/dank-memer-suggestions-and-bugs#405]
u can use k to bet like 5000 at once by doing pls bet 5k
pretty smart idea, ngl
but, u decided that ITS ONLY FOR BET?
like wut, like theres already cooldowns there is no downside to allowing people to use k
im tired of writing pls with 2e3, just let me write 2k

pls i beg u

**Comment by melmsie** [comment]
you can do this lmfao

**Comment by King-Of-Cold** [comment]
> you can do this lmfao

u can only use 'k' for bets
u cant use it for withdrawls
![image](https://user-images.githubusercontent.com/47277934/82844424-6721fc00-9eae-11ea-87bf-93e2b29e53a1.png)
