### ISSUE TITLE
Pls daily stuck at 0

### ISSUE THREAD

**Issue by Haise0398** [DankMemer/dank-memer-suggestions-and-bugs#406]
Describe the bug:
I've been using pls daily for about a week and my streak and daily money have not increased at all

How to reproduce:
I don't know

Expected behavior:
Daily streak increases
Pls daily money increases

Screenshots:
![Screenshot_20200524_195049](https://user-images.githubusercontent.com/65878969/82771250-a130c680-9df8-11ea-8de6-400ba13605a4.jpg)
![Screenshot_20200524_194138_com discord](https://user-images.githubusercontent.com/65878969/82771254-a55ce400-9df8-11ea-95ac-59788d5e918a.jpg)

Context: 
N/A

**Comment by Haise0398** [comment]
My @ is Haise#0398
Id: 338565282639642634

**Comment by melmsie** [comment]
can't reproduce
