### ISSUE TITLE
Rich list no more shows inactive users

### ISSUE THREAD

**Issue by BewkoofBaba** [DankMemer/dank-memer-suggestions-and-bugs#407]
**Is your feature request related to a problem? Please describe.**
Earlier the pls rich command used to show all users from the server (irrespective if they are active or not) - now it only shows users who have used the server or at least done something after bot reboots. this keeps them hidden for infinity if they never become active again or when bot reboots every time.

**Describe the solution you'd like**
If this is hampering the speed of "pls rich" functionality then there should be a "pls richall 1" function which can take its sweet time in loading/indexing all users and show all rich ppl in server after its processing is done. either parameterize the existing or make a totally separate command.

**Describe alternatives you've considered**
None.

**Additional context**
The frequent reboot of server keeps wiping rich list.

**Comment by melmsie** [comment]
This functionality won't change.
