### ISSUE TITLE
Pls disable list ain't working

### ISSUE THREAD

**Issue by newdeveloper1256** [DankMemer/dank-memer-suggestions-and-bugs#408]
The command `pls disable list` ain't working in my server for more than 24h. It returns the following message below:
oopsie poopsie
There was a problem with the disable command, if this happens for more than a few hours please join our server to report this error (https://discord.gg/meme)

**Comment by SergeTFM** [comment]
you have to do pls disable clear and then it will work same happened to me i guess something in code messed that up just run `pls disable clear` and then disable all ur other stuff and the `pls disable list` will work
