### ISSUE TITLE
Tie gamble 

### ISSUE THREAD

**Issue by rayhan6726** [DankMemer/dank-memer-suggestions-and-bugs#41]
**Is your feature request related to a problem? Please describe.**
I always need to type "Pls bal" command after got a tie in gambling feature or counting the half of the amount of coin(s) I gambled.

**Describe the solution you'd like**
When gambling and got a tie, there's should be an information about how much coins the user have, also Dank Memer shouldn't say "you both rolled ...", Dank Memer should say "**we** both rolled ...". The tie box I think will be good if the border color is yellow.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DatHam** [comment]
It can be an embed similar to the win/lose messages but the color is yellow

**Comment by rayhan6726** [comment]
Accidentally reopened lol
