### ISSUE TITLE
Using sand

### ISSUE THREAD

**Issue by DrTerror69** [DankMemer/dank-memer-suggestions-and-bugs#410]
If I sand someone it says person has been sanded and cannot steal for 2 hours while the affect only lasts for 30min on the person and he can rob again after 30min and cannot be sanded again for a time which not sure about is a day probably and says give the person a break his already sanded i mean like whats the use of sand when his gonna start robbing again after 30min without getting sanded again like everyone is doing this to protect themselves gettng sanded again and keep on robbing.

**Comment by oliverysfx** [comment]
I think it's a typo in the reply message of the bot, last time it was 2 hours, but then it got nerfed to 30 minutes but the reply message wasn't changed. Happens to me as well

**Comment by melmsie** [comment]
fixed next update
