### ISSUE TITLE
Pedophile

### ISSUE THREAD

**Issue by Slinkey** [DankMemer/dank-memer-suggestions-and-bugs#411]
**Is your feature request related to a problem? Please describe.** No, i just think it’d be cool to have a “pls pedophilerate @user”
 
**Describe the solution you'd like** For this command to be added.

**Describe alternatives you've considered** I think it should be like “pls howgay”, like pls pedorate @user and it’ll show a random percentage. 

**Additional context** Thanks

**Comment by melmsie** [comment]
no, pedophilia is not a joke

**Comment by DANKSHITMEMER** [comment]
![immagine](https://user-images.githubusercontent.com/65983329/82955812-d92e3a00-9faf-11ea-88cd-6498e6f06e28.png)
