### ISSUE TITLE
Typo of the word provolone in cheese event

### ISSUE THREAD

**Issue by RealMrPeach** [DankMemer/dank-memer-suggestions-and-bugs#412]
**Describe the bug**
Provolone is not spelled with an "a", but an "o" instead.

**To Reproduce**
1. Get a cheese event, with the prompt word "provalone"

**Expected behavior**
The word should be correctly spelled as "provolone"

**Screenshots**
https://media.discordapp.net/attachments/491466924799164426/714478923697750087/Screen_Shot_2020-05-25_at_10.03.45_AM.png

**Comment by melmsie** [comment]
fixed in next update
