### ISSUE TITLE
FakeIDs Should Affect Gamelb (Trivia Leaderboard)

### ISSUE THREAD

**Issue by NotScappy** [DankMemer/dank-memer-suggestions-and-bugs#413]
I used a fake id to prevent myself from getting robbed. However, a few hours after, someone still found me and robbed a good chunk of money. I wanted to find out how they knew I had money to rob, and to my surprise, found that my name wasn't masked when the pls gamelb command was used. I see a lot of people finding people to bankrob by using the pls gamelb command, and I think that fake IDs should cover it up on all the leaderboards. If that makes the price of the item go up, so be it. However, as of right now, fake ids are useless for people who like to grind the trivia command.

**Comment by Wise2006** [comment]
Interesting...

**Comment by melmsie** [comment]
the game leaderboard doesn't mention how much money you have
