### ISSUE TITLE
Selling stuff easier

### ISSUE THREAD

**Issue by AAA-A1a** [DankMemer/dank-memer-suggestions-and-bugs#414]
**Is your feature request related to a problem? Please describe.**
When wanting to sell all of a specific item, it's annoying having to put the exact number to sell all of them

**Describe the solution you'd like**
"Pls sell [item] max/all" command

**Describe alternatives you've considered**
No alternatives

**Additional context**
Example: "pls sell fish max" sells all the fish you have in your inventory

**Comment by melmsie** [comment]
already planned
