### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by SortaMadBernie** [DankMemer/dank-memer-suggestions-and-bugs#415]
Whenever someone wants to sell something, trade something, they have to look at their inventory. People have their laptops broken, their fishing poles broken, and so on. Now, that person has to look through their entire inventory just to see if they have that certain item or not. 

My solution is a new command. The command is: pls inventory (item). This will make finding items much quicker and it would also not fill up an entire chunk of the chat. It would show how much of that item you have, how much it can sell for, and if you do not have it, just make the persons life easier and tell them how much it would cost.

I was originally thinking of a command such as: pls inventory tool (fishing rods, laptops, hunting rifles, etc), pls inventory animal (duck, dragon, boar, common fish, etc.), and pls inventory miscellaneous (padlocks, Santa's hat, stuff like that). I feel like pls inventory (item) is better though because it can just show the one item that the user wants to see.

Hopefully you will consider this.

**Comment by oliverysfx** [comment]
there's already pls shop (item), this is useless

**Comment by SortaMadBernie** [comment]
My command has nothing to do with shop, its for inventory. The only thing that it has to do with shop is if the item that you are looking for is not in your inventory, it would then show the price and the selling price

**Comment by melmsie** [comment]
they're saying `pls shop item` says how many you own, which is true.
