### ISSUE TITLE
I lose coins when reversal the reversal

### ISSUE THREAD

**Issue by V31is1av** [DankMemer/dank-memer-suggestions-and-bugs#416]
i lost 500 000 coins, this happened when somebody steal from me, i use reversal, and he use reversal too. Then i reverse his reversal by using another one. And the the money that this person tried to steal from 

1. somebody steal from me
2. i use reversal
3. he use reversal
4. i use reversal again 
5. The amount of money that he tried to steal from me dissapear from my bank

i expected that my coins will be back to me, and yes they were. But somehow the coins that dissapear were from my bank which iss inpossible and in that time nobody bankrobed me.

![image](https://user-images.githubusercontent.com/65917791/82835024-7c595380-9ecb-11ea-9e46-c9a03da2165c.png)
![image](https://user-images.githubusercontent.com/65917791/82835053-91ce7d80-9ecb-11ea-9747-991d1ce70b0c.png)
![image](https://user-images.githubusercontent.com/65917791/82835066-9d21a900-9ecb-11ea-8d29-161b77327c97.png)
![image](https://user-images.githubusercontent.com/65917791/82835090-ad398880-9ecb-11ea-8645-85b5525e0ae9.png)
![image](https://user-images.githubusercontent.com/65917791/82835104-bb87a480-9ecb-11ea-8b8a-9dfadf1a60c8.png)
![image](https://user-images.githubusercontent.com/65917791/82835122-c6dad000-9ecb-11ea-8872-8423003c584e.png)
![image](https://user-images.githubusercontent.com/65917791/82835145-d3f7bf00-9ecb-11ea-85ff-ba0935e106b8.png)
![image](https://user-images.githubusercontent.com/65917791/82835151-dbb76380-9ecb-11ea-9b73-fbc12612b217.png)
![image](https://user-images.githubusercontent.com/65917791/82835160-e2de7180-9ecb-11ea-9cdc-80e99c9afeee.png)

**Comment by oliverysfx** [comment]
not impossible, if you have enough in your bank / wallet, it will be deducted, this is intended
