### ISSUE TITLE
don't do blackjack all when have robbed people before in 5 min

### ISSUE THREAD

**Issue by tester404nope** [DankMemer/dank-memer-suggestions-and-bugs#417]
**Describe the bug**
the bug include negative money that can get by successfully robing someone then playing blackjack 

**To Reproduce**
1. ask your friend to rob you at if was 
successfully robed over 500 money  process to next step
2. ask you friends to post pls blackjack all then don't do anything 
3. you have to use reversal card 
4. let your friends continue blackjack session

**Expected behavior**
your friend is now have 250 amd then got took away by amount they bet before you have use reversal/2 so your friend got negaive number in wallet

**Screenshots**
![Screenshot_20200526_011135](https://user-images.githubusercontent.com/65918405/82837696-01f0f980-9ef4-11ea-987b-42c31805320d.jpg)

**Additional context**
my friend has lose at least 100k in order they discovered a bug please help him

**Comment by oliverysfx** [comment]
if I am not wrong this is intended

**Comment by melmsie** [comment]
It's intended to counter people duplicating money before this existed.
