### ISSUE TITLE
Being able to work twice, maybe more. 

### ISSUE THREAD

**Issue by Slick56278** [DankMemer/dank-memer-suggestions-and-bugs#419]
**Describe the bug**
A user, on running "pls work," or "pls job" will be able to then run "pls work" after the mini game for the first one starts. 

**To Reproduce**
1. Run "pls work"
2. Instead of giving a normal answer to the mini game, run "pls work" again.
3. Complete both mini games and either gets 1.5 amount of the coins or double. 

**Expected behavior**
If one were to run "pls work" after running it once, it should count as an invalid answer rather than running another mini game. 
**Screenshots**
Please take a look at this screenshot if you're still confused. https://cdn.discordapp.com/attachments/666530965958557706/714581973254930452/Screen_Shot_2020-05-25_at_1.48.40_PM.png

**Additional context**
Not the biggest problem out there, but some users could abuse it for a little extra money.

**Comment by DuhDino** [comment]
Yeah that happened to me today 👁️👄👁️

**Comment by Slick56278** [comment]
Yeah I got it from it happening to someone else and then i tried it myself.
