### ISSUE TITLE
Passive mode 

### ISSUE THREAD

**Issue by The-blackout** [DankMemer/dank-memer-suggestions-and-bugs#42]
**Is your feature request related to a problem?**
Not really but if you wanna look at like a problem it can be

**Describe the solution you'd like**
I want the passive mode command to be disabled in the support server cause there’s no point in it.

**Describe alternatives you've considered**
Disable the passive command in support server

**Additional context**
I have none

**Comment by kablekompany** [comment]
Passive mode is globally adherent to its setting. It will stay enabled in support server as there’s a lot of confusion in toggling it. They can find details regarding the mode, and toggle it in our bot command channels.
