### ISSUE TITLE
removemydata command bug

### ISSUE THREAD

**Issue by Squidtoon99** [DankMemer/dank-memer-suggestions-and-bugs#420]
**Describe the bug**
when bot banned users run `pls removemydata` they get DM'd the welcome to dank memer message but nothing changes.
**To Reproduce**
1. run `pls removemydata` on a bot banned account (no commands work, not even pls fun, pls meme, etc)
2. You'll get a DM showing dank memer's welcome message

**Expected behavior**
The bot shouldn't be registering commands from banned user's and shouldn't DM the user or accept the command 

**Screenshots**

**Additional context**

**Comment by oliverysfx** [comment]
pls removemydata is intended to work even when bot banned. not bug

**Comment by Squidtoon99** [comment]
I understand that is supposed to work bit it still DM's rhe user welcome to dank memer and there is no cooldown on the command.

**Comment by melmsie** [comment]
yes, because it wiped their data and counts that as their first new command ran lol
