### ISSUE TITLE
Bolt Cutters Item

### ISSUE THREAD

**Issue by JaysinChay** [DankMemer/dank-memer-suggestions-and-bugs#422]
Padlocks have become quite overpowered in the game and are used more of as a deterrence item. It's getting too overpowered.

I think a real bolt cutters item would be useful, but should remain a little bit more expensive than the padlock, so it doesn't make it completely useless. It should have a decent fail rate, and a mini activity where the bolt cutters can break. (Maybe costing 5000-10000)

**Comment by wolf653** [comment]
simply rob them again better solution the padlock breaks after a rob attempt allowing you to attempt it again

**Comment by oliverysfx** [comment]
the bolt cutters is a meme item after all, only the bot has it. and wolf653 is correct
