### ISSUE TITLE
Get to give and receive money when passive mode is enabled

### ISSUE THREAD

**Issue by undermaster141** [DankMemer/dank-memer-suggestions-and-bugs#425]
**Is your feature request related to a problem? Please describe.**

- Not really a problem since it's a feature request

**Describe the solution you'd like**

- Allow us to still be able to give and receive money when passive mode is enabled

**Describe alternatives you've considered**

- There's no alternative, I just need to disable passive mode every time I win a Dank Memer Giveaway or a friend wants to give me coins and I have to wait 24 hours to enable it again and the money I received will just be stolen 

**Additional context**

- If this won't be added, I'd suggest for a smaller wait time to re-enable or re-disable for passive mode such as 12 hours or 15 hours

**Comment by oliverysfx** [comment]
the reason that passive was added in the first place was to allow people who wants to grind the bot on their own do that, and not interact with others. so it simply doesn't make sense for people to be able to share. also, it's not the least bit intended to allow people to just prevent stealing by disabling passive then reenabling it, which is the reason of the 24 hour cooldown.
P.S. the passive nerf of no giving was put in place after passive was released
