### ISSUE TITLE
Dank Memer server suggestion

### ISSUE THREAD

**Issue by Ducki7977OnDiscord** [DankMemer/dank-memer-suggestions-and-bugs#429]
I would prefer, and most likely many other people, for there to be more bot command channels, and no cool down. The bot has commands that the cool down ruins like, pls search, as you would need a response after you type it, or the type <whatever the sentence / word is> especially if its a boss. I would mainly just like the slow mode removed, but to reduce spam, many channles for bot cammands should be introduced.

**Comment by oliverysfx** [comment]
but most people will still only spam in one channel

**Comment by oliverysfx** [comment]
also if you are unhappy with the slowmode, add the bot to your own server
