### ISSUE TITLE
Passive mode spelled wrong

### ISSUE THREAD

**Issue by The-blackout** [DankMemer/dank-memer-suggestions-and-bugs#43]
**Describe the bug**
The word passive is spelled wrong

**To Reproduce**
1. Say pls settings passive true
2. Bet any amount 
Look at the bottom and it spells passive wrong 

**Expected behavior**  
it be spelled right 

**Screenshots**
![65945378-7E7D-4665-B39E-C657CCC04CF1](https://user-images.githubusercontent.com/62353274/77118940-c32e5700-6a0b-11ea-9ad0-70192b3f8744.png)

**Additional context**

**Comment by kablekompany** [comment]
fixed as of 3.20.20
