### ISSUE TITLE
Rare pepe And Pepe coin Buff

### ISSUE THREAD

**Issue by bruhder** [DankMemer/dank-memer-suggestions-and-bugs#430]
**Is your feature request related to a problem? Please describe.**
It’s sad how I collected a lot of rare pepe and pepec and the price just reduced to half. It was really hard accumulating the pepes.

**Describe the solution you'd like**
I guess it’s better to bring back the value of the pepe (100k) and pepec (1m)

**Describe alternatives you've considered**
Rising the value of the pepe (75k) and pepec (750k)

**Additional context**
Try giving some use of pepe and pepec. Like for a pepec when doing “pls use pec” it flips the pepe coin and doing “pls use pepe” shows the pepe looking side by side.

**Comment by oliverysfx** [comment]
there's pepe medal and pepe trophy now

**Comment by melmsie** [comment]
no
