### ISSUE TITLE
Totems!

### ISSUE THREAD

**Issue by Sadrazoozoo8** [DankMemer/dank-memer-suggestions-and-bugs#432]
**Is your feature request related to a problem? Please describe.**
hunting and fishing seem pretty underwhelming.
**Describe the solution you'd like**
add hunting and fishing totems that you can buy from the shop / get as drops and they increase your chance at finding better animals and fish when fishing and hunting!

**Describe alternatives you've considered**

**Additional context**

**Comment by DANKSHITMEMER** [comment]
![immagine](https://user-images.githubusercontent.com/65983329/82955980-23172000-9fb0-11ea-9794-3db4adc45ad8.png)
