### ISSUE TITLE
Calling the police from any server

### ISSUE THREAD

**Issue by Aura0448** [DankMemer/dank-memer-suggestions-and-bugs#433]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when people heist me and then spam ttt or fight in that channel so that I can't call the police. 

**Describe the solution you'd like**
I would like to be able to call the police from any server.

**Describe alternatives you've considered**
You can leave the server but in the case where you're being targeted for being staff, you can't just leave the server.

**Additional context**
This often happens when people are trying to heist you. By spamming ttt or fight Dank memer is waiting for you to respond to the game and won't accept any commands, so therefore you can't call the police from that channel which is the only way to stop a heist.

**Comment by DANKSHITMEMER** [comment]
![immagine](https://user-images.githubusercontent.com/65983329/82955962-1db9d580-9fb0-11ea-9868-7cc6b23f4169.png)

**Comment by omgitzmo** [comment]
I second this
