### ISSUE TITLE
Move pls give stats and pls gift stats to pls profile 

### ISSUE THREAD

**Issue by DatHam** [DankMemer/dank-memer-suggestions-and-bugs#438]
**Is your feature request related to a problem? Please describe.**

It is just inconsistant how the gamble and rob stats are in pls profile --help, but give and gift are not. Also, you cannot view give and gift stats while you are in passive mode. 

**Describe the solution you'd like**

Instead of the commands pls give/gift stats, make it pls profile --give/gift. 

**Describe alternatives you've considered**

Make passive mode users able to use pls give/gift stats 

**Additional context**
N/A

**Comment by melmsie** [comment]
added last update
