### ISSUE TITLE
Add a Total line to pls bal

### ISSUE THREAD

**Issue by WonderfulFairy** [DankMemer/dank-memer-suggestions-and-bugs#439]
The `pls bal` command shows the amount of money in your wallet and bank. Sometimes it isn't easy to calculate the exact total of your money like when you have 3, 221, 836 in wallet and 54, 927, 231 in bank, all you'll know is that the total might be something around 58, 000, 000. Whenever I want to know the exact total of my money I should follow these steps: 1. `pls with all` 2. `pls bal` 3. `pls dep all` and that's kinda annoying. It would be very nice to have another line called **Total**: [number] in`pls bal`'s embed which would look like this:
![Capture](https://user-images.githubusercontent.com/65344716/83014733-79c63d80-a034-11ea-9f7e-d1b001c2a205.PNG)

**Comment by melmsie** [comment]
added last update
