### ISSUE TITLE
Normie Box opening 

### ISSUE THREAD

**Issue by Mine-ManWR** [DankMemer/dank-memer-suggestions-and-bugs#44]
The bug is that when I typed "pls open normie" Dank Memer responded with "opening Normie Box" that did nothing. it didn't tell me what i got

**To Reproduce**
1. Me: Pls use normie
2. Dank: Opening Normie box

**Expected behavior**
to tell me what i got, coins, etc

**Screenshots**
![image](https://user-images.githubusercontent.com/62437195/77180326-210c7e80-6aa0-11ea-9b99-f795cdbdce6d.png)

**Comment by melmsie** [comment]
9 times out of 10, it's because discord API is having issues. There's nothing we can do about this bug
