### ISSUE TITLE
New Command: pls net

### ISSUE THREAD

**Issue by MooMooMooMooMooMooMoo2** [DankMemer/dank-memer-suggestions-and-bugs#440]
### **Describe the solution you'd like**
I would like a new command called `pls net` related to the new animal crossing game, New Horizons. To use the command, you have to buy a butterfly net from the shop.

### **Additional context**
**New Item:** Butterfly Net
**Price:** 15k
**Usage:** Net bugs with this!

**New Command:** `pls net`
**Usage:** Use this command to get one of 10 bugs:
   **Name — Sell Price**
Ant🐜 — 60
Black Beetle — 150
Snail🐌 — 250
Ladybug🐞 — 400
Cricket🦗 — 500
Scorpion🦂 — 700
Centipede🐛 — 850
Wasp🦟 — 1000
**😡 BOSS 😡 | 3% chance of happening, medium-tiered items or one of these bugs:**
Spider🕷 — 3500
Butterfly🦋 — 5000
(Prices are subject to change.)
### Idea for a secret
When you get a spider, you can use the command `pls use spider` and Dank Memer will say something on the lines of this: “Who would you like to scare with your creepy crawly?” Then the member you respond with will be scared out of their mind and feint. (Allowing you to rob them for the next ten minutes even with some items that regularly would stop you. (Landmine, padlock) (if you have a pet that can attack/defend it will)

**Comment by wolf653** [comment]
ok listen passive is designed to be well passive it allows newer players to progress more without getting their coins taken every 5 seconds also for rich users it allows them to keep their cash without people wiping them clean

**Comment by oliverysfx** [comment]
the idea is quite good, but allowig people to rob people in passive is just kind of too much. I mean after all passive is already nerfed so much

**Comment by MooMooMooMooMooMooMoo2** [comment]
Yeah, I kind of thought someone would say that, so let me change this a bit. I think that this alternative will be more fair to users involved with the bot. I changed the millipede to a wasp, because there was no emoji for that. I could replace the black beetle, but that’s a common thing to catch in New Horizons.

**Comment by melmsie** [comment]
I get what you're going for, but we're not going in this direction at this time
