### ISSUE TITLE
Gambling addictions

### ISSUE THREAD

**Issue by username-not-available-not-available** [DankMemer/dank-memer-suggestions-and-bugs#442]
**Is your feature request related to a problem? Please describe.**
gambling addiction ig
**Describe the solution you'd like**
alrighty, since theres some people who are addicted to gambling and need some way to stop easier, maybe add a setting call gamble, so you can do pls settings gamble off and you won't be able to gamble if its off. It should stop ppl from being so addicted to gambling and it won't blow away thre wallet. theres no extra buffs given if you have it on, just to solve gambling problems.

**Describe alternatives you've considered**

**Additional context**

**Comment by King-Of-Cold** [comment]
or you could make it so that you can't turn it off for how long you set it for (like a day or something) kinda like passive mode
