### ISSUE TITLE
Ability to Transfer a Pet or have 2 pets

### ISSUE THREAD

**Issue by dcaiadaviation** [DankMemer/dank-memer-suggestions-and-bugs#445]
**Is your feature request related to a problem? Please describe.**
I want to complete the dragon quest, but for that I must disown my pet cat.  I want to know my pet is in good care, even though he is digital, so I can have my pet dragon.  Or, I want to be able to have the dragon and the cat.

**Describe the solution you'd like**
I want there to be a way to give your pet to someone without a pet with a `pls pet transfer @username` and you have to say (y/n) and the person you tag has to say (y/n). Also, you should be able to have multiple pets, and to do things with each one, you can do `pls pet (action) (pet name)`

**Describe alternatives you've considered**
I could disown my current pet to complete the dragon quest, but I've grown an attachment to him, because the pet I have with Dank Memer represents the pet I have in real life.

**Comment by wolf653** [comment]
so basically you want 2 pets cause so for some reason you got a virtual pet based on your pet and don't want to disown it without feeling bad? listen mate the two pets idea seems to be for your own advantage here as basically this idea allows you to double skills effectively making pet hunts more common and pet protection chances more common as well the only idea i agree with is pet trading as basically no need to bother leveling up that damn crab hell you can sell your dog for a thousand pink dildos if you want
