### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by King-Of-Cold** [DankMemer/dank-memer-suggestions-and-bugs#447]
there is a chance this might've been intentional, but if it is, its just annoying ngl

![image](https://user-images.githubusercontent.com/47277934/83089628-ccb7e900-a064-11ea-9a0d-1b1baf59c2b4.png)
why does send the notification 4 times. even if it's for emphasis, that's kinda dumb

**Comment by melmsie** [comment]
It's a bug lol
