### ISSUE TITLE
New pls travel command

### ISSUE THREAD

**Issue by IAmMysteriousM** [DankMemer/dank-memer-suggestions-and-bugs#448]
This seems like a fairly complex idea so get a drink because you'll need it. Happy reading!

**Describe the solution you'd like**
I spent 3 days to cook up the details but what about implementing a pls travel command? This is a mix of pls search and pls fish/hunt. It's similar to pls search because users will able to select one of 3 countries (or you can change them to major cities) to fly to. It's similar to pls fish/hunt because instead of bringing back different types of fishes/animals, you'll bring back gifts/souvenirs. Like pls fish and pls hunt where you need a fishing rod/rifle, you need a passport to use pls travel. Similar to how a fishing rod and rifle can break, a passport can expire in 6 months.

The only way to "renew" your passport is to buy another one to fly... or you can use the command "pls passport renew" 1 week before it expires. It will cost less to renew your passport rather than buying a new passport. The only difference is that it can only be renewed 1 week before it expires. If someone forgets, they'll have to buy a new passport. Also, if you die or prestige, you lose your passport. We're human after all, am I right? 

**How to:**
1. Type "pls use passport". This will go on your profile and show when it expires like how a padlock works for a year.
2. Type "pls travel". If you type pls travel without a passport, you can't travel like you need a rod to fish/ rifle to hunt.
3. User gets prompted 3 random countries to pick from. Similar to pls search and 3 options.
4. User picks ONE country and they get to find the items below or nothing at all.

 They will select one and they'll get to bring back one of the following souvenirs. These souvenirs **cannot** be bought in the store. Users have to travel around the world to collect these items, but perhaps they can sell these items at the store for coins. 

**Locations/Souvenirs**
Traveling to the following continents can bring back a small amount of  1 of these 3 souvenirs... or nothing at all.
- Flying to a _EUROPEAN_ country can bring back
     - 🏺antique vase, 👑royal crown, 🛡️ancient shield.
     - Countries include: UK, France, Spain, Greece, Germany
- Flying to an _AUSTRALIAN_ country can bring back
     - 💎diamond, 🐛big bug, 🐠nemo.
     - Countries include: New Zealand, Australia, Tasmania, Polynesia, New Guinea
- Flying to an _ASIAN_ country can bring back
     - 🧧red envelope, 🏮 lantern, 🍣sushi.
     - Countries include: Japan, India, Korea, China, Singapore
- Flying to an _AFRICAN_ country can bring back
     - 🦴lion's bone, 💰gold, ☥ankh.
     - Countries include: Egypt, Nigeria, Kenya, Ethiopia, Botswana
- Flying to a _N.AMERICAN_ country can bring back
     - 🧻toilet paper, 🎥camera, 🍁maple leaf.
     - Countries include: United States, Canada, Jamaica, Mexico, Puerto Rico
- Flying to a _S.AMERICAN_ country can bring back
     - 🎸mariachi guitar, 🗿moai, 🌶️ hot pepper.
     - Countries include: Argentina, Brazil, Peru, Venezuela, Bolivia

_Why these countries? I picked a country in each direction for each continent. (Central North South East West). If these countries (or if the devs rather use major city names) get selected, it'll be good for you to learn your geography/spelling again. They are also major countries so don't complain unless the dev choose some name like: Seychelles, Kiribati, Lesotho, Azerbaijan... in that case, we're screwed. Jk. No offense to anyone living in these countries._

Also there could be a 3-5% chance you bring back:
- 🎁Special crate, 📦normal crate.
- 🔑Special key: opens special crate, 🔑regular key: opens normal crate.
- Both keys are bought at the item shop. Special key cost more than regular key.
- I haven't thought of what is in the special/normal crate. Maybe a few more of an souvenir stuff 
        is in the box? Like you normal find 1-4 items per trip but a crate can give you 5-8 items. 
        Another possibility is to put 1 or 2 high tier items from the store like cheese, rare pepe, pcs, 
        idk... surprise us!

_All Country names, souvenirs, emojis, prices for each souvenir, passport, renewal cost, time frame for passport expiration, etc can be changed. I picked these as an example to understand my idea._

**What are these items that people find in the countries used for?**
Other than selling the items, you can craft up an idea to combine these items to make a better item like the dragon quest where we can combine stuff and coins for a better item. Maybe users can build a level 1, level 2, level 3 item. Item like a fishing rod/rifle or you can make up a new weapon like a sword. For example, a level 3 rifle might have a lower chance of breaking after you meet a dragon or a higher chance of finding higher priced animals like a boar.

You can use the leveled up item or sell the higher level item for a higher price at the store. Ex: Level 1 item needs 5 maple leaves + 10 hot peppers + 5 red envelopes + etc to build. It gives people a push to fly around the world to collect these souvenirs.

Also, you can pay a dank merchant to make the items. The merchant charges you a small fee to build the leveled items. In order for users not to be able to make a level 3 item off the bat, you can make it so that users need 5 level 1 fishing rods + 15 gold +  20 shields + etc to build a level 2 fishing rod. And maybe 5 level 2 rods + whatever items and so on to make a level 3 rod.

I was thinking if it would be fair to charge more to build a level 1 rod than a level 3 rod, but I honestly don't know. Normally people say yes a level 3 cost more (since it has better functions) but if we do it where you need 5 level 2 rods to make a level 3 rod, you already paid the merchant so much to build a level 1 rod for a level 2 rod. Users are also continuously paying for a passport to travel around the world. I also don't know if the merchant should be able to make 1 item at a time or if a merchant can make up to 5 to 10 items at a time. Can't overwork our merchant now can we? I haven't thought that far so it's up to your discretion. 

**Describe alternatives you've considered**
Instead of a dank merchant, you pay mysterious Merchant M (the first letter of my name) because you know... it's in tribute to me for thinking of this idea. Yes? No? Well, it was worth a try. Or we can go with the more popular option -> Merchant Melms who can craft these items. Say it's Merchant Melms, he is not a god. **Sorry**. Since he's not a god, the cooldown to make these leveled items might be 1 or 2 hours or so. Not sure what command to use to call for to make the items. Maybe use "pls merchant" then a table pops up for options like the pls pet commands.

ORRRRR maybe you can put the phone in good use and **finally** get to talk to Merchant M... oops I mean Merchant Melms himself. Get it? Because Melms doesn't like to be @ in discord. Ha ha ha.

Ok that's it. I spent too much time thinking of this... Probably not worth more of my time if the idea gets rejected lol

**Comment by SymboLife** [comment]
I like your idea a lot and I would use it but bro, I think dmo will not go thru with this due to how long this code will take to write. You're asking for a new system. Ten outta ten on creativity bro
