### ISSUE TITLE
Gambling with each other

### ISSUE THREAD

**Issue by 6ix9ineThicc** [DankMemer/dank-memer-suggestions-and-bugs#45]
**Is your feature request related to a problem? Please describe.**
It's not. 

**Describe the solution you'd like**
I think it would be fun to gamble with each other in dank memer if both parties agree. (e.g 
>pls gamble 200 @urmom gay
>@urmom gay would you like to gamble with @melms? y or n
>y
>@urmom gay won 342 coins 
>@urmom gay rolled an 8
> @melms rolled a 5) just the way it might work.

**Describe alternatives you've considered**
I'm certain that there are other alternative discord gambling bots, but I wanna gamble dank memer coins. with friends.

**Additional context**

**Comment by The-blackout** [comment]
I like it

**Comment by DxrkWolf** [comment]
Same here

**Comment by melmsie** [comment]
This is already something on our docket.
