### ISSUE TITLE
New Item to buy in the shop

### ISSUE THREAD

**Issue by N3T-X** [DankMemer/dank-memer-suggestions-and-bugs#452]
I have a new item idea, a Shotgun. The shotgun would cost 45,000 coins, and you would buy shells for it for 500 coins. The use of the shotgun would to kill people and be able to take their money from their wallet. ( If they have a Life Saver they wouldnt die, yet the person who shot the shotgun would still have used a shell )

I would think this would be fun!

**Comment by oliverysfx** [comment]
add a chance that the shotgun backfires and you die instead

**Comment by King-Of-Cold** [comment]
if it only works for non-passive users then it is worthless, as could just rob them instead

if it works for passive users, then it destroys the point of passive mode existing

**Comment by oliverysfx** [comment]
not really, if the chance of back fire is really high, then people might just not wanna risk it.

**Comment by oliverysfx** [comment]
actually it would be better that if you have a shotgun and at least one shell, you have a higher chance of succeeding in a heist

**Comment by N3T-X** [comment]
> actually it would be better that if you have a shotgun and at least one shell, you have a higher chance of succeeding in a heist

**Comment by N3T-X** [comment]
> add a chance that the shotgun backfires and you die instead

very good
