### ISSUE TITLE
start with hunting rifle on prestige

### ISSUE THREAD

**Issue by oliverysfx** [DankMemer/dank-memer-suggestions-and-bugs#453]
**Is your feature request related to a problem? Please describe.**
it's kinda annoying that you get every useful item but hunting rifle on prestige

**Describe the solution you'd like**
get a hunting rifle on prestige

**Describe alternatives you've considered**
non alternatives

**Additional context**
I just prestiged.

**Comment by N3T-X** [comment]
HMMMMMMMMMMMMMMMMM good idea

**Comment by SymboLife** [comment]
I like your idea. Fishing, hunting, laptop, and rare pepe really help get me on my feet after prestiging.

**Comment by melmsie** [comment]
done
