### ISSUE TITLE
Caught robbing/heisting

### ISSUE THREAD

**Issue by King-Of-Cold** [DankMemer/dank-memer-suggestions-and-bugs#455]
I understand why you would want to make people get caught, I think it's cool, but I think there should be an item that would prevent you from getting caught

![image](https://user-images.githubusercontent.com/47277934/83106367-59c16900-a08a-11ea-81ed-26cdf3927935.png)
I think there should be an item called a face mask that costs like 2000 coins and if you use it before  a heist, then you won't get that message.

Getting a job fail isn't that big of a deal so I don't see the item as that OP

**Comment by SymboLife** [comment]
No bro getting caught is like a warning and bro least of your problems you aren't fired yet. A face mask is encouraging crimes. Also that off chance that someone with 100K bank gets heisted but they wear a 2K face mask to save themselves is a cheap deal.

**Comment by melmsie** [comment]
not really important right now over other features and bugs
