### ISSUE TITLE
Tic-tac-toe spam to interfere with police call

### ISSUE THREAD

**Issue by lynnsquad24** [DankMemer/dank-memer-suggestions-and-bugs#456]
Once a heist has been started, people in chat start spamming ``pls tictactoe @victim`` to start dozens of games with them. When the victim tries to use their cell phone to call police and stop the heist, they are unable to because it is an invalid response to the tictactoe game. 

**To Reproduce**
1. run ``pls heist @victim``
2. spam ``pls tictactoe @victim``
3. Victim tries to use cell phone using ``pls use cell``
4. Victim is unable to use cell phone due to ongoing tictactoe games

**Expected behavior**
Any tictactoe games should not be started when the requested opponent is being heisted. Additionally, only one tictactoe game should be able to be started with a certain user within a given threshold (say 30 seconds). This will prevent tictactoe games from being spammed before the heist to incur the same issue. 

**Screenshots**
![Screen Shot 2020-05-28 at 3 17 01 AM](https://user-images.githubusercontent.com/65643156/83110913-c855f500-a091-11ea-82f3-65cd9d0b2e1c.png)

**Additional context**
It should be looked into to see if any other dank memer features + games can expose this same cheat

**Comment by oliverysfx** [comment]
this is a duplicate bug report, a lot of people have already reported this

**Comment by MooMooMooMooMooMooMoo2** [comment]
I fix this by going in a different channel/server and then doing it.

**Comment by lynnsquad24** [comment]
> I fix this by going in a different channel/server and then doing it.

I tried this, but the particular server I was in had someone planted in each bot channel, all spamming tictactoe games. 
If I go into a different server and call it counts as a "prank call"
