### ISSUE TITLE
Using multiple candies

### ISSUE THREAD

**Issue by IAmMysteriousM** [DankMemer/dank-memer-suggestions-and-bugs#457]
**Is your feature request related to a problem? Please describe.**
We can only use candy one at a time. Let us use candy in a bulk like opening normies and dank boxes. It’s frustrating using them one by one.

**Describe the solution you'd like**
Saying pls use candy 20 lets us use 20 candies at once.

**Comment by melmsie** [comment]
not really important right now over other features and bugs
