### ISSUE TITLE
Pls rich bug

### ISSUE THREAD

**Issue by CheezyOyster1** [DankMemer/dank-memer-suggestions-and-bugs#458]
**Describe the bug**
A clear and concise description of what the bug is. The pls rich feature bug for my users

**To Reproduce**
1. Go to 'my server'
2. Click on 'a channel'
3. Scroll down to 'the bottom'
4. Type “pls rich” and see the problem

**Expected behavior**
It should show many emoji and prestige emojis.

**Screenshots**
![73955A31-2683-4CD3-934F-0468B1E055D1](https://user-images.githubusercontent.com/66067839/83136005-4f9a7b80-a119-11ea-9887-ac4e4548ca23.jpeg)

**Additional context**
It only happens to my other users, but me myself it won’t happens.

**Comment by melmsie** [comment]
Actually this won't be fixed, it's bc of the weird formatting of someone's username
