### ISSUE TITLE
Betting "2.01k" in blackjack

### ISSUE THREAD

**Issue by TheBronzeCat** [DankMemer/dank-memer-suggestions-and-bugs#459]
**Describe the bug**
A very specific amount of coins shortened to "k" with two decimals causes the blackjack game to not start and Dank Memer instead says "you have to to actually share a whole number, dummy. Not ur dumb feelings", which is the string from the share command that appears when you tag somebody but don't provide an amount to share.

**To Reproduce**
Type "pls blackjack 2.01k" or with whatever prefix you have in your server.

**Expected behavior**
Start a game of blackjack from betting 2.01k = 2010 coins. The regular number works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/66067647/83136799-b41ff100-a0ad-11ea-9ec1-3053e832f5c0.png)

**Additional context**
Any other amount like 2.00k or 2.02k works fine. 2.01000k or any derivative triggers the bug too.
Also:
2.011k triggers this bug
2.012k is fine
2.013k is fine
2.014k triggers this bug
2.015k triggers this bug
2.016k is fine
2.017k is fine
2.018k triggers this bug
2.019k triggers this bug

**Comment by TheBronzeCat** [comment]
Oh dear, it's even worse than I thought! I tested some other numbers with no coins in my wallet (all in the bank)
![image](https://user-images.githubusercontent.com/66067647/83139739-7376a680-a0b2-11ea-9690-c23c5881a4f4.png)

**Comment by WonderfulFairy** [comment]
Because 2.01k = 2009.9999999999998, How are you gonna blackjack that, dummy. Not your dumb feelings.

**Comment by WonderfulFairy** [comment]
Like 2.013k works because it equals 2013$ but 2.014k doesn't because equals 2013.9999999999998 and will not properly divide.

**Comment by WonderfulFairy** [comment]
well idk i got confused that's probably a calculation problem cuz 2.01*1000 should equal 2010 ._.

**Comment by melmsie** [comment]
This is a really really stupid request, sorry.

2.01k is more characters to type than 2010.
