### ISSUE TITLE
Tidepod hospital fees not coinciding with the amount lost

### ISSUE THREAD

**Issue by silae099** [DankMemer/dank-memer-suggestions-and-bugs#46]
**Describe the bug**
Hospital fees from tidepod consumption amount to 25%~ of what's in your wallet, but the bot will say you lost around 18.75% of it.
e. g. while having a wallet of 10,000 coins, to the instance
"What are you thinking???... costing you around 1875 coins", you actually lose 2500 coins instead. 

**To Reproduce**
1. Use a tidepod with some money in your wallet. 
2. If you end up to the hospital, that's what happens. 

**Expected behavior**
Lose the exact amount stated by the bot. 

**Screenshots**
https://cdn.discordapp.com/attachments/655566260666499094/690630337793097788/IMG_20200320_193604.png
https://cdn.discordapp.com/attachments/655566260666499094/690630355241402498/IMG_20200320_193728.png

**Comment by melmsie** [comment]
Should be fixed next update
