### ISSUE TITLE
Idea to make "pls hunt" better (new ideas and correct format this time)

### ISSUE THREAD

**Issue by backinboliet** [DankMemer/dank-memer-suggestions-and-bugs#465]
**Is your feature request related to a problem? Please describe.**
At this time I feel that the "pls hunt" command is lacking in terms of exploration and can be made more fun and adventuress

**Describe the solution you'd like**
To a more in depth way of hunting, make it so that whenever you hunt you have four options labeled "n" "s" "e" "w" and each are a direction north south east west which is the direction you search to hunt. In addition you add secret rare animals which can be found via a specific option of directions for example north, north, east, north, west and you arrive at a dragons lair then do the traditional type "Oh shit a dragon". In addition for each time you choose a direction to go, you have a chance to meet an animal which you have a 25% to catch. So to sum it all up you have 5 opportunities to catch an animal meaning by chance you should always get at least one and if you're lucky you can stumble upon the dragons lair by a specific path which will be a secret to the public. Also to make sure that using a path is not abused the path is randomized each time.

**Describe alternatives you've considered**
For an alternative way to do this you could change the amounts of times you have to choose a direction or maybe have the path to the dragon change every 10 minutes so someone can catch a dragon a few times in a row if they get very lucky finding the correct path. 

**Additional context**
I've also thought about making different levels of guns. Lets say with the basic 20k gun you have a 25% chance of catching an animal each time you choose a direction but maybe with a 30k gun you would have a 40% chance of catching an animal and so on as the guns get more expensive the chance increases too.

**Comment by melmsie** [comment]
I've already closed this issue, that doesn't mean to reopen a new one. This isn't happening

**Comment by backinboliet** [comment]
Sorry I thought you closed it becuase it was the wrong format
