### ISSUE TITLE
Wrong link on 'pls daily'

### ISSUE THREAD

**Issue by snowy1000** [DankMemer/dank-memer-suggestions-and-bugs#466]
**Describe the bug**
The link that takes us to loot box market is incorrect, it should be "https://dankmemer.lol/loot" instead "https://dankmemer.blimey/loot"

**To Reproduce**
1. Type `pls daily`
2. See the paragraph that starts with "You can get a lootbox that contains more coins..."
3. Click to link at the end of this parahraph, which is marked here.
![k4p0ykjrw0owa1f](https://user-images.githubusercontent.com/63533083/83201371-06185380-a14e-11ea-82cb-1cca2084beb7.png)

**Expected behavior**
That button have to take us to the correct link, but it does not.

**Screenshots**
![k4p0ykjrw0owa1f](https://user-images.githubusercontent.com/63533083/83201403-13cdd900-a14e-11ea-8d46-808843b7885f.png)
Try clicking on "Click Here", link is incorrect.

**Comment by melmsie** [comment]
thanks pirate speak

**Comment by melmsie** [comment]
fixed in next update
