### ISSUE TITLE
When doing pls gift stats the bot says listen you have two options, but one of the options is pls gift stats

### ISSUE THREAD

**Issue by DatHam** [DankMemer/dank-memer-suggestions-and-bugs#467]
**Describe the bug**

When doing pls gift stats or some other invalid query, it still says that we can do pls gift stats even though it has been moved. 

**To Reproduce**

1. Do “pls gift stats” or “pls gift <invalid query>”
2. See “ **listen you have two options:**
`pls gift <amount> <item name> <@user>`
`pls gift stats`”

**Expected behavior**

The response to the invalid query should be edited so that “pls gift stats” is removed

**Screenshots**

![94A12EEA-A8EA-463B-999A-0076CA0BF085](https://user-images.githubusercontent.com/50222314/83203080-4821a500-a10e-11ea-987e-c44cf25e6a1e.jpeg)

**Additional context**

I’m the guy who suggested to move pls gift stats to pls profile, so I guess that’s why I care lmao

**Comment by melmsie** [comment]
fixed in next update
