### ISSUE TITLE
instance of aces not performing as intended

### ISSUE THREAD

**Issue by Letoplaz** [DankMemer/dank-memer-suggestions-and-bugs#468]
![image](https://user-images.githubusercontent.com/45012086/83204934-bff1ce80-a112-11ea-86ee-a7da8cd14260.png)

An instance of an ace resulting in a bust where it should not.

run "pls blackjack or pls bj"
start with 2 aces
get any card with a value of 9 or greater
you will bust instead of the second ace taking on the value of a 1

the second ace would act as 1 and you would not bust, you would get the value of the drawn card + 2

I know instances of aces not acting properly were recently fixed, this is on of them that was missed.

**Comment by oliverysfx** [comment]
This is a known bug and the devs are still working on a fix
