### ISSUE TITLE
Embed Profile Command Suggestion

### ISSUE THREAD

**Issue by V3NOM2802** [DankMemer/dank-memer-suggestions-and-bugs#47]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Currently it is not possible to change the color that shows up in the color field of an embed while using "pls level --embed", 

It would be great if it could be made as if the same color appears both on the embed bar, and in the progress bar of the image level command that we set using "pls profile color #hex"

**Describe alternatives you've considered**
Or any other option to change the above described color field

**Additional context**
N/A

**Comment by melmsie** [comment]
Due to the way we parse colors for imgen this isn't really possibly right now, maybe in the distant future
