### ISSUE TITLE
Using phone

### ISSUE THREAD

**Issue by King-Of-Cold** [DankMemer/dank-memer-suggestions-and-bugs#471]
It's already been said, but there is a functionality of games like tic-tac-toe that prevent people from calling the police. I think this can be stopped by making it possible to just call the police (or anyone) in one command.

So instead of:
@user: pls use phone
DM: What do you want to do?
@user: p (for police)

You can do it like this:
@user: pls use phone police
DM: calling emergency services

**Comment by Letoplaz** [comment]
this is a great idea

**Comment by Letoplaz** [comment]
even with tic tac toe stalling aside this is just nice for convinence.
