### ISSUE TITLE
Pls scout

### ISSUE THREAD

**Issue by SortaMadBernie** [DankMemer/dank-memer-suggestions-and-bugs#473]
If you use pls pm and say anything else other than n,e,r,d, it will not give you anything, it will just say that it is not and option and let you try again with no cooldown. With pls scout, however, it makes it so if you say the wrong thing, it will make you wait out the cooldown.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Remove the cooldown from pls scout when you say something else other that the 3 places

**Describe alternatives you've considered** 
A clear and concise description of any alternative solutions or features you've considered. None, we are at the final frontier 

**Additional context**
Add any other context or screenshots about the feature request here. No

**Comment by melmsie** [comment]
good idea, I should fix pm

**Comment by Slick56278** [comment]
^This also happens with bet and slots, not like the cooldown for either of those commands is that bad.

**Comment by melmsie** [comment]
fixed in next update (PM gives a cooldown if you don't response or give a wrong response)

**Comment by SortaMadBernie** [comment]
Epic

**Comment by SortaMadBernie** [comment]
Wait wut NO DONT ADD COOLDOWN TO PM

**Comment by SortaMadBernie** [comment]
EVERYONE IS GONNA FUCKING HATE ME

**Comment by andrewisaboomer** [comment]
we hate you :D
