### ISSUE TITLE
Inv rob

### ISSUE THREAD

**Issue by SnappedPupil** [DankMemer/dank-memer-suggestions-and-bugs#474]
Using the command "pls invrob", you can rob a players inventory. However, less valuable items (fresh bread, chill pill, etc:) are more likely to be stolen than more valuable items (pepe trophy, bank note, etc:). Padlocks can also be added to inventories, although you have to specify if you want to apply it to your bank or your inv (after saying pls use padlock, dank will ask if you want to apply it to your inv or your bank). Checking another player's inv will also show if there's a padlock applied to it.

**Comment by SortaMadBernie** [comment]
Dude robbing inv is going to be way to op

**Comment by oliverysfx** [comment]
it can be a counter to the counter to infinite reversals though

**Comment by BewkoofBaba** [comment]
so basically the economy will never have rich robbers at all since they cant shift their money anywhere. way to go for killing game designs.

**Comment by wolf653** [comment]
imagine one of your lootboxes or pepe coins going missing cause some robbed your inventory lmao
