### ISSUE TITLE
Shop Menu for Normie Boxes

### ISSUE THREAD

**Issue by King-Of-Cold** [DankMemer/dank-memer-suggestions-and-bugs#475]
![image](https://user-images.githubusercontent.com/47277934/83296895-8aef8580-a1bf-11ea-9e67-6b98c3840707.png)
This is what the shop menu looks like for normie boxes, it says undefined. It's the same for the other boxes.

**Comment by oliverysfx** [comment]
it's because there isn't an emote for it
