### ISSUE TITLE
When we do the command pls search make `bank` a option and a chance to win a bank note.

### ISSUE THREAD

**Issue by Plaaant** [DankMemer/dank-memer-suggestions-and-bugs#477]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wolf653** [comment]
although banknotes are rare and this will make it easier finding them i would suggest keeping the typical acquirement method of partaking in events/quests and lootboxes i classify this idea as a "self benefit suggestion"
