### ISSUE TITLE
Possibly add being able to reverse negative effects?

### ISSUE THREAD

**Issue by wolf653** [DankMemer/dank-memer-suggestions-and-bugs#478]
i suppose it's rather annoying to attempt sanding someone but you forget to type y or n and instead go on to pinging someone instantly they then sand you instead leaving your vulnerable and thus not allowing you to stop their attempts of wallet cleansing. so with the upcoming update that will reimplement the reverse reversals you can reverse debuff inflictions like snowballs or sands?

**Comment by melmsie** [comment]
not really important right now over other features and bugs
