### ISSUE TITLE
Be able to sell items in bulk

### ISSUE THREAD

**Issue by N3T-X** [DankMemer/dank-memer-suggestions-and-bugs#479]
change the sell command to have this
pls sell <amount> <item>
if you want to sell one bread for example, pls sell 1 bread

**Comment by isxbel** [comment]
There is already this feature, you just put the number on the end. For example: pls sell bread 5, and that will sell 5 bread.

**Comment by N3T-X** [comment]
> There is already this feature, you just put the number on the end. For example: pls sell bread 5, and that will sell 5 bread.

i tried doing that with chill pills, and it completely ignored the other digit and sold one ( i was trying to sell 11 )

**Comment by isxbel** [comment]
When you do multiple you can’t do a plural of the item, and the code for chillpill is one word, could that be why?
