### ISSUE TITLE
Gambling is TOO OP, Everyone is 5Mil rich

### ISSUE THREAD

**Issue by febanbog7101** [DankMemer/dank-memer-suggestions-and-bugs#48]
**Is your feature request related to a problem? Please describe.**
YES, Gambling TOO OP and everyone is 5Mil wallet dumb rich.

its not that im complaining or anything but mel previously said that people get rich soo easily hence he nerfed gambling abit with the previous updates but with the new update and the limit raised alot of people are even more rich now. previously it would be like the first 2 pages filled with people that have 2mil wallet but now all 5 pages on the rich list are people with 5 mil wallet and honestly since everyone can be rich the bot itself have become boring. You limit items to 500 however anyone can be rich and easily max out 500 items other than pepec and pepes within a few days.
what ive noticed with the gambling problem is that, although theres longer lose streaks but it is less frequent however theres way bigger win streak and they are more common.

**Describe the solution you'd like**
Nerf gambling win% and streak and inflate the prices of items.

**Describe alternatives you've considered**
Theres no alternatives

**Additional context**
Cant be asked to screenshot, you can easily find how dumb rich everyone is by visiting popular dank premium servers and typing pls rich.

**Comment by melmsie** [comment]
can confirm, not everyone is rich
