### ISSUE TITLE
Robbing MEE6 bot to get infinite money.

### ISSUE THREAD

**Issue by Skeppys-Skep** [DankMemer/dank-memer-suggestions-and-bugs#481]
MEE6 the Discord bot somehow has $500 to its name and once they are robbed, one can rob them infinitely every 30 seconds for $500

Literally just have MEE6 on a server and rob him

It should say that you should be unable to rob the bot because of lack of $250

![Screenshot 2020-05-30 at 02 19 01](https://user-images.githubusercontent.com/66156301/83321215-05e68980-a21c-11ea-9bab-f4b7a9f20af7.png)

I don't really think there is anything else that needs to be said here.

**Comment by melmsie** [comment]
fixed in next update
