### ISSUE TITLE
Daily streak stuck on 3days 

### ISSUE THREAD

**Issue by galyxi** [DankMemer/dank-memer-suggestions-and-bugs#484]
My daily streak has been stuck on 3 days for at least three days. It may have been stuck longer and I didn't notice it. I'm trying to unlock my dragon quest but can't because of this issue.

![20200530_182828](https://user-images.githubusercontent.com/66187245/83340947-8a301f80-a2a3-11ea-8df1-7cbc566f21cd.jpg)
![20200530_182844](https://user-images.githubusercontent.com/66187245/83340948-8a301f80-a2a3-11ea-9f37-5444b947058b.jpg)
![20200530_182854](https://user-images.githubusercontent.com/66187245/83340949-8ac8b600-a2a3-11ea-8aca-0f7a24ac014f.jpg)

**Comment by melmsie** [comment]
miiiight be fixed after the next update, not 100% sure what causes it though
