### ISSUE TITLE
Advertising using dank memer

### ISSUE THREAD

**Issue by sluckar** [DankMemer/dank-memer-suggestions-and-bugs#487]
Hey dank memer staff I hope you are having a wonderful time.

I wanted to say this clearly,
People are using dank memer to advertise invite links.

How do they do it?

First they send an invite link
It gets blocked by another moderation bot
And then they say "pls snipe"
And that way they bypassed the bot moderation.

Also another thing they can say pls tweet (invite link here) and other related stuff 
Pleass fix this.

**Comment by melmsie** [comment]
Servers need to moderate their own shit
