### ISSUE TITLE
Issue with the events

### ISSUE THREAD

**Issue by jcatND** [DankMemer/dank-memer-suggestions-and-bugs#49]
**Is your feature request related to a problem? Please describe.**
When the events pop up, the ones where you type a phrase repeatedly until the counter hits zero, some people spam the answer so nobody else can get a chance at it. 
**Describe the solution you'd like**
I have 2 solutions, in case the first one is impossible to do (I know nothing about coding, sorry)
1) I'm not sure if this is possible, but set something like a slowdown for members so they cannot spam it, like having a message pop up saying, hey, let others have a shot at it! 
2) remove the counter so that it's just a timer like other events, 
**Describe alternatives you've considered**

**Additional context**

**Comment by melmsie** [comment]
"like a slowdown for members" so like, discord slow mode?

**Comment by jcatND** [comment]
Yes, but no. I mean a slowdown specifically for the events so that people don't spam it, and not allow anyone else a chance
