### ISSUE TITLE
Allow “on/off” for settings

### ISSUE THREAD

**Issue by mjshein** [DankMemer/dank-memer-suggestions-and-bugs#493]
**Is your feature request related to a problem? Please describe.**

It is annoying when I’m changing settings and I try to say ‘on’ or ‘off’, but it doesn’t work.

**Describe the solution you'd like**

I’d like to be able to enable and disable settings by using on and off in addition to being able to use the other options.

**Describe alternatives you've considered**

None

**Additional context**

Please consider adding this. Thanks!

![5DCA85B0-064B-4EA6-93A5-F2FE172EC79D](https://user-images.githubusercontent.com/59715207/83358536-3a546580-a342-11ea-8883-a5e59b2a23e3.jpeg)

**Comment by melmsie** [comment]
added in next update
