### ISSUE TITLE
You cannot sell Chill Pill in bulk

### ISSUE THREAD

**Issue by N3T-X** [DankMemer/dank-memer-suggestions-and-bugs#494]
I do the command, "pls sell Chill Pill 8" and it sells only one
![Screenshot 2020-05-31 at 1 24 36 PM](https://user-images.githubusercontent.com/66051491/83359791-1abd3d00-a342-11ea-928d-dd394e3c834e.png)

**Comment by Isot1** [comment]
try doing pls sell pill 8
