### ISSUE TITLE
Loaning system

### ISSUE THREAD

**Issue by shrexylicious** [DankMemer/dank-memer-suggestions-and-bugs#495]
I would like to suggest a loaning system, where users can ‘loan’ (ik there’s the share command, but loans can be the harsh way of giving money) money to other users. Said user would have to gradually, or instantly pay the money off, otherwise they’d be indebted to the person who gave them the money.
Thank you for reading!

**Comment by TheBoiPotato** [comment]
I like the sound of this a LOT.
