### ISSUE TITLE
Shop item

### ISSUE THREAD

**Issue by NoNameLolOk** [DankMemer/dank-memer-suggestions-and-bugs#497]
I want a nuclear in the Dank Memer shop that will explode when you use it and kill everyone except you and you will automatically collect their coins but the price will be 9,900,897,000 coins.

**Comment by NoNameLolOk** [comment]
Please

**Comment by TheBoiPotato** [comment]
uhhhh.... there is no way the devs are going to add that. sorry m8. way too overpowered.

**Comment by Wise2006** [comment]
Yeah, mate. Too OP.

**Comment by NoNameLolOk** [comment]
Ok

**Comment by oliverysfx** [comment]
not op, considering the price
