### ISSUE TITLE
pls rich showing bots

### ISSUE THREAD

**Issue by SqueakyBeaver** [DankMemer/dank-memer-suggestions-and-bugs#498]
**Describe the bug**
Pls rich showing bots instead of players

**To Reproduce**
1. Type pls rich
2. Will show bots with same balance as players

**Expected behavior**
Should only show humans

Bug can be shown here
![Screenshot_20200531-233136](https://user-images.githubusercontent.com/63939550/83376195-06eff600-a397-11ea-8118-9672b13cf213.jpg)

**Comment by oliverysfx** [comment]
this is not a bug, it's normal, it's just that the bots have enough money and is on the list

**Comment by inklingboi** [comment]
Is there a way to Disable Bots showing up in pls rich?
