### ISSUE TITLE
New Items: Fishing Pole/Hunting Rifle Tiers

### ISSUE THREAD

**Issue by 4vdr3** [DankMemer/dank-memer-suggestions-and-bugs#499]
**Is your feature request related to a problem? Please describe.**
I keep on coming up empty-handed when using the command "pls fish/pls hunt".

**Describe the solution you'd like**
Different qualities/tiers of the fishing/hunting gear. The higher it is, the higher the price will be and the better percentage of getting good items.

**Describe alternatives you've considered**
Nothing really.

**Additional context**

**Comment by pythagorasaur** [comment]
I think this would be great. In addition to this, I think specialized stores for hunting and fishing gear would be great, with `pls shophunt` and `pls shopfish`. 
- _For hunting:_
  - Different gun types (rifle, sniper rifle, carbine, lever-actions, shotguns); larger guns for larger prey and smaller guns for smaller prey
  - Different chamber upgrades (9mm, .308, .357, 5.56, 7.62, 50cal); larger upgrades cost more but increases the chance of getting something big
  - A suppressor to increase chance of finding anything at all
  - Binoculars to let you select your prey (but there is a chance that the one you select may kill you)

- _For fishing:_
  - Different rod grades
  - Different reels and lines
  - Different bait and lures for different fish (e.g. tuna bait but only for rare fish, but only usable on the top-grade rod and only once every 10 minutes with a 50% chance of failure)
