### ISSUE TITLE
Enabled Server Steal/Banrob

### ISSUE THREAD

**Issue by Happycutepandaa** [DankMemer/dank-memer-suggestions-and-bugs#5]
I just got robbed while I was offline in a server where I was inactive. When I joined it, Dank memer wasn't present so Robbing & Stealing was inexistent. 

**Describe the solution you'd like**
I would like you, people who code Dank memer bot to add a command where I can see a list of the servers where the rob & steal are active and what not.

Thanks for you dedication  on reading  this and have a good day

—ThatCrazyLunatic / Happycutepandaa

**Comment by melmsie** [comment]
This is not something we're interested in at this time.

**Comment by MasterGamingYT** [comment]
Also passive mode exists lol
