### ISSUE TITLE
Bank interest.

### ISSUE THREAD

**Issue by TheBoiPotato** [DankMemer/dank-memer-suggestions-and-bugs#500]
Personally, I think that when you put money in your bank, you should be given a small percentage of it added to your account over time, like real banking. And the higher the amount is in your bank, the smaller the percentage you get back is. 

EG: You have 10 coins in your bank. Every 1-3 days, you will earn 10-20 percent of it (1-2 coins).
EG2: You have 10,000 coins in your bank. Every 2-4 days, you will earn .05-.10 percent of it (5-10 coins).

I know the way I explained it was bad, so please mind it. Of course, I would want it to be a fair and equal system, so change it if you please.

**Comment by oliverysfx** [comment]
if I am not run in the economy system you are running your bank
