### ISSUE TITLE
Vote reminder

### ISSUE THREAD

**Issue by NMW03** [DankMemer/dank-memer-suggestions-and-bugs#502]
It would be nice if the bot sent us a reminder message when we had the right to vote again.

**Comment by Wise2006** [comment]
You can set a vote reminder yourself in the site. both [Top.gg](top.gg) and [Bots for Discord](botsfordiscord.com) give you an option to set a reminder when you can vote again.
[Discord Bot List](discordbotlist.com) Automatically sets a reminder for you too!

But, if you want a discord message to remind you, You can use @Carl-Bot's Command `!remind <12h or 1d> Upvote`

Hope it helped!

**Comment by Wise2006** [comment]
Can Close #502
