### ISSUE TITLE
Better requirements and improvements for the Dragon

### ISSUE THREAD

**Issue by pythagorasaur** [DankMemer/dank-memer-suggestions-and-bugs#505]
Recently, I have found that Dragons are being quite the ubiquitous pets, with the existing Dragon Quest. Nonetheless, I find that the Dragon may be overvalued at times, especially by newer users. So, here's my two cents regarding possible improvements to the Dragon & Dragon Quest:

### Part One
- _Quest requirements:_
  - from 25K in wallet to 175K (I'd say this is more than reasonable)
  - from needing 50 cookies to needing 15 deer/rare fish and 5 boars/super-rare or legendary fish
  - allows having a pet, but the Dragon eats the existing pet. Message for this: "... and there next to you... Your pet dragon, as well as the remains of your previous pet."

### Part Two
- _Possible Dragon improvements:_
  - **Special "attack" command for Dragons**; only available if dragon stats are >95%, and dragon has the maximum Attack stat (10). The attack command will use up 50% of the existing stats and only works once every three days.
  - **The Dragon can be used to bankrob**. After typing "JOIN HEIST", Dragon owners will be given a Y/N choice to use the Dragon; this gives a 75% chance that the owner will get more than 50% of the total loot, and no police will be able to stop the owner. This will be very effective for robbing million-dollar banks.
    - However, the Dragon will have a 15% chance of dying if it is used (the army is called in).
    - Only one Dragon can be used for a heist. The first person who selects the 'yes' option will use it.
    - Dragon cooldown for bankrob: 7 days.
  - The Dragon should have **buffed defense**:
    - Anyone robbing a person who owns a Dragon with >60% Energy will automatically have a 60% chance of dying.
    - The "Defense" stat can be used to buff the chance to 90%.
    - However, if the robber has a hunting rifle, he has a 2.5% chance of shooting the Dragon and getting out alive (despite not getting any coins).
  - If the Dragon owner robs or bankrobs too frequently, the Dragon's Love stat will decrease quickly.
  - **Dragon duels.** Dragon owners on a server can choose to participate in Dragon duels, which cost 5000 coins to participate in. The winner takes 10K coins and Dragon EXP. Other people in the server can spectate and bet on the winner (multipliers 1 ÷ % chance Dragons have of winning).
    - How the duels would function: Attack and defense stat %, existing Dragon experience. The more the attack+def stats/experience are, the more chance the Dragon has at winning.

### Part Three
- _Misc. Dragon improvements_
  - **Feeding the dragon requires food from hunting.** The size of the meal is determined by what you have caught with your hunting rifle, e.g. Boar, Deer, Duck, Skunk. It must be in your inventory, and before feeding the dragon, you can select which one to feed.

###### [ᴍʏ ᴏʀɪɢɪɴᴀʟ ᴘᴏsᴛ ᴏɴ ʀᴇᴅᴅɪᴛ](https://www.reddit.com/r/dankmemer/comments/gue3hi/suggestion_for_the_dragon/)

**Comment by melmsie** [comment]
Part three is the only part I want, and it's already planned to feed pet with items rather than coins
