### ISSUE TITLE
Responding bug

### ISSUE THREAD

**Issue by Furry-Like** [DankMemer/dank-memer-suggestions-and-bugs#506]
why does plsnfish works? isn't it pls fish?
![Screenshot_240](https://user-images.githubusercontent.com/66227239/83385192-9edaf780-a40a-11ea-855c-742d17ec140f.png)

**Comment by TheBoiPotato** [comment]
I think it is the fact that it will try and guess what your saying. so if you say "plsnfish", it will auto-correct it to "pls fish".

**Comment by Furry-Like** [comment]
But the thing is that it doesn't work for other commands

**Comment by TheBoiPotato** [comment]
Really? Huh. Maybe something else then.
