### ISSUE TITLE
Pet leveling and skill point bug

### ISSUE THREAD

**Issue by xXSrRyanXx** [DankMemer/dank-memer-suggestions-and-bugs#509]
**Describe the bug**
When your pet levels up, it sometimes won't receive a skill point. 

**To Reproduce**
1. Run "Pls pet (commands to level it up)(could be possible this is a bug for dragon only) 
2. When it levels up, check for it if it has any new skill points
3. See error

**Expected behavior**
Receiving a skill point so my pet could be trained. 

**Screenshots**
![Screenshot_20200601_101230_com discord](https://user-images.githubusercontent.com/66011229/83389524-a2618500-a3f0-11ea-8ccc-998fbf612078.jpg)

**Additional context**
The bug appeared as my dragon leveled up to level 2. It could be possible this bug is for dragons only.

**Comment by oliverysfx** [comment]
this looks completely normal to me, would you screenshot the number of skill points you have at level 2 or level 3?

**Comment by xXSrRyanXx** [comment]
> this looks completely normal to me, would you screenshot the number of skill points you have at level 2 or level 3?

I will take a look at it, it's been pretty long since my dragon leveld up go level three, I'll post it right here then
