### ISSUE TITLE
Prestige

### ISSUE THREAD

**Issue by Pomlk501** [DankMemer/dank-memer-suggestions-and-bugs#510]
HI I got my first prestige but my level is now so slow leveling and I don't now if this is normal. With the normal leveling I got 3 levels in 1 hour now I got 1 level in 5 days. Can you tell me if this is normal.

**Comment by IAmNotAwake** [comment]
I'm pretty sure that this is normal as the devs had recently made it more difficult to level up.

**Comment by Pomlk501** [comment]
From 1hour to 5 days is not just a little!

**Comment by Pomlk501** [comment]
Never maind
