### ISSUE TITLE
Pls removemydata

### ISSUE THREAD

**Issue by AureliaAuri** [DankMemer/dank-memer-suggestions-and-bugs#517]
**Is your feature request related to a problem? Please describe.**
so this isn't really much of a "bug", so I decided to make it a suggestion about it. Basically I do think that the pls removemydata can be abused by members considering that after you remove your data and then do a command on dank memer, you could get a free meme box each time you do it.... My friend decided to delete her data since she was migrating to a new account, she ran the pls removemydata command and did pls beg on impulse shortly after... the bot gave her a free meme box and it seemed like the bot registered her as a new user and gave her a box. We then thought that the feature could be abused by someone in future... I decided to remove the data I had from an old account of mine since I don't really want my old account to have any data on dank memer. I then found out that the command in itself could be ran every hour and that a feature that gives free meme boxes could be abused. If someone found out that it did, then people might use alts to rank up free meme boxes every hour.

**Describe the solution you'd like**
I think that one solution would be to increase the cool down to removemydata to a week or so, that way the feature could not be abused in future. 

**Describe alternatives you've considered**
Maybe the bot should keep a tag on who's a new user or who's a returning user, so that new users get a meme box and returning users wouldn't, but would get a welcome back message instead.  

I also think that people who removed their data from the bot shouldn't be able to use commands after 24 hours or something like that, considering the fact that the person wanted their data removed from the bot in the first place, why would they be using commands again just to have their data added back on to the bot?

**Additional context**
My data is removed from the bot as of now and my friend is wondering if she'd have to remove her data again just to be sure. We don't want to abuse the feature, neither do we want others doing the same.

**Comment by melmsie** [comment]
might be fixed?
