### ISSUE TITLE
Passive mode

### ISSUE THREAD

**Issue by Kylinity** [DankMemer/dank-memer-suggestions-and-bugs#519]
I accidentally did pls settings passive no even though I do not have passive on (since I want to go passive because of robbers) and I tried to put it on and it gave me the 24 hour cooldown. I can’t get to passive because of an accident

**Comment by Aoof** [comment]
This isn't a bug, this is you being irresponsible.

**Comment by CalvinCDG** [comment]
> This isn't a bug, this is you being irresponsible.

i dont think you understand what he means, he wanted to turn passive on, but he already had passive off and he typed passive off, this indeeds needs to be fixed, its not his fault, he's probably tired

**Comment by Aoof** [comment]
Oh my bad then, so the bug is that this is possible

```
pls settings passive enable
pls settings passive disable
# After 23 hours
pls settings passive disable
# timer resets from 1 hour left to 24 hours left
```

Right?

**Comment by DeskPilot01** [comment]
Same thing happened, I was gonna show how to disable it, but then, it happened.

**Comment by melmsie** [comment]
fixed next update
