### ISSUE TITLE
Pls daily resets at midnight

### ISSUE THREAD

**Issue by xEpsi** [DankMemer/dank-memer-suggestions-and-bugs#524]
**Is your feature request related to a problem? Please describe.**
Not really. It's a suggestion to improve the bot.

**Describe the solution you'd like**
Please make so pls daily resets at midnight every day, that way we are not forced to connect at the same hour everyday. We are not robots x(

**Describe alternatives you've considered**
Maybe make so you can choose your timezone.

**Additional context**
I haven't thought about anything like this

**Comment by melmsie** [comment]
no
