### ISSUE TITLE
Pls take bots off the richest leaderboard. Its annoying to look at the first page only to see 4 bots up there and more on the 2nd page

### ISSUE THREAD

**Issue by Yubbs** [DankMemer/dank-memer-suggestions-and-bugs#528]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheBoiPotato** [comment]
I completely agree with you. Either the devs make it possible to rob the bots, or make it so money is impossible to add to them.

**Comment by melmsie** [comment]
its a bug
