### ISSUE TITLE
Inventory items worth shows different values.

### ISSUE THREAD

**Issue by SoulHarsh007** [DankMemer/dank-memer-suggestions-and-bugs#53]
**Describe the bug**
The inventory items worth value is different for the embedded version of profile and image version of profile

**To Reproduce**
1. Run the command "pls profile".
2. Run the command "pls profile --embed".
3. Check the values of inventory items worth which are displayed in both the results.
4. Compare the results you find major difference between those values.

**Expected behavior**
The values of inventory items worth should be same for both results.

**Screenshots**
2 screenshots are attached.

**Additional context**
N/A
![IMG_20200323_152302](https://user-images.githubusercontent.com/57407752/77304336-4efcf780-6d1a-11ea-845e-a70d771e7265.jpg)
![IMG_20200323_152316](https://user-images.githubusercontent.com/57407752/77304383-5d4b1380-6d1a-11ea-8396-a2752e6e5f1b.jpg)

**Comment by Rhino149** [comment]
isnt that the shops total buy price for the inv on the embed

**Comment by melmsie** [comment]
Should be fixed next update
