### ISSUE TITLE
Can you make a way to not show bots in pls rich, seeing as theres no point in them being there

### ISSUE THREAD

**Issue by inklingboi** [DankMemer/dank-memer-suggestions-and-bugs#531]
**Is your feature request related to a problem? Please describe.**

Most people on my server use pls rich to show off or find people to rob. Its a lot harder when the 5 richest people on the server are bots and there's a cooldown until you can send pls rich 2

**Describe the solution you'd like**

A setting to not display bots in pls rich or just remove them from the pls rich list or the currency system entirely

**Describe alternatives you've considered**

**Additional context**

**Comment by TheBoiPotato** [comment]
I completely agree with this. The bot right now has over 3m.
