### ISSUE TITLE
pls pet has a cooldown for donators

### ISSUE THREAD

**Issue by MakingPoutine** [DankMemer/dank-memer-suggestions-and-bugs#54]
**Describe the bug**
`pls pet` commands, if typed/pasted fast enough, still yield a cooldown message if you are donator (there is not supposed to be a cooldown)

**To Reproduce**
1. Go to a Premium channel/be a donator
2. Either repeatedly copy and paste `pls pet` commands into the chat or type them as fast as you can
3. At some point there'll be a cooldown message

**Expected behavior**
There are not supposed to be any cooldown messages, some lag maybe.

**Screenshots**
![image](https://user-images.githubusercontent.com/46879337/77331530-40511900-6cf7-11ea-9121-58f63f093b89.png)

**Additional context**
If this is **not** a bug, maybe change it to a 0.50 cooldown or something for donators in the cooldown message for comprehension

**Comment by melmsie** [comment]
Not really worth the dev time for a minor rounding error
