### ISSUE TITLE
Event idea

### ISSUE THREAD

**Issue by Letoplaz** [DankMemer/dank-memer-suggestions-and-bugs#542]
My idea: You have the Paul Brothers event, but there's another shitty youtuber that's pretty relevant right now thanks to h3h3s content nuke: Keemstar! My idea is to create an event that says "Keemstar just posted another video! Quick, the first person to type the following word in chat will help stop this psycho and get a reward!" (word options: rat, dislike, gnome)

Additional context: Keemstar has been causing a stir for a long time with all the problems he causes and terrible behaviors he has, so if we can make fun of the paul brothers, keemstar should get it too. It has also gained a lot of attention from h3h3 production's recent "content nuke".

**Comment by melmsie** [comment]
doesn't seem very important
