### ISSUE TITLE
Bank dep max bugged

### ISSUE THREAD

**Issue by Helper100** [DankMemer/dank-memer-suggestions-and-bugs#543]
**Describe the bug**
Whenever you do pls dep max sometimes it will deposit more than you bank can hold and when you fo it again it will take away some of you coins

**To Reproduce**
1. Do pls dep max
2. Do pls bal
3. See error

**Expected behavior**
You shoud be able to deposit the most that you bank can hold at the time

**Screenshots**
![image](https://user-images.githubusercontent.com/66279038/83454848-b36ebe00-a411-11ea-9141-b15910c5c269.png)

![image](https://user-images.githubusercontent.com/66279038/83454903-c2557080-a411-11ea-8c38-d77b8a988614.png)

**Comment by PhantomFrenzy151** [comment]
...what's the problem?

**Comment by PhantomFrenzy151** [comment]
Your total stayed the same, and you didn't lose any money.

**Comment by LytningStryke** [comment]
I think your math is off, my friend. Let me explain:

Your current amount in your wallet is 114,740
Your current amount in your bank is 154,506, with your maximum amount being 155,125
You deposited 619 coins

114,740 - 619 = 114,121
154,506 + 619 = 155,125
155,125 = 155,125

You lost no money, and the command worked as it should, depositing the maximum amount possible from your wallet to your bank without taking or inserting more than necessary.

**Comment by Helper100** [comment]
Look.
![image](https://user-images.githubusercontent.com/66279038/83544002-19128700-a4b2-11ea-8af5-f1a60c959525.png)
The bank has allowed more money in than it should you guys are right that I didn't lose any money but the bug is still there.

**Comment by LytningStryke** [comment]
No offense, but you seriously need to study math more. Once again, let me explain:

Wallet Before - 48,478
Bank Before - 185,476
Amount Deposited - 3,943

48,478 - 3,943 = 44,535
The wallet, after the deposit, had 44,535.
185,476 + 3,943 = 189,419
The bank, after the deposit, had 189,419

The wallet had no extra money taken either. Once again, the command worked as it should, with no mathematical or visual errors. The right amount was deposited, the right amount was taken, etc. Unless my own math was off, and you are indeed correct, everything is working fine.

**Comment by Helper100** [comment]
oh yea you are right my bad the digits are off. 🤦‍♂️
