### ISSUE TITLE
I have a idea 

### ISSUE THREAD

**Issue by 1mran142** [DankMemer/dank-memer-suggestions-and-bugs#544]
I was trying to rob a bank and it said take a chill pill and I think it would be cool if chill pill decreases wait time to heist again
![Screenshot_20200601-211037](https://user-images.githubusercontent.com/62609328/83458931-539d0500-a45b-11ea-98ba-84fd24b542ea.jpg)

**Comment by Trazhy7** [comment]
and decreases pls beg, and other commands

**Comment by Helper100** [comment]
Yea I like that idea

**Comment by HongKonger1234** [comment]
Also increase price of chill to match. This will actually give some value to the chill pill.
