### ISSUE TITLE
Event Bug

### ISSUE THREAD

**Issue by TheBoiPotato** [DankMemer/dank-memer-suggestions-and-bugs#546]
This bug makes it so I'm not able to participate in the Dank Memer events if I say something RIGHT before the event appears/if I say anything that isn't related to the event when the event appears. It's getting really annoying to deal with.

![Screenshot 2020-06-01 at 4 04 27 PM](https://user-images.githubusercontent.com/65529380/83463076-d2754c00-a421-11ea-87f6-bafd80b7fa52.png)

**Comment by melmsie** [comment]
probably equally as annoying as duplicate bug reports
