### ISSUE TITLE
I won the giveaway but I still haven't got my coins 

### ISSUE THREAD

**Issue by itspsw** [DankMemer/dank-memer-suggestions-and-bugs#548]
**Describe the bug**

**To Reproduce**
1. Go to 'that channel you run the giveaways' 
2. Click on 'that channel you run the giveaways'
3. Scroll down to 'almost the last giveaway'

**Expected behavior**
You didn't even give me coins. It has been already over 24 hours. 

**Screenshots**

**Additional context**
I won a 500k coins giveaway and you can check that I really won it but I still haven't got any coins.

**Comment by melmsie** [comment]
I can't check anything without your ID

**Comment by itspsw** [comment]
itspsw#4880

**Comment by melmsie** [comment]
You did get your giveaway, and it looks like you then had it stolen from you, and then you cleared your notifs
