### ISSUE TITLE
Small Visual Bug with Pls slots

### ISSUE THREAD

**Issue by NotScappy** [DankMemer/dank-memer-suggestions-and-bugs#549]
**Describe the bug**

The message saying "You now have xx coins." displayed the wrong number.

**Expected behavior**

The message should've displayed my current balance, not my balance before I won the money

**Screenshots**
![Screen Shot 2020-06-01 at 8 57 53 PM](https://user-images.githubusercontent.com/65908192/83468571-234d6a80-a44b-11ea-88e7-5e30a5f3435f.png)

**Comment by melmsie** [comment]
Is this still happening?
