### ISSUE TITLE
Admin Command To Give Your-Self Free Coins

### ISSUE THREAD

**Issue by happybirthday343** [DankMemer/dank-memer-suggestions-and-bugs#55]
---
name: Discord: Borky#0001
about: I would like an admin command so you can add as many coins as you want
title: 'Admin Command For Free Coins'
labels: enhancement
---
**Describe the solution you'd like**
A clear and concise description of what you want to happen. I want admin command for free coins

**Additional context**
Add any other context or screenshots about the feature request here. A command like >add (coin amount) @(discord user)

**Comment by melmsie** [comment]
no

**Comment by RandomTurtleBoi** [comment]
uh
