### ISSUE TITLE
Pls Suggest is Broken

### ISSUE THREAD

**Issue by PhantomFrenzy151** [DankMemer/dank-memer-suggestions-and-bugs#551]
**Describe the bug**
When you use pls suggest, the link brings you to an error.

**To Reproduce**

1. Pls Suggest
2.Click on Link

**Expected behavior**

I expected to go to the Bug Report page.
![Screenshot (28)](https://user-images.githubusercontent.com/65619554/83470905-4f6bea00-a451-11ea-9ff7-8bdb3b771a31.png)

**Screenshots**

**Additional context**

**Comment by asianmemeboi** [comment]
Lol didnt you do pls suggest to even get on this page? plus i just used it like 20 seconds ago
![image](https://user-images.githubusercontent.com/58711340/83470977-762a2080-a451-11ea-8308-b59ac10d23da.png)
works for me

**Comment by oliverysfx** [comment]
Not for others, the and part in the link in pls suggest is n', which is wrong, should be and

**Comment by PhantomFrenzy151** [comment]
@asianmemeboi It didn't work, It brought me to an error page. Furthermore, I got here because I searched for the page because I know how to work as search bar.

**Comment by asianmemeboi** [comment]
![image](https://user-images.githubusercontent.com/58711340/83666817-8b12cb00-a59b-11ea-9a42-fde61e9a3580.png)

**Comment by PhantomFrenzy151** [comment]
@asianmemeboi nope still a problem. The link is still https://github.com/DankMemer/dank-memer-suggestions-n%27-bugs
