### ISSUE TITLE
Pls post meme failure nerf

### ISSUE THREAD

**Issue by asianmemeboi** [DankMemer/dank-memer-suggestions-and-bugs#552]
It seems as if my laptop has a high chance of breaking now for pls post meme. My laptop just broke three times the last four times i did pls post meme.

1. Go to Dank Memer bot server
2. Do `pls post meme`
3. See the chances of it breaking

I expect the laptop to break quite often.

![image](https://user-images.githubusercontent.com/58711340/83470831-277c8680-a451-11ea-9a18-346981e46205.png)
![image](https://user-images.githubusercontent.com/58711340/83470868-3bc08380-a451-11ea-8026-9ef5133525ef.png)
Both from today(6/1/2020)

**Comment by LytningStryke** [comment]
The chances of your laptop breaking are pretty low, but we don't know the exact chances. You must have gotten very unlucky.

**Comment by asianmemeboi** [comment]
> The chances of your laptop breaking are pretty low, but we don't know the exact chances. You must have gotten very unlucky.

Hmmmm.... You're probably right but my laptops usually last a week and I would expect it to break at least in a day or so. But you're probably right.

**Comment by melmsie** [comment]
The chances to break a laptop haven't been changed in months, nor are they getting changed either direction anytime soon
