### ISSUE TITLE
BlackJack Aces are bugged

### ISSUE THREAD

**Issue by PhantomFrenzy151** [DankMemer/dank-memer-suggestions-and-bugs#553]
**Describe the bug**

THIS IS NOT MY SCREENSHOT, but I saw this was posted in the Support channel of the dank memer discord by someone, and was told by the mod that the behavior was "normal" and "it's just a game", which was clearly not (for the first one). He/she was ignored and not directed to the bug report page.

When the player gets two aces, it's a 12, even if you bust.
When the bot gets two acres, it's 2.

**To Reproduce**

Blackjack until you see two aces.

**Expected behavior**

If you bust, with an ace that is defaulted to 11, it should become 1.

**Screenshots**

![DankMSomeoneElseSS1](https://user-images.githubusercontent.com/65619554/83471308-63fcb200-a452-11ea-9aeb-e1a3936b002a.jpg)
![DankMSomeoneElseSS](https://user-images.githubusercontent.com/65619554/83471315-66f7a280-a452-11ea-882d-ecce6bf75700.jpg)

**Additional context**

I REPEAT, these are not my screenshots, but someone who was ignored in the Support Channel's.

**Comment by asianmemeboi** [comment]
Yes blackjack is kinda rigged for the bot ngl and also, them edits keep tripping me up

**Comment by LytningStryke** [comment]
I personally agree with this. As of now, there seems to be a little bit of RNG with the aces.

**Comment by oliverysfx** [comment]
Not rng, this is a bug that the devs are working on to fix, it has been reported a million times

**Comment by Neptunus-Equester** [comment]
this isnt a bug, in most forms of blackjack (you can even look this up) only the first ace can count as 1 or 11

**Comment by oliverysfx** [comment]
most things I find online doesn't work like that, all aces are choosable, and whichever is more advantageous to the player is used

**Comment by melmsie** [comment]
> Yes blackjack is kinda rigged for the bot ngl and also, them edits keep tripping me up

That's not true at all, there's more than a single bug that cause the dealer to not hit past a low number, and suffers from the same bug. It's not "rigged" and assertions otherwise are idiotic
