### ISSUE TITLE
Blackjack rules 

### ISSUE THREAD

**Issue by RealKingAwesome** [DankMemer/dank-memer-suggestions-and-bugs#556]
In blackjack the dealer is always supposed to hit until they get 17 but here they didn’t 
![FDBDE6DF-FB0D-4755-ADC2-58EBFCA80583](https://user-images.githubusercontent.com/66052046/83483529-da101180-a470-11ea-864b-43637fd6945f.png) and even though it helped me win here I think it should be fixed

**Comment by oliverysfx** [comment]
The dealer can't hit after 4 cards, which explains this

**Comment by RealKingAwesome** [comment]
What do you mean the dealer can’t hit after 4 cards? I know how to play blackjack and that’s not a rule
