### ISSUE TITLE
please buff prestige

### ISSUE THREAD

**Issue by danksup** [DankMemer/dank-memer-suggestions-and-bugs#557]
can you please buff prestige? it isn't as worth it as the requirement to get prestige. i know you will get rare pepe from it, but you can just buy rare pepe if you could. my suggestion is make a role for prestige. it doesn't have to do something, but it sure will make someone know if you're prestige or not. the more the prestige level will give you different color. please make gaining level much faster with prestige.

**Comment by oliverysfx** [comment]
There's already a custom badge

**Comment by melmsie** [comment]
everything you suggested exists within the bot
