### ISSUE TITLE
more LGBTQ+ Commands

### ISSUE THREAD

**Issue by GerritTime** [DankMemer/dank-memer-suggestions-and-bugs#558]
**Is your feature request related to a problem? Please describe.**
im not frustrated, and just asking for more LGBTQ+ Commands

**Describe the solution you'd like**
it's more Commands like "pls gay", like "pls bisexual" it gives you the Bisexual Flag instead of the Gay Flag. maybe even more Flags

**Comment by melmsie** [comment]
I'll give you the same answer as people asking for a flag for each country:

We support the most common ones, we don't have the capacity to add something for everyone
