### ISSUE TITLE
Minigame Stats 

### ISSUE THREAD

**Issue by Ledgeview** [DankMemer/dank-memer-suggestions-and-bugs#56]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
A minigame statistic, similar to pls gamble  --stats but with a similar twist to the trivia statistics . Minigames pop up randomly,  but it'd be wonderful to see a statistic of minigames. It could show a global leaderboard, server leaderboard, and/or assign points dependent on the complexity level.
**Describe alternatives you've considered**
There isn't necessarily an alternative, but trivia is slightly similar. 
**Additional context**
It could have several commands. Pls minigames, pls minigames --stats, pls minigamesserver, pls minigamesglobal This would mainly show your success in minigames, but it wouldn't display answers or specific minigame details. It could have different point totals- 9 for rare, 1 for common, etc

**Comment by lululemonspamiess** [comment]
cool!
