### ISSUE TITLE
inventory robbing

### ISSUE THREAD

**Issue by rforzachamp821** [DankMemer/dank-memer-suggestions-and-bugs#560]
inventory robbing on Dank Memer is a good option. Suppose the person stole from your coins and spent it all before you could use your reversal card. To get the money back, there could be a way to rob another person's inventory. you would need at least 2 things in your inventory that is worth more than 100 coins (that includes fish, ducks, etc) so you can rob another person's inventory. Similar to the padlock, you could also make a locker or vault as a protection. The locker/vault should be similar cost to the padlock. Hope you agree!

**Comment by rforzachamp821** [comment]
yup pls do it!

**Comment by HongKonger1234** [comment]
Heck no people can steal really expensive things like pepe trophies and medals. Mel put this to a vote in Dank Memer Official a week back and no won out by 3712:2603

**Comment by rforzachamp821** [comment]
ok then...
