### ISSUE TITLE
Disable the disabling of ping command

### ISSUE THREAD

**Issue by Akash9409** [DankMemer/dank-memer-suggestions-and-bugs#563]
**Is your feature request related to a problem? Please describe.**
Admins disable the ping command by the usage of pls disable ping. And I feel this command should not be disabled because this is the command we use to check whether the bot is active or not. 

**Describe the solution you'd like**
So my solution is please make sure that "pls ping" command cannot be disabled by anyone. 

**Describe alternatives you've considered**

**Additional context**
If people spam the usage of pls ping (hypothetically if someone says pls ping is spammed, then increase its cooldown but do not make the command to be disabled by admins. Its the very first command the developers put into the bots and admins disable the "pls ping" which makes me annoyed because I cant check whether the bot is working or not.) I hope you understand thanks!

**Comment by melmsie** [comment]
this is idiotic
