### ISSUE TITLE
BJ, see opponents card ammount

### ISSUE THREAD

**Issue by EbsterG** [DankMemer/dank-memer-suggestions-and-bugs#564]
It's kind of annoying how in BJ, if the enemy is representing a 2 and a ?,  I would go for a stand because i have a 14, but I lost because the enemy actually had 4 cards.

I feel like it would be better if you could see how many cards the enemy has, so you can make more tactical moves. The cards could be represented by (for example) 3, ?, ?, ?.

**Comment by Downergrading** [comment]
The enemy is allowed to take more cards once you stand. That's how blackjack works.
