### ISSUE TITLE
Languages option

### ISSUE THREAD

**Issue by Fresaazul** [DankMemer/dank-memer-suggestions-and-bugs#565]
**Is your feature request related to a problem? Please describe.**
I'm spanish so I mostly fail in pls work unscramble and probably many people do too.

**Describe the solution you'd like**
Adding language option in pls settings and making it to change all bot language for you, even unscramble in pls work (Not in events because they're global)

**Describe alternatives you've considered**

**Additional context**

**Comment by oliverysfx** [comment]
dank memer only works in english and there's no translation planned any time sooner, sorry to bring that bad news to you

**Comment by melmsie** [comment]
as mentioned about a month ago, translations will be hopefully coming before the end of the year
