### ISSUE TITLE
Daily Streak not appearing

### ISSUE THREAD

**Issue by Downergrading** [DankMemer/dank-memer-suggestions-and-bugs#566]
I've been trying to get the dragon pet and I have been claiming dailies for 4 days and I've only realized now that it hasn't made my streak higher.
Not sure if this is a visual glitch or not, but this should be fixed.
**Timezone is GMT +2 for reference**
![image](https://user-images.githubusercontent.com/66307652/83513035-cbaa1000-a4d9-11ea-8359-beb19ac359c6.png)
![image](https://user-images.githubusercontent.com/66307652/83513048-d49ae180-a4d9-11ea-96c8-c6b6d53ec38a.png)
![image](https://user-images.githubusercontent.com/66307652/83513065-dbc1ef80-a4d9-11ea-913e-bf3d0ccdd4ec.png)
![image](https://user-images.githubusercontent.com/66307652/83513081-e2e8fd80-a4d9-11ea-9f42-cdf1ac437f13.png)
![image](https://user-images.githubusercontent.com/66307652/83513144-01e78f80-a4da-11ea-809c-fe0da717c48f.png)

**Comment by melmsie** [comment]
need your ID
