### ISSUE TITLE
"pls settings passive" Bug

### ISSUE THREAD

**Issue by Veinify** [DankMemer/dank-memer-suggestions-and-bugs#568]
If you turned on passive, you can turned it off right after without waiting 24 hours. And the bot responded with 2 messages "You have to wait 24 hours before turning passive mode back on." and "Setting Passive successfully changed to red Disabled"

**Comment by oliverysfx** [comment]
it's intended, the 24h cooldown is only for people who turns it off

**Comment by Veinify** [comment]
> it's intended, the 24h cooldown is only for people who turns it off

It is? Well i think it's still a bug because the bot send 2 messages and one of them are not supposed to...
![20200602_191231](https://user-images.githubusercontent.com/59754235/83519235-cd89c880-a505-11ea-9916-056c0ff6d2e7.jpg)

**Comment by PhantomFrenzy151** [comment]
No, that's normal. It's to discourage people turning off passive just to run some commands, then turning it back on.
