### ISSUE TITLE
The % multi changes between gambling and slots

### ISSUE THREAD

**Issue by DankPlayer** [DankMemer/dank-memer-suggestions-and-bugs#570]
Gamble gave me a 59% multi
Slots gave me a 57% multi
Pls multi gave me a 59% multi

**To Reproduce**
(I don’t understand this step sorry)

I expected a consistent multi between gamble slots and pls multi.

I had a tide and a fidget spinner throughout the demo, ik it didnt mess up the results because i did gamble first then i did slots(the one with the lower multi) then i did pls multi and it was the same multi as gamble.

**Comment by DankPlayer** [comment]
![80E4C9F8-40CB-417C-B398-904C20CC6AB3](https://user-images.githubusercontent.com/66322592/83541866-d2c42480-a4bf-11ea-986e-99b20eec6ec9.png)
![3CC2258B-7305-4235-9824-95E39811342C](https://user-images.githubusercontent.com/66322592/83541869-d3f55180-a4bf-11ea-9666-61ec12275c81.png)
![2A652A67-E1F9-4516-822C-4BCEB3098AF6](https://user-images.githubusercontent.com/66322592/83541872-d48de800-a4bf-11ea-8415-6fc116b9fbc2.png)

**Comment by melmsie** [comment]
is it different 100% of the time?

**Comment by DankPlayer** [comment]
I originally thought it was slots has the higher multi Because i remember
my friend asking me about it and i said its probably just because slots has
a lower win rate, so its the opposite of the picture i sent, ill try to get
some solid data but i have to sleep now, gn!

**Comment by DankPlayer** [comment]
Yeah i figured as much, its once again slots has the higher multi.

**Comment by DankPlayer** [comment]
Oh mb gamble didnt have the higher multi, meant to say slots did.. i just
confused myself but yes, from what ive seen slots has had a higher multi
100% of the time.
