### ISSUE TITLE
pls battle and pls battleshop currency commands

### ISSUE THREAD

**Issue by OxoTheRandomGuy** [DankMemer/dank-memer-suggestions-and-bugs#571]
### I would like to think a new pls fight or as i call it pls battle.
it would be the time to change the pls fight and turn it into a currency command as of it right now it's bland and no winning prizes and also there's not that much multiplaying currency commands. and also renaming it to pls battle as it would make sense later on. 

As for the execution it would be like this:
pls battle <@user> <bet> / <item>
the prize will determine on the prestige and level if left blank or the user can include a prize within it and then the challenged user can either choose to accept or decine.

As for the function, is could be like this:
![dankmemer suggestion](https://user-images.githubusercontent.com/66323890/83547774-4b18fd00-a535-11ea-87aa-52c2f0fd7474.PNG)
there will be 3 (more if you want) options.
**Fight** will let the user fight with the current item they have but if they have nothing or use it in the first move, they will use their fist.

**Item** will let you use an item in your inventory such as a Rifle or Box of Sand. But not all items are usable like a Rare Pepe, you would just throw it and do a certain amount of damage like 10 or 15 and so.

**Run** pretty much self explanitory, you run away from the battle but you will drop some coins from running, either 1-10 Coins or 5-15 Coins.

also it would keep the health bar from the original but instead of 100, make it 200 or 500 or if not enough 1000 Health Points

There would be also a timer like 20 seconds to respond but if the battle takes like 100 or more turns it will end immediately

I would also include pets but... 
**PETA** just **PETA**

Next is pls battleshop which is exclusive for pls battle, it simply contain weapons, potions, and other stuff enhancing the battle and stuff but i could think of some things for it like:
Sword, Sheilds, scythe, Hammer and Sickle <--(Recomended if is planned to be added), Potion of healing. potion of BUFF and more.

For some nerfs for all of it:

- Passive Users cannot use pls battle

- Max amount of healing turns is 3 if anymore than that will cancel the turn

- It will have a 30 Minute cooldown to avoid Abuse of it

and then some things i want for it to be included:

- When someone trys to challenge a passive user its will say: Hey that guy is a ghost, you can't attack ghosts

- When someone challenges me (OxoTheRandomGuy#8161) it will say **ARE YOU WILLING TO CHALLENGE THE CREATOR OF THIS COMMAND** *Yes* or *No* i would really love it

and that's it on what i can think about it, i really hope this gets to be as a command as i think it would be amazing and if it gets to be a command thank you very much as it can make my day. Thank you.

**Comment by PhantomFrenzy151** [comment]
Lol imagine if Dank Memer literally just became a battle simulator.

**Comment by OxoTheRandomGuy** [comment]
> Lol imagine if Dank Memer literally just became a battle simulator.

Totally Dank Battle Bot would be the name lol

**Comment by melmsie** [comment]
This is something that sounds like a good idea for a totally separate bot
