### ISSUE TITLE
Add a disabled command response?

### ISSUE THREAD

**Issue by MrMudkip** [DankMemer/dank-memer-suggestions-and-bugs#573]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I [...]
I try to use some disabled comamnds, but there is no response, unlike what other bots do.

**Describe the solution you'd like**
Add a command disabled response (like "This command is disable you idiot" or anything like that?

**Describe alternatives you've considered**

**Additional context**

**Comment by melmsie** [comment]
No
