### ISSUE TITLE
Blackjack splitting and doubling

### ISSUE THREAD

**Issue by RealKingAwesome** [DankMemer/dank-memer-suggestions-and-bugs#574]
In blackjack if your first 2 cards is a pair you can split it and it’s basically like your playing 2 separate hands (you have to put an equal bet first) also on your first 2 cards you can double down (double your bet and receive ONE card) I would like to see this added to Dank Memer blackjack

**Comment by melmsie** [comment]
We're not interested in doing this at this time.
