### ISSUE TITLE
Link command not able to link?

### ISSUE THREAD

**Issue by Xynnix** [DankMemer/dank-memer-suggestions-and-bugs#576]
**Describe the bug**
Patreon isnt linking properly. I did link my Discord account with.patreon and ran `pls link`, and even disabled Pirate speak as i knew it could cause issues sometimes.

**To Reproduce**
1. Link patreon account as normal...
2. Go to a text channel and send `pls link`
3. Wait until Dank Memer replies.

**Expected Behaiviour**
Supposed to reply with a successfully linked response and add the perks with the $(amount) patron tier.

**Screenshots**
![Failed](https://cdn.discordapp.com/attachments/715389631989940266/717469647837986867/Screenshot_20200602-155617.jpg)
![Linked](https://cdn.discordapp.com/attachments/715389631989940266/717469784144347276/Screenshot_20200602-160820.jpg)
![Discord](https://cdn.discordapp.com/attachments/715389631989940266/717471505356947477/Screenshot_20200602-161510.jpg)

**Comment by melmsie** [comment]
This is something for mods to support with, this repo is for non-urgent bugs
