### ISSUE TITLE
Sale cycle

### ISSUE THREAD

**Issue by CowboyKarma** [DankMemer/dank-memer-suggestions-and-bugs#577]
**Is your feature request related to a problem? Please describe.**
I have spare coins that I want to spend on before I prestige. However, the items barely appear on sale. 

**Describe the solution you'd like**
A sale cycle where there is a set timeline of items going on sale. For example, day 1 of Januaray can be padlock. Day 2 would be life-saver, etc. Feb 1 will then be padlock and Feb 2 will be life-saver. So on and so forth

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by melmsie** [comment]
This is more complicated than we care to do
