### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by ARiceFarmer** [DankMemer/dank-memer-suggestions-and-bugs#58]
**Describe the bug**
Dank Memer does no reward me whenever I participate in any events, (drink, provolone, attack the boss, etc.). It states that there were no winners (if no one else participates) or states the rewards given to everyone else except for me.

**To Reproduce**
To the best of my knowledge, there is no way to reproduce the bug. 

**Expected behavior**
Dank Memer should state what I got from participating in the event and give me the reward.

**Screenshots**
2 screenshot links below.
![image](https://user-images.githubusercontent.com/62629170/77491380-d752c980-6dfa-11ea-8b16-e1af39a844c6.png)
![image](https://user-images.githubusercontent.com/62629170/77491416-ee91b700-6dfa-11ea-9106-b8a3669eb2a8.png)

**Additional context**
N/A

**Comment by MooMooMooMooMooMooMoo2** [comment]
Yes I have found this error too.

**Comment by Hariz420** [comment]
Same case as me

**Comment by The-blackout** [comment]
Same

**Comment by aidenislit** [comment]
same for me

**Comment by Letoplaz** [comment]
same.

**Comment by Goofierknot5537** [comment]
Happens to me sometimes too, but the only times this has happened to me is when I used a command right after the event started, (ex: event start, I do a pls command without realizing there’s an event, try to enter event, failure).

**Comment by Wise2006** [comment]
This is happening to a lot of people.

**Comment by REEEYEET** [comment]
also same

**Comment by melmsie** [comment]
events will be rewritten later this summer
