### ISSUE TITLE
Make it so you get a message if someone tries to rob/heist you in a server and you're passive

### ISSUE THREAD

**Issue by SergeTFM** [DankMemer/dank-memer-suggestions-and-bugs#581]
**Is your feature request related to a problem? Please describe.**
Yeah I guess because me, as a person with a lot of money in the bank and in the wallet, I want to avoid robbing servers [leave robbing servers] and if someone tries to rob me while im passive i would like to know where its from and from who so i can leave that server.

**Describe the solution you'd like**
I want the bot to DM you whenever someone tries to rob you while you're passive and that it will show the server and the person.

**Describe alternatives you've considered**
None, actually.

**Additional context**
Just some example I made: 
![image](https://user-images.githubusercontent.com/50763771/83598161-b2ed3900-a571-11ea-9909-d744572efcd5.png)

**Comment by melmsie** [comment]
I don't think this is needed, and would put pointless strain on our servers
