### ISSUE TITLE
“Pls daily” bug

### ISSUE THREAD

**Issue by epicjonny312** [DankMemer/dank-memer-suggestions-and-bugs#582]
When i do ‘pls daily’ a bug occurs. Every time i do ‘pls daily’ when the count down has finished, it doesn’t give me a daily streak.
I have seen other people’s daily streaks and they all seem to be working. Is it just my device?
My daily streak was supposed to be 2 but it doesn’t change.
![BA3A9F71-524E-4C03-B627-ABA1AEFDC027](https://user-images.githubusercontent.com/66352429/83603931-9f18f580-a5b8-11ea-9b15-bae573f13cb7.jpeg)
Pls fix this. If you can’t, I’ll just prestige and see what happens.

**Comment by epicjonny312** [comment]
It’s working now, it’s just my device. Needed restart.

**Comment by craisinfran** [comment]
hi, i am having the same problem with the daily streaks not appearing. my id is 488142901197668401

**Comment by PizzaHeart** [comment]
same with me, discord id: 442447291836661773

**Comment by KennywasTaken** [comment]
Been having this prob for awhile id is 400855350045048833
