### ISSUE TITLE
Ability to get a blackjack when you first start the game.

### ISSUE THREAD

**Issue by MiloMurphyIsHere** [DankMemer/dank-memer-suggestions-and-bugs#585]
**Is your feature request related to a problem? Please describe.**
Well, not really but irl there is a small chance you can actually get either an ace and a king/queen/jack or a 10 of spades or a 10 of diamonds or a 10 of clubs or a 10 of hearts at the start of blackjack game.

So, you get a blackjack at the start of the game.
**Describe the solution you'd like**
Add a chance to get a blackjack at the start of the game.

**Describe alternatives you've considered**
None.

**Additional context**
Wish it would be added. Luck in blackjack.

**Comment by PhantomFrenzy151** [comment]
This already can happen.

**Comment by Sadrazoozoo8** [comment]
this can already happen!
