### ISSUE TITLE
Pls quest bug

### ISSUE THREAD

**Issue by Mathias2222** [DankMemer/dank-memer-suggestions-and-bugs#586]
**Describe the bug**

When I do any form of pls quest command it says "oopsie poopsie
There was a problem with the quests command, if this happens for more than a few hours please join our server to report this error" This bug has been occuring for more than a month (since I returned to dank memer.)

**To Reproduce**

**Expected behavior**
Expected to show my current quest/list of quests

**Screenshots**
![image](https://user-images.githubusercontent.com/66368576/83637791-7426a580-a5a8-11ea-9772-4e825b6210ce.png)
![image](https://user-images.githubusercontent.com/66368576/83637832-8274c180-a5a8-11ea-8fd1-b9f784a33a71.png)

**Additional context**

**Comment by melmsie** [comment]
I need your Discord ID

**Comment by Mathias2222** [comment]
Hey, my ID is 400398231260889098
Thanks for helping out!

**Comment by melmsie** [comment]
working on a fix, should be deployed soon
