### ISSUE TITLE
Using a user's name is giving warning and probable innocent ban

### ISSUE THREAD

**Issue by BewkoofBaba** [DankMemer/dank-memer-suggestions-and-bugs#587]
**Describe the bug**
A user named "Duckys" shows up in list. We tried to rob that user and got warning from bot.
"pls rob duckys" >> 
![image](https://user-images.githubusercontent.com/64680785/83659850-b4eee080-a5e1-11ea-824b-b709d679fd55.png)
 BOT
 Memer (pls): This type of language breaks our TOS. Continued usage within commands will result in a permanent ban.

**To Reproduce**
rob a user with some banned word in the users name.

**Expected behavior**
these words r not known in all parts of the world and also the user trying to rob din mean to use and bad word.. using any command on this user results in warnings - which is wrong.
instead of banning, bot should start ignoring commands fired by the user with such a name with mentioning what word is not allowed. Eg; Your name contains "kys" which is not allowed by bot so please change it and try again.

**Screenshots**
![image](https://user-images.githubusercontent.com/64680785/83660229-334b8280-a5e2-11ea-99f3-711e84559b43.png)

**Additional context**
none

**Comment by melmsie** [comment]
this has been fixed
