### ISSUE TITLE
pirate speech

### ISSUE THREAD

**Issue by DankMemerFan** [DankMemer/dank-memer-suggestions-and-bugs#588]
**Describe the bug**
Pirate speech changes words in links as well for example:
github.com/DankMemer/dank-memer-suggestions-and-bugs
turns into
github.com/DankMemer/dank-memer-suggestions-n'-bugs
which makes certain links unusable 

**To Reproduce**
turn on pirate speech
say pls suggest (or any other command that shows a link with "and" in it) 

**Expected behavior**
for pirate speech to ignore links

**Comment by Sadrazoozoo8** [comment]
lol that's funny xD.
