### ISSUE TITLE
Dank Memer Phone Message Abuse

### ISSUE THREAD

**Issue by TrainerEevee615** [DankMemer/dank-memer-suggestions-and-bugs#59]
There are always times we want to block somebody. Maybe you don’t want to let them dm you or whatever.
But Dank Memer can bypass it. People can just use phone to dm you, maybe even spam/annoy you.
So please add a feature where we can disable somebody using dank memers function to dm us(like blocking), or add a functionality to our phones called do not disturb mode, where people cant dm you with this on.

**Comment by melmsie** [comment]
We'll take your idea into consideration
