### ISSUE TITLE
prestige hunting rifle

### ISSUE THREAD

**Issue by Sadrazoozoo8** [DankMemer/dank-memer-suggestions-and-bugs#590]
When prestiging, it dosen't say that you also start with a hunting rifle Along with everything else (like fishing pole, laptop, etc.) but you do. please fix! :)

**Comment by Downergrading** [comment]
This is an enhancement request rather than a bug,

**Comment by oliverysfx** [comment]
it is a bug, not an enhancement request, because the reply is wrong

**Comment by Sadrazoozoo8** [comment]
how is this an enhancement request lol

**Comment by oliverysfx** [comment]
idk, we need to ask @Downergrading

**Comment by melmsie** [comment]
fixed in next update
