### ISSUE TITLE
New Item: The axe

### ISSUE THREAD

**Issue by totallydankmemer** [DankMemer/dank-memer-suggestions-and-bugs#592]
Back again for a new suggestion, a new item.

The axe

Normie cooldown - 1m 10

Donor cooldown - 45 seconds

Axe price - 7.5k - 10k
Axe can be sold for: 3500 - 4500 coins

You use it to go to the forest and cut down trees and you get logs for it, the amount of logs you get is 1 - 5 and you can either buy them for 450 - 750 coins or sell them for 200 - 300 coins each (I dont know how much it should be so I'll let you decide if you do plan on adding it) 

Like fishing, there are some times you need to type a phrase within a certain amount of time otherwise the tool will break. In the case of cutting trees, the axe sometimes gets stuck in the tree. You need to type a phrase within 10 seconds or your axe gets completely stuck, you rag it out the tree too hard and it snaps. Or if you're really unlucky, you get a splinter in your hand and cut your hand, you get a weird infection from the wood and die. The chances of dying are 5 - 10 %

Potential phrases:
"Oh crap it got stuck again"
"Get out the tree please"
"chop chop chop"
"Should've brought my other axe"
"Time to buy another axe then"

If you type the phrase within the 10 seconds you can either get a few extra logs, or get some free items, such as:

Padlocks
Another axe
Another item suggestion: Apple - Eat it to gain a temporary XP boost ( 1 - 10%) for 15- 20 minutes.
Normie boxes
Pink phallics
Skunk,Duck,Deer,Rabbit

Thought of this when I went hunting and thought it'd be a pretty cool addition

**Comment by aidenislit** [comment]
smart but there will be too many item grinding commands. I would say no if i were a dev

**Comment by melmsie** [comment]
not a bad idea, but not really the direction we're going right now
