### ISSUE TITLE
pls inv steal 

### ISSUE THREAD

**Issue by aidenislit** [DankMemer/dank-memer-suggestions-and-bugs#593]
Basically a command that allows you to steal items from other people's inventory. 
Command description:
Can't steal rare Pepe, pepecoin, pepemedal, or pepetrophy. It cost 2.5k coins to try to steal the item. The success rate is 30%. Can't steal from users in passive mode. The most of an item you can steal is 10. Cooldown is 3 minutes and if victim has a padlock you would fail.

Just a thing I thought of in quarantine.

**Comment by xXSrRyanXx** [comment]
The inventory is most likely our last place where (luckily) nothing can be robbed, I wish for it to stay like this, if this was added, I seriously would havd to turn on passive mode but that's for ******* only. Please don't

**Comment by oliverysfx** [comment]
dup of #560
