### ISSUE TITLE
pls meme Upgrade

### ISSUE THREAD

**Issue by King-Of-Cold** [DankMemer/dank-memer-suggestions-and-bugs#594]
Not actually a currency command request, but a meme one.

The pls meme command has a very likely chance to give the same meme multiple times. So I thought it would be a good idea that if you were to react to it, then it would remember that and if you use pls meme again then it won't give you memes it already reacted to.

In the case that this causes any problems, you can always clear what memes you reacted to every 6 hours or so, if that helps.

**Comment by King-Of-Cold** [comment]
You can also use alternative ways to make it not repeat memes, but this is one that I thought would be the simplest

**Comment by oliverysfx** [comment]
there are only no more than 20 memes that the bot chooses from, so repeats are expected

**Comment by melmsie** [comment]
the meme commands grabs the top 100 memes from reddit daily, if you see over 100 come back in 24h for more.
