### ISSUE TITLE
Pls archive command

### ISSUE THREAD

**Issue by MyNameIsNotDerek** [DankMemer/dank-memer-suggestions-and-bugs#595]
So recently I feel like I've been slacking on my life because I'm too addicted to dank. My grades are dropping (though school is basically over) and I can't seem to get anything done. I thought of this idea called "pls archive", where basically it preserves your dank data and you can check you inv and pet, and you can fight and things like that, but you can't do commands such as beg, pm, rob, or any money making commands. The thing is, I want to keep my dank data because I worked hard to get where I am and I want to still flex on my friends, but I also want to stop playing and focus on achieving something in life besides being good at dank. It would be in pls settings, but you won't be able to turn it off once you do it.

**Comment by melmsie** [comment]
so you want passive mode that lasts longer than 14 days?

**Comment by oliverysfx** [comment]
I think what he means is a permanent passive mode that you can't turn off

**Comment by MyNameIsNotDerek** [comment]
Yes, but you also can't do commands that can make you money or get you more items like fish and hunt, and you can't prestige, but you can do other commands like pls fight and pls inv, maybe pls pet. It's to help people who are way too addicted and don't have the will power to stop, and don't want to feel like they wasted their time on dank just to lose all their progress.

**Comment by oliverysfx** [comment]
right that part

**Comment by yasirukavishka** [comment]
Damm my grades XD poofed into atoms thanks to melmsie
