### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by JoeBidein** [DankMemer/dank-memer-suggestions-and-bugs#596]
**Is your feature request related to a problem? Please describe.**
Sort of; whenever I choose a quest, like Streaker for an example I can’t change my quest to Shopper, what I would have to do is finish the quest and then do shopper.  

**Describe the solution you'd like**
There should be a command like “pls quest cancel” or “pls quest change [insert the following quest here]”

**Describe alternatives you've considered**
“Pls quest stop”

**Additional context**
This may not seem like a big issue to a lot of people, but to it would be nice to have this slight feature.  Because some quests can take a while or maybe another there’s another quest that you’d like to try or it’s cooldown has finished.

**Comment by MyNameIsNotDerek** [comment]
do pls quest stop

**Comment by OmegaWarrior04** [comment]
-_-

**Comment by aidenislit** [comment]
@JoeBidein do what @MyNameIsNotDerek said
`pls quest stop`
smfh

**Comment by JoeBidein** [comment]
@aidenislit mk
