### ISSUE TITLE
Make a system where you cannot do anything to a blocked user, and that blocked user can't do anything to you

### ISSUE THREAD

**Issue by titananticheat** [DankMemer/dank-memer-suggestions-and-bugs#597]
There should be a system in the bot where you cannot interact with blocked users and the blocked user cannot interact with you. If someone blocks you, you can't rob, bankrob, or use any items on them. If it is attempted, it will say, "Hey they have blocked you. Now leave them alone."

**Comment by aidenislit** [comment]
That would be stupid because that's basically **free** sand. Also, people would abuse and end up blocking like everyone they know so that's stupid. It's basically a cheap passive mode.

**Comment by oliverysfx** [comment]
@aidenislit has a point, and the bot has no way of knowing who you have blocked, discord doesn't pass this information to clients

**Comment by titananticheat** [comment]
well. i mean there was this user who was bring super annoying when i was trying to do a giveaway. he just kept robbing me even when i told him i was going to do a giveaway. thanks to him, it was cancelled

**Comment by oliverysfx** [comment]
you can make a server mod disable rob

**Comment by oliverysfx** [comment]
plus I said, blocked user information is not knowable by bots

**Comment by titananticheat** [comment]
true, but he was just being a d*** and robbed a lot of my dank memer coins when i was doing a giveaway

**Comment by oliverysfx** [comment]
I said you could have contacted a mod, now close this issue because it would be a waste of time if mel reads this

**Comment by oliverysfx** [comment]
and there's really nothing that says he can't rob you when you are doing giveaways

**Comment by titananticheat** [comment]
well i am getting revenge on him though because there is a lot of mods in the server where he tried to sabotage

**Comment by titananticheat** [comment]
and im a bit new to github how do u close this

**Comment by titananticheat** [comment]
done
