### ISSUE TITLE
Disturbing NSFW gif (more than normal)

### ISSUE THREAD

**Issue by OmegaWarrior04** [DankMemer/dank-memer-suggestions-and-bugs#598]
**Describe the bug**
Used porngif and got something a little disturbing. You might want to blacklist it or something. It isn't illegal though.

**To Reproduce**
1. type pls porngif lol

**Screenshots**
![image](https://user-images.githubusercontent.com/65581395/83710073-78bd7f00-a5e5-11ea-965b-90cd21cfd511.png)
link to the gif: https://cdn.boob.bot/Gifs/1644.gif

![Capture](https://user-images.githubusercontent.com/65581395/83718866-79f9a680-a5fb-11ea-8560-5e9f24d4a41c.png)

link to the gif: https://cdn.boob.bot/Gifs/1668.gif

**Comment by aidenislit** [comment]
@OmegaWarrior04 They made it NSFW for a reason. If you think its disturbing don't use it. Next time when you open an issue do a real issue because this isn't a bug.

**Comment by OmegaWarrior04** [comment]
> @OmegaWarrior04 They made it NSFW for a reason. If you think its disturbing don't use it. Next time when you open an issue do a real issue because this isn't a bug.

I think we all can agree that this is more disturbing than normal and if the devs can blacklist it or something, it won't take much time and I think they would probably do it. If it is too much work, they can simply read my issue and dismiss it, which would take them less than 10 min.
And I know this isn't a bug, should I have reported it as a feature request?
