### ISSUE TITLE
About not working commands

### ISSUE THREAD

**Issue by Gehanwairus** [DankMemer/dank-memer-suggestions-and-bugs#599]
**Describe the bug**

**To Reproduce**
1.Go to group
2. type pls Steal
3. no Responce

**Expected behavior**
No Reply Or no Action

**Comment by scp174** [comment]
Is stealing disabled? If yes the bot wont respond to you

**Comment by Gehanwairus** [comment]
How To Know It?

**Comment by aidenislit** [comment]
@Gehanwairus If you're in a server with dank memer rob enabled pls rob will not respond to you. The only other explanation is if your blacklisted or bot is down. Hope this helps

**Comment by Gehanwairus** [comment]
Ok thanks
