### ISSUE TITLE
Prestige requirement & cheese % cap

### ISSUE THREAD

**Issue by maddieuwuwu** [DankMemer/dank-memer-suggestions-and-bugs#60]
**Is your feature request related to a problem? Please describe.**
Yes, regarding the prestige level being 125 to prestige, this will make it take (weeks-months) to be able to prestige.

**Describe the solution you'd like**
The solution to people not getting frustrated over the level requirement, I would highly suggest increasing the cheese % cap so it would be easier for us all to reach the level required for prestige. I understand that yes, level 125 is possible to reach but is too difficult to reach with the cheese % cap being low.

**Comment by melmsie** [comment]
Not looking for a solution to this currently.
