### ISSUE TITLE
POLICE

### ISSUE THREAD

**Issue by aidenislit** [DankMemer/dank-memer-suggestions-and-bugs#600]
The POLICE or whatever you call it will remove the fake id from someone. You have to say `pls use POLICE` then a message will pop up saying **Who would you like to use it on? Enter their name in the next 30 seconds** you'll enter their name and their fake id will be removed and you can rob them. I would like the POLICE to be pretty rare so it wouldn't destroy the fake id hype. I would say you can buy from shop for 20k or have a chance to get from loot boxes. Please consider this idea.

**Comment by oliverysfx** [comment]
will the name be the name of fake id or the person's real username, if it's real username it's useless

**Comment by oliverysfx** [comment]
because you can rob someone with fake id if you know their identity
