### ISSUE TITLE
bread 4 pets :3

### ISSUE THREAD

**Issue by peruba** [DankMemer/dank-memer-suggestions-and-bugs#601]
im suggesting that you could feed pets bread command would look like maybe this: (pls feed pet bread) and when pets eat it they get a little xp, also you maybe could feed candies to pets too. :3

**Comment by HongKonger1234** [comment]
Also feed pets with animals and fish, the rarity of the animal determining how much XP the pet can obtain.

**Comment by peruba** [comment]
> Also feed pets with animals and fish, the rarity of the animal determining how much XP the pet can obtain.

yes that's an amazing idea

**Comment by aidenislit** [comment]
thats a good idea but that destroys the purpose of waiting to level up your pets. People can easily get there pets to max level in 10 minutes if this is added.

**Comment by PhantomFrenzy151** [comment]
I mean, they could make special pet candy.

**Comment by melmsie** [comment]
its almost like I said this was planned on the 31st in my mel talk
