### ISSUE TITLE
Heisting "Rage Quitting" Enchancements

### ISSUE THREAD

**Issue by aRandomGithubUser** [DankMemer/dank-memer-suggestions-and-bugs#602]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when someone is on the server and we start heisting them, but they immediately leave the server causing us to lose 2k each.

**Describe the solution you'd like**
I would like the bot to give our money back instead of taking it.

**Describe alternatives you've considered**
Still go ahead with the heist and remove some of their money as punishment for leaving before the heist finished.

**Additional context**
None

**Comment by oliverysfx** [comment]
dup of #431
