### ISSUE TITLE
Getting the hunting rifle when prestige 

### ISSUE THREAD

**Issue by XapexR** [DankMemer/dank-memer-suggestions-and-bugs#603]
**Is your feature request related to a problem? Please describe.**
No it isn't related to any problem its just something that would be usefull

**Describe the solution you'd like**
Maybe when prestiging you also get the hunting rifle as a starter from prestige.

**Describe alternatives you've considered**
I do not know any other way to break the game with that method but hopefully you do add it because that would be great.

**Additional context**

**Comment by oliverysfx** [comment]
you do get it now, this is a repeat of #453

**Comment by dorijanko** [comment]
You get it but it isn't mentioned when you prestige; it just says "A fishing pole, laptop, and cellphone" but you also get a hunting rifle.

**Comment by oliverysfx** [comment]
yes
