### ISSUE TITLE
After i bj a certain amount of coins my dragon immediatly found 4k coins but when i check my bal it wasn't there 

### ISSUE THREAD

**Issue by XapexR** [DankMemer/dank-memer-suggestions-and-bugs#604]
**Describe the bug**
I was doing a bj with like 2.7k or something like that I lost that bj but immediately like 1 second later my pet dragon found 4k coins I check my bal to see if I got it but It wasn't there I am not too sure how it happened but it just did.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
![image](https://user-images.githubusercontent.com/66411604/83733568-9c181680-a645-11ea-854c-ec8688457504.png)

**Additional context**

**Comment by oliverysfx** [comment]
would you send a new screenshot with the amount you bet for the game please? makes it easier for the devs
