### ISSUE TITLE
pets update

### ISSUE THREAD

**Issue by rombiko** [DankMemer/dank-memer-suggestions-and-bugs#605]
name: pets[manager11#6666]
about: pet buff
title: 'pets update'
labels: enhancement
assignees: ''

Is your feature request related to a problem? Please describe.
the problem is pets cost a lot of money and not really help you at any point[and if you are passive its worst]

Describe the solution you'd like
make that the pets going to help you like: dragon going to give you better stuff when you hunting or the crub[i just pick a pet that like water type]can help you fishing or a dog can protect you from cops when you search and so...

maybe you can add more pets that can maybe unlock more commends like a horse that with him you can do pls travel or when you do pls search it's going to show you more options when you have hours...

also maybe the more you use the pet the more it help and the more thing he can do like if the dragon is maxed he can use fire when someone trying to rob you
Describe alternatives you've considered
maybe just make them cheaper and make them money buff you...

Additional context
you unlock new command!
you found nothing, but your pet got 600 coins!
you use your dragon to protect you the robber died[50%chance]

**Comment by rombiko** [comment]
also, i have new pets that you can add that can be cool[also i typing them in types]
fishing types:
1.shark, he going to multiply the fish that you get for example if i got 2 and i have the shark i going to get 4.
2.super fish, you can only craft him[with 100 fish]and it's going to give you more luck in fishing, for example, you never going to get 0 fish when you fish
hunting type:
1.wolf, he going to hunt with you so it's going to be like you hunt 1 and your pet 3 and more...
2.dragon, multiply by 4 all the things that you got...[not rare drops]
Search types:
1.dog, going to stop the cops,also give you more money when you do search
2.dragon[i know its already in hunting but he is the rarest pet so you got to give him more]
, you can fly with him when you search so you going to be able to search in bigger places
3.hours, same us dragon just ride...
gambling types:
1.Pepe, just more chance to get good and more money
2.cat, more money, and no cooldown when gambling
begging types:
little dog[you can pick when you buy a dog if you want a doggo or police dog], going to give you more money when begging
------------------------
that's all the pets that i can think of[some of the pets already there but without the thing that they help] also there is pets that i didn't put in here, just give them ability base of there type like turtle going to help fishing

**Comment by oliverysfx** [comment]
if you think pets are useless in passive, then disown them or leave passive, passive is intended to have quite a lot of nerfs

**Comment by oliverysfx** [comment]
because they aren't useless, hunting status can give you items / coins at random

**Comment by rombiko** [comment]
> if you think pets are useless in passive, then disown them or leave passive, passive is intended to have quite a lot of nerfs

its useless even if you aren't a passive it useless at everypoint

**Comment by oliverysfx** [comment]
it's useful, they can protect u from robbing, and they can find stuff for you

**Comment by oliverysfx** [comment]
like 50% of robbing attempts at me are ate up by my pet

**Comment by rombiko** [comment]
> like 50% of robbing attempts at me are ate up by my pet

so for that you going to pay like 70k when you can just have a pad lock?

**Comment by oliverysfx** [comment]
anyways a pet is helpful when a whole server is spamming rob at u

**Comment by rombiko** [comment]
> anyways a pet is helpful when a whole server is spamming rob at u

still not worth it.... and you can do with them so much good stuff like so its very disappointing that they just help you with that little

**Comment by oliverysfx** [comment]
actually dragon pet has another use that I won't say here

**Comment by oliverysfx** [comment]
for it's secret

**Comment by rombiko** [comment]
> for it's secret
he give you a little multiply

**Comment by rombiko** [comment]
just buff pets.........

**Comment by melmsie** [comment]
no
