### ISSUE TITLE
boss hits 

### ISSUE THREAD

**Issue by rombiko** [DankMemer/dank-memer-suggestions-and-bugs#607]
**Describe the bug**
even when the boss dies you can still get hits on them 
**To Reproduce**
1.wait until there is a boss event
2.wait until the boss have 0 hp...
3.hit him...

**Expected behavior**
you not going to get more hits if the boss dead 

**Screenshots**
ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Additional context**
that gives you more things and more money....

**Comment by oliverysfx** [comment]
no they do not, any hits beyong 0hp are useless
