### ISSUE TITLE
A new setting

### ISSUE THREAD

**Issue by CosmoPlays** [DankMemer/dank-memer-suggestions-and-bugs#609]
**Is your feature request related to a problem? Please describe.**
Yes, I was wondering if you could make a new setting where no one could steal from you but you can still trade with others. (kinda like passive mode)

**Describe alternatives you've considered**
There is still a cost like passive mode: able to get less money when doing things like working or gambling etc

**Comment by oliverysfx** [comment]
too op, that's why the nerf of no sharing / gifting in passive was added
