### ISSUE TITLE
breaking laptop

### ISSUE THREAD

**Issue by CoconutGator** [DankMemer/dank-memer-suggestions-and-bugs#61]
I think that, in case you post a bad meme on your laptop (one that gets you negative points and no money) you should be able to play a minigame. If you win the minigame, you delete the meme before too much negative backlash goes towards it. If you lose the minigame, then your laptop breaks.

This is just to make it so you can actually control your laptop breaking or not.

**Comment by melmsie** [comment]
We'll take your idea into consideration
