### ISSUE TITLE
Rare Event (Trivia) Bug

### ISSUE THREAD

**Issue by DeskPilot01** [DankMemer/dank-memer-suggestions-and-bugs#611]
When there is a rare event by trivia, that doesn't show results, like this:
![Polish_20200604_150754376](https://user-images.githubusercontent.com/66275717/83755289-034dbf00-a676-11ea-930a-7a30db7c5b1f.jpg)

**Comment by scp174** [comment]
You might have picked the wrong answer?

**Comment by Neptunus-Equester** [comment]
saying the correct answer is B, its not responding to you because you answered A first which was incorrect

**Comment by oliverysfx** [comment]
only the first answer register

**Comment by melmsie** [comment]
NAB
