### ISSUE TITLE
Incorrect trivia(Le Mans) 

### ISSUE THREAD

**Issue by GeorgeSofroniouCy** [DankMemer/dank-memer-suggestions-and-bugs#612]
A trivia question asks for which Japanese manufacturer is the only Le mans 24 Winner. Mazda won in 1991 and was the only Japanese manufacturer until Toyota won in 2018 and 2019. So the question is now invalid.

**Comment by aidenislit** [comment]
Do you have a screenshot?

**Comment by GeorgeSofroniouCy** [comment]
Yes I do!

**Comment by GeorgeSofroniouCy** [comment]
![Screenshot_20200604-151644](https://user-images.githubusercontent.com/66422818/83795586-5b051e00-a6a8-11ea-8ef9-1eeb79e38272.jpg)
Sent in email, will send here as well

**Comment by aidenislit** [comment]
@GeorgeSofroniouCy Toyota won the last 2 Le Mans but they won the FIA World Endurance Championship. Mazda was the only one on the list that won the World Sportscar Championship. Although the question didn't specify the World Sportscar Championship was the official award. Hope this helps

**Comment by melmsie** [comment]
we don't control the trivia api
