### ISSUE TITLE
Piratespeak breaks meme commands

### ISSUE THREAD

**Issue by Reselit58iql** [DankMemer/dank-memer-suggestions-and-bugs#613]
**Describe the bug**

pls meme and some other memey commands don't show the image when pirate speak is turned on

**To Reproduce**

1. Do pls settings piratespeak true
2. Do pls meme
3. Image shouldn't show up

**Expected behavior**

The image should show up

**Screenshots**
![Przechwytywanie](https://user-images.githubusercontent.com/66426946/83768442-144efe00-a67f-11ea-823d-3adc56275d69.PNG)
![piratespeak2](https://user-images.githubusercontent.com/66426946/83768454-187b1b80-a67f-11ea-8f3a-5f8f9da68bb0.PNG)
![obraz](https://user-images.githubusercontent.com/66426946/83769302-f9c95480-a67f-11ea-8ff5-ad3118235d89.png)

**Additional context**
It also break these commands: surreal, sequel, memeeconomy, meirl, 4chan, comics, blacktwitter, wholesome and facepalm.

**Comment by aidenislit** [comment]
Your internet might be slow and the images haven't registered in yet.

**Comment by Reselit58iql** [comment]
> Your internet might be slow and the images haven't registered in yet.

I doubt that,  when I turned off pirate speak the images loaded + when I used the command with piratespeak my friends couldn't see the images either

**Comment by DankMemerFan** [comment]
it is the pirate speech, it changes someof the words, sometimes it does it with links as well, it turns "and" into "n'" and "is" into "be"

**Comment by andrewisaboomer** [comment]
this also screws up the link to this github page as well when using pls suggest

**Comment by melmsie** [comment]
should be mostly fixed, rare af if not
