### ISSUE TITLE
heist bug

### ISSUE THREAD

**Issue by SharloR** [DankMemer/dank-memer-suggestions-and-bugs#615]
**Describe the bug**

• in every friendly heist with a lot of people, the last person always wins! he/she's always on the bottom, tons of people try being last and accidentally end up missing it. I don't want to have to try to be last to win the heist, its very annoying
**To Reproduce**
Steps to reproduce the behavior: ???

**Expected behavior**
 
• I expect it to be random and the last person isn't the one that gets most of the money, one time there was a 1mil heist and of course the last person got the 900k!!! im tired of the last person getting all of it from friendly heists.

**Screenshots**

• I cant put screen shots as I am currently on mobile.

**Additional context**

**Comment by aidenislit** [comment]
That is not true. The last person doesn't always get the most. There is a really high chance but not always. The devs put it that way on purpose and it is not a bug. They programmed it to make the last person get the most and they didn't accidentally do it.
