### ISSUE TITLE
PLS DAILY RESET AT MIDNIGHT

### ISSUE THREAD

**Issue by bigbrain123123** [DankMemer/dank-memer-suggestions-and-bugs#617]
make pls daily reset at midnight or at a specific time (timezones).

**Comment by aidenislit** [comment]
that means a person has to set there timezone and sometimes their timezones can be personal.

**Comment by oliverysfx** [comment]
this completely doesn't make sense, because timezone can be quite sensitive information sometimes

**Comment by RandomTurtleBoi** [comment]
mel said multiple times that he's not going to add this. you're not the only one that wants this (like me) but mel says "why should he make this specific command reset at midnight as opossed to every single other command" so i dont have high hopes for this. and timezones are going to be hard to figure out, like the others mentioned

**Comment by oliverysfx** [comment]
and private information is going to be more problematic
