### ISSUE TITLE
change using tide pods/hospital fees when you get injured

### ISSUE THREAD

**Issue by andrewisaboomer** [DankMemer/dank-memer-suggestions-and-bugs#618]
when you get farther into the bot you lose way more money from when you get injured and paying hospital fees rather than dying and using a life saver

i dont want to be screaming at the bot saying "WHY DIDNT YOU KILL ME YOU IDIOT" i want to be happy that i was only injured and not killed

edit: im dumb and retarded and made the label bug instead of suggested feature

**Comment by aidenislit** [comment]
@andrewisaboomer are you an idiot? This is not a bug this is you trying to make it easier for you to get coins. Has it ever occurred to you that they did this on purpose? SMFH don't waste the dev's time.

**Comment by andrewisaboomer** [comment]
no but the thing is whats the point of making injuries take more money from you than life savers

in real life id rather get injured and not die, but in the bot dying is generally better than getting injured because injury takes a percentage of wallet and dying takes a static 5k as long as you have life savers

**Comment by oliverysfx** [comment]
the amount take is percentage if I am not wrong, so just deposit your coins into your bank

**Comment by melmsie** [comment]
death and hospital fees and fines are all being reworked in the future
