### ISSUE TITLE
Graverobbing

### ISSUE THREAD

**Issue by wolf653** [DankMemer/dank-memer-suggestions-and-bugs#619]
Death in dank memer is a rather empty mechanic i feel could actually be expanded on *With grave robbing!*
a new search area could be added called the graveyard where you can acquire coffins that can contain loot lost from the last # dead members from that server however unfortunately you cannot get your own coffin.
To prevent getting carried from dead members only a certain percentage of coins will be added to a user's coffin and the amount of loot can possibly affect the rarity of that user's coffin.
of course graverobbing can result in fines or even worse death from the ghosts of dead memes
**alternate idea**
A new shop item called the shovel that grants access to "pls graverob" which is basically the idea above but not hoping to have the graveyard area in pls search.

**Comment by melmsie** [comment]
could be fun in the distant future

**Comment by epicjonny312** [comment]
+1

**Comment by MadScriptCode** [comment]
maybe add a command "pls graveyard" that lists coffins/people who died recently
and then do "pls graverob" a certain person to collect the same percentage of coins as rob (20% to 80% of the grave)
Except you have a high chance of dying yourself because it's haunted by evil spirits.

**Comment by oliverysfx** [comment]
erm robbing percentage is now 355 - 100% now
