### ISSUE TITLE
Work Rewards

### ISSUE THREAD

**Issue by MooMooMooMooMooMooMoo2** [DankMemer/dank-memer-suggestions-and-bugs#62]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem; it is only a suggestion I would like to see implemented with the Dank Memer bot.

**Describe the feature you'd like to implement**
I would like to implement something called Work Rewards, and let me explain before you make a decision. When you work, you only get coins and 1 success on you record you can see using pls work info. At the end of every day, Dank Memer counts up your successes and fails and rewards you accordingly. Lets say you have 4 successes and 1 fail. Dank Memer subtracts this two numbers to get your total score, (in this case 3) which will get you a low-tiered item. If you have more fails than successes, you get fired without any reward. If you have a total score from 0-2, then you haven’t been working that well (or enough) and you’ll have to try again the next day. Here are my ideas for **total score** to the rarity of the item you get:
0-2: Nothing
3: 100 bonus coins
4-5: low-tiered item
6-8: medium-tiered item
9-10: high-tiered item
These are only examples, you may change them or use them.

Thank you for your time, and have a nice day.

**Comment by melmsie** [comment]
We'll take your idea into consideration
