### ISSUE TITLE
BJ negative balance

### ISSUE THREAD

**Issue by aidenislit** [DankMemer/dank-memer-suggestions-and-bugs#620]
So basically whenever I withdraw money I BJ it and people from another server rob me so if I lose the BJ I get a negative balance. Please add you can keep you balance back cause i'm 75k in the hole.

**Comment by oliverysfx** [comment]
this is completely intended, this is to prevent people from using this to farm money if 100% of your money is your stolen

**Comment by melmsie** [comment]
NAB
