### ISSUE TITLE
My bank did not keep the my bank note expansions after prestiging.

### ISSUE THREAD

**Issue by WoIfyy** [DankMemer/dank-memer-suggestions-and-bugs#621]
**Describe the bug**
After completing my first prestige AFTER the update was released, my bank did not keep its bank note expansions.

**To Reproduce**
Not necessarily reproducable. Just a one time issue where my bank did not keep the expansions provided by bank notes.

The way I did this was through:
1. Prestiging
2. Checking balance
3. Scrolling back through history to check previous balance.

I'm not entirely sure how to write this part, sorry if it is unclear.

**Expected behavior**
To have kept the expanded bank notes after expansion, but the bank removed all of it.

**Screenshots**
![pls bal](https://user-images.githubusercontent.com/66454985/83838510-be409000-a73c-11ea-961a-d8bf8d68bcec.png)
![pls bal after prestige](https://user-images.githubusercontent.com/66454985/83838517-c39dda80-a73c-11ea-9cf5-4a1314342fb6.png)

**Additional context**
Did the prestige AFTER the update was realised. Did not keep my bank notes. I have not used any bank notes in my current prestige, please help 👍

**Comment by aidenislit** [comment]
@WoIfyy I don't know if your stupid or pulling a prank because the DEV's made it so when you prestige your banknote expansion resets. This is not a bug.

**Comment by WoIfyy** [comment]
![image](https://user-images.githubusercontent.com/66454985/83840081-01046700-a741-11ea-8e54-28bbf35e16fd.png)

@aidenislit

**Comment by dorijanko** [comment]
You said that the bank removed all of it but i see 142659 bank space; that's probably the amount of expanded bank space you had.

**Comment by oliverysfx** [comment]
^

**Comment by WoIfyy** [comment]
> You said that the bank removed all of it but i see 142659 bank space; that's probably the amount of expanded bank space you had.

Hm, i think i've looked at bank space incorrectly. I believe that it probably scales with EXP. I will look into this for a few hours and close this. I'll reopen if I find an issue.
