### ISSUE TITLE
Old age Padlock

### ISSUE THREAD

**Issue by rayhan6726** [DankMemer/dank-memer-suggestions-and-bugs#622]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Padlock expiry is 1 year. But the longer the lock is installed, the older the lock is, the easier it is to open it with your bare hands. Make people 10% easier to unlock padlock after 3 months, 20% after 6 months, 30% after 9 months.

**Describe alternatives you've considered**
Make the cooldown 3 minutes to make people who broke the padlock with bare hands because they need to rest their hands. 

**Additional context**
None.

**Comment by oliverysfx** [comment]
eh the padlock is meant to make people instant fail, so this really doesn't make sense, you are effectively making the durability of padlock basically 3 months, because 25% is very high

**Comment by rayhan6726** [comment]
> eh the padlock is meant to make people instant fail, so this really doesn't make sense, you are effectively making the durability of padlock basically 3 months, because 25% is very high

- Edited

**Comment by oliverysfx** [comment]
still freaking high, especially in large servers, it's not that hard to get 10 people to gang on you and ur padlock is pretty much a goner

**Comment by oliverysfx** [comment]
basically 6 months durability now...
