### ISSUE TITLE
Pls quests type commands not working 

### ISSUE THREAD

**Issue by PeacefulSirSheep** [DankMemer/dank-memer-suggestions-and-bugs#625]
Anything related to the pls quests commands, such as the list and that for me it just shows the 'oopsie poopsie' error message, but when I got my friend to do it it works perfectly for him.

No idea why this is happening to only me, I've waited a good few hours and still the same

![DAE8128E-7191-4F86-B5D7-761D4743E523](https://user-images.githubusercontent.com/66467325/83859176-75c1ac00-a715-11ea-9645-73ba86004d35.jpeg)
![E043AB7F-089E-43D7-B174-36B12EF34213](https://user-images.githubusercontent.com/66467325/83859336-aacdfe80-a715-11ea-8b31-5b5530326dfb.jpeg)

**Additional context**
The second one is just to show that it can work for other people perfectly fine and it's only this command that's bugged for me, everything else is fine as can be. Thanks for reading.

**Comment by melmsie** [comment]
I'll need your Discord ID

**Comment by PeacefulSirSheep** [comment]
> I'll need your Discord ID

453082696067842050 <- This should be it

**Comment by inooby333** [comment]
Quests hasn't been working for me too for almost 10 months now. When I asked back then they said it's a known glitch but it's still broken. It happens to random users and has nothing to do with where you use the bot.  For the users that the quests is broken, EVERY quest command resilts in error. It isn't something in settings or items in inventory. That's all I know.
