### ISSUE TITLE
add a command that server admins can use to hide passive users off the pls rich leaderboard

### ISSUE THREAD

**Issue by oliverysfx** [DankMemer/dank-memer-suggestions-and-bugs#626]
**Is your feature request related to a problem? Please describe.**
as stated before, it's annoying that passive users are basically making pls rich useless

**Describe the solution you'd like**
I would suggest a command "pls hidepassive" that only the admins can use that hides passive users off the pls rich leaderboard.

**Describe alternatives you've considered**
make it a setting for everyone to choose whether to hide passive users or not under pls settings

**Additional context**
nil

**Comment by melmsie** [comment]
I've said it countless times. It's "pls rich" not "pls who can I rob"
