### ISSUE TITLE
an aquarium for the fishes you caught 

### ISSUE THREAD

**Issue by backagainwiththatwhitevans** [DankMemer/dank-memer-suggestions-and-bugs#628]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
maybe having a command like **pls aquarium** and it’ll show the aquarium if you bought one. and maybe do **pls add (fish type)** and it would add that fish into the aquarium, i would say around 15-20 fishes max. also the aquarium can give coins based on the fish that is currently in the aquarium. also maybe having to buy food for fish for them not to die.

**Describe alternatives you've considered**
i don’t have any, sorry.
**Additional context**
.

**Comment by melmsie** [comment]
While an interesting idea, not something I see us adding
