### ISSUE TITLE
Just misspelling 

### ISSUE THREAD

**Issue by meleemelon** [DankMemer/dank-memer-suggestions-and-bugs#63]
when fishing sometimes you are asked a phrase. One phrase is “thats very fishy” and when you have auto correct it’s “that’s” so you fail the fishing Because you either make an error or don’t get it in time of you go back to fix it. the spelling of the phrase should be changed to that’s.

**Comment by melmsie** [comment]
This isn't a bug, it's intended to not have the punctuation.
