### ISSUE TITLE
Allow passive mode to be able to share coins and gift stuff

### ISSUE THREAD

**Issue by mjshein** [DankMemer/dank-memer-suggestions-and-bugs#630]
**Is your feature request related to a problem? Please describe.**

I am in passive mode because I have 6 million+ coins and not enough bank space. I love sharing stuff with people and giving stuff away, but recently a new update was made that disallows people in passive mode to be able to share coins and gift items.

**Describe the solution you'd like**

Be able to share and gift items just like non-passive people.

**Describe alternatives you've considered**

I have considered turning off passive mode for a little while to gift things, but there is a 24-hour cooldown and I could get robbed during that time.

**Comment by melmsie** [comment]
interact with EVERYONE or interact with NO ONE. You're not getting the good parts of the bot while avoiding the "bad" parts.
