### ISSUE TITLE
Tic Tac Toe suggestion

### ISSUE THREAD

**Issue by Tomothy05** [DankMemer/dank-memer-suggestions-and-bugs#634]
**Is your feature request related to a problem? Please describe.**
It's always annoying when I'm playing Tic Tac Toe and I mix up rows and columns.

**Describe the solution you'd like**
I'd like for there to be letters and numbers beside the game indicating which row and column is which. So it would look something like this:
_123
A000
B000
C000

**Describe alternatives you've considered**
An alternative would be to memorise the format for Tic Tac Toe but having the letters and numbers on the side would be much more convenient for users.

**Comment by aidenislit** [comment]
The current format is already good. Yours is more confusing.
