### ISSUE TITLE
Normie box gives items but not coins

### ISSUE THREAD

**Issue by fatguy1248** [DankMemer/dank-memer-suggestions-and-bugs#635]
When I used the normie box I would get all the items but not the coins

**Expected behavior**
I expected to get the coins and items

**Screenshots**
![4CA50E6B-B5DE-4CD9-9128-652368486DC0](https://user-images.githubusercontent.com/66499489/83930277-b7c60e80-a764-11ea-922d-886e1b1fc67c.png)
![3682AC5A-5431-4D50-A839-3E0644ADB529](https://user-images.githubusercontent.com/66499489/83930278-ba286880-a764-11ea-88b6-8112db8d5e76.png)
![D0812782-DF78-4566-84E7-A102A27AB5FF](https://user-images.githubusercontent.com/66499489/83930279-bb599580-a764-11ea-818a-f497d90ba86e.png)
![5354D9E7-BA73-4301-B0AC-16EAA79448BD](https://user-images.githubusercontent.com/66499489/83930282-bbf22c00-a764-11ea-9487-6541a87c6c6c.png)
![93DEE739-1AA1-439C-B871-E2D84D101017](https://user-images.githubusercontent.com/66499489/83930284-bbf22c00-a764-11ea-9d42-d1a60f52010c.png)
![5963B27D-D306-4DD3-AD01-32A9F6B09484](https://user-images.githubusercontent.com/66499489/83930286-bc8ac280-a764-11ea-9a46-9045b433b991.png)

**Additional context**

**Comment by aidenislit** [comment]
hmmm, check your notifs cause you might have been robbed. This never happens. But it probably is a bug.
