### ISSUE TITLE
Pls guess as a gambling game

### ISSUE THREAD

**Issue by RealKingAwesome** [DankMemer/dank-memer-suggestions-and-bugs#636]
You should have a gambling version of pls guess, but you only have one attempt but you receive that number x your bet for example pls betguess 10 100 would be a 100 coin bet in a number 1-10 if correct you receive 10x your bet with a maximum of I guess maybe 10,000

**Comment by oliverysfx** [comment]
overall this doesn't help at all, if you look at expected payouts, you earn nothing more, and lose nothing less

**Comment by melmsie** [comment]
no

**Comment by RealKingAwesome** [comment]
You can make it so it’s a little less so like if you did 50 it’s only pays 45X or something
