### ISSUE TITLE
Fishing rod tiers

### ISSUE THREAD

**Issue by CowboyKarma** [DankMemer/dank-memer-suggestions-and-bugs#64]
**Whats the problem?**
The simplicity of "pls fish"
Pls fish feels so basic. You just type the command and hope for the best, The concept is so unique but the execution feels underwhelming

**What if your solution?**
Add rod tiers/bait/more fish
Add rod tiers that allow better chances of fishing rare and exotic fish. Additionally, add more tiers of fish (maybe sharks can be one). Baits can also make the concept more entertaining

**What other solutions did you come up with?**
Minigames
Like what you did to "pls pet play", add minigames whenever you fish.

**Extra info**
I know fishing is a very VERY recent concept and I understand that you may need to test some things out, but please take in consideration on my suggestions. Other than that, have a great quarantine

**Comment by melmsie** [comment]
We've got more advanced plans for various commands that we aren't willing to share at this time.
