### ISSUE TITLE
Allow people to rob bots

### ISSUE THREAD

**Issue by Jiakai7521** [DankMemer/dank-memer-suggestions-and-bugs#640]
I would like the bot to allow us to rob from bots. As some people give money to bots, we should be able to take it from them and hence, I suggest that we can rob from bots. Anyways, the bots cannot use the money

**Comment by aidenislit** [comment]
That would be stupid because the Dank Memer Bot has 4MIL coins. Also the DEV's set it so people can't rob bots for a reason.

**Comment by melmsie** [comment]
no

**Comment by Jiakai7521** [comment]
Why not?
