### ISSUE TITLE
Not getting exp from pls bet 100 and slots 100

### ISSUE THREAD

**Issue by Dragoseum** [DankMemer/dank-memer-suggestions-and-bugs#641]
**Describe the bug**
Pls bet and pls slots don't give any exp when running them.

**To Reproduce**
1. Deposit all money until full bank
2. Do pls level to check exp
3. Pls bet 100 or slots 100
4. Wait 5 seconds
5. Pls bet 100 or slots 100 again
6. repeat until done 7or 8 times
7. Do pls level to check exp again
8. do pls dep all to check for new bankspace

**Expected behavior**
That some amount of exp and bankspace is gained after running the commands.

**Screenshots**
![image](https://user-images.githubusercontent.com/49676957/83941323-ab849480-a7ea-11ea-9cd6-54d4c6de9890.png)
![image](https://user-images.githubusercontent.com/49676957/83941337-c0612800-a7ea-11ea-8f9e-880376a0b6a2.png)
![image](https://user-images.githubusercontent.com/49676957/83941342-cc4cea00-a7ea-11ea-8885-a06dda8b103e.png)
![image](https://user-images.githubusercontent.com/49676957/83941347-dec72380-a7ea-11ea-8927-8b957ad6fe3c.png)
![image](https://user-images.githubusercontent.com/49676957/83941352-e981b880-a7ea-11ea-8bab-4af816a31b2b.png)
![image](https://user-images.githubusercontent.com/49676957/83941358-f3a3b700-a7ea-11ea-8c6e-acc0b6ee2fbc.png)

**Additional context**
I am in passive mode, but other commands do give exp and bankspace

**Comment by melmsie** [comment]
Not a bug, we don't want people spamming the minimum amount of gamble for easy money and easy xp
