### ISSUE TITLE
Suggestion To Allow Passive Mode Users To Send/Receive Items ( Not Money )

### ISSUE THREAD

**Issue by MantisGalaxy** [DankMemer/dank-memer-suggestions-and-bugs#642]
I feel like being in passive mode means the only way you can earn stuff is through the economy commands. Sometimes, my friends try to send me stuff but they can't because I'm in passive mode. I would have disabled it but I'm #1 on many leaderboards on Dank Memer which means I'll be instantly robbed. 

I know this might have many flaws but we can work away around it. Like only accounts older than a month can send/receive items in passive mode to prevent alt farming

**Comment by melmsie** [comment]
No
