### ISSUE TITLE
Can't gift cupid big toe even though an inventory item

### ISSUE THREAD

**Issue by BewkoofBaba** [DankMemer/dank-memer-suggestions-and-bugs#643]
**Describe the bug**
It was announced that every inventory item is giftable but one cannot gift cupids big toe as it keeps saying the item does not exist.

**To Reproduce**
pls gift cupid or any other command

**Expected behavior**
It should be allowed to be gifted same as a blob is.

**Comment by melmsie** [comment]
NAB
