### ISSUE TITLE
Increase the amount of time before DankMemer cancels the work

### ISSUE THREAD

**Issue by Sup3rCell** [DankMemer/dank-memer-suggestions-and-bugs#646]
**Is your feature request related to a problem? Please describe.**
When i am in the middle of typing out the sentence that Dankmemer asked me to type, it will end the work because i have run out of time. Its is sometimes humanly impossible for a person using a phone to type out the sentence shown by Dankmemer and is very frustrating that it says that i failed the job when there was not enough given time to type it out.

**Describe the solution you'd like**
A clear and concise description of what I want to happen, is to increase the time limit of when Dankmemer fails me, since its impossible to type it on phone that fast.

**Describe alternatives you've considered**
You could alternatively make the sentence requested by dankmemer to type out, to be shorter so that people using mobile phones can type out the sentence in time.

**Additional context**
No

**Comment by melmsie** [comment]
It is plenty of time
