### ISSUE TITLE
Lego Star Wars Character Portrait

### ISSUE THREAD

**Issue by DarthTauntaun** [DankMemer/dank-memer-suggestions-and-bugs#651]
This would be for the section under pls help images.

The image in question:
![Lego Star Wars Character Icon](https://user-images.githubusercontent.com/47067452/83953271-b3e9c900-a804-11ea-8f98-cba2f04b5d67.png)

It would be along the lines of pls portrait, and it would put the image/ profile picture centered inside the ring. (It's already a png as well)

**Comment by melmsie** [comment]
I'm not really sure how this would be interesting
