### ISSUE TITLE
Leaderboard issue involving passive mode users

### ISSUE THREAD

**Issue by samdabloxyccola** [DankMemer/dank-memer-suggestions-and-bugs#654]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is: I'm frustrated when the whole 10 pages of the "pls rich" leaderboard is filled with people in passive mode.

**Describe the solution you'd like**
A clear and concise description of what you want to happen: I should suggest that players who are in passive mode should not be in the "pls rich" leaderboard due to users having the inability to search for users who are not in passive mode and have some money in their wallet.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered: The leaderboard can be extended from page 10-25 (Depending on the wallet capacity of users) so that users can find some users to steal from 

**Additional context**
Add any other context or screenshots about the feature request here: N/A

**Comment by xXSrRyanXx** [comment]
Rather pulling some kind of extension like Pls rich --passive
