### ISSUE TITLE
Leaving after heisting

### ISSUE THREAD

**Issue by samdabloxyccola** [DankMemer/dank-memer-suggestions-and-bugs#655]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is: I'm always frustrated when players get the lion's share of the heist money and never share the money with those who died/failed/got lesser money. E.g: Adam#7120, Billy#0001 and MarioAndPeach#9210 started a heist on YourMum#1999. The heist was successful. Results:
-MarioAndPeach died
#Adam stopped by for Macdonalds which costed them 1003 coins
+Billy took off with 108384 coins
However, after the heist, Billy left the server without sharing the heist money with Adam and MarioAndPeach. The two who failed the heist told Billy to share them some cash but Billy refused. He even made fun of them.

**Describe the solution you'd like**
A clear and concise description of what you want to happen: The user who got the money must be dmed by the bot to inform him to share the heist money equally. The bot then gives the person on how much to give the rest of the participants of the heist. However, if the player fails to comply with the instructions, the bot will have no choice but to confiscate the money and either share with the other users itself or return the money to its owner's bank.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered: The users who received the money from the heist will be immune from anyone robbing the users for a few minutes. This way, no one will rob the user for a while and the user will have to share the heist money with the rest or deposit his cash.

**Comment by HongKonger1234** [comment]
The entire purpose of the uneven split is to make heisting more fun. If you want to split evenly, there are some heisting servers that will do that. No change to the bot required.

**Comment by andrewisaboomer** [comment]
instead of forcing the guy who got the money to share, bot devs could just make the money from the heist be shared equally.

but thats really boring because then theres no excitement to heisting and its just die, fail, or get money
