### ISSUE TITLE
Didnt receive other rewards

### ISSUE THREAD

**Issue by Gonpachirou** [DankMemer/dank-memer-suggestions-and-bugs#656]
i didnt receive the banknote that i should have (from level 40 rewards)

there should be a banknote that i received when i levelled up to 40

![Screenshot_2020-06-07-20-14-17](https://user-images.githubusercontent.com/66556398/83968402-99dee200-a8fb-11ea-8b64-7d39516a0117.png)

**Your User ID**
[708197045202190366]

**Additional context**

**Comment by andrewisaboomer** [comment]
yeah i can confirm that i didn't get a banknote when i leveled up earlier

**Comment by melmsie** [comment]
No one gets these rewards, kind of a bug but not a priority
