### ISSUE TITLE
pls rich blue dash doesnt show when theyre not in passive

### ISSUE THREAD

**Issue by lex1268** [DankMemer/dank-memer-suggestions-and-bugs#657]
**Describe the bug**

**To Reproduce**
1. go in a robbing server (pls rich and pls rob enabled)
2. do pls rich
3. if you try to rob from them and theyre in passive theres still the diamond emoji, and if theyre not then its there still. you dont know when they're in passive or not and its very annoying (its a bug i believe)
4. you spend your entire life trying to find someone who isnt in passive-mode

**Expected behavior**
uhh, something to make me know whos in passive and whos not?
**Screenshots**

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed
617986302863998986 

**Additional context**
not really, but please fix it

**Comment by melmsie** [comment]
I'll need screenshots
