### ISSUE TITLE
Multiplier Percentage Error

### ISSUE THREAD

**Issue by MrSkyCube** [DankMemer/dank-memer-suggestions-and-bugs#659]
**Describe the bug**
When using the official dank memer server I noticed a visual error on my profile. The multiplier percentage displays as 24.75%. This is incorrect, when I gamble it shows 21.7% or when I do pls multiplier. This is all happening on the dank memer official server. I know that multiplier's are different per server.
**To Reproduce**
1. Go to bot commands in Dank Memer Official
2. Type pls profile and see that it displays as 24.75%
3. Win a gamble or do pls multiplier and see that it displays as 21.75%

**Expected behavior**
I expected the multiplier on my profile to be the same as displayed when typing pls multi or winning a gamble.
**Screenshots**
Pls multi in #botcommands in Dank Memer Official:
https://user-images.githubusercontent.com/66569905/83977685-705c9100-a8d0-11ea-9f10-69698dc28ea9.jpg
pls bet multiplier in #botcommands in Dank Memer official
https://user-images.githubusercontent.com/66569905/83977716-b74a8680-a8d0-11ea-864e-caac837feb9e.png
Pls profile multiplier in #botcommands in Dank Memer Official
https://user-images.githubusercontent.com/66569905/83977741-eb25ac00-a8d0-11ea-8090-da969990ebae.png

**Your User ID**
359067481362530325
**Additional context**
N/A

**Comment by andrewisaboomer** [comment]
im fairly sure it has something to do with the channel name multipliers
thats really all i know

**Comment by MrSkyCube** [comment]
> im fairly sure it has something to do with the channel name multipliers
> thats really all i know
No, both channels are named bot commands, even if I did all 3 commands(pls profile pls multi and pls gamble 100), the multiplier is different only for pls profile on this server. It is 24.75% even though nothing else shows that on the server. If you look at the picture of my multipliers, you will not see the one called dank memer channel.

**Comment by melmsie** [comment]
should probably maybe be fixed next update
