### ISSUE TITLE
Ideas for Dank Memer

### ISSUE THREAD

**Issue by ClaasicMan** [DankMemer/dank-memer-suggestions-and-bugs#66]
_**Is your feature request related to a problem? Please describe.**_
No its not

**_Describe the solution you'd like_**
_I have quite a few ideas that i think would really make memer a bit better_
- In the future is the legendary fish that you can catch gonna give more time like 10 seconds instead of 5 seconds? Some people cant type that fast
-  an item called console, "Pls buy console" for like 15k or 25k or something like that and has a 50/50 chance of winning a game of some sort like a battle royale, racing game, some kind of competitive game, etc stuff like that and if you win you get like 100+ coins & make the command like "pls game"
- add "pls coinflip" [amount] or "pls cf" [amount] and you are able to choose head or tales 
- make it so you can gift more than 1 item
- add some sort of item that robs someone at random and make it like 1k to buy
-  the fishing pole should get levels, make it so you can buy places and the more places you buy the better the fish your  have different baits & add more kind of fish. Also make it so its harder to get certain fish depending on the bait and place
- add a connect 4 game that's just like tic tac toe but you can only say like a,b,c etc or 1,2,3 etc to make it so it places since the game pieces drop to the bottom. If you win you get like 50+ coins
- a gambling info or stats that shows how many times you lost and won
- add more quests, jobs, & items
- make it so you can do a heist alone
- add more places to search for pls search
- make it so you can post memes with a cellphone for "pls pm" or "pls postmemes"
- make a item call gun & can buy it by using "pls buy gun" and you can go hunting with your pet with "pls pet hunt" or you could do a currency code like "pls hunt" and you have a 50/50% chance or 60/40% (60% = you get nothing, 40% = you win a certain bird and each bird would have a different value)
- make a trader "pls trade" where you can either trade money or items to a ai for certain items he has in stock and he/she resets every 24hs 
- In normie loot boxes you have a 1% - 5% chance to get a different lootbox

_**Describe alternatives you've considered**_
- For the random rob item all the items the prevent robbing still works for it
- For Fishing make it so if your pole breaks (doesn't matter if you have more than 1 pole) then you go back to the first place before you bought a place to fish

**_Additional context_**
If anyone needs anymore information please comment on this idea post

**Comment by melmsie** [comment]
We will take these ideas into consideration
