### ISSUE TITLE
Make search, pm, beg commands more OP and interesting.

### ISSUE THREAD

**Issue by Azim-lab** [DankMemer/dank-memer-suggestions-and-bugs#665]
Right now, search, beg, and pm commands ain’t so entertaining. And they don’t give a lot. Maybe you can add more choices to pls search. Like carpet, toilet, train, and etc. And add events. For example, you searched the car, and before getting fined there is going to be mini game, and if you loose it, you will be fined but if you win it, you won’t. Maybe you could also scout fish and animals and other items. 
With pls beg, you could get fined by police for begging. But you won’t if you win a mini game or something. Maybe you could also add choices from who you can beg from.
With post meme, add more choices too. Like corona meme, Fortnite meme, school meme, and etc.  Also add a chance that you will be banned from posting memes if you post something bad. But you can get unbanned if you pay a fine or smth. 
And since these commands will be harder but more entertaining, why don’t you buff them?

**Comment by melmsie** [comment]
dont like these ideas
