### ISSUE TITLE
my trivia command doesnt work anymore. :(

### ISSUE THREAD

**Issue by KayleeAhh1** [DankMemer/dank-memer-suggestions-and-bugs#668]
everytime I try and use pls trivia it works but when I try and answer it it says error it's been happening for awhile its the only command I have a problem with.
![Screenshot_20200608-025954_Discord](https://user-images.githubusercontent.com/66589793/84002852-1511b980-a937-11ea-8f5a-198a2c585d1c.jpg)

( my id 719443109406048277 aka kaylee ahhh#2619)

**Comment by melmsie** [comment]
Is this still happening?
