### ISSUE TITLE
Idea For Fishing Commands

### ISSUE THREAD

**Issue by dddownnn** [DankMemer/dank-memer-suggestions-and-bugs#67]
**Is your feature request related to a problem? Please describe.**
No. It is a suggestion for the new fishing commands.

**Describe the solution you'd like**
I would like for there to be a way that you can cook fish and sell them for even more, like a 100 or 200 coin increase depending on the fish (normal fish for 200 cooked and rare fish for 600-700 cooked.) There should be a type of grill in the shop you can buy for 5,000 coins so it will be fair.

**Describe alternatives you've considered**
The fish cooking can take 30-1 hour depending on what fish and how many you want to cook at a time. When it is done it should alert you (@ you)

**Additional context**

**Comment by MooMooMooMooMooMooMoo2** [comment]
I like this idea!

**Comment by melmsie** [comment]
We've got more advanced plans for things that we're not willing to share at this time.
