### ISSUE TITLE
Spelling fault in rare pepe

### ISSUE THREAD

**Issue by Tiago9667** [DankMemer/dank-memer-suggestions-and-bugs#674]
There is a spelling fault in Rare Pepe shop, i have left a picture below.
Instead of the it says Thar.

Greetings,
EXCLUSIVE
![686ABE34-9497-4E5F-BACC-4C40129C7138](https://user-images.githubusercontent.com/47426842/84041332-feee1280-a9a3-11ea-88a7-314c4146f4f0.jpeg)

**Comment by melmsie** [comment]
pirate mode would like to have a word with you
