### ISSUE TITLE
The "Pls quest" command

### ISSUE THREAD

**Issue by LockSoulGT** [DankMemer/dank-memer-suggestions-and-bugs#680]
**Using the PLS QUESTS command**
Hey, I seem to have some problems with the pls quest command. Every time i use it, it always say:
oopsie poopsie
There was a problem with the quests command, if this happens for more than a few hours please join our server to report this error (https://discord.gg/meme)

I don't know what to do. My other friends can use the pls quests but I cant. Please help me. I need
answers as soon as possible. 
![pls quest](https://user-images.githubusercontent.com/66656211/84099749-86836200-aa34-11ea-9176-f78c9425bf44.PNG)

Thank you and i'll see your answers as soon as possible.
My discord Name and tag is LockSoul#0001

**Comment by oliverysfx** [comment]
discord id please, name and tag is useless

**Comment by LockSoulGT** [comment]
556816021345009689 discord id

**Comment by melmsie** [comment]
fix coming soon
