### ISSUE TITLE
My friend lost coins

### ISSUE THREAD

**Issue by hohannah** [DankMemer/dank-memer-suggestions-and-bugs#70]
**Describe the bug**
Well my friend bought a landmine but she didn't receive it but the bot took away her money.

**To Reproduce**

**Expected behavior**
Well she expected the landmine to be in her inventory

**Screenshots**
![image](https://user-images.githubusercontent.com/62786875/77816870-0c139900-70f9-11ea-8654-fd260b38ee68.png)
![image](https://user-images.githubusercontent.com/62786875/77816877-1766c480-70f9-11ea-8119-7f9b1d363687.png)
![image](https://user-images.githubusercontent.com/62786875/77816888-32393900-70f9-11ea-8884-f995f740e265.png)

**Additional context**

**Comment by melmsie** [comment]
Not only can I not reproduce this, but the bot doesn't even confirm they bought a landmine in that first screenshot.
