### ISSUE TITLE
Pls share doesn't work

### ISSUE THREAD

**Issue by detnecs** [DankMemer/dank-memer-suggestions-and-bugs#700]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) I'm @detnecs(KU5H) on discord

**Additional context**

**Comment by detnecs** [comment]
![Annotation 2020-06-11 111702](https://user-images.githubusercontent.com/66747554/84349847-cf265100-abd5-11ea-90cc-a7673ab857b5.jpg)

This has happened four times in my server...

**Comment by PhantomFrenzy151** [comment]
Oh yeah that's a problem.

**Comment by oliverysfx** [comment]
that is not an id though
