### ISSUE TITLE
Pls work shorter cooldown for Premium/Donators

### ISSUE THREAD

**Issue by BeastNation1234** [DankMemer/dank-memer-suggestions-and-bugs#701]
I think a good addition to premium/donator perks would be a shorter cooldown for pls work/pls job. Instead of the cooldown being an hour, it could be 30 or 45 minutes. 
This would help some of us who don’t have 8 hours a day to do some of the higher paying jobs.
 If implemented, premium servers should probably have this perk but that is a choice on your part.

**Comment by oliverysfx** [comment]
I mean all $10+ premium servers have all donator perks but the secret multi and pls redeem so
