### ISSUE TITLE
Pls Daily Streak Help

### ISSUE THREAD

**Issue by SmolBirdie** [DankMemer/dank-memer-suggestions-and-bugs#702]
I want to get the dragon and have been doing my pls dailys every day but the streak hasnt formed. 

**Expected behavior** 
The pls daily streaks appear 

I have no screenshots for it :’) sorry

**Your User ID**

503786223714697226

**Comment by oliverysfx** [comment]
miss the streak for a day first then start claiming again, it should be fixed
