### ISSUE TITLE
Slots

### ISSUE THREAD

**Issue by Kaiwaaii** [DankMemer/dank-memer-suggestions-and-bugs#704]
The Slots Game Feels Rigged . I lost all games in a row till i lost my 1 mil . Pls fix it. A lot of people quit the game because of it.
Just increase the chances of winning thats all.

**Comment by stefan5641** [comment]
Lol, u just mad cuz u lost ur coins gambling. There's a famous sentence which says "The house always wins" so I think this applies here too. If you don't have the cojones to lose don't play.

**Comment by oliverysfx** [comment]
ofc all the gambling games are rigged in house's favor, but if you know how to gamble, you still can win money
