### ISSUE TITLE
No fair distribution of coins in big heists

### ISSUE THREAD

**Issue by Anonymous1189** [DankMemer/dank-memer-suggestions-and-bugs#705]
**Describe the bug**
Im not sure if this is a bug, but the support server claims this is not the case and the winnings arw randomised for every person. 
Moreover, I've also noticed that the person who gets the most money is often the last person to join (the messages show up on different times on my screen but its possible dank memer just gets the command run at a very slight millisecond later making them the last)
![Screenshot_20200611-044206_Discord](https://user-images.githubusercontent.com/66759439/84335722-2c061500-ab9e-11ea-8274-b7d7366b132e.jpg)
![Screenshot_20200611-044223_Discord](https://user-images.githubusercontent.com/66759439/84335729-2f999c00-ab9e-11ea-9064-aebaf94a3c18.jpg)
![Screenshot_20200611-044233_Discord](https://user-images.githubusercontent.com/66759439/84335731-31635f80-ab9e-11ea-81cd-3078a529bd16.jpg)
![Screenshot_20200611-044243_Discord](https://user-images.githubusercontent.com/66759439/84335734-332d2300-ab9e-11ea-8d48-1dc85579ef97.jpg)
![Screenshot_20200611-044255_Discord](https://user-images.githubusercontent.com/66759439/84335738-34f6e680-ab9e-11ea-92de-111850a7dc17.jpg)
![Screenshot_20200611-044304_Discord](https://user-images.githubusercontent.com/66759439/84335741-36281380-ab9e-11ea-97a8-1103f59d8251.jpg)
![Screenshot_20200611-044321_Discord](https://user-images.githubusercontent.com/66759439/84335743-37f1d700-ab9e-11ea-8de8-3f3b2d808d62.jpg)
![Screenshot_20200611-044339_Discord](https://user-images.githubusercontent.com/66759439/84335747-39bb9a80-ab9e-11ea-9722-ee5e5cccadfb.jpg)

**To Reproduce**
1. Go to 'Any big dank memer server and join a heist (friendly ones mostly)'
2. Click on 'join heist'
3. Scroll down to 'too see the list of how much each person got.'

**Expected behavior**
Im not asking for every person to get exactly the same amount of coins. All Im saying is, it doesn't make sense when one person captures more than 90%(roughly) of the winnings in a heist. This just seems really unfair.
**Screenshots**

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed

**Additional context**

**Comment by PhantomFrenzy151** [comment]
(Not a mod.) This is not a bug. This is intentional. I believe there Melmsie on the support discord at some point made a vote where he asked if we wanted the winnings to be balanced, and I remember properly, people did. So maybe an update's coming?

**Comment by Anonymous1189** [comment]
Oh okay thanks for letting me know. I was just confused how something like this could have been overlooked for so long.

**Comment by oliverysfx** [comment]
this is intended
