### ISSUE TITLE
pls dank bug 

### ISSUE THREAD

**Issue by n0dm4c** [DankMemer/dank-memer-suggestions-and-bugs#706]
I used 'magik' on my profile photo and then set the magikal pic as my new profile photo then I tried to use 'pls dank' because I'm dank as fuck. However it gave me an error response saying, "HMMMMMM something isn't right with this command. Are you sure you used it correctly??" 
It gave this response until I pinged myself afterwards I was able to use the command without pinging myself.
![Screenshot_20200610-231400_Discord](https://user-images.githubusercontent.com/18689779/84344939-a79d9d00-ab71-11ea-8521-0727c2352141.jpg)

**Comment by oliverysfx** [comment]
this is not a command, are you suggesting to add it?

**Comment by DottySpam** [comment]
Pls dank is a command that already exists
How the command works: Pls dank (user that u wanna dank)

**Comment by n0dm4c** [comment]
sorry I forgot to include bug in the title

**Comment by n0dm4c** [comment]
I have revised the title to reflect that I was reporting a bug , I ask
support in the discord server and was redirected to here with no further
instructions other than a link. It was very helpful, that link, I knew
nothing of what I was supposed to do from there. So if I did not post it
correctly I do apologize!
