### ISSUE TITLE
A way to counter phones

### ISSUE THREAD

**Issue by MiloMurphyIsHere** [DankMemer/dank-memer-suggestions-and-bugs#709]
**Is your feature request related to a problem? Please describe.**
Bankrobs are getting harder to win. I am mostly heisting with my crew people and the targets, just call cops... like they are online 24/7 Its getting annoying...

**Describe the solution you'd like**
Add a new item:
Internet blocker
-You can put this item on someone to prevent them from using their phone was their „internet“ doesn’t work to do something with their phone.
-The internet gets hacked for around 3m 
-Item cost could be like, over 10k or lower.
**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by samdabloxyccola** [comment]
Its actually a good idea but take note people still can call for the police even without internet. Maybe have a device which removes the signal?
