### ISSUE TITLE
!hax command

### ISSUE THREAD

**Issue by HexCoder101** [DankMemer/dank-memer-suggestions-and-bugs#71]
So... i've been long thinking is it possible to make a hack command named: !hax
so that you need a hacker's laptop to hack and you might succeed might get caught from hacking and stuff like that. Also, a very little chance of a big target in there and you need to say a phrase on 5 secs to win a good amount and if you dont you have a little chance of you laptop breaking. (30% maybe?)

And these money aren't being hacked from real players though.

Thank you, if you do add it.

**Comment by melmsie** [comment]
not planning on this, have other things planned instead
