### ISSUE TITLE
Dank memer daily streak not working 

### ISSUE THREAD

**Issue by A12Bionic** [DankMemer/dank-memer-suggestions-and-bugs#710]
The bug says 0+ streak whenever i do pls daily, I didn't notice until my 3rd day of doing pls daily in a row

It just keep saying 0+ streak whenever i do pls daily

I couldn't find my pls daily screenshot since i did it on a public server but I am positive i did it yesterday and the day before.

my ID is 683052511678300165

I am trying to do the dragon quest thats why i'm so frustrated

**Comment by MrMcGreedy** [comment]
I am also having this exact same problem my ID is 442040511520309259

**Comment by samdabloxyccola** [comment]
Happened to a guy in my server. He was so close to getting a 7 daily streak for a dragon so when did "Pls daily", he was infuriated that it was a "0" daily streak.

**Comment by oliverysfx** [comment]
> Happened to a guy in my server. He was so close to getting a 7 daily streak for a dragon so when did "Pls daily", he was infuriated that it was a "0" daily streak.
> Note that he does "pls daily" every day

ask that guy to miss day, should fix it

**Comment by T04STy** [comment]
Same problem is happening to me, I've been trying to do the "Streaker" quest and trying to get a pet dragon. My ID is 580939222727393280
