### ISSUE TITLE
New Icon for Life Saver

### ISSUE THREAD

**Issue by V3NOM28** [DankMemer/dank-memer-suggestions-and-bugs#711]
A friend of mine "Abra#9562" designed a new icon of the Life Saver, I had noticed that icons designed by users other than the developers (pink phallic and pepe trophy) were introduced into the bot, I really liked this one so decided to forward it here:
https://media.discordapp.net/attachments/715022752515620896/720728230516228228/lifesaver.gif

**Comment by melmsie** [comment]
Looks neat, but not something we want at this time

**Comment by andrewisaboomer** [comment]
who even has friends ew
