### ISSUE TITLE
Robbing when someone wins after a heist

### ISSUE THREAD

**Issue by samdabloxyccola** [DankMemer/dank-memer-suggestions-and-bugs#713]
So there was once someone won a heist and got 32k from it. However, as he was about to try to rob the person who they attempted heisting immediately (He thought the heist failed initially) 
and deposit the cash (and withdraw later to share), someone was quick enough to rob him and take all of his cash from his wallet. However, I think that users who win a heist and get the heist money will have the immunity of 5 minutes against robbing, so that means the player will not get robbed for 5 minutes after he wins a heist and gets the money.
Screenshots:
![image](https://user-images.githubusercontent.com/66548007/84459867-07dc2e00-ac9b-11ea-8c14-60317c1f0810.png)

![image](https://user-images.githubusercontent.com/66548007/84459901-1c202b00-ac9b-11ea-9d7b-bbfbd11535f3.png)

**Comment by samdabloxyccola** [comment]
It was edited due to the guy's perspective. I copied and pasted what he said down here. I apologise bout that (he's my best friend)

**Comment by oliverysfx** [comment]
again, free passive

**Comment by samdabloxyccola** [comment]
well, he I asked him, he said he recently exited passive mode a few hours ago
