### ISSUE TITLE
Robbing someone while he is blackjacking

### ISSUE THREAD

**Issue by samdabloxyccola** [DankMemer/dank-memer-suggestions-and-bugs#714]
It is pretty annoying that when I blackjack a high amount, someone comes and robs me of my money
Here is a screenshot of what happened 
![image](https://user-images.githubusercontent.com/66548007/84458768-5b994800-ac98-11ea-83be-fb1b4eac9a2b.png)
So, I suggest that whenever someone is blackjacking, the user cannot be robbed. Also, when more than 6000 coins is won, the user will be given 1 minute to deposit his cash (1 min immunity from robbing), to prevent a risk of getting robbed of such a high amount.

**Comment by oliverysfx** [comment]
hey, that's free passive, people can just bj 100 all the time and not be robbed and not lose a shit ton of stuff

**Comment by samdabloxyccola** [comment]
well I was not on passive cuz I wanted to heist people
