### ISSUE TITLE
picking up lost coins after dying

### ISSUE THREAD

**Issue by TheOneAboveAll42069** [DankMemer/dank-memer-suggestions-and-bugs#716]
**Is your feature request related to a problem? Please describe.**
no it is not related to a problem

**Describe the solution you'd like**
i want to suggest the addition of a "pick up lost coins" mechanic

**Describe alternatives you've considered**
After you die, you lose the coins in your pocket. there should be a feature in which you can risk your life again and retrieve some of that money but there is a 50% chance you die once again

**Additional context**
i just suggested this because i have been killed by a dragon multiple times and it was some technical issue at my end so i lost more than 200k to it. i hope you consider adding this mechanic

**Comment by oliverysfx** [comment]
just get a freaking life saver

**Comment by oliverysfx** [comment]
now close this issue because it's stupid

**Comment by DottySpam** [comment]
> just get a freaking life saver

i agree lmao
