### ISSUE TITLE
Feature/Bug Issue: selling multiple common fish

### ISSUE THREAD

**Issue by digitalsierra1** [DankMemer/dank-memer-suggestions-and-bugs#718]
I have many Common Fish in my inventory.  I would like to sell them all at once.
When I sell other items like 'pls sell deer max', that works and sells all my deer.
However, it looks like the space between 'common' and 'fish' prevents me from using the max switch.
'pls sell common fish max' only sells one common fish

For your consideration.
Thank you.

**Comment by melmsie** [comment]
`pls sell common max`
