### ISSUE TITLE
Username Bug

### ISSUE THREAD

**Issue by MortalSkies** [DankMemer/dank-memer-suggestions-and-bugs#719]
**Describe the bug**
My name on dank memer changed to "A Stupid person" and it won't change back when I change my username. 

**To Reproduce**
1. I did pls bal/pls rich.
4. My name was "A Stupid Person"

**Expected behavior**
When I changed my username to Mortal Skies, I expected to se "Mortal Skies" when pls bal or pls rich was typed in. Instead, it was still, "A Stupid Person".

**Screenshots**
**Your User ID**
(Mortal Skies#6026) (https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed

**Additional context**

**Comment by melmsie** [comment]
NAB

**Comment by MortalSkies** [comment]
I need help please.
