### ISSUE TITLE
Username on Discord Dank Memes

### ISSUE THREAD

**Issue by MortalSkies** [DankMemer/dank-memer-suggestions-and-bugs#720]
Describe the bug
My name on dank memer changed to "A Stupid person" and it won't change back when I change my username.

To Reproduce

I did pls bal/pls rich.
My name was "A Stupid Person"
Expected behavior
When I changed my username to Mortal Skies, I expected to se "Mortal Skies" when pls bal or pls rich was typed in. Instead, it was still, "A Stupid Person".

Screenshots
Your User ID
(Mortal Skies#6026) (https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed

**Comment by oliverysfx** [comment]
that is not an id 🤦
