### ISSUE TITLE
Stonks market

### ISSUE THREAD

**Issue by wolf653** [DankMemer/dank-memer-suggestions-and-bugs#721]
Some people like to stockpile fish or hunt results *mainly to get the satisfaction of getting over 1k for common fish* but what if there was an opposite of the lightning sale aka the stonks market that will effectively boost the price of items outside of the store by a maximum of 50% this would give a reason to stockpile items instead of selling them straight away.

**Comment by oliverysfx** [comment]
there's already a reason to collect, that's because fishes are collectable, you can't get them from anywhere but fishing and trading

**Comment by wolf653** [comment]
> there's already a reason to collect, that's because fishes are collectable, you can't get them from anywhere but fishing and trading

So by that logic i should buy a bunch of dildos and then sell them for profit?

**Comment by oliverysfx** [comment]
pink phallic objects aren't really collectables, the read definition of collectables is unpurchasable yet acquireable items

**Comment by wolf653** [comment]
> pink phallic objects aren't really collectables, the read definition of collectables is unpurchasable yet acquireable items

Ok is there a reason to stockpile fish and hunt results other then satisfaction from getting 1k from common fish?

**Comment by oliverysfx** [comment]
nope
