### ISSUE TITLE
Incorrect Coin deposit

### ISSUE THREAD

**Issue by MasterHeap** [DankMemer/dank-memer-suggestions-and-bugs#723]
**Describe the bug**
When depositing my coins into the bank I noticed the bug. My balance was at 137, 082 coins out of 137, 832 space. I deposited 850 coins. This means I should've been at 137, 932 coins instead of the max balance I could hold. This struck me as odd so I checked by balance again and saw that 750 coins when into the bank but I was charged 850. Now 100 coins is almost nothing but what if it reproduced on a massive scale.

**To Reproduce**
1. Type 'pls bal'
2. Note 'start balance'
3. Type  'pls dep all'
4. Note 'amount deposited'
5. Type 'pls bal
6. Note 'New balance'
7. Do the Math
8. See error

**Expected behavior**
I expected only 750 coins to be deposited

**Screenshots**
![Math = wrong](https://user-images.githubusercontent.com/66858967/84559706-a8196d80-ad02-11ea-8e84-13c973cd84b7.PNG)

**Your User ID**
MasterHeap#7777

**Additional context**
Incident occurred from 2255 (10:55 p.m) to 2256 (10:56 p.m) central standard time on 12 June 2020. Please contact me in the Dank Memer Discord if issue was resolved.

**Comment by oliverysfx** [comment]
first things first, that is not a fucking id
