### ISSUE TITLE
show time left before being able to share/gift for new accounts

### ISSUE THREAD

**Issue by oliverysfx** [DankMemer/dank-memer-suggestions-and-bugs#727]
**Is your feature request related to a problem? Please describe.**
it's annoying when you forget how long it's been since you first used a dank memer command and how long do you need to wait

**Describe the solution you'd like**
show time remaining when new accounts do share/gift to they can use it.

**Describe alternatives you've considered**
the time could also be left on pls profile

**Additional context**
my friend just started using dank memer and wants to make a deal from me but they can't because just started

**Comment by melmsie** [comment]
not just time based

**Comment by oliverysfx** [comment]
oh ok
