### ISSUE TITLE
kennel idk

### ISSUE THREAD

**Issue by andrewisaboomer** [DankMemer/dank-memer-suggestions-and-bugs#729]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when if you go on a vacation or smth u get screwed over by ur pet eating you or smth
**Describe the solution you'd like**
add a kennel that puts ur pet in purgatory
basically it wont be able to defend wallet and wont get xp
**Describe alternatives you've considered**
no idea im not that smart ok
asking me to think is too hard
**Additional context**
nope

**Comment by andrewisaboomer** [comment]
dont close i pressed enter by accident im gonna edit it to say what i want

**Comment by loser7007** [comment]
lol I like ur idea but I think the chances of it being in the game would be increased if u weren't so idk all the time u know, lol but what do I know?
