### ISSUE TITLE
Tell people the word for missing letter minigame when they fail

### ISSUE THREAD

**Issue by inooby333** [DankMemer/dank-memer-suggestions-and-bugs#732]
**Is your feature request related to a problem? Please describe.**
Its annoying when you can't get a word right and you have to ask like 50 people what that word is so you can get it right next time.

**Describe the solution you'd like**
After someone fails to guess a word right, the bot would tell you what that word was

**Describe alternatives you've considered**
People would normally just ask staff for the word but that's impractical and creates unnecessary spam. Another feature I would like to suggest is to pay coins to unlock more letters though that may be a bad idea for some things like jobs.

**Additional context**
N/A

**Comment by DankMemerFan** [comment]
and the unscramble word ones too please
