### ISSUE TITLE
Multipliers

### ISSUE THREAD

**Issue by DankMemerFan** [DankMemer/dank-memer-suggestions-and-bugs#733]
**Is your feature request related to a problem? Please describe.**
It is sometimes a bit bothersome when I want to know what multipliers give how much, but can't

**Describe the solution you'd like**
each multipliers' percentage next to the multiplier itself in `pls multi`

**Describe alternatives you've considered**
instead maybe you could do `pls multi {multiplier}` to see what each multiplier does and what's needed to unlock it

**Additional context**
I imagine it would look something like this
![acd8d8ef7878296a147259ecbdb1a7ca](https://user-images.githubusercontent.com/65544334/84593948-53373d80-ae4f-11ea-9b9d-c50c194eac66.png)

**Comment by loser7007** [comment]
they want multis to be secret tho

**Comment by DankMemerFan** [comment]
it'll only show the multipliers you currently have active
