### ISSUE TITLE
Way to see the hours you have worked that day.

### ISSUE THREAD

**Issue by JustSomeoneOnGithub** [DankMemer/dank-memer-suggestions-and-bugs#734]
**Describe the solution you'd like**
An easy and simple command, to check the hours you have done in the past day.

**Describe alternatives you've considered**
The only way I have counted my hours was using a .txt file, which is a bit of a pain to put in the hour, multiple times.

**Additional context**
The days counted will obviously be different because of timezones, so the "days" is counted in the EST timezone.

**Comment by loser7007** [comment]
pls work info gives u a bit on info but idk why us want to see all the hours uve worked
