### ISSUE TITLE
Block Feature for the phone

### ISSUE THREAD

**Issue by wolf653** [DankMemer/dank-memer-suggestions-and-bugs#740]
So the phone can be used in a big brain move to contact those who blocked you and have DM notifications. I'm actually surprised that this isn't a feature so in short summary you can block users on the phone by responding with *insert letter here* and then inputting their ID within 30 seconds upon that user attempting to text the person that blocked them A notification won't be sent and they will get a message regarding it
**[blocker] has unfortunately not responded due to blocking you!**
this is just an example of what the notification could be
of course you can execute the block feature on the same person again to unblock them

**Comment by oliverysfx** [comment]
eh making the feature on phone would be weird, add a setting instead

**Comment by DankMemerFan** [comment]
like `pls block {User}`
