### ISSUE TITLE
daily work hours

### ISSUE THREAD

**Issue by DankPancake** [DankMemer/dank-memer-suggestions-and-bugs#744]
whenever I type "pls job info" it says ive completed an absurd amount of daily hours

im not sure if it happens to everyone, but type "pls job info" and then it should just do it

**Expected behavior**

screenshot: https://user-images.githubusercontent.com/66970790/84698065-2f422d80-af1d-11ea-8744-48d280a11749.png
as you can see, it says I worked 81 hours today

my ID is 405178988919521284

**Comment by melmsie** [comment]
Not worth fixing until the rewrite
