### ISSUE TITLE
"pls dig" request

### ISSUE THREAD

**Issue by Crezzo** [DankMemer/dank-memer-suggestions-and-bugs#745]
I have always been a little frustrated of how little the commands are to gain coins in a safe way. So, I would like to suggest you to make a new way which is "pls dig".

It works by buying a shovel for 15K, or a jackhammer for a little bit more expensive (which increases the luck). By buying the shovel or jackhammer, you'll have access to the command "pls dig". You could put different varieties of stones, some are expensive, while some are worthless.

I hope you consider to make this new feature because pls scout, pls beg, pls fish, and pls hunt are way too little for people to gain coins, thank you for reading.

**Comment by oliverysfx** [comment]
Just gamble ur life savings if you know how, it's not that hard

**Comment by samdabloxyccola** [comment]
its a nice idea tbh
