### ISSUE TITLE
Sand Box Time overestimate

### ISSUE THREAD

**Issue by SonicofProdigy** [DankMemer/dank-memer-suggestions-and-bugs#746]
**Describe the bug**
Whenever you use the box of sand, it says the affected user can't steal for 2 hours but instead justs does it for 30 minutes.

**To Reproduce**
1. Buy a box of sand (if you haven't already)
2. Do pls use box of sand 
3. put "y"
4. enter a user name
5. It should hit the user or yourself and only prevents you from robbing for 30 minutes

**Expected behavior**
Should say it would be 30 minutes 

**Result**
Says 2 hours and overestimates the time

**Comment by alexmehta** [comment]
yes this is so annoying

**Comment by samdabloxyccola** [comment]
yes, and when we try to rethrow sand on the same person, bot no allow us to do so

**Comment by melmsie** [comment]
fixed next update
