### ISSUE TITLE
NSFW 

### ISSUE THREAD

**Issue by Yuahman** [DankMemer/dank-memer-suggestions-and-bugs#747]
I am unsatisfied with the LGBT+ selection in the NSFW specifically (Gay). There is a lot of Lesbian pictures, but only one command for gay p*rn . So when I bought the donor's pass I was not happy because this was (specifically) the only reason I bought the donor's pass. 

I would like if you could add some more (Younger) men pictures added I found it was a lot of old men, also would be nice if there could be added commands, ex. pls c*cks (shows a picture of a cock), another one 'pls bulge' (shows a picture of a mans bulge). I would love for these considerations to be taken into account :) 

There are no other bot's that work nearly as good as the Pepe bot, nor are as versatile as this one.

I feel like this could be in the best interest for you guys as a company view, because you may have a more open product for everyone.

**Comment by melmsie** [comment]
We don't control the NSFW, it's someone else's API.
