### ISSUE TITLE
chat event no rewards

### ISSUE THREAD

**Issue by rockketing** [DankMemer/dank-memer-suggestions-and-bugs#748]
**Describe the bug**
When there is an event in the chat, I do not receive any rewards for participating in the event or answering first, etc...
**To Reproduce**
Wait for a chat event, then do as the event requires
**Expected behavior**
The event will close or only give rewards to others who participated. It seems to be only my account.
**Screenshots**
![image](https://user-images.githubusercontent.com/66991339/84740757-510ce480-aff1-11ea-92fd-4ee73b810a8a.png)

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed
413583883515330562
**Additional context**
I've been blacklisted a while ago for spamming pls work, it might be related to this

**Comment by samdabloxyccola** [comment]
Its either because you copied and pasted (which doesn't count for some reason) or event alr expired

**Comment by rockketing** [comment]
no i think it’s something to do with me being blacklisted before. It happens with every event
