### ISSUE TITLE
Passive timer resetting if you accidentally do pls settings passive false while not in passive

### ISSUE THREAD

**Issue by Spectator0920** [DankMemer/dank-memer-suggestions-and-bugs#749]
**Describe the bug**
The passive timer, aka 24 hours before turning passive back on, resets if you run the passive false command

**To Reproduce**
1. Do: pls settings passive false
2. Wait
3. do pls settings passive false again
4. Observe timer

**Expected behavior**
It should not do this in my opinion

**Your User ID**
501234396012085256

**Comment by oliverysfx** [comment]
Duplicate

**Comment by Spectator0920** [comment]
> Duplicate

Where is the first one? I looked through and did not find one?
