### ISSUE TITLE
A pickaxe in the shop

### ISSUE THREAD

**Issue by StraightGamin** [DankMemer/dank-memer-suggestions-and-bugs#75]
**Is your feature request related to a problem? Please describe.**
No, but it can provide one more source of money to the user's.
**Describe the solution you'd like**
You can buy the pickaxe for a certain amount of money like 20,000 or something and then when you time pls mine. When you mine there is a percentage of getting different ores that are worth different amounts. For example: Gold, Diamond, Iron, (Memeite which can be rare).
**Describe alternatives you've considered**
No alternatives.
**Additional context**
No context.

**Comment by melmsie** [comment]
Check the trello before taking the time to type stuff up https://trello.com/c/08NTVIay/36-mining-command-and-items
