### ISSUE TITLE
a suggestion for a new command

### ISSUE THREAD

**Issue by Tsoishinghei0501** [DankMemer/dank-memer-suggestions-and-bugs#751]
**Is your feature request related to a problem? Please describe.**
no its not

**Describe the solution you'd like**
add pls yeet @person
**Describe alternatives you've considered**
or pls throw @person

**Additional context**

**Comment by oliverysfx** [comment]
What is this command supposed to do, elaborate

**Comment by Tsoishinghei0501** [comment]
it will do the lion king yeet but in the hands it the profile pic of @person
