### ISSUE TITLE
Inability to redo a quest like Chronic Gambler

### ISSUE THREAD

**Issue by deathskull728** [DankMemer/dank-memer-suggestions-and-bugs#754]
It's pretty clear in the title, I'm not able to redo quests, it always says you have to wait 0 seconds, as shown in the picture:
![dm bug](https://user-images.githubusercontent.com/66839991/84767091-7b5da280-afef-11ea-852b-cd350ceb46bf.png)
Please have this bug fixed, I really want to do the quest again!

**Comment by PhantomFrenzy151** [comment]
you can't redo quests. This is intentional. Notice how in the quest list you can see they are crossed out.

**Comment by deathskull728** [comment]
ok, thanks!
