### ISSUE TITLE
Dying glitch in server 

### ISSUE THREAD

**Issue by TanyaTachibana** [DankMemer/dank-memer-suggestions-and-bugs#755]
Dank memer bot repeatedly kills my account without reasoning and doesn't notify me via the DM notifications despite them being turned on. Only when "pls notifs" command is used in server am I able to see notifications

**Your User ID**
657548102814793746

**Comment by samdabloxyccola** [comment]
It either shows you that you lost stuff or a life saver has been used

**Comment by TanyaTachibana** [comment]
> It either shows you that you lost stuff or a life saver has been used

The thing is, it doesn't send me anything

**Comment by samdabloxyccola** [comment]
f

**Comment by chegde01** [comment]
If you can see notifications from pls notifs then you prolly don't have DM notifs enabled correctly
