### ISSUE TITLE
NSFW

### ISSUE THREAD

**Issue by Markus2809** [DankMemer/dank-memer-suggestions-and-bugs#758]
Either remove NSFW completly or make it so you need to verify you are 18+ before you can use the command and add pls dick.

**Comment by oliverysfx** [comment]
Verifying will require quite some private info that even discord doesn't ask for so this is bad

**Comment by Yuahman** [comment]
That's a breach of personal information that could get leaked very easily if there is someone sketchy working, as well with over 40k servers with the bot it would be impossible to even ID everyone

I agree w/ the command u want added too

**Comment by melmsie** [comment]
@Markus2809 NSFW is only allowed to be used in NSFW marked channels, which you agree to being 18 to enter.
