### ISSUE TITLE
Add a stock market system.

### ISSUE THREAD

**Issue by Maxmoney11** [DankMemer/dank-memer-suggestions-and-bugs#759]
Sometimes I just run out of ways to make money and used all of the commands available, so I just have to wait for all the cooldown timer to finish. It is also a bit repetitive using the same commands over and over again.

Add a stock market to the currency system, so we can invest money, buy shares, and earn money over time. This could add more fun to the system and maybe learn people about stocks and shares.

**Comment by oliverysfx** [comment]
Dude there's pls gamble and pls slots
