### ISSUE TITLE
Passive mode

### ISSUE THREAD

**Issue by jeddfadhley** [DankMemer/dank-memer-suggestions-and-bugs#76]
Is there a way to turn passive mode off?
In my server no one wants people using passive mode as it ruins the fun for everyone but people just abuse it for long periods of time.
I was wondering is there a way to turn it off?

**Comment by smallbranboi** [comment]
There is do pls settings passive disable.

**Comment by Iwitrag** [comment]
As far as I know you cannot disable passive on your server... 

People would just activate on other server... dank memer is cross-server bot.

So all you can get is to put it to rules... whoever have passive on, he will be banned from channel.
