### ISSUE TITLE
Blackjack glitch

### ISSUE THREAD

**Issue by superips200** [DankMemer/dank-memer-suggestions-and-bugs#760]
So if i have 4000 i blackjack 4000 i half way on a blackjack match i got rob like a shit ton i will have negative 2000 because the bot thinks i trying to scam the bot but i have a suggestion to the ploblem , to not have any money during the blackjack after you win you get the the money you won or loss after gamble
![Screenshot_20200614-190431_Discord](https://user-images.githubusercontent.com/67016728/84803734-f6957780-b034-11ea-8831-754106fe4caa.jpg)
![Screenshot_20200614-190512_Discord](https://user-images.githubusercontent.com/67016728/84803742-f85f3b00-b034-11ea-84eb-9d6fec45ad54.jpg)
![Screenshot_20200614-190521_Discord](https://user-images.githubusercontent.com/67016728/84803747-f9906800-b034-11ea-8d5c-b6c9b8039b8a.jpg)

**Comment by oliverysfx** [comment]
This is more like a suggestion than a bug
