### ISSUE TITLE
Scammer Problem And, Maybe Solution

### ISSUE THREAD

**Issue by ninjajsjk** [DankMemer/dank-memer-suggestions-and-bugs#761]
So, my friend said that there was a server that disable rob and then when people don't know they enable it and steal then, they disable it so, can you make disableing rob and bankrob only once in 24h also here was the message for proof, 
"https://discord.gg/4cFgbX3
^^ dont join, owners disable and enable rob, tricks players". Thanks for such a good bot.

-NinjaJSJK#5067

**Comment by ninjajsjk** [comment]
Also sorry for not having the template i'm new to this.

**Comment by oliverysfx** [comment]
There's nothing the devs can do about this, and the solution will make servers that often do friendly heists not work, so this is bad
