### ISSUE TITLE
Allow bots limited access to commands

### ISSUE THREAD

**Issue by Pandapip1** [DankMemer/dank-memer-suggestions-and-bugs#764]
**Is your feature request related to a problem? Please describe.**
Sort of. I'd really like it if bots could be used as places to store stuff, such as for trading. Right now bots cannot use any currency or inventory commands, or so I've heard.

**Describe the solution you'd like**
The solution I would like would be a whitelist of allowed commands that bots could use, such as pls inv, pls use (maybe), and pls share. Things like pets, jobs, hunting, and stealing could be disabled for bots.

**Describe alternatives you've considered**
Failing that, a simple REST bot API would also be useful.

**Additional context**
I tried to create an automatic trading bot for dank memer, not realizing that bots cannot use commands, but stopped when a friend told me that it couldn't be done. This kind of thing could be a nice feature.

**Comment by oliverysfx** [comment]
Eh that literally make bots free alts

**Comment by Pandapip1** [comment]
They're free alts in the sense that they have an inventory/purse and can send and receive coins/items, but can't use other currency-related commands like pls work and pls beg.

Here is my proposed whitelist:
- pls bal
- pls buy / pls sell
- pls gift
- pls inv
- pls multiplier
- pls profile
- pls rich
- pls use / pls remove
- pls dep / pls with

at the very least, pls profile, pls inv, pls bal, pls rich should be whitelisted.

**Comment by oliverysfx** [comment]
I would suggest pls shop to be whitelisted as well

**Comment by oliverysfx** [comment]
so that people can know which item is on sale

**Comment by Pandapip1** [comment]
Agreed.
