### ISSUE TITLE
Protec levels reset to 0 when another person fights you

### ISSUE THREAD

**Issue by smallbranboi** [DankMemer/dank-memer-suggestions-and-bugs#77]
**Describe the bug**
You get your protec reset to 0 if 2 people fight you when in one of them, you have protec levels.

**To Reproduce**
1. Do pls fight
2. Defend to increase protec level
3. Have someone else fight you
4. In both fights, your protec is now 0.

**Expected behavior**
You lose protec level in both fights, tough you can still add protec levels after the reset.

**Possible reason for bug**
The setprotec=0 trigger is either at the begginning or end of a fight. Thus the 2nd fight sets the 1st fight's protect to 0.

**Possible Solution to solve the bug if the above reason for bug is true**
Place the protect count for the INDIVIDUAL FIGHTS,not the PLAYER.

**Additional context**
N/A

P.S. will check which of the 2 cases it is and will report back. Doesn't change anything, but I might edit this post

**Comment by melmsie** [comment]
fight inherently has a lot of bugs, and will be improved in the distant future
