### ISSUE TITLE
pls kill yourself

### ISSUE THREAD

**Issue by TheCreatorofPenguins** [DankMemer/dank-memer-suggestions-and-bugs#770]
I know this can be done by typing “pls kill @dank memer” but typing “pls kys” or “pls kill yourself“ .... instead of saying “please mention someone next time” it would be funny if the bot left the room for a while or refused to do commands for that person for a while ?
the bot could “kill itself” like it would do if you typed “pls kill @dank memer” but with a little added twist?

The idea came to my group of friends when someone said “pls kys” as a joke to someone and dank memer told us to mention someone.

**Comment by melmsie** [comment]
that breaks discord tos
