### ISSUE TITLE
Daily streak not going past 1

### ISSUE THREAD

**Issue by sirdutton** [DankMemer/dank-memer-suggestions-and-bugs#772]
My daily streak is stuck at 1 for some reason. I've gone back in the chat logs and I've done it consistently since 6/13 so I should at least be on day 5. It wouldn't be a big deal but I was trying to turn the dragon into a pet.

My user id is 477840961657897029

**Comment by oliverysfx** [comment]
Miss a day first

**Comment by sirdutton** [comment]
I missed a day and the bot still shows 1 day streak for me for some reason
