### ISSUE TITLE
Dm lottery joins

### ISSUE THREAD

**Issue by MiloMurphy** [DankMemer/dank-memer-suggestions-and-bugs#774]
**Is your feature request related to a problem? Please describe.**
When I use autolottery, I always think I didnt enter. I almost think Autolottery does not work.

**Describe the solution you'd like**
Add a setting like: **pls settings lotteryjoins yes** which will now always tell you if you joined the lottery via notifications.

**Describe alternatives you've considered**
Maybe dank memer will ping you if you entered the lottery and you have Autolottery on.

**Additional context**
None.

**Comment by RandomTurtleBoi** [comment]
autolottery works, you can just check the coins in your bank a few hours apart from each other
