### ISSUE TITLE
Add businesses that will cost 100k so u earn money without using cmds

### ISSUE THREAD

**Issue by Pavelslavoo** [DankMemer/dank-memer-suggestions-and-bugs#778]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oliverysfx** [comment]
will you give more details on this, you can't expect the devs to work on this when they are working on the rewrite and have no idea how this is supposed to work
