### ISSUE TITLE
Double working bug

### ISSUE THREAD

**Issue by Goofierknot5537** [DankMemer/dank-memer-suggestions-and-bugs#78]
**Describe the bug**
This only works when the bot slows down, or has a “lag spike”. I was doing pls work, and it didn’t work, so I did it again, as it usually works. The bot proceeded to make me do two things at once, one I failed at and the other I didn’t. 

**To Reproduce**
1. Do “pls work”
2. Bot must be in this “lag spike”
3. Do “pls work” again.

**Expected behavior**
For the bot to show me the puzzle once, not two at the same time.

**Screenshots**
Can’t put screen shot in here or else it will reveal my real name :( but I do have the screenshot on my iPad so I can dm it

**Additional context**
It could’ve been something about my internet, but I’m not so sure about it.

**Comment by melmsie** [comment]
Known bug
