### ISSUE TITLE
cant buy apples

### ISSUE THREAD

**Issue by loser7007** [DankMemer/dank-memer-suggestions-and-bugs#785]
**Describe the bug**
some people cant buy the new apples
**To Reproduce**
do pls buy apple
then it doesn't let you buy one

**Expected behavior**
the apple goes into your inventory 

**Screenshots**
![image](https://user-images.githubusercontent.com/64291781/85086845-d509cc80-b1a9-11ea-9787-e023325bd33e.png)
![image](https://user-images.githubusercontent.com/64291781/85086858-de933480-b1a9-11ea-8abe-8b96766249ed.png)
![image](https://user-images.githubusercontent.com/64291781/85086874-ea7ef680-b1a9-11ea-9b2b-5caaa340c97e.png)
![image](https://user-images.githubusercontent.com/64291781/85086894-f66ab880-b1a9-11ea-9e41-8d1c16ea6642.png)

**Comment by loser7007** [comment]
hm, I just tried to buy one in the official server and it worked... I have no idea why the server I was in has all of the dank memer multipliers though I don't know if that means anything. all of the screenshots were taken from people in that server. here is the server link if you want to check it out [https://discord.gg/ZpfA3Fb](https://discord.gg/ZpfA3Fb) :/

**Comment by melmsie** [comment]
"if this happens for more than a few hours"

let me know if it's happening after a few hours still as instructed.
