### ISSUE TITLE
Blackjack aces dont turn into 1 when busting

### ISSUE THREAD

**Issue by Xiyangyang1026** [DankMemer/dank-memer-suggestions-and-bugs#787]
I started the game with 2 aces and busted with a 22 even though it should've defaulted to a 12
![image](https://user-images.githubusercontent.com/32981461/85088686-b528d780-b1ae-11ea-82f5-4a0786a59f71.png)

**Comment by yeetusdeletusurchungusisafungus** [comment]
In blackjack, two aces always add up to 12. This isn't a bug; it was intentionally put in because that's how the rules of blackjack work.
