### ISSUE TITLE
Investments, 401Ks and Stocks

### ISSUE THREAD

**Issue by DudeManGuy0** [DankMemer/dank-memer-suggestions-and-bugs#794]
Currently in the Dank Memer Discord bot, the only ways to earn money in a proportional rate to your total balance is by gambling. Basically, the money you earn through all other means is consistent but gambling gets you rewards that are related to how much money you have. I was thinking a safer option could be implemented like investing where you can for example put in money into a savings account and have it grow by 2% every day.

This system can allow for many fun ways to play around with the currency in the game. I was thinking the creator could create a simulated stock market with numbers and statistics from the real world updating every 5 minutes or so where a player can buy a stock and sell it to the bot. This would obviously take a lot of effort but it would change the dynamics and fun of the currency system drastically.

We don't have to start with something like this though. The creator can introduce a simple system like a 401k or putting money into different kinds of banks that yield different return rates the further up you go. The ideas branching off of this are endless and have massive potential for the bot. Just think of how cool it would be to be able to trade stocks in real time or to put millions into a savings account and have it grow.

I think this should be implemented because:
1. It's cool
and 2. The only way currently to earn money proportional to how much you already have is gambling. This would provide something different to gambling and a strategic way of building income.

Most of the success of this will rely on the execution. The 401K and savings accounts wont be hard to implement but stocks will need hard work and polish. It should provide an option to look up any stock/currency to buy and bring up a panel with a graph of its history among much other information. A bit like how Google displays stocks and currencies.

I think the first step to implementing some form of investments should be banks and saving accounts. Here is a list of possible ideas:
 - Stocks updating in real time, tradeable for virtual currency, based off the real stock market
 - Savings accounts, maybe have a way to achieve better ones as you go like buying them and waiting for them to make a return on investment, a simple savings account also works
 - 401K

A good first idea is a item you would need to buy which would allow you making a certain % of what you put in back.

**Comment by JustSomeoneOnGithub** [comment]
This is wake a lot of people rich, and will probably make a lot of people use alts, which is against Dank Memer rules.

**Comment by melmsie** [comment]
for the 500th time, no
