### ISSUE TITLE
Can give money and items to Bots

### ISSUE THREAD

**Issue by JustSomeoneOnGithub** [DankMemer/dank-memer-suggestions-and-bugs#795]
**Describe the bug**
Basically you can give coins and items to bot.

**To Reproduce**
`pls gift 1 cookie @[bot]` - Gives bot cookie.
`pls give @[bot] 1` - Give bot one coin.

**Expected behavior**
Not give the items/coins.

**Screenshots**
https://i.imgur.com/9V5Qe36.jpg

**Additional context**
Not too big of a problem, I just wanted to point out that this is possible.

**Comment by melmsie** [comment]
its not a bug lol
