### ISSUE TITLE
Copypaste for events/etc

### ISSUE THREAD

**Issue by Uchla** [DankMemer/dank-memer-suggestions-and-bugs#797]
**Describe the bug**
When you copy paste something, at least on mobile, and comment it so for the needed procedure, the bot responds as if you commented the wrong text
**To Reproduce**
1. Go to ''

**Screenshots**
![Screenshot_20200619-081040_Discord](https://user-images.githubusercontent.com/67160014/85151418-9ce5a680-b208-11ea-848b-41d389962f24.jpg)

**Your user ID**
545040740909187084

**Additional context**
I am not the user in the screenshot, but we are on the same server

**Comment by Anonymous1189** [comment]
P.S- not a mod.
This is intentional.
The bot has a way of detecting copy waste. You're meant to type it on your own.
