### ISSUE TITLE
Auto add padlock

### ISSUE THREAD

**Issue by ddong15** [DankMemer/dank-memer-suggestions-and-bugs#8]
Make a setting so that you can automatically add a padlock whenever one is removed, given a certain amount of money is in your bank (like the lottery setting). You can make it so that you have to prebuy the padlocks or if theres money they can automatically buy it from the shop. To penalize people for doing this you could also make the price to buy a padlock higher than the regular price. This would help prevent stealing for rich people.

**Comment by melmsie** [comment]
This will not happen
