### ISSUE TITLE
Tidepod - you lost all money, but I had lifesaver

### ISSUE THREAD

**Issue by Iwitrag** [DankMemer/dank-memer-suggestions-and-bugs#80]
**Describe the bug**
I have used tidepod and died - and dank memer said that I lost all coins. But I did not lose any coins because of lifesaver, but I was pretty scared when that happened.

**Comment by melmsie** [comment]
This is because it killed you, the "lost all your money" isn't dynamic and doesn't check for a lifesaver. Not really worth our time fixing

**Comment by Iwitrag** [comment]
This comment took more time that would take fixing that.

**Comment by melmsie** [comment]
Then go ahead and leave a PR to fix it. 

Wait it's closed source and you have no clue what it would take to "fix" it? Huh, weird.

**Comment by Iwitrag** [comment]
I'm a dev, but yep, PRs are difficult with closed source lmao.

**Comment by melmsie** [comment]
You being a dev has no bearing on what our source code looks like for currency and whether this is something worth spending time on rather than things that actually matter.

**Comment by Iwitrag** [comment]
I agree, but I'm pretty sure that chaning one String is not something very time-consuming.
