### ISSUE TITLE
Lootboxes have undefined in the place of their icon 

### ISSUE THREAD

**Issue by mjshein** [DankMemer/dank-memer-suggestions-and-bugs#800]
**Describe the bug**
Lootboxes have undefined in the place of their icon 

**To Reproduce**
pls shop <normie|dank|god|meme>

**Expected behavior**
an icon

**Screenshots**
[screenshot here](http://blurple.is.better.than.blue/yay/b363048c8A.png)

**Comment by melmsie** [comment]
isn't a bug, has literally always been like this. They don't have icons, nor have they ever.
