### ISSUE TITLE
Auction

### ISSUE THREAD

**Issue by NepaGrim** [DankMemer/dank-memer-suggestions-and-bugs#801]
I believe it would be very interesting if there was an auctioning system, or a command that allows players to auction item to their server or all servers. The command could be "pls auction [item] [price]" or something similar. Players would bet the current price or a higher price within the allotted time. So there's no last second buy-outs if it's under one minute it could add another minute to the timer. Some items shouldn't be allowed to be auctioned such as dragons and wishlists, but it would make an interesting addition. If people don't want to use it they can just not use the command.

**Comment by melmsie** [comment]
no
