### ISSUE TITLE
Problems regarding the "pls rich" leaderboard

### ISSUE THREAD

**Issue by NeverUsingThisAgain** [DankMemer/dank-memer-suggestions-and-bugs#802]
**Is your feature request related to a problem? Please describe.**
I'd like to bring up this issue mostly because of the newly introduced item in the shop, named the Robber's Wishlist (this was however still an issue even before this). From what I've noticed, the "pls rich" leaderboard only registers a user and updates their current amount of coins only if said user has used the bot or if someone pings them. Based on how the leaderboard currently functions, this Robber's Wishlist is nowhere near as helpful at it should be, if we take its price into consideration, since from what I've noticed from using it so far, it only displays users in accordance with the leaderboard. This is an issue because for example, there may be one or more rich users in the server, who are not on passive mode, that however do not use the bot in that specific server and thus do not appear on the leaderboard, which in turn results in them not appearing on the Robber's Wishlist either.

**Describe the solution you'd like**
The simplest (and in my opinion most effective) solution would be for the bot to register everyone in the server and update the leaderboard accordingly regardless of whether they have used the bot in that server or not, which would make the leaderboard (which was supposed to only display the richest in the server from the start) more accurate and thus also making the Robber's Wishlist much more trustworthy.

**Describe alternatives you've considered**
The only other solutions I can think of are ti either reduce the Wishlist's price to make up for what it's currently lacking or to replace it sompletely with a different item that has more uses and is generally more likely to be of use.

Just to clarify something, I'm not saying that the Robber's Wishlist is a useless item. It's just that (in my opinion) its uses are limited since it can only be of real use in a larger server with at least 5k+ members and has extremely limited uses in smaller servers due to the function of the current leaderboard.

**Comment by melmsie** [comment]
"The simplest (and in my opinion most effective) solution would be for the bot to register everyone in the server and update the leaderboard accordingly regardless of whether they have used the bot in that server or not"

no
