### ISSUE TITLE
Apple Usage Bug

### ISSUE THREAD

**Issue by SonicofProdigy** [DankMemer/dank-memer-suggestions-and-bugs#804]
**Describe the bug**
Whenever you use the Apple item, it only serves as a use once. And it also disrupts the other active items in the inventory.

**To Reproduce**
1. Buy or collect an Apple
2. Activate an item
3. Do pls use Apple
4. The activated items disactivate and the Apple works once only 

**Expected behavior**
Apple should be given infinite protection against loosing items for 24 hours 

**Actual result**
Can only be used to protect once and disrupts activated items like tide pod, etc.

**Your User ID**

678379218509496393

**Additional context**
I lost 10 bank notes from the 2nd time I died after I used the apple

**Comment by melmsie** [comment]
fixed next update
