### ISSUE TITLE
Quest list bug

### ISSUE THREAD

**Issue by Fr33ze123** [DankMemer/dank-memer-suggestions-and-bugs#805]
When I do pls quest list, an error messages appears. So far to my understanding this has only happened to me.

Expected behaviour: A list of all the quests

![A59E5763-33A2-45B1-B1BC-47881D55F90B](https://user-images.githubusercontent.com/67177951/85190081-4e5b0980-b2e7-11ea-83ca-c27cdcb6f9ba.jpeg)

**Your User ID**
Fr33ze_#0173

**Comment by melmsie** [comment]
should be fixed next update
