### ISSUE TITLE
1-2 weeks in a seever before rob command can be used

### ISSUE THREAD

**Issue by NotSugden** [DankMemer/dank-memer-suggestions-and-bugs#807]
**Is your feature request related to a problem? Please describe.**
As i see quite alot, the rob command is abused quite alot for big servers, and it seems that would be greatly reduced if a user had to be a member of a server for 1-2 weeks before they can rob people in that server

**Describe the solution you'd like**
the command to be aborted of the user hasn't been in the server for 1-2 weeks

**Describe alternatives you've considered** simply disabling the command using pls disable, however i feel my suggestion would solve alot of the problems

**Additional context**

**Comment by DankMemerFan** [comment]
I like the concept, but not a full week... a day or two would make sense, or maybe you just have to send like, a minimum of 100 messages first before you can rob people, or undo the rob if you leave the server within 24 hours of the rob... Maybe something like that but not 2 whole weeks

**Comment by NotSugden** [comment]
> I like the concept, but not a full week... a day or two would make sense, or maybe you just have to send like, a minimum of 100 messages first before you can rob people, or undo the rob if you leave the server within 24 hours of the rob... Maybe something like that but not 2 whole weeks

maybe, but really just any amount of time, i suggested a week or two because thats more likely to put an end to it, but sure 3-4 days would also do well

**Comment by NotSugden** [comment]
i don't want to be that guy but, what is wrong with this suggestion? @melmsie
