### ISSUE TITLE
People are abusing tic tac toe

### ISSUE THREAD

**Issue by Iwitrag** [DankMemer/dank-memer-suggestions-and-bugs#81]
**Describe the bug**
People are abusing tic tac toe to paralyze users.

**To Reproduce**
pls ttt <user>
and that user is now prompted for his action and other input is ignored...

**Expected behavior**
I would expect that if someone else challenges me for tic tac toe, I would have to agree first... but instead I cannot use command that I wanted to use before.

**Comment by melmsie** [comment]
added a 60 second cooldown so it can't be spammed in next update
