### ISSUE TITLE
Apple Does Not Last 24 Hours

### ISSUE THREAD

**Issue by achenws** [DankMemer/dank-memer-suggestions-and-bugs#812]
The apple only stops the loss of inventory when you die the first time. After the first time, the apple gets removed from your inventory.

1. Use an apple.
2. Try to die through tide pod, heist, etc.
3. Check your profile again to see that the apple is no longer active.

**Expected behavior**
I expected the apple to last 24 hours, not just 1 death.

**Screenshots**
The screenshot shows a time I died 2 times in a row while using an apple.
![image](https://user-images.githubusercontent.com/24927137/85208016-fd94e200-b2e1-11ea-8df1-172a6c9dea93.png)

**Your User ID**
411359020113330188

**Additional context**

**Comment by SonicofProdigy** [comment]
Yeah I had the same issue and reported another small bug with it - https://github.com/DankMemer/dank-memer-suggestions-and-bugs/issues/804

**Comment by melmsie** [comment]
fixed next update
