### ISSUE TITLE
Spelling error 

### ISSUE THREAD

**Issue by DIOOVA** [DankMemer/dank-memer-suggestions-and-bugs#825]
**Describe the bug**
It’s spelling mistake regarding not putting money in the “pls give” command. “You have to to given a whole number, dummy. Not your dumb feelings”

**To Reproduce**
1. Open discord 
2. Say “pls give @(player name) (object)
3. Press enter

**Expected behaviour**

**Screenshots**

**Your User ID**
DIO OVA#1696

**additional notes**
non

**Comment by andrewisaboomer** [comment]
maybe the number is supposed to go before the mention? idk
