### ISSUE TITLE
Bank bug

### ISSUE THREAD

**Issue by Eee12345799** [DankMemer/dank-memer-suggestions-and-bugs#83]
Describe the bug
This bug makes it so the balance is essentially lost.

To Reproduce
There isn't a specific way to reproduce this bug and it seemingly happens at random intervals.

Expected Behavior
I would expect that the amount in the wallet would not randomly disappear.
<img width="332" alt="Screen Shot 2020-04-01 at 5 21 41 PM" src="https://user-images.githubusercontent.com/63021564/78192206-4a80bf00-743d-11ea-828e-f4e0c4b31abd.png">

**Comment by melmsie** [comment]
can't reproduce
