### ISSUE TITLE
using "random" as a coin amount

### ISSUE THREAD

**Issue by ghost** [DankMemer/dank-memer-suggestions-and-bugs#830]
**Is your feature request related to a problem? Please describe.**
No, it was based on an idea from the gambling commands
**Describe the idea**
there should be a random amount for gambling and other commands, for example "Pls gamble random" would automatically set an amount for you and same for other commands. This would cut time and you wouldn't have to spend every few seconds putting a random gold amount.

**Additional context**
This was inspired by the gambling commands (Also so sorry for the short enhancement request)

**Comment by MadScriptCode** [comment]
sounds kinda dangerous... (imagine if it gambled 1M for you) :)

**Comment by SonicofProdigy** [comment]
It can't for betting, but slots it could...
Maybe they can add another feature like maybe pls settings Random amount and you can set the max and the min of the random amount maybe?
