### ISSUE TITLE
Pls search addition.

### ISSUE THREAD

**Issue by StarStruck1** [DankMemer/dank-memer-suggestions-and-bugs#831]
I have tried many times to die when searching the tree in pls search. I have not died yet nor seen anyone die.  You should be able to die if searching the tree. "You didn't bring your tree climbing smarts and fell out of the tree F" When doing so. That is just my idea of course.

**Comment by andrewisaboomer** [comment]
i mean it kinda makes sense
at least add a super rare chance of dying like dying to a murder hobo in an attic thing
something like "u fell out of the tree cuz ur bad and broke ur neck. f to pay no respects" or smth

**Comment by bruhder** [comment]
Well it says " why were you even looking in a tree?". Which means you are looking inside the tree not climbing it. If the response was "you climbed a tree a got blabla coins" it may have a chance
