### ISSUE TITLE
Cant buy things.

### ISSUE THREAD

**Issue by 2400dani** [DankMemer/dank-memer-suggestions-and-bugs#832]
Describe the bug A clear and concise description of what the bug is.
When I withdraw money and try to buy anything from the store, it doesnt let me even though I have money in my wallet. It says "your wallet is empty, go withdraw some BANK money to make this purchase." every time. I prestiged recently, if that helps. I also tried to withdraw different amounts of money and buy different items, still wouldnt work. 

To Reproduce Steps to reproduce the behavior:
Withdraw money. (Pls with 4000, in this case.)
Go to buy item. (Pls buy *item*, a life saver in this case.)
See error

Expected behavior A clear and concise description of what you expected to happen.
I expected the cost of the life savers to be withdrawn from my wallet and to then have them in my inventory for use. 

Screenshots If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/64772539/85237013-1b04a180-b3f1-11ea-9cdd-144cd9c0432a.png)

Your User ID Get your user id and add it here if needed
disintegrates#9340 on discord, my user ID on here is 2400dani

**Comment by oliverysfx** [comment]
I think you forgot the cost of life savers, it's 5000, which you don't have

**Comment by 2400dani** [comment]
> I think you forgot the cost of life savers, it's 5000, which you don't have in your wallet

I noticed that after, but it was the same for other items as well that I'm certain I could afford. That was just one example.

**Comment by oliverysfx** [comment]
screenshot please? this is just empty talk without you screenshotting

**Comment by 2400dani** [comment]
> screenshot please? this is just empty talk without you screenshotting

My apologies, it appears to be working now, mustve been on my end. Truly hope I didnt waste too much of your time. I'll be more thorough next time.

**Comment by oliverysfx** [comment]
then close this thread first so melmsie doesn't waste more time
