### ISSUE TITLE
Typing "app" instead of apple gives you error message 

### ISSUE THREAD

**Issue by scp174** [DankMemer/dank-memer-suggestions-and-bugs#833]
**Describe the bug**
A clear and concise description of what the bug is. The item doesn't show up but rather a error message appears 

**To Reproduce**
1. Type pls shop app
2. Enter

**Expected behavior**
A clear and concise description of what you expected to happen. It should give you the info of the apple

**Screenshots**
![Screenshot_20200622-115815_Discord](https://user-images.githubusercontent.com/61387327/85247245-b7758500-b47f-11ea-93f1-981b6e2baf73.jpg)

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed 610517607971291137

**Additional context**

**Comment by samdabloxyccola** [comment]
"App" works for me. Sometimes there will be an error message shown so you will have to redo the command again

**Comment by HongKonger1234** [comment]
"app" does not work for me. I've tried it 5 times and every time it returned an error message
