### ISSUE TITLE
Balaclavas (Ski masks) 

### ISSUE THREAD

**Issue by DankMemerFan** [DankMemer/dank-memer-suggestions-and-bugs#835]
**Is your feature request related to a problem? Please describe.**
It always frustrates me when boss calls me about a recent robbey

**Describe the solution you'd like**
A ski mask for 50k that reduces the chance of boss finding out about the robbery by 75%

**Describe alternatives you've considered**
Maybe instead of 75% it could be 100% or just 50%

**Additional context**

**Comment by MadScriptCode** [comment]
sounds kinda cool... although maybe make it so that it breaks after some time (like alcohol). otherwise it's kinda OP.

**Comment by Aelloner** [comment]
well,you are paying 50k for it
