### ISSUE TITLE
Bank notes

### ISSUE THREAD

**Issue by Motsyrhc** [DankMemer/dank-memer-suggestions-and-bugs#837]
Maybe make it so you can buy banknotes.

**Comment by MadScriptCode** [comment]
Then people would mass-buy banknotes and work um millions in bank space, making them invincible to robbing. Even worse, they keep their bank space after they prestige.

**Comment by HongKonger1234** [comment]
No tag? I didn't even know how that was possible

**Comment by toot-toot** [comment]
you can:
me: pls shop banknote
Dank Memer:  :banknote: Bank Note
                       TYPE - Item
                       COST - 12,000 coins (sells for 4,000 coins)
