### ISSUE TITLE
No chance

### ISSUE THREAD

**Issue by DIOOVA** [DankMemer/dank-memer-suggestions-and-bugs#838]
**Describe bug**
A rare trivia event bug

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to do anything
2. See rare trivia event 
3. The event ends as soon it starts

**Expected behaviour** 
The event will end the second it appears 

**Screenshots**

**Your User ID**
DIO OVA#1696(https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed

**Additional context**

**Comment by MadScriptCode** [comment]
hmmmm happened to me too. I just live with it (i hate trivia anyways)

**Comment by PhantomFrenzy151** [comment]
You didn't post your id.
