### ISSUE TITLE
Some new restrictions on robbing/passivemode/bank.

### ISSUE THREAD

**Issue by MadScriptCode** [DankMemer/dank-memer-suggestions-and-bugs#839]
**Is your feature request related to a problem? Please describe.**
I've had many people in the past just rob me & then turn on passive mode so I can't rob them back, or deposit it in a bank.

**Describe the solution you'd like**
If I'm not wrong, the whole point of passive mode is for others not to be able to rob you. Therefore, if you wish to nerf it, I think you should change it so that you can turn passive mode off/on whenever you want, but if you robbed someone, you have to wait 24 hours before turning it on. This way, it prevents cowards from waiting, robbing someone, and quickly turning on passive mode. 

**Describe alternatives you've considered**
Also, you should add a "transaction fee" for banks, because I've seen people work up millions in bank space (via banknotes or something else). Then, they rob withdraw some money, rob someone, and quickly deposit all the money. They might repeat this up to 10 times.
However, with the bank fee in place (which would work similarly to taxes), it would discourage people from withdrawing/depositing money so quickly over and over again.

**Additional context**
I've see people rob me for ~ 500K, then quickly turn on passive mode or deposit it in a bank. This way, I can't rob them back.

**Comment by andrewisaboomer** [comment]
then go on passive mode

**Comment by MadScriptCode** [comment]
> then go on passive mode

by then it'd be too late. I don't really care about my coins. I just don't want others to be affected by this (because I'm sure others have been affected by this).

**Comment by soul0101** [comment]
You just need to protect it better, you can't just go on and change stuff to suit your interests.
