### ISSUE TITLE
Interest

### ISSUE THREAD

**Issue by hecktate** [DankMemer/dank-memer-suggestions-and-bugs#84]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like.**
A separate bank account that has interest on it. The interest would be very low unless it can be raised by levels or buying a higher interest rate.

**Describe alternatives you've considered.**
N/A

**Additional context**
Example:
Pls savings dep 69420  
1 day later
Pls savings
Dank Memer: 69420 savings + 694.20 interest

**Comment by melmsie** [comment]
Not interested in interest
