### ISSUE TITLE
Its closed

### ISSUE THREAD

**Issue by idekou** [DankMemer/dank-memer-suggestions-and-bugs#840]
Its closed now

**Comment by MadScriptCode** [comment]
do "pls notifs" to see if anyone stole it or if you died.

**Comment by idekou** [comment]
> do "pls notifs" to see if anyone stole it or if you died.

Can anyone rob someone but not in the same server¿¿

**Comment by idekou** [comment]
> do "pls notifs" to see if anyone stole it or if you died.

Nvm, the problem is on my phone. Ty for helping
