### ISSUE TITLE
Make "pls guess" more profitable

### ISSUE THREAD

**Issue by Bulmenisaurus** [DankMemer/dank-memer-suggestions-and-bugs#841]
So, all we all know, `pls guess` is one of the "game" commands. It **_sucks_**, coin-wise. Here is my opinion on how to improve it:
 Firstly, make it give more money. If you guess the number correctly on the first try, it gives you **100** coins, and _maybe_ a chance for some item. If the second guess is correct, it gives you **30** coins. 3rd attempt correct, it gives you only **15** coins. Then, make the wait time something like 30 seconds.

**Comment by andrewisaboomer** [comment]
honestly tho guess isnt supposed to be used for money, its supposed to be a game thing that gives money if you get it right

trivia gives around 31 coins on average if you do pls trivia then do a without looking at the question
obviously, u would get more money based on the answers you know and the amount of money its worth, but i feel like guess shouldn't be used as a major currency amount that makes money

**Comment by andrewisaboomer** [comment]
close this?
