### ISSUE TITLE
Wishlist bug

### ISSUE THREAD

**Issue by samdabloxyccola** [DankMemer/dank-memer-suggestions-and-bugs#842]
**Describe the bug**
Sometimes, the wishlist does not show people with over 500 coins. There was once I found a person with 19k coins in a server, he was not on passive mode, but the wishlist does not show the person with his balance of 19k. 

**Expected behavior**
People with their balance over 500 coins must be shown on the wishlist to avoid confusion among users and a lot of time spent on searching for the users to rob.

**Your User ID**
𝓒𝓸𝓻𝓷#2383
594165913381503000

**Comment by RandomTurtleBoi** [comment]
does the user have a fake id active? if so, they won't show up on the list

**Comment by samdabloxyccola** [comment]
No he doesnt

**Comment by ARU300** [comment]
I think its to do with caching. If the person hasn't used their account or made any money in a while it is not stored on the cache and therefore they don't show up. If you do `pls bal @USER`, it may show up. I'm not sure this is just a guess but its the same with `pls rich`. If a person is inactive they won't show up on pls rich until someone checks their balance.

**Comment by oliverysfx** [comment]
> I think its to do with caching. If the person hasn't used their account or made any money in a while it is not stored on the cache and therefore they don't show up. If you do `pls bal @USER`, it may show up. I'm not sure this is just a guess but its the same with `pls rich`. If a person is inactive they won't show up on pls rich until someone checks their balance.

yeah that's correct
