### ISSUE TITLE
Candy

### ISSUE THREAD

**Issue by ARU300** [DankMemer/dank-memer-suggestions-and-bugs#844]
**Describe the bug**
You are unable to use multiple `candy` at a time.

**To Reproduce**
1. Have more than 1 `candy` in your inventory.
2. Type `pls use candy 10`
3. Only one `candy` is used.

**Expected behavior**
You would expect 10 `candy` to be used and hence 10 messages regarding the `candy` would be sent along with a decrease of 10 in the number of `candy` in your inventory.

**Screenshots**
![image](https://user-images.githubusercontent.com/33807399/85370340-708e9a80-b526-11ea-9a00-a8d4a2da40b2.png)

**Your User ID**
`416286817822703627` is my UserID.

**Additional context**
If this is not a bug and you are meant to only be able to use one `candy` at a time then there should not be a message when you attempt to use more than 10 which is also shown in the screenshot.

**Comment by bruhder** [comment]
I guess this should be an enhancement rather than a bug

**Comment by ARU300** [comment]
Well, it is sort of a bug because you can't do `pls use candy 30`.

**Comment by andrewisaboomer** [comment]
its more like an enhancement and not a bug, but i would like for this to be implemented onto other things, like banknotes
i'd expect for it to function like how it works when you open multiple normie boxes

**Comment by ARU300** [comment]
There's already quite a lot of issue requests about this that have been seen by Melmsie so I'm closing it.
