### ISSUE TITLE
Searching under the bed

### ISSUE THREAD

**Issue by bruhder** [DankMemer/dank-memer-suggestions-and-bugs#847]
It always say how generous the demon under your bed is. Do you agree they should give a dying chance while searching in bed? Like when you die it will say "The demon under your bed brought you to hell"

**Comment by PhantomFrenzy151** [comment]
same with searching in discord i think

**Comment by SonicofProdigy** [comment]
There are already enough chances to die, like at the streets or at the sewers

**Comment by Toast10645** [comment]
yes i dont think there should be a death chance for that. but it is a creative idea though!
