### ISSUE TITLE
make the giveaway command public

### ISSUE THREAD

**Issue by damboi38** [DankMemer/dank-memer-suggestions-and-bugs#848]
**Is your feature request related to a problem? Please describe.**
- Nope

**Describe the solution you'd like**
- Y'all gave away coins and items in the giveaway celebrating the 7500 survey submits. Y'all used a giveaway command built into dank memer that gave the winner the prize. Make this giveaway feature public and available for all. Where someone can host a giveaway with the command and after the time is over the bot will take away the prize from the hosts bank and put it in the winners bank.

**Describe alternatives you've considered**

**Additional context**

**Comment by RandomTurtleBoi** [comment]
they're still developing it and fixing bugs, that's why they switched from dank memer to giveawaybot halfway through. and they used pls d/pls dev which is only for the developers
