### ISSUE TITLE
Boss

### ISSUE THREAD

**Issue by ARU300** [DankMemer/dank-memer-suggestions-and-bugs#849]
**Is your feature request related to a problem? Please describe.**
It's quite annoying when your boss fails you for doing a `heist` or a `rob` on someone as that's quite an enjoyable aspect of **Dank Memer** and it means you're often getting fired and you have to wait another day to get another job.

**Describe the solution you'd like**
My idea is that if you have worked in that **hour**, then your **Boss** ignores any `heist` or `steal` you've done within the **hour**. If you haven't worked that hour then there is an increased chance of your boss failing or firing you after a `heist` or `steal`.

**Describe alternatives you've considered**
The other idea was that you only get a `+1 job fail` if you have failed the `rob` or `heist` or were caught during the `heist` and had to pay a **fine** or a **bail**. If you didn't get caught then you don't get a `+1 job fail`.

**Comment by andrewisaboomer** [comment]
for some reason, i get screwed over by my boss all the time but i've never been fired
just never been promoted, and that's fine with me because im getting more money from bankrobs than if i had gotten a promotion

**Comment by PhantomFrenzy151** [comment]
i swear the +1 job fail is already in the game.

**Comment by ARU300** [comment]
Did you even read anything I wrote?

I said that you should only get the `+1 job fail` if you didn't work that hour.
