### ISSUE TITLE
Money Draining glitch

### ISSUE THREAD

**Issue by VeekTaur** [DankMemer/dank-memer-suggestions-and-bugs#85]
I dont know how it happened basically I stole money from a guy then a few minutes later my account was empty.

Please give me my money back I’ve worked hard for it
Also my name on disc is: Suduri#8670

![15A88ADB-58A8-4649-9E58-9950368D0930](https://user-images.githubusercontent.com/63035126/78213305-e580a400-74e4-11ea-80b9-827acb5fedb6.png)
![E3EA6865-727E-4908-8A8D-07373BE32B1B](https://user-images.githubusercontent.com/63035126/78213319-ea455800-74e4-11ea-8f49-c9e81e8fbe7f.png)

**Comment by melmsie** [comment]
This isn't a bug, they very likely reversed it with a reversal card.
