### ISSUE TITLE
lightning sale causes items to sell for less

### ISSUE THREAD

**Issue by andrewisaboomer** [DankMemer/dank-memer-suggestions-and-bugs#850]
literally what the title is
if an item has like a 95% off sale, the sell price will also be affected.

**Comment by PhantomFrenzy151** [comment]
I mean, it's not like it could be abused. You can't make money from selling a discounted item at full price.

**Comment by andrewisaboomer** [comment]
no but then you can lose a lot of money if ur mass selling
