### ISSUE TITLE
Duplicating Items

### ISSUE THREAD

**Issue by Chugh2** [DankMemer/dank-memer-suggestions-and-bugs#852]
**Describe the bug**
This bug will duplicate items from the shop, but you will only pay for 1 of them.

**To Reproduce**
1. Type "pls buy <whateveritemyouwanttoduplicate> <number of duplicates here>

**Expected behavior**
If you decide to buy 10 laptops (pls buy laptop 10), you only pay 3,000 (the original price for 1) and u receive 10 laptops.

**Screenshots**

**Your User ID**
665679445662629898

**Additional context**
None.

**Comment by ARU300** [comment]
You've kinda done the **`Expected Behaviour`** wrong. 

You should write what should normally expect if there was no bug.

Also, you should aim to be a bit more clear in the **`To Reproduce`** section.

**Comment by ARU300** [comment]
I tried this to see if it was a bug. I couldn't seem to replicate the issue.
