### ISSUE TITLE
Where is my alcohol?

### ISSUE THREAD

**Issue by samdabloxyccola** [DankMemer/dank-memer-suggestions-and-bugs#853]
**Describe the bug**
I drank some alcohol a while ago. However, after a while, the alcohol was gone although 12 hours is not over yet.

**Expected behavior**
The alcohol should be valid in its 12 hour cooldown and not disappear during the cooldown

**Your User ID**
𝓒𝓸𝓻𝓷#2383 - 594165913381503000

**Comment by andrewisaboomer** [comment]
did you die? or prestige? or do pls ri/remove alcohol?
i dont even know if some of these affect item effects going away, but its best to check

**Comment by samdabloxyccola** [comment]
I didnt do anything of those?
And I have lifesavers so i didnt die
