### ISSUE TITLE
Gifting

### ISSUE THREAD

**Issue by The-blackout** [DankMemer/dank-memer-suggestions-and-bugs#86]
**Is your feature request related to a problem? Please describe.**
Yes, When i was trying to give someone a rare pepe today I accidentally gave it to dank memer the bot.

**Describe the solution you'd like**
Just fix it so your not allowed to gift items to the bot.

**Describe alternatives you've considered**
None.

**Additional context**
I could show you when I have dank memer the rare pepe but there’s no point.

**Comment by melmsie** [comment]
That seems like a you problem? You tagged the wrong person. People have fun giving the bot random shit, not removing that.
