### ISSUE TITLE
The pls tweet command has so much potential 

### ISSUE THREAD

**Issue by Roblo2315** [DankMemer/dank-memer-suggestions-and-bugs#860]
My username is @realDonaldTrump, the “pls tweet” feature was one the reasons I changed my username.  When I changed my username, I had to wait a whole day for Dank Memer to refresh my twitter username, but it didn’t take that long for him/her etc. to refresh my profile picture, when the “pls tweet” command is used, your username appears twice, with a smaller and grey version with an @ under the other username, the problem is that they both have the same name, but in Twitter, that is not the case. 

          I'm always frustrated when you have both the same name and nickname, and when you have to wait for it to refresh your username and profile picture.

          The nickname problem can be fixed by adding a command that can change your nickname, I don’t know about the profile one.

          Adding a command, maybe “pls nick twitter” or “pls nickname tweeter” something along those lines can make you customize your nickname (the one on the top, not the grey username)

          Regardless of whether you consider my suggestions or not, I may or may not be giving more suggestions in the future.

**Comment by andrewisaboomer** [comment]
seems like a lot of unnecessary complication for a command that might not be used a lot
idk
