### ISSUE TITLE
Robbers wishlist bug

### ISSUE THREAD

**Issue by xnah** [DankMemer/dank-memer-suggestions-and-bugs#866]
In this bug when you use the robbers wishlist and you rob someone from the list about 2 or 3 times their name dissapears from the list. And this happens even though the person still has over 500 coins and no fake id/not passive. And this can only be reproduced if you don't rob the full 100% from the person each time. 
 
1. Go to the wishlist  
2. Rob someone but you must not take the full amount the first few times, which yes you cant really control 
3. Once you've robbed them about 2-3 times 
4. Name won't appear on list even though they have over 500 coins, not in passive and no fake id  

**Expected behavior** 
Well basically I would expect their name to still be on the list even when they have all the required things.

**Your User ID** 
397864221016064002

**Comment by andrewisaboomer** [comment]
maybe they're just not rich? sometimes people have over 500 coins but if they have like 501 coins they dont appear

**Comment by xnah** [comment]
> maybe they're just not rich? sometimes people have over 500 coins but if they have like 501 coins they dont appear

The guy had like 50k and wasn't appearing on the wishlist anymore after I kept robbing him

**Comment by DankMemerFan** [comment]
it's because the wishlist only shows the players on pls rich (which has a max of 10 pages) and not all players on the server. Meaning if the player has less money than the person at the bottom of pls rich 10,thwy will not show up on the wishlist

**Comment by samdabloxyccola** [comment]
> it's because the wishlist only shows the players on pls rich (which has a max of 10 pages) and not all players on the server. Meaning if the player has less money than the person at the bottom of pls rich 10, they will not show up on the wishlist

Idts as some users still appear on the wishlist despite not being in the rich list

**Comment by xnah** [comment]
> > it's because the wishlist only shows the players on pls rich (which has a max of 10 pages) and not all players on the server. Meaning if the player has less money than the person at the bottom of pls rich 10, they will not show up on the wishlist
> 
> Idts as some users still appear on the wishlist despite not being in the rich list

Yeah thats true, I noticed that the last person on pls rich 10 had way more then the people on the wishlist
