### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by AnimatedY** [DankMemer/dank-memer-suggestions-and-bugs#867]
This can or can not be a problem sometimes, but the thing is that when you want to see what new update has been added, you always have to go to the official server and then search for what you want. 
My solution for this problem is add a command like "pls update" that will show you a list of recent updates.

**Comment by andrewisaboomer** [comment]
what about web hooks

**Comment by melmsie** [comment]
the "follow this channel" system exists for a reason
