### ISSUE TITLE
Pet names can be used to ping users/roles

### ISSUE THREAD

**Issue by JessRogue** [DankMemer/dank-memer-suggestions-and-bugs#868]
**Describe the bug**
You can use `pls pet name` to ping roles/users.
When you use a pet command with a name that mentions a role/user, the person/people mentioned will be pinged.
(Provided the bot has permission to ping `@everyone`, which it does by default)
This has some limitations, mainly it being difficult to get the ID of the role you want to mention with the bot, but it still exists and works.

**To Reproduce**
User: 
In developer mode, right click user and Copy ID. Put in <@id> to make a ping, then put that into your pet name. Then use a command that puts your pet name into the output, like `pls pet` or `pls pet play`

Role:
Step 1: Get the ID for the role, which can be a little tricky. Either get someone with the ability to ping a role to do \@role to get the ID of the role, or copy ID from the roles list. That, or, you can put the ping into the pet name while you might temporarily have access to ping the role.
Step 2: Put the ID into <@&id>, and put that into your pet name.
Step 3: Use a command that puts your pet name into the output--such as `pls pet` or `pls pet play`

**Screenshots**
![image](https://user-images.githubusercontent.com/67443460/85803048-2d395500-b6fb-11ea-973b-cd29bd42912f.png)
As you can see, the user (which is my testing alt) can name their pet a mention, even if they can't ping the role themselves. Then, Dank Memer (without their role permissions being modified) pings the role.
![image](https://user-images.githubusercontent.com/67443460/85803664-8b1a6c80-b6fc-11ea-987b-85382d212050.png)
The role _is_ unpingable, and the `@everyone` permissions deny the ability to ping `@everyone` or `@here`.

**Your User ID**
Jess Rogue#8863 237380587852136449

Jess' Testing Alt#1068 287105079604019200

**Comment by oliverysfx** [comment]
the roles bug is fixed, as for user pinging, eh what's the point of disabling it

**Comment by oliverysfx** [comment]
role is already fixed, as for pinging users, what's the point of disabling it

**Comment by anonymouswrita** [comment]
this specific thread issue is already fixed, close this
