### ISSUE TITLE
pls pet energy bar bug

### ISSUE THREAD

**Issue by ghost** [DankMemer/dank-memer-suggestions-and-bugs#870]
**Describe the bug**
Whenever you do pls pet 2 times in a row, the energy bar refills for some odd reason

**To Reproduce**
1. Get a pet dragon
2. do pls pet 2 times in a row really fast

**Expected behavior**
Energy bar should have not went up and only with pls pet pat or other pet commands

**Result**
Energy bar goes up by the 2nd pls pet command

**Screenshots**

<img width="669" alt="Bug #1" src="https://user-images.githubusercontent.com/66980377/85805708-ae501680-b712-11ea-9c76-6aec07f900de.png">

**Your User ID**
678379218509496393

**Additional context**
I found this bug annoying, and I want it to be patched

**Comment by SonicofProdigy** [comment]
It could happen with other pets, I don't know for sure

**Comment by PhantomFrenzy151** [comment]
That's intentional. Any commands run with a "pls pet" prefix refill the energy bar. The energy bar basically shows them time since the pet was last interacted with.

**Comment by SonicofProdigy** [comment]
"Any commands run with a "pls pet" prefix refill the energy bar. "
I didn't know that, I thought only with pls pet twice would be a bug

**Comment by oliverysfx** [comment]
this is not a bug

**Comment by oliverysfx** [comment]
it's specifically for dragon pets

**Comment by oliverysfx** [comment]
other pets you have to pls pet pat or do any of the actions, but dragon you can just pls pet
