### ISSUE TITLE
Refund system - "pls refund"?

### ISSUE THREAD

**Issue by trashbinprod** [DankMemer/dank-memer-suggestions-and-bugs#871]
Sometimes I spend lots of coins on items with the Dank Memer bot, but the item is not exactly as expected. However, I had alrrady bought the item and have no way of getting my coins back.

I think that there should be a "pls refund" command, that removes the most recent item that you bought from the shop from your inventory, and gives you back a fraction of the item's original price (maybe 3/4 or 2/3 the original price).

I think a lot of users would benefit from a refund system, including me. Please consider implementing this.

**Comment by andrewisaboomer** [comment]
then legit everyone would never use the sell command and they would only use the refund command lol

**Comment by trashbinprod** [comment]
> then legit everyone would never use the sell command and they would only use the refund command lol

People could still use the sell command for anything but refund things if they want to sell for a higher price directly after buying. The refund command could only be used on the last thing they bought so they can't just refund anything they ever bought for a higher price than selling.

**Comment by DgodmodeD** [comment]
I think that if this becomes a thing, then it should only work on the most recent item in the past 24 hours. So if you bought an item and its been longer than 24 hours, you can't refund it.

**Comment by trashbinprod** [comment]
> I think that if this becomes a thing, then it should only work on the most recent item in the past 24 hours. So if you bought an item and its been longer than 24 hours, you can't refund it.

That sounds like a good idea

**Comment by oliverysfx** [comment]
have you considered people buying in flash sale?

**Comment by oliverysfx** [comment]
then refunding after the sale is over?

**Comment by oliverysfx** [comment]
that's free money basically

**Comment by oliverysfx** [comment]
and this is also dumb, why would you not read the item description b4 you buy it

**Comment by trashbinprod** [comment]
> have you considered people buying in flash sale?

There could be a way of tracking how much you spent on the item, and then using that amount to calculate a refund price

**Comment by trashbinprod** [comment]
> and this is also dumb, why would you not read the item description b4 you buy it

Also some people.get confused by the descriptions. Some items don't really give full explanations of what they actually do
