### ISSUE TITLE
One-letter aliases

### ISSUE THREAD

**Issue by jay3332** [DankMemer/dank-memer-suggestions-and-bugs#872]
Inspired by idle miner,  you should maybe add 1-letter aliases for commands (or very short ones)

Examples:
pls b = pls balance
pls p = pls profile
pls i = pls inventory
pls s = pls search

**Comment by DgodmodeD** [comment]
I actually really like this idea. Nice!

**Comment by oliverysfx** [comment]
eh it would cause confusion though

**Comment by wasi-master** [comment]
Would be helpfull
