### ISSUE TITLE
item: hand sanitizer

### ISSUE THREAD

**Issue by DgodmodeD** [DankMemer/dank-memer-suggestions-and-bugs#873]
**Is your feature request related to a problem? Please describe.**
 I know this is LITERALLY ALCOHOL but this has a special property than alcohol. First off, it doesn't make you more prone to being robbed from and secondly, it's special property is that it has multiple uses. By this i mean that it could have 3-10 uses per bottle (meaning every bottle you buy, theres a chance your bottle will have 10 pumps meaning 100 min/1 hour and 30 min of rob/heist boost. OR your bottle will have the lowest amount of pumps: 3 pumps :which is pretty unlucky.

**Describe alternatives you've considered**

This is the one item that I felt strongly for dank memer to have. The description is a bit vague and I could probably give more info but for now this is all i've got.

**Additional context**
ITEM: "hand sanitizer"

Effects:
Use this item before robbing someone to get a 10% boost (or something less) of not getting caught when robbing someone (EXTREMELY useful when bankrobbing [EX. when people are bankrobbing someone they would use hand sanitizer instead of alcohol because when using hand sanitizer before a heist, the person has less of a chance of getting caught AND gets more coins in the process] and it has multiple uses, every bottle containing 3-10 pumps)
Costs 3,000 coins (sells for: 1,336) 
Can get from:
shop and events

Can't get from:
boxes, scouting, and anything else than shop and events.

P.S. I just think that this would be convenient and pretty useful for those who really like to rob people.
I might come back with more suggestions if this one goes in. Welp hopefully it will be in a update.

-edwoke#2865
cya.

**Comment by andrewisaboomer** [comment]
so basically alcohol x fidget spinner with some changes

**Comment by DgodmodeD** [comment]
> so basically alcohol x fidget spinner with some changes

yeah pretty much
