### ISSUE TITLE
Bank Loans

### ISSUE THREAD

**Issue by Ramika57** [DankMemer/dank-memer-suggestions-and-bugs#874]
There should be an option where a certain user will be able to borrow money from dank member, and if they don't pay it in a certain amount of time, they would have a punishment period. This period could either be not being able to use the bot for a couple of days etc.

**Comment by DgodmodeD** [comment]
This could create problems such as:

Daily streak resetting
bugs
and extra work for the devs

tbh it sounds like a good idea but there are some things that could go wrong

**Comment by samdabloxyccola** [comment]
However, the bot must be programmed to take back the money from the users, even if it means leaving negative balance in the user's wallet

**Comment by andrewisaboomer** [comment]
then people would get an alt to get like 10million loan, share it away, and then delete the account lol

**Comment by melmsie** [comment]
no
