### ISSUE TITLE
different number formatting in "tie" output of "blackjack"

### ISSUE THREAD

**Issue by deltaflyer4747** [DankMemer/dank-memer-suggestions-and-bugs#875]
When blackjack makes a tie, you get different monetary number formatting than when you win/lose.

![Tie](https://user-images.githubusercontent.com/7271362/85838189-83f56c00-b799-11ea-8d9a-9781868dda2a.png)
![regular output](https://user-images.githubusercontent.com/7271362/85838217-8a83e380-b799-11ea-816c-33c5ccf29ac1.png)

**Comment by melmsie** [comment]
fixed next update
