### ISSUE TITLE
Auto lottery not working

### ISSUE THREAD

**Issue by Prompty-Doofus** [DankMemer/dank-memer-suggestions-and-bugs#878]
Bank money doesn't deduct every hour for auto lottery system.

So according to auto lottery my money shud deduct every hour whenever the lottery happens but I check every hour and it doesn't happen (Even after 20 mins give or take). So please look into my problem. My name and I'd is Prompty#9946.

**Comment by SonicofProdigy** [comment]
Yeah, I disabled the auto lottery, and when I did pls lottery, it worked. I don't know why the auto lottery isn't working
