### ISSUE TITLE
Finding apples in trees with pls search/scout

### ISSUE THREAD

**Issue by JaceyPlayz** [DankMemer/dank-memer-suggestions-and-bugs#879]
You should update searching in trees to where you can find apples in them, but not too common to find since they are pretty useful for saving items when you die

**Comment by HUHLOLH** [comment]
Good thinking

**Comment by oliverysfx** [comment]
trees already give high payouts, so this is bad(there's a location where you won't expect to find apples, as for which one it is, go figure)

**Comment by melmsie** [comment]
you can find them there, it's rare
