### ISSUE TITLE
Quest Reward Doubled 

### ISSUE THREAD

**Issue by ovaltines** [DankMemer/dank-memer-suggestions-and-bugs#88]
After completing the quest, ‘Won’t Back Down’ I received my rewards of 2,500c and a Fake ID. I attempted to pick a new quest using the command “pls quests choose Working Hard or Hardly Working”, and the bot replied with “you are already doing a quest!”. Obviously that confused me, but soon after I received the rewards of ‘Won’t Back Down’ again. When I checked my inventory I had 5,000 in bank and 2 Fake IDs. 

![bug](https://user-images.githubusercontent.com/63083617/78316741-21cb0780-75ac-11ea-9ab8-991dcf2b5e60.jpg)

Hopefully you can see the screen shot provided ^

I expected that I claim the quest rewards ONCE. And when I requested to do another quest that it accept my request first try. 

Thank you for your time c:

**Comment by melmsie** [comment]
Known bug, won't be fixed until the rewrite
