### ISSUE TITLE
Getting failed work attempt when not using `pls work`

### ISSUE THREAD

**Issue by carmstrong070** [DankMemer/dank-memer-suggestions-and-bugs#881]
**Describe the bug**
After starting a new job, I will get numerous failed work attempts while not using the `pls work` command

**To Reproduce**
I don't have specific repro steps

**Expected behavior**
Failed work attempts only occur when you fail the work task after using the `pls work` command

**Screenshots**
![Screenshot of issue](https://cdn.discordapp.com/attachments/609151771478065156/726226087889207306/unknown.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.18362)
 - Discord

**Additional context**
You can see from the screenshot that I have only had the job for 5 hours so I could only have worked 5 times (4 pass 1 fail). However, I have 8 work attempts logged (4 pass 4 fail).

**Comment by andrewisaboomer** [comment]
did you rob/bankheist? if you get caught you get a job fail

**Comment by carmstrong070** [comment]
@andrewisaboomer Does the `steal` command cause this too, or just `bankrob`?

**Comment by andrewisaboomer** [comment]
your boss will tell you if he catches you in ur notifs. he says something like mate i saw on the new that you were in a BANK HEIST/ROBBERY! if u keep this up ill kick you right out the door +1 daily job fail

**Comment by andrewisaboomer** [comment]
ignore my crappy spelling

**Comment by carmstrong070** [comment]
Thanks for the clarification. Not a bug
