### ISSUE TITLE
Would be nice to be able to look up your most/least used commands 

### ISSUE THREAD

**Issue by BattleRex** [DankMemer/dank-memer-suggestions-and-bugs#882]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andrewisaboomer** [comment]
as far as i know there on some super old profiles it showed the most common command used, so it's definitely possible at least, but the devs might have cut that feature to save memory or some programming thing

**Comment by melmsie** [comment]
least wouldn't make sense, it's gonna be commands that have 0. Most will be added at some point in the future
