### ISSUE TITLE
Minesweeper Suggestion

### ISSUE THREAD

**Issue by HappyL381** [DankMemer/dank-memer-suggestions-and-bugs#883]
**Is your feature request related to a problem? Please describe.**
**Answer** No, this is not because of an issue, it is about adding a new game function.

**Describe the solution you'd like**
**Answer** To make the bot auto-generate a message with bombs, numbers emoji, and use vertical bars to hide the emoji.

**Describe alternatives you've considered**
**Answer** Emm... Let the bot find a Minesweeper image?

**Additional context**
![image](https://user-images.githubusercontent.com/63688135/85916279-20545880-b804-11ea-9cb7-5194844754a9.png)

**Comment by melmsie** [comment]
not really interested
