### ISSUE TITLE
autonsfw categories not posting

### ISSUE THREAD

**Issue by kingwizardlizard** [DankMemer/dank-memer-suggestions-and-bugs#884]
**Describe the bug**
When autonsfw is set to random certain categories are displaying the message but not the image. The categories in question seem to be gif and lesbian. 

**To Reproduce**
set autonsfw to random wait for gif or lesbian category to be posted. 

**Expected behavior**
A message will appear with the category name and "Thanks for being a premium server" but no image.

**Screenshots**
![image](https://user-images.githubusercontent.com/67497419/85916597-3283c600-b807-11ea-9761-6a7b631e164d.png)

**Your User ID**
179496510281482241

**Additional context**
N/A

**Comment by melmsie** [comment]
is it 100% of the time those types don't work?

**Comment by kingwizardlizard** [comment]
Yes only those two categories (lesbian and gif) are not working when they are posted at random by autonsfw.

**Comment by melmsie** [comment]
will be fixed soon
