### ISSUE TITLE
Colorblind mode

### ISSUE THREAD

**Issue by Cokem4n** [DankMemer/dank-memer-suggestions-and-bugs#885]
Hi Dankmemer staff, (or melmsie)

I suffer under a strong **deuteranopia** and can't differentiate the left and the right heart. It's always very frustrating to see both blue(or whatever it is) and rejoice and then get the "_You lost xyz_" message.  Really annoying and frustrating ... and reminding me everytime i'm "pleased" with this deuteranopia shit.
It make's me really sad to first rejoice and then get the F in my face.
![Colorblind](https://user-images.githubusercontent.com/53498137/85922699-abc1fe00-b885-11ea-81c6-94838067b053.jpg)
Would it be possible to implement colorblind modes? 
Commands could be :
pls settings deuteranopia <e/d>
pls settings protanopia <e/d>
pls settings tritanopia <e/d>
It really wouldn't afford thaaat much time and make me and other colorblind memers very happy.
You only need to change the colors of the hearts in _pls slots_ for example
Also i sent a suggestion for a new currency command in the dank memer survey sheet. 
Would be awesome if you'd take a look on that ;) 
Best regards, 
Dank |Cokem4n#1186

**Comment by DgodmodeD** [comment]
This is one of those problems that could be very useful for other colorblind players, but the hearts don't come in all colors just specific ones. This could lead to a problem on how the developers will do the hearts.

**Comment by Squidtoon99** [comment]
Using custom emojis the developers could possibly make more shades of hearts for colorblind users they aren't as much limited to the current selection of hearts.

**Comment by soul0101** [comment]
Even the pls pet play command has a color task which is a pain for CB users.

**Comment by PhantomFrenzy151** [comment]
honestly they could just replace colors with shapes

**Comment by melmsie** [comment]
hopefully we'll be able to address this in the rewrite later this year

**Comment by Squidtoon99** [comment]
During the rewrite will you change your string sanitization methods? because no offense great bot and all but they're not working so well now.
