### ISSUE TITLE
"pls use dragon" not working

### ISSUE THREAD

**Issue by CoronaZoro** [DankMemer/dank-memer-suggestions-and-bugs#886]
When I type "pls use dragon" it comes up with a quest but for the past two days "pls use dragon" is not working. The bot is reading it as a item because there is no "That item doesn't even exist what are you doing" message. The bot does not reply with anything. I asked the discord support and they said it might be a bug. How can I fix this?

**Comment by SonicofProdigy** [comment]
Do you have a dragon item? You need one to do pls use dragon

**Comment by melmsie** [comment]
fixed next update
