### ISSUE TITLE
Vacuum Spelling Error

### ISSUE THREAD

**Issue by heysh** [DankMemer/dank-memer-suggestions-and-bugs#887]
**Describe the bug**
After running the command "pls work" when working as a House Wife, one of the missing words in hangman is spelled wrong. The word expected by the bot is "vaccum", however it should be spelled "vacuum".

**To Reproduce**
1. Work as a House Wife.
2. Run the command "pls work".

**Expected behavior**
I expect the word "vacuum" to be valid, and not "vaccum".

**Screenshots**
[The problem.](https://imgur.com/a/FqMqHGD)

**Your User ID**
144566595665133568

**Comment by melmsie** [comment]
fixed next update
