### ISSUE TITLE
pls house command

### ISSUE THREAD

**Issue by hellslurpee** [DankMemer/dank-memer-suggestions-and-bugs#888]
This command isn’t related to any problems.

If a pls house command was created, I was thinking there could be:
pls house list - list of houses and prices, even the condition
pls house renovate - spend money on your property to keep or sell later!
pls house market - people can list their houses for sale or you can put one on the market
pls house bid - person can put their house up for sale and bid on the ones they want if the owner allows bids.

**Comment by pierremart** [comment]
good idea i think
