### ISSUE TITLE
Even with DM notifications on, you should be able to use “pls notifs” to be able to see your notifications

### ISSUE THREAD

**Issue by CrystalLiquid3** [DankMemer/dank-memer-suggestions-and-bugs#889]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oliverysfx** [comment]
why, what's the point, the user can just check their dms

**Comment by Squidtoon99** [comment]
I have seen servers after a heist display the notification in a special channel / pin that heist message. This would probably be aimed at those servers which have people running friendly heists who want to display in chat **and** get a DM notification.

**Comment by ItsFlashPvP** [comment]
Yes yes yes yes yes. Everyone would love this, I don’t know why it isn’t added rn. If you want to show something to your friend it’s so annoying having to take a screenshot. I think many more people would also enable dm notifications if this was added.

**Comment by melmsie** [comment]
added next update. There's probably a bug this will cause later which is why it existed but we'll figure that out once people report it
