### ISSUE TITLE
pls use dragon is bugged for me

### ISSUE THREAD

**Issue by HUHLOLH** [DankMemer/dank-memer-suggestions-and-bugs#890]
**Describe the bug**
Whenever I do pls use dragon it does not work
**To Reproduce**

**Expected behavior**

**Screenshots**

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed

**Additional context**

**Comment by oliverysfx** [comment]
it's because you satisfy none of the requirements, you need to at least satisfy one for it to work

**Comment by melmsie** [comment]
fixed next update probably
