### ISSUE TITLE
 pls bet for rock, paper, scissors (rps) | pls rps 5000

### ISSUE THREAD

**Issue by SolaWatsila** [DankMemer/dank-memer-suggestions-and-bugs#891]
Example 

Me: pls rps 50000

Dank: I have chosen my. Type `rock`, `paper`, or `scissors`

Me: Rock

Dank: You chosen **rock** & I chosen **paper** meaning you lost 50000 now you have 82892817 coins

**Comment by oliverysfx** [comment]
a 50% win rate game
