### ISSUE TITLE
Sending Messages

### ISSUE THREAD

**Issue by PikuPiku04** [DankMemer/dank-memer-suggestions-and-bugs#892]
Hi, I'm unsure if this has been requested before, however, I would like to request something for the messages in the bot. When you finish sending a message, could the bot delete what you sent so that you would not have to do it manually? Because maybe the recipient will have already seen the message without even checking their notifications. Oh, and I thought that maybe giving an actual notification such as a ping to the recipient so that they know they actually received a message, I thought these ideas were trivial and I also believe it would make sending messages a lot more fun. 

Thank you for taking the time to read my request, I would be happy to hear back from you. Have a wonderful day!

**Comment by oliverysfx** [comment]
a dm is by default a ping, and a message is to really make people know that someone wants to talk, if they have seen the message, what's the point of sending it anyways
