### ISSUE TITLE
Cooldown on using passive after robbing

### ISSUE THREAD

**Issue by aRandomGithubUser** [DankMemer/dank-memer-suggestions-and-bugs#893]
**Is your feature request related to a problem? Please describe.**
I noticed that some people rob like 100k from someone and immediately go into passive after
**Describe the solution you'd like**
A cooldown so if you rob someone you have to wait like 30 mins before going into passive

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by oliverysfx** [comment]
bruh, what's the poing of this, it's useless

**Comment by aRandomGithubUser** [comment]
It's just so the person who was robbed in the first place could rob the person that robbed them as reversal cards currently do not exist.

**Comment by andrewisaboomer** [comment]
then they'd just leave the server

**Comment by oliverysfx** [comment]
> It's just so the person who was robbed in the first place could rob the person that robbed them as reversal cards currently do not exist.

there's something called strategy

**Comment by oliverysfx** [comment]
also the time is just way too freaking long

**Comment by oliverysfx** [comment]
also as to why I say it's useless, people can just very well buy items with it or deposit it, either case will make the money unretrievable

**Comment by aRandomGithubUser** [comment]
I guess you're right.
