### ISSUE TITLE
Money Loss.

### ISSUE THREAD

**Issue by asteria118** [DankMemer/dank-memer-suggestions-and-bugs#894]
So what happened was, I used a tide pod and I lost 1.2 million due to hospital fees, according to Dank memer. 2 minutes later, after freaking out, I checked my balance. I had somehow lost 1.6 million instead. After reposting this in support and investigating the problem with even 2 different mods, they concluded that this was a glitch. I did not join any heists, I did not buy anything, I did not get heisted or robbed, and I did not rob anyone and leave the server shortly after. In conclusion, the problem is that dank memer said I lost 1.2 million but in reality, I lost 1.6 million. Here are screenshots for proof. 

![C751C6FE-84EE-4B45-BC84-9A8462F78D71](https://user-images.githubusercontent.com/67529824/85936873-8ba93380-b8b3-11ea-9965-f48dd57f8c12.png)
![C17EE65D-B7EA-4C9A-BD36-167C32BC8FDB](https://user-images.githubusercontent.com/67529824/85936876-8ea42400-b8b3-11ea-95ac-6ac77630e98f.png)
![E4002FE1-3E69-4F16-84D3-2100B8AE6D9F](https://user-images.githubusercontent.com/67529824/85936877-8f3cba80-b8b3-11ea-9815-c4d486aac8af.png)

**Comment by REALFAREEQASY** [comment]
That's lotta damage

**Comment by soul0101** [comment]
F
