### ISSUE TITLE
Event Bug

### ISSUE THREAD

**Issue by REALFAREEQASY** [DankMemer/dank-memer-suggestions-and-bugs#897]
When I was doing pls guess, I saw an event happen but when I say the word that I supposed to say to get some money of the event, the event boss doesn't decrease.
![IMG_20200628_135753_666](https://user-images.githubusercontent.com/67532724/85939469-6d414780-b948-11ea-92e0-35dd62521991.jpg)
It's maybe because I late to say it or maybe it's a bug and if it's both please fix it

**Comment by oliverysfx** [comment]
too late
