### ISSUE TITLE
bet revers

### ISSUE THREAD

**Issue by DeadLif** [DankMemer/dank-memer-suggestions-and-bugs#898]
New Item: add a bet revers item. You can use it 3 times and it costs 165k. If you betted money and lost and younwant it back you can use the bet revers within in 10 seconds. If you did it you get ur money back if not u suck.

**Comment by oliverysfx** [comment]
too op bro

**Comment by SonicofProdigy** [comment]
It would be very useful though...

**Comment by PhantomFrenzy151** [comment]
way too op and takes away the concept of gambling.
