### ISSUE TITLE
When I use command pls disable steal and pls disable bankrob it worked before but now if I do it shows its already disabled but we can still rob and bankrob plz help 

### ISSUE THREAD

**Issue by SubhamBS** [DankMemer/dank-memer-suggestions-and-bugs#899]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed

**Additional context**

**Comment by andrewisaboomer** [comment]
check your pls enable list i think it overrides the disables
