### ISSUE TITLE
Pet XP after maxed

### ISSUE THREAD

**Issue by atlambros** [DankMemer/dank-memer-suggestions-and-bugs#9]
Once our pet’s stats are maxed out we continue to accrue pet xp. The xp just builds and builds and to my knowledge there is nothing we can do with it other than watch that bar get bigger and bigger...

**Describe the solution you'd like to see** I’d like to have a way of using the extra xp that continues to accrue after our pet has reached max stats. Maybe a treat shop or something where we can spend xp to buy treats for our pets that temporarily boosts abilities like improves or speeds up the frequency items are found by your pet for a short period of time or increases attack ability so that your pet (for a short period of time) is more likely to kill robbers if they try to rob/steal from you. Another possible idea for a treat would be one that extends the pet’s sustainability for 24 hours or something so that it could go a day or any period of time longer than it does without needing to use feed/wash/play/pat.

**Describe alternatives you've considered**
An alternative to this could just be once our pet’s stats are maxed, perhaps we could just receive coins in place of additional xp.

**Additional context**
![1802A48E-AB30-44B0-8CE2-51BB342196C6](https://user-images.githubusercontent.com/62021491/76321388-57841580-62b8-11ea-8a24-17056f145953.jpeg)

**Comment by melmsie** [comment]
The experience growing is just a bug.
