### ISSUE TITLE
pls fish minievent - adjust time limit

### ISSUE THREAD

**Issue by adankmemey4264** [DankMemer/dank-memer-suggestions-and-bugs#90]
**Is your feature request related to a problem? Please describe.**
The pls fish mini event where you type a phrase is fine but...some people - maybe not only me - are havinga hard time typing the phrase especially when they're on mobile or have trouble reading the phrase right away

**Describe the solution you'd like**
I would like to have its time to be adjusted to not more than 8 seconds, maybe people can adjust a bit more on their reading time and typing time.

**Describe alternatives you've considered**
Or maybe have a shorter phrase to type in, if you don't want to adjust the timer

**Additional context**
n/a

**Comment by melmsie** [comment]
Considering how rewarding pls fish is, we want to keep a little challenge. It's not meant to be easy, and it's also definitely not impossible.
