### ISSUE TITLE
A way to counter selfbots/farming bots

### ISSUE THREAD

**Issue by pierremart** [DankMemer/dank-memer-suggestions-and-bugs#900]
Hi guys,
I have a suggestion for you.
I think it's REALLY too easy to code a selfbot/farming bot for Dank Memer. I did an experience this afternoon, to see in how much time i could code a farming bot (educational purpose only, i don't use it), it took me about 15 minutes to code a neat little one, in bash, using xdotool, an keyboard emulator. By the way this one is pretty basic, but it does works.
-------------------------------------------------------------
Here is the code : 
#!/bin/bash
while true; do
xdotool sleep 2
xdotool type "pls beg"
xdotool sleep 2
xdotool key "Return"
xdotool sleep 1
xdotool type "pls hunt"
xdotool sleep 2
xdotool key "Return"
xdotool sleep 1
xdotool type "pls fish"
xdotool sleep 2
xdotool key "Return"
xdotool sleep 1
xdotool type "pls pm"
xdotool sleep 2
xdotool key "Return"
choices=("n" "e" "r" "d")
choice=${choices[$RANDOM%${#choices[*]}]}
xdotool sleep 2
xdotool type "$choice"
xdotool key "Return"
xdotool sleep 1
xdotool type "pls dep all"
xdotool key "Return"
xdotool sleep 40
done;

So i have a solution to counter that type of selfbot, just use a speed type controler, and if they type speed is too high, then launch a RECAPTCHA verification to verify they aren't a bot, or any other type of CAPTCHA you want.

If you wanna contact me on Discord, here is my tag : 
VX | OURANOS#0001

**Comment by pierremart** [comment]
Oh and, i forgot to say, this script will take a random choice between normie, edgy, repost, and dank, and i could even a pls triv auto farm, using random answers between A, B, C and D.

**Comment by melmsie** [comment]
We cannot see how fast someone types, and we can't give captchas.

**Comment by pierremart** [comment]
Oh ok then. So you can't do anything about that ? :/
