### ISSUE TITLE
Gamble count bug

### ISSUE THREAD

**Issue by SonicofProdigy** [DankMemer/dank-memer-suggestions-and-bugs#901]
**Describe the bug**
When you win from slots, it doesn't appear on the gambling winning amount

**To Reproduce**
1. Gamble 
2. do pls profile --gamble
3. do pls slots (big amount)
4. do pls profile --gamble again

**Expected behavior**
Should add the won coins to the winning amount

**Result**
Doesn't count the winnings from the slots
**Screenshots**
<img width="392" alt="Screen Shot 2020-06-28 at 4 06 02 PM" src="https://user-images.githubusercontent.com/66980377/85958236-ac2bc900-b959-11ea-8f0a-5c6c14f0eca6.png">
<img width="453" alt="Screen Shot 2020-06-28 at 4 00 52 PM" src="https://user-images.githubusercontent.com/66980377/85958238-af26b980-b959-11ea-9b2a-7976340b6f0e.png">
<img width="420" alt="Screen Shot 2020-06-28 at 4 06 14 PM" src="https://user-images.githubusercontent.com/66980377/85958239-b1891380-b959-11ea-8d86-c1dbbbd4f175.png">

**Your User ID**
678379218509496393

It only works from betting not from slots

**Comment by melmsie** [comment]
only the 10th time this has been reported, no big deal
