### ISSUE TITLE
Pls work not working 

### ISSUE THREAD

**Issue by HalfHeartedyay** [DankMemer/dank-memer-suggestions-and-bugs#904]
when the dank memer bot asks me to memorize a list of 4 words then has me type them in chat it doesn't respond after I send my response. I then have to type pls work again and get a different prompt to get paid.

![image](https://user-images.githubusercontent.com/67567542/85965692-5879a980-b972-11ea-8920-51d359b6aaf0.png)

**Comment by PhantomFrenzy151** [comment]
The problem described is a bug, but you know you're supposed to write all the words on one line right?
