### ISSUE TITLE
PICKAXE

### ISSUE THREAD

**Issue by yeetedfrs** [DankMemer/dank-memer-suggestions-and-bugs#905]
Simply a new item to buy in the shop, a pickaxe. could be 15k like the rifle and fishing rod, or it could perhaps be a 20k one or more. And of course the rewards for “pls mine” could be different types of ores climbing in value. Probably been suggested before but yeah

**Comment by PhantomFrenzy151** [comment]
this has been suggested SO MANY TIMES. Also it was mentioned in a livestream.
