### ISSUE TITLE
Pls yearly

### ISSUE THREAD

**Issue by Amalik-yoaz** [DankMemer/dank-memer-suggestions-and-bugs#906]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andrewisaboomer** [comment]
dude everyone would make an alt, do pls yearly, share away the items, and then delete the account lol

**Comment by Bananabob999** [comment]
keep seeing the pls yearly idea pop up. 
I think it is a good idea to include rewards for longer periods (yearly/monthly) but you definitely have to consider alt accounts. Not sure what you would do about this, maybe add an 'unshareable' flag to certain items from daily/weekly/monthly/yearly loot so people can't do that, but then again, some people legitimately want to share things with their friends.
