### ISSUE TITLE
You should make the 365th daily, giving 1 mil coins, 10 dank boxes, some Pepe coins, and more stuff. 

### ISSUE THREAD

**Issue by Amalik-yoaz** [DankMemer/dank-memer-suggestions-and-bugs#907]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oliverysfx** [comment]
too much bro

**Comment by andrewisaboomer** [comment]
its too much but i do feel like you should get something after a year of successful daily's, maybe a small multi or smth
