### ISSUE TITLE
There Should be a 3650th daily, which is basically "pls decadly", which gives 100 million, 500 dank boxes, 10 pepe trophys, 50 pepe coins, 1000 dragons and 1000 bank notes

### ISSUE THREAD

**Issue by Amalik-yoaz** [DankMemer/dank-memer-suggestions-and-bugs#909]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DgodmodeD** [comment]
Um... This would literally destroy the economy in dank memer.

**Comment by DgodmodeD** [comment]
also, no one would wait a decade for a bot game to get 100 mil

**Comment by SonicofProdigy** [comment]
It would be really useful for everyone though...

**Comment by Bananabob999** [comment]
It would work, but if I remember correctly (correct me if I'm wrong), upon using the bot for the first time, you can get your pls daily and pls weekly for your first week and day without waiting for a whole week/day, and if this command works the same way, you would be able to get 100 million pretty much instantly. You could solve this by doing first time = lower-tier loot/money, 2nd time = higher-tier loot/money, 3rd time = insane-tier loot/money.

This is a good idea to have rewards for longer intervals, but a pls monthly/yearly seems better (with reward amounts better suited to those time periods of course).

**Comment by ItsFlashPvP** [comment]
Are you okay while making this? Literally everyone would make alts to do this even if they had to wait 2 weeks.

**Comment by melmsie** [comment]
literally idiotic
