### ISSUE TITLE
Better Inventory

### ISSUE THREAD

**Issue by Druva-D** [DankMemer/dank-memer-suggestions-and-bugs#91]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It is frustrating to search through my inventory to find the item I need and identify its quantity and if i don't have the item i have to search all the pages just to be sure.This is time-consuming and can be solved easily, right?

**Describe alternatives you've considered**
1) add a search parameter to the inv command. make it so  that you can search the inventory for items just life shop.
2)add detail in `pls shop {itemname}`.Details about wether u have the item and its quantity could be made available in this command

**Comment by melmsie** [comment]
Will consider this in future updates
