### ISSUE TITLE
Add office handshake as an image meme

### ISSUE THREAD

**Issue by papsavas** [DankMemer/dank-memer-suggestions-and-bugs#910]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/50584606/85997590-5a934500-ba12-11ea-8bb8-01493d958e03.png)

**Comment by melmsie** [comment]
100% agree, coming right up

**Comment by GeoffreyWesthoff** [comment]
This has been implemented with https://github.com/DankMemer/imgen/commit/c63802123e2f3aebfde9b02b768b4722f952f2fd
