### ISSUE TITLE
Missing Coins from around half a year ago

### ISSUE THREAD

**Issue by sam1357** [DankMemer/dank-memer-suggestions-and-bugs#913]
**Describe the bug**

I am currently missing coins from around 5-6  months ago when I was playing on the Dank Memer currency game - I am unsure of whether this may be caused by inactivity or a server reset however my stats have been completely reset to 0, including levels and amount of coins able to be stored in the bank. I have not used the resetmydata command nor I have been killed since. I have contacted support and they advised to issue a bug report.

**To Reproduce**
**N/A**

**Expected behavior**
**N/A**

**Screenshots**
Before: ![Before](https://user-images.githubusercontent.com/67609409/86057940-25d7ca00-bab4-11ea-908a-8f6366304693.PNG)
After: ![After](https://user-images.githubusercontent.com/67609409/86057949-28d2ba80-bab4-11ea-94ca-09441fd66035.PNG)

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed
Discord username: 🆂.🆉#3086

**Additional context**

**Comment by melmsie** [comment]
<img width="1149" alt="Screen Shot 2020-06-29 at 5 50 17 PM" src="https://user-images.githubusercontent.com/20218284/86059645-1cf1e480-ba31-11ea-9eaf-40fbc4ec72ba.png">
