### ISSUE TITLE
Gain money bug THIS NEEDS TO BE FIXED ASAP. 

### ISSUE THREAD

**Issue by bluebreezy0** [DankMemer/dank-memer-suggestions-and-bugs#914]
**Describe the bug**
I had 130k and when i died i got 180k.

**To Reproduce**
1. Run the command 'pls use apple' 
2. then do 'pls search' until you die

**Expected behavior**
I expected to die and lose 465 coins as it said. 

**Screenshots**
![Screenshot_20200630_023206](https://user-images.githubusercontent.com/67610771/86062583-176cbc80-ba7a-11ea-98ac-39c215343be3.jpg)
![Screenshot_20200630_023124](https://user-images.githubusercontent.com/67610771/86062588-189de980-ba7a-11ea-8a5b-6eb4b18e29a5.jpg)
![Screenshot_20200630_022900_com discord](https://user-images.githubusercontent.com/67610771/86062589-19368000-ba7a-11ea-8502-18ead8d7b09f.jpg)
This is how i knew how i got the bug and how it happened i hope you fix the this asap because this bug is huge and op. 

**Your User ID**
375347917613170698
Blue Breeze#6650

**Additional context**
At that time no one gave me any coins and i didn't give anyone coins.

**Comment by SonicofProdigy** [comment]
I don't think it is a bug, I don't see how it is. Someone have you coins, it isn't a bug

**Comment by bluebreezy0** [comment]
> I don't think it is a bug, I don't see how it is. Someone gave you coins, it isn't a bug

like i said no one gave me.

**Comment by SonicofProdigy** [comment]
I still don't see the bug.... explain it to us again but with more detail

**Comment by bluebreezy0** [comment]
> I still don't see the bug.... explain it to us again but with more detail

well i don't know how can i explain further do i talk in morse code or what

**Comment by bluebreezy0** [comment]
you know what ill try to do it again

**Comment by andrewisaboomer** [comment]
did you dep all during that time?
if he didn't then it doesn't explain how money got in his bank
