### ISSUE TITLE
Using "pp" instead of "apple" & many more shortcuts bug

### ISSUE THREAD

**Issue by ItsFlashPvP** [DankMemer/dank-memer-suggestions-and-bugs#915]
**Describe the bug**
When selling/using/looking at an item in the shop using shorcut words such as "bank" for "banknote", "g" for "spinner", or "pp" for "apple" some of these shortcuts show errors when using them. Known shortcut errors: "pp" "r" "m"

**To Reproduce**
1. Type "pls shop pp (or any other shortcut errors)"
2. See error

**Expected behavior**
It is expected to be able to use "pp" ("pp" as an example) easily normally to buy/sell/use items.

**Screenshots**
![image](https://user-images.githubusercontent.com/63632959/86075045-f5ece000-ba3b-11ea-9df3-b0dcb19831ad.png)
(If the first link didn't work: https://cdn.discordapp.com/attachments/701353852204482567/727344792174067792/unknown.png )

**Your User ID**
527994612271546379

**Additional context**
*None*

**Comment by melmsie** [comment]
not really important, you're supposed to use the item name not random letters that are within an item
