### ISSUE TITLE
pet featues

### ISSUE THREAD

**Issue by celebipogo** [DankMemer/dank-memer-suggestions-and-bugs#916]
At the moment you can't do much with pet it would be good if you add features for pet. maybe like
we can do pls petsearch (works just like pls search but gives idk different items).
while doing pls petsearch your pet will lose some energy and you'd need to buy food item that you can feed pet to restore energy.
pet can also have chance to get attack or die while using pls petsearch and youd need to buy potion to heal.

if anyone reading this have other suggestion for pets pls comment. would be love to see more use/features of pets

**Comment by promages** [comment]
i would say pls pet search and not petsearch as you know, its pls pet feed and not pls petfeed. i would say its just like pls pet play except you get items from it, scaling with hunting level. but if thats the case the random 'has found x for you!' should be removed
