### ISSUE TITLE
Using multiple items at once

### ISSUE THREAD

**Issue by CrystalLiquid3** [DankMemer/dank-memer-suggestions-and-bugs#923]
I am vouching for one of my fellow discord mates here. They had 30 something bank notes and they wanted to use all of them. They obviously had to use them one by one but they really wish they could have used them like you use normie boxes. You can say “pls use norm 5” and it will use all 5. If you could do this with bank notes, candies, and those sort of items, that would be great. Thank you for considering my request.

**Comment by oliverysfx** [comment]
I think the main reason it isn't implemented for other items is because random number generation might take a while, cause the bot to lag out, but I am not sure, best for melmsie to answer this
