### ISSUE TITLE
Pls enable/disable remove bug

### ISSUE THREAD

**Issue by ItsFlashPvP** [DankMemer/dank-memer-suggestions-and-bugs#924]
**Describe the bug**
When having a large enable or disable list and you try to remove a rule that the list shows it sometimes does not work if it is one of the last rules. I have seen this happen in multiple other servers, not just mine. 

**To Reproduce**
1. Run ‘pls enable list (last page #)”
2. Try to remove the last few rules
3. Notice it does not work

**Expected behavior**
Be able to remove the rule normally. 

**Screenshots**
![2FED1B73-1911-403C-9846-66D4B3874CC4](https://user-images.githubusercontent.com/63632959/86200751-70882f00-bb12-11ea-99f0-348799db8bd5.png)

![](https://cdn.discordapp.com/attachments/701353851747303488/727730163630080040/image0.png)

**Your User ID**
527994612271546379

**Additional context**
Keep up the great work with the rewrite!

**Comment by ItsFlashPvP** [comment]
*I accidentally uploaded the screenshot twice so ignore the second one lol*

**Comment by melmsie** [comment]
doesn't matter, will be rewritten
