### ISSUE TITLE
sell multiple of the same item at once

### ISSUE THREAD

**Issue by pwXs** [DankMemer/dank-memer-suggestions-and-bugs#926]
too hard to sell items
im frustrated beacuse i gotta write like "pls sell candy"or smthn a million times

make it so u can do pls sell (Item) (amount)
or pls sell (item) max

**Comment by andrewisaboomer** [comment]
this is already implemented
u sure you didn't screw up smth?

**Comment by pwXs** [comment]
sorry I made a typo smh
