### ISSUE TITLE
Implement system to fix grammar in "you got" to change "fishs" to "fishes" etc

### ISSUE THREAD

**Issue by DaChickenKing** [DankMemer/dank-memer-suggestions-and-bugs#929]
**Is your feature request related to a problem? Please describe.**
When I use `pls fish`, for example, Dank Memer will tell me something like `You successfully sold 3 Common Fishs`

**Describe the solution you'd like**
I believe there should be a system put in place so that if an item name ends in `h` it should add `es` instead of `s`, changing "fishs" to "fishes", for example.

**Describe alternatives you've considered**
I don't really know what alternatives there would be for my situation.

**Additional context**
None.

**Comment by melmsie** [comment]
literally could not care less
