### ISSUE TITLE
Impossible to win a live event

### ISSUE THREAD

**Issue by Spicyhotdog24** [DankMemer/dank-memer-suggestions-and-bugs#932]
When a live event happens, it is impossible for you to win.

During a live event you would usually type in or copy and paste what the prompt tells you to do. I have done 20+ live events and havent won anything in the past day or so.

Usually the system would recognize you and give you your prize

**Comment by Rhino149** [comment]
Im 99% sure the devs already know of this problem events work sometimes or other times dont

**Comment by oliverysfx** [comment]
copy paste = fail

**Comment by oliverysfx** [comment]
and if you have one message after the event happened that doesn't meet the sentence that's not a boss fight, no success as well, all of these are intended

**Comment by oliverysfx** [comment]
and if the health of the boss of a boss fight event is 0, sending anything that satisfies will increase the hits but won't give rewards
