### ISSUE TITLE
I want to bet more than 75000

### ISSUE THREAD

**Issue by Arcticwolf69** [DankMemer/dank-memer-suggestions-and-bugs#933]
I want to bet more than 75000 cuz its not op it depends on luck it can be bad also

**Comment by andrewisaboomer** [comment]
imo this shouldnt be implemented for betting/slots, since at high multipliers thats just op, but i think this should be implemented with blackjack because it isnt all luck and multis dont affect it

**Comment by Arcticwolf69** [comment]
So why not dew it
