### ISSUE TITLE
After prestige

### ISSUE THREAD

**Issue by ER6969** [DankMemer/dank-memer-suggestions-and-bugs#934]
**Describe the bug**
After prestige 5,the level does not rise

**Screenshots**
![Screenshot_20200702-123214__01](https://user-images.githubusercontent.com/67738620/86348552-1d23f700-bc60-11ea-9767-d97edf16a63d.jpg)

**Your User ID**
522822998491922432

**Comment by oliverysfx** [comment]
dup of #725
