### ISSUE TITLE
When I went hunting i got a dragon but it only gave me like 3 seconds

### ISSUE THREAD

**Issue by Cinnamon820** [DankMemer/dank-memer-suggestions-and-bugs#935]
When I went hunting i got a dragon but it only gave me like 3 seconds

**Comment by oliverysfx** [comment]
nope, you were too slow at typing, it's always 10s, unless you typed wrongly, which terminates the timer when you fail

**Comment by andrewisaboomer** [comment]
might have been lag/bad wifi on your end
nothing anyone can do about that
