### ISSUE TITLE
My request for Dank Memer Investments.

### ISSUE THREAD

**Issue by voidultra** [DankMemer/dank-memer-suggestions-and-bugs#939]
**Is your feature request related to a problem? Please describe.**
I have an idea that I think would be really fun for the dank memer bot.
**Describe the solution you'd like**
It would be really cool if there was a “pls investments list” command and it would bring up a list of things you could invest in with coins. It would work the same way as “pls bet” except you choose what you invest in and you wait to see how lucky you get, if you do you win thousands of coins or you lose however much you invested.
**Describe alternatives you've considered**

**Additional context**

**Comment by oliverysfx** [comment]
that's dumb

**Comment by voidultra** [comment]
> that's dumb
why may that be dumb?

**Comment by oliverysfx** [comment]
it sounds exactly like bet?
