### ISSUE TITLE
Pls slots

### ISSUE THREAD

**Issue by The-blackout** [DankMemer/dank-memer-suggestions-and-bugs#94]
This is just a suggestion for a another simple command I’m suggesting that you add the command pls slots —stats just like pls gamble —stats.

**Comment by rayhan6726** [comment]
There's already a slots command months before you suggest that

**Comment by Arj2021** [comment]
He meant to have a `pls slots --stats` , that would give you stats for slots similar to the `pls bet --stats`

**Comment by melmsie** [comment]
as already announced at the same time as gamble stats, more stats will come in the future.
