### ISSUE TITLE
Lost Coins

### ISSUE THREAD

**Issue by EverRees** [DankMemer/dank-memer-suggestions-and-bugs#940]
So my wallet has at least 20k-ish when I logged in about 7pm and rank 3rd in my server. But when I logged in again at around 10pm, all my coins in my wallet are gone.

When I input pls rich around 7pm Im still at 3rd place but when I did the same command at 10pm I went down the ranks and checked my balance, and huzza! My coins yeeted.  

![Screenshot_20200702-234121](https://user-images.githubusercontent.com/67751866/86381114-84bd5f00-bcbf-11ea-92e4-824232d5b2f2.png)
![Screenshot_20200702-234251](https://user-images.githubusercontent.com/67751866/86381152-91da4e00-bcbf-11ea-8976-50939c369dba.png)

I was in passive mode btw, so beind robbed was out of the question. Thats why I'm wondering what the heck happened to my coins.

**Comment by oliverysfx** [comment]
do pls notifs and screenshot it

**Comment by EverRees** [comment]
I died?? But I was logged out during that time frame. 
![Screenshot_20200706-100831](https://user-images.githubusercontent.com/67751866/86548917-b446c280-bf70-11ea-9519-be671bfbd45e.png)

**Comment by oliverysfx** [comment]
your account might be hacked then, change your password, email and everything
