### ISSUE TITLE
Pls use medal

### ISSUE THREAD

**Issue by UserNice12** [DankMemer/dank-memer-suggestions-and-bugs#949]
Like the old pls use pepec, it would be helpful if there was a command for pls use medal. It says that this item cannot be used but  as the description of the item says "to flex on normies who cannot afford one", this command would make it easier to flex.

**Comment by oliverysfx** [comment]
no, pls use trophy is a thing

**Comment by UserNice12** [comment]
"no, pls use trophy is a thing"
Then why not the same for medal? That is unfair for the people who have medals, why only for trophy? I understand why they removed it for the pepec as it is a way cheaper item now but medal costs about 5 million, the pepec used to be for 1 mil but it still had a "use" feature and the medal is way costlier than that. So I believe it should have a similar feature.

**Comment by oliverysfx** [comment]
because trophy is more expensive for medal and it's unfair that people can use medal as well?
