### ISSUE TITLE
Stock Market

### ISSUE THREAD

**Issue by uhhshrimp** [DankMemer/dank-memer-suggestions-and-bugs#950]
Dank Stocks.

It’s quite self explanatory and I think would make a big impact on the game. you could run “pls stocks” to see how in-game random value “stocks” are valued at and say make it 100 coins for one share of the stock and stocks fluctuate every twenty (or random) minutes and then it could be at 84 or 117. You can then sell your share of the stock with “pls stock sell [amount you want to sell or just “max”] (name of stock) also a “pls stocks view (name of stock) and you can see the rising and falling of the stock. Some stocks are riskier than others meaning they fluctuate higher and lower and others are pretty steady. 

I think you could get really creative with some of the stock names, too.

**Comment by Sadrazoozoo8** [comment]
Ah hard as it sounds to add in, I really like this and i wish the devs would do it! xD

**Comment by PhantomFrenzy151** [comment]
i'm pretty sure this is a dupe

**Comment by oliverysfx** [comment]
yeah I think it is

**Comment by oliverysfx** [comment]
dup of #721
