### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Qu13t13** [DankMemer/dank-memer-suggestions-and-bugs#956]
![F70DF319-26B3-44DA-B504-DB4146CF38BD](https://user-images.githubusercontent.com/67789905/86469452-5f3e5d00-bd74-11ea-93d3-27ea744e950d.jpeg)

Theres a typo when you fail to hunt a dragon.
Instead of “your” weak little macaroni legs its“you” weak little macaroni legs

**Comment by SortaMadBernie** [comment]
Do u have the pirate thing on? Or does it not matter?

**Comment by andrewisaboomer** [comment]
if it was pirate it would say yer

**Comment by Qu13t13** [comment]
I dont have pirate on

**Comment by melmsie** [comment]
fixed
