### ISSUE TITLE
Passive mode. - Currency Related.

### ISSUE THREAD

**Issue by AquaticVortex** [DankMemer/dank-memer-suggestions-and-bugs#96]
**Is your feature request related to a problem? Please describe.**
Passive mode seems a bit overpowered as i see people with little to no money can just turn it on, and auto-magically can not get robbed or stolen form.

**Describe the solution you'd like**
I would just like to suggest that perhaps passive mode can be enabled if you have 20k+ in your bank for example, because that is actually worth something.

**Describe alternatives you've considered**
Another alternative is maybe if they are a longer user of Dank Memer they can also use Passive Mode without any issues.

**Additional context**
I don't mind if this doesn't get implemented, but I don't really understand why if people have no money why they can be in total heaven.

**Comment by melmsie** [comment]
> i see people with little to no money can just turn it on, and auto-magically can not get robbed or stolen form.

Yes that's what passive mode means. There **IS** a downside, they get 20% less winnings on gambling, and they also cant earn money from robbing. Your solution is not being considered.
