### ISSUE TITLE
Make The Animals you Hunt The food to you dragon Pet

### ISSUE THREAD

**Issue by HelloWorld9897** [DankMemer/dank-memer-suggestions-and-bugs#962]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HelloWorld9897** [comment]
This request isn’t related to a problem, rather, an idea to make hunting rabbits, And other lower animals more useful.

Say you hunt a duck, now you have it in your inventory, you can choose to sell it, or feed it to your dragon or other carnivorous pets by saying: pls pet feed duck 

You can also make a new item called foragers bag that you can hunt berries with to feed to your mom carnivorous pets.

Since rabbits are definitely smaller than, say a boar, you can make the rabbit fill up hunger less and the boar more. This will encourage trading of these food items from user owned shops.

**Comment by oliverysfx** [comment]
very similar to the rejected #601
