### ISSUE TITLE
Option to specify comic number with pls xkcd command

### ISSUE THREAD

**Issue by Technoguyfication** [DankMemer/dank-memer-suggestions-and-bugs#964]
**Is your feature request related to a problem? Please describe.**
Currently the `pls xkcd` command always displays a _random_ xkcd comic. This is kinda pointless if you want to drop a specific xkcd in chat.

**Describe the solution you'd like**
Accept an optional integer parameter specifying the number of the xkcd you want to retrieve. If left blank, the bot still shows a random comic. Example, if I type `pls xkcd 327` I want to get the [bobby tables](https://xkcd.com/327/) xkcd.

**Describe alternatives you've considered**
Using another bot I suppose, other bots with an xkcd command usually have a random mode and comic number mode.

**Comment by melmsie** [comment]
maybe in the rewrite
