### ISSUE TITLE
A family-friendly

### ISSUE THREAD

**Issue by 195O** [DankMemer/dank-memer-suggestions-and-bugs#965]
Hello!

I think there should be a command for Dank Memer to enter family-friendly mode. This would disable all NSFW commands and prevent the bot from swearing.

I have a family-friendly server where I want to get Dank Memer, but I'm afraid it's too inappropriate even if I disable the NSFW module. The memes can still have swearing.

Thank you for taking the time to read this. Have a nice day!

Regards

**Comment by oliverysfx** [comment]
all the memes have nsfw filters, so genererally it should be fine, only in some very rare cases the filter somehow fails
