### ISSUE TITLE
Lock abuse

### ISSUE THREAD

**Issue by samdabloxyccola** [DankMemer/dank-memer-suggestions-and-bugs#968]
People always abuse the lock function by giving someone 250 coins and then breaking your lock deliberately so you would have no lock. I have met so many of these selfish users who always break my locks on purpose just so that they can conveniently rob me next time or just waste my locks. Please make a function where you cannot keep breaking people's locks on purpose

**Comment by oliverysfx** [comment]
passive is a freaking thing mate

**Comment by samdabloxyccola** [comment]
> passive is a freaking thing mate

Hello I want to rob people lmao

**Comment by oliverysfx** [comment]
this is a feature, that I am pretty sure is intended by the devs, they aren't gonna do anything about it, this is called strategy

**Comment by UserNice12** [comment]
This also happens to me a lot, but I cant think of any good solution to this problem. Maybe the devs could make a certain minimum amount which can be given, nothing lower than that to a person but I'm not sure that would fix the problem

**Comment by samdabloxyccola** [comment]
> This also happens to me a lot, but I cant think of any good solution to this problem. Maybe the devs could make a certain minimum amount which can be given, nothing lower than that to a person but I'm not sure that would fix the problem

Yes
Cuz the person could give more and then break someone's lock

**Comment by Rhino149** [comment]
If someone wants to rob you and break your lock then they can its not lock abuse for thr other person to keep using locks the lock is meant to be used to prevent being robbed temporarily if you complain about your lock being broken just leave that server
