### ISSUE TITLE
Using pink phallic objects like actual dildos

### ISSUE THREAD

**Issue by Jiakai7521** [DankMemer/dank-memer-suggestions-and-bugs#969]
Could we use pink phallic objects like actual dildos? And not using them to give to ppl?

**Comment by oliverysfx** [comment]
that would be nsfw, so no

**Comment by Stormboy931** [comment]
Is there something bad with it being nsfw, there is a nsfw category.

**Comment by oliverysfx** [comment]
because this is a freaking currency command? putting this there would be very inappropriate??

**Comment by Jiakai7521** [comment]
Then we can use the command only in a NSFW channel, hence making "pls use pinkphallicobject" a special currency command.

**Comment by soul0101** [comment]
Lmao

**Comment by oliverysfx** [comment]
> Then we can use the command only in a NSFW channel, hence making "pls use pinkphallicobject" a special currency command.

that would be weird lmfao, and I don't think that's gonna get accepted

**Comment by Jiakai7521** [comment]
Idk
Let's just wait for someone else to step in.
