### ISSUE TITLE
Work command

### ISSUE THREAD

**Issue by Stormboy931** [DankMemer/dank-memer-suggestions-and-bugs#970]
**When using the work command sometimes it appears a retype minigame then when i type it it tell me i failed. If this is a bug the can someone please fix it.**

**![image](https://user-images.githubusercontent.com/67826625/86511421-0b109880-bdc7-11ea-8475-a554edd2457c.png)**

**Comment by andrewisaboomer** [comment]
im p sure if you copy paste you fail, but if u didnt do that it might be lag that causes messages to be sent later

**Comment by Stormboy931** [comment]
I dont copy paste it, the problem is that it always fail not even one time it has succeeded.
