### ISSUE TITLE
Shows my name when I try to see other users profiles with the gift flag

### ISSUE THREAD

**Issue by wasi-master** [DankMemer/dank-memer-suggestions-and-bugs#972]
**Describe the bug**
The bug happens when I try to see other peoples profile with the gift tag

**To Reproduce**
Type pls profile <mention> --gift
See your name

**Expected behavior**
The name should be of the user we are mentioning and not mine

**Screenshots**
None

**Your User ID**
538332632535007244

**Additional context**
It happened to me as of July 4 2020 and may be fixed later.

**Comment by oliverysfx** [comment]
this happens to me as well

**Comment by melmsie** [comment]
fixed next update
