### ISSUE TITLE
Cannt remove utilities 

### ISSUE THREAD

**Issue by Kuharri** [DankMemer/dank-memer-suggestions-and-bugs#973]
had a memer mod in my server try to help and support also told me to come here 
![b973342be49bb497e11a1c7ef6beaf6a](https://user-images.githubusercontent.com/62859318/86520225-058b7080-be10-11ea-9a5f-25afb7b045e0.png)

**Comment by oliverysfx** [comment]
it's a known bug that categories can't be removed, so you have to just deal with it, or you can do pls enable clear

**Comment by Kuharri** [comment]
well i have 24 enable pages. any easier way than losing all of that? and
starting over?

**Comment by melmsie** [comment]
Minor and hard to reproduce, will be fixed in the rewrite
