### ISSUE TITLE
Pls profile --gamble not working as intended.

### ISSUE THREAD

**Issue by Anonymous1189** [DankMemer/dank-memer-suggestions-and-bugs#974]
**Describe the bug**
Doing pls profile --gamble helps you know how much you've made betting/slotting and i like to keep a log of winnings to see how much money I've spent/earned.
Lately my losses seem to be keep rising at a steadier rate but my winnings don't. Im pretty sure im making a profit or i would've been broke by now
**To Reproduce**
1. Do pls profile --gamble, note your winnings down.
2. Do pls profile bal, note your balance down.
3. Start betting/slotting for a bit, higher amounts would show the error faster.
4. Do pls profile bal again along with pls profile gamble after a few mins.

**Expected behavior**
Quite self explanatory, should show the correct sum for winnings/losses.

**Screenshots**
The time/day in the pictures aren't accurate, picture marked with 1 is an old screenshot.
Picture marked with 1- about 3ish day old shows positive net winnings. (Before the update that added slot winnings)
Picture marked with 2 - same user, shows a big negative losses. (After update)
I've cut the names out to keep user anonymity as they're not my stats.
![20200704_234220](https://user-images.githubusercontent.com/66759439/86520726-663a9d80-be50-11ea-98f5-c89272c82349.jpg)
![20200704_234341](https://user-images.githubusercontent.com/66759439/86520727-6b97e800-be50-11ea-999c-03a23690c13a.jpg)
![20200704_234413](https://user-images.githubusercontent.com/66759439/86520729-6f2b6f00-be50-11ea-92b6-fd1c5e898b2a.jpg)

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed
Don't think its necessary here.

**Additional context**
Ps. You would probably need a good multi to efficiently reproduce this along with some time as you could get caught up in a lose streak. Also, the issues seems to be from slotting from my observance, either its not adding my slot winnings correctly or not adding them all but, seems to be adding my losses properly.

**Comment by oliverysfx** [comment]
slots amount was added not long ago

**Comment by Anonymous1189** [comment]
Yea im aware when the update happened, but i don't think the calculation being done to add slots winning is coded right.

**Comment by melmsie** [comment]
fixed next update
