### ISSUE TITLE
Bank Robbing preventions

### ISSUE THREAD

**Issue by SonicofProdigy** [DankMemer/dank-memer-suggestions-and-bugs#975]
**Describe the solution you'd like**
Add an item that can also decrease chances of bank robbing you by either making an item that functions similar to padlock but for your bank or an item to temporary decrease the chances of being bank robbed

**Describe alternatives you've considered**
Decreasing the actual chances of bank robbing, or allowing your pet to protect you from bank robbing
**Additional context**
Sorry for this very short feature request

**Comment by oliverysfx** [comment]
I am pretty sure this is a duplicate but I can't remember which one it is
