### ISSUE TITLE
Camers 360° no scope 

### ISSUE THREAD

**Issue by AssBeater420** [DankMemer/dank-memer-suggestions-and-bugs#976]
https://media.discordapp.net/attachments/662746149555404843/728589036976996372/unknown.png
Hi me name is AssBeater420 e wamt to be reich ab damk kemar me love kebab me want to eating kebab on me laptop me love damk kemar me want to be coming  soon rich az passablile as me can

**Comment by oliverysfx** [comment]
wtf?
