### ISSUE TITLE
PLS PET NOT WORKING

### ISSUE THREAD

**Issue by rooooooooosa** [DankMemer/dank-memer-suggestions-and-bugs#978]
**Describe the bug**
THE PLS PET THING NOT WORKING

**To Reproduce**
tf is this

**Expected behavior**

**Screenshots**

(https://user-images.githubusercontent.com/67861098/86531318-e00e6d80-bec8-11ea-9ada-0b799315091c.png)

**Your User ID**
326645821271441409

**Additional context**
dude can my pet die??????????

**Comment by oliverysfx** [comment]
yeah this is a bug, and sadly, your pet can die oof

**Comment by melmsie** [comment]
what commands are happening to cause that, is it whenever you run pls pet? Is it only certain arguments?

**Comment by rooooooooosa** [comment]
NVM it's working now LOL 
Ty anyway
