### ISSUE TITLE
the guess thingy is kinda dumb..

### ISSUE THREAD

**Issue by thankunect** [DankMemer/dank-memer-suggestions-and-bugs#979]
I’m sorry but the guessing thingy is kinda dumb because you only get 2 coins, why?
can you like make it give you at least 100-300 coins?

**Comment by andrewisaboomer** [comment]
bruh its not supposed to be something thats a legit way to make money, its a GAME that you are supposed to play when you are bored not something you are supposed to grind for money

**Comment by melmsie** [comment]
how about no coins, it's not a currency command
