### ISSUE TITLE
Add a chance for failure if you reverse a reversal

### ISSUE THREAD

**Issue by W1NGD1NG5-G4ST3R** [DankMemer/dank-memer-suggestions-and-bugs#98]
**Is your feature request related to a problem? Please describe.**
So when someone gets robbed, and the guy uses a reversal, the robber will always use another one. This cycle will continue until either someone doesn't use reversal for 20 mins, or they run out of money. When a person gets robbed by someone who is richer than him, the robber will almost certainly win because he has more money for reversals. Thus, making it unfair for the relatively poorer users.

**Describe the solution you'd like**
Add a 40% chance that the robber will fail a reverse reversal(does not apply to the guy who got robbed)

**Describe alternatives you've considered**
Or remove the ability to reverse reversals entirely

**Comment by melmsie** [comment]
no
