### ISSUE TITLE
New meme template

### ISSUE THREAD

**Issue by natecool** [DankMemer/dank-memer-suggestions-and-bugs#981]
Can you guys add a command for the Obama awarding Obama meme template? 
![e33](https://user-images.githubusercontent.com/67801222/86559844-29bd8d80-bf87-11ea-9f0f-5306c7748fa1.jpg)

Like that one for example. A user can type the command "pls obamaaward" then put a person's @ and then add another @ and then the person's names would show on the template.

**Comment by GeoffreyWesthoff** [comment]
Wouldn’t having two different names kinda ruin the joke?

**Comment by melmsie** [comment]
yeah ignore his suggestion, just put avatar1 as both heads and it'll be good @GeoffreyWesthoff

**Comment by GeoffreyWesthoff** [comment]
Implemented as of https://github.com/DankMemer/imgen/commit/5053ab5cbe3b96b14d389b40cde34080e5115c71
