### ISSUE TITLE
Reversal Debt

### ISSUE THREAD

**Issue by W1NGD1NG5-G4ST3R** [DankMemer/dank-memer-suggestions-and-bugs#99]
**Is your feature request related to a problem? Please describe.**
When you get stolen, you can use a reversal unless the robber bought stuff with his stolen money, or shared it to other users. This is very frustrating when someone robs you and instantly buys a high value item(rare pepe, pepecoin...etc) so you can't reverse his steal.

**Describe the solution you'd like**
No matter what he does with his money, when you reverse it, if he doesn't have enough money for you to reverse, the amount is still deducted from his balance, leaving him with a negative amount.

**Describe alternatives you've considered**
none

**Comment by melmsie** [comment]
You can't take money that doesn't exist, we're not putting anyone negative over this.
