### ISSUE TITLE
Blackjack, dealer hitting even after dealer wins

### ISSUE THREAD

**Issue by rbb-dev** [DankMemer/dank-memer-suggestions-and-bugs#991]
When playing BJ i got  ♥ K ♦ 4
i hit and got ♥ K ♦ 4 ♦ 2 for total of 16

The dealer opened up cards and proceeded to hit  ♣ K ♥ 10 ♠ 4
Dealer already won but still proceeded to hit
https://imgur.com/YdU2Qty

**Comment by PhantomFrenzy151** [comment]
You win at 21, not 20

**Comment by rbb-dev** [comment]
That's no blackjack rules :)
Dealer must draw if below 16/17 and must not draw if after the reveal already has a winning combo.
Just thought you'd want to know...

**Comment by PhantomFrenzy151** [comment]
Yeah, the dealer had 20, and drew again for some reason. However, the cards aren't necessarily in order. He could have got a 14 and then drew a 10.

**Comment by andrewisaboomer** [comment]
what they said, its certainly possible that the dealer had less than you then drew a 10
