### ISSUE TITLE
quest cancellation

### ISSUE THREAD

**Issue by rackepte** [DankMemer/dank-memer-suggestions-and-bugs#993]
a problem ive often seen alot is that there is no way of canceling quests 
and this can be a really bad problem if i choose a quest which will take me a very long time to do and i cant cancel to a easier one so i am stuck with said quest untill i complete it

just a way to cancel quests it can be on a daily cooldown or maybe even an item that can do so
 there really is nothing more to be said i just wanted to suggest this since i have not seen this suggested here yet

**Comment by Anonymous1189** [comment]
The command "pls quest stop" cancels your active quest.
A better suggestion would be to make all the quest commands uniform.
To choose a quest you do, "pls quests choose <name>"
To view the list you do  "pls quests list"
I can't wrap by head around why the cancel command was designed so differently to this given dank memer mostly doesn't have commands that are actually plural.

**Comment by PhantomFrenzy151** [comment]
just use pls quest stop

**Comment by rackepte** [comment]
oh thank you ive never heard of the pls stop command before but i am very glad to know it exists now
