### ISSUE TITLE
LOST 85K FOR NO REASON

### ISSUE THREAD

**Issue by pwXs** [DankMemer/dank-memer-suggestions-and-bugs#997]
just lost all my coins

heres a screenshot of my coins at 85k while i had passive mode on
![Screenshot (17)](https://user-images.githubusercontent.com/67694131/86827014-5389b980-c046-11ea-9fcb-bbc46de9cd38.png)

heres a screenshot of me just suddenly jumping to 0 (i got the 700 by doing pls work)
![Screenshot (18)](https://user-images.githubusercontent.com/67694131/86827188-892ea280-c046-11ea-828f-272ebf2425b5.png)

PLSEASE HELP I HAVE NO IDEA WHAT HAPPANED EVEN CHECKED ALL SERVERS I DIDINT GET ROBBED OR ANYTHING

passive mode switched off while i was offline for some reason but i checked all my servers and no i didnt get robbed

**Comment by PhantomFrenzy151** [comment]
use pls notifs

**Comment by SeylarPook** [comment]
Did you by any chance die? i died and lost 75k in passive

**Comment by pwXs** [comment]
hey uhh does it show it in the chat if I died? if it does it didn't show it
also didn't use any items like alcohol or something that kills you I just
sell em all and not take the risk

**Comment by pwXs** [comment]
NVM I DIED I DID PLS NOTIFS
thanks for the help anyways but I don't understand how I died rip hours lol

**Comment by andrewisaboomer** [comment]
close this?

**Comment by pwXs** [comment]
yeah I guess there's nothing me or u can do
 sorry for opening issue without checking notifs
