### ISSUE TITLE
Was slots multiplier nerfed without issuing patch notes?

### ISSUE THREAD

**Issue by Anonymous1189** [DankMemer/dank-memer-suggestions-and-bugs#998]
**Describe the bug**
Normally doing pls slots max and getting 2 tridents would give me around 400k~ with a 50% multi, update happened and slots was changed on the 1st of july that states, 
"Slots now plays out a bit more fair that before at higher icon multipliers" all good till here and i still used to get somewhere a bit under 400k~ (350k i think)
But heres where things get weird, in the update on the 6th of july, the slots percentage has seemed to taked a very a big hit, have a look at the screenshot.

**To Reproduce**
1. Start slotting max.
2. Look at multis
3. See error

**Expected behavior**
Well, with respect to the update on june 1st, it clearly states how slots would play out a bit more "fair" but no additional context was given to what is meant by this fair. This update didn't cause the issue and you could still make money while slotting as long as you had a high multi. I think something went wrong in the update released on the 6th that messed up with slots and makes the multi way to low.
**Screenshots**
![Screenshot_20200708-023146_Discord](https://user-images.githubusercontent.com/66759439/86856057-385d8f00-c0c4-11ea-86e2-5301b5968972.jpg)

**Your User ID**
[Get your user id](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) and add it here if needed

**Additional context**
Im not sure if this a bug or intentional, but given that nothing was mentioned in the patch notes/update section of the bot i did say it's safe to make an assumption that it is indeed an error. The screenshot attached shows the current multiplier for the tridents.

**Comment by SonicofProdigy** [comment]
You will loose eventually, big amount of wins always follows with looses

**Comment by Anonymous1189** [comment]
Thats not my point, im just saying slots was changed twice, 
1. On july 1st - mentioned in the update notes.
2. On july 6th - not really mentioned.
Hence this could be a bug where the mutli isn't working as intended.
